SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone:: @ 8173FF7
    .string "¿Has ido a la ZONA SAFARI en\n"
    .string "CIUDAD FUCSIA?\p"
    .string "Hay muchos tipos de POKéMON\n"
    .string "raros ahí.$"

SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome:: @ 817404F
    .string "¡Yo y mi papi creemos que la ZONA\n"
    .string "SAFARI es increíble!\l"
    .string "Ojalá pudieramos ir allá de nuevo.$"

