OneIsland_PokemonCenter_1F_Text_BillHeyThereCelio::
    .string "BILL: ¡Oye!\n"
    .string "¡CELIO!$"

OneIsland_PokemonCenter_1F_Text_CelioCantBelieveYouCameOut::
    .string "CELIO: ¡BILL!\n"
    .string "No puedo creer que estés aquí.$"

OneIsland_PokemonCenter_1F_Text_BillHowsYourResearchComing::
    .string "BILL: ¡Pues claro!\n"
    .string "¿Cómo va tu investigación?\p"
    .string "…Oh, espera un segunda.$"

OneIsland_PokemonCenter_1F_Text_ThisIsMyBuddyCelio::
    .string "{PLAYER}, éste es mi amigo CELIO.\n"
    .string "¡Es un dedicado MANÍACO de las PCs!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsRisingPokemonChamp::
    .string "CELIO, ést{EA} es {PLAYER}, un{A}\n"
    .string "candidat{OA} a CAMPE{ONONA} POKéMON!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsReigningPokemonChamp::
    .string "CELIO, ést{EA} es {PLAYER}, {ELLA}\n"
    .string "actual CAMPE{ONONA} POKéMON!$"

OneIsland_PokemonCenter_1F_Text_CelioThatsReallyImpressive::
    .string "CELIO: Eso es impresionante.\p"
    .string "Odio decirlo, pero no soy apto\n"
    .string "para las batallas.\p"
    .string "En fin, es un gusto conocerte.$"

OneIsland_PokemonCenter_1F_Text_BillBringMeUpToSpeed::
    .string "BILL: Bueno, cuéntame.\n"
    .string "¿Cómo funciona tu máquina?$"

OneIsland_PokemonCenter_1F_Text_CelioPCsCantLinkWithYours:
    .string "CELIO: Funciona bien, pero estamos\n"
    .string "demasiado lejos aquí.\p"
    .string "No hay manera de conectar las PCs\n"
    .string "de esta isla con tu PC, BILL.$"

OneIsland_PokemonCenter_1F_Text_BillLetMeHelpYou::
    .string "BILL: ¿Ah, no?\n"
    .string "Bueno, déjame dar una miradita.\p"
    .string "…Espera un momento…\n"
    .string "Creo que podemos hacerlo funcionar.\l"
    .string "Déjame ayudarte, ¿de acuerdo?$"

OneIsland_PokemonCenter_1F_Text_CanYouDeliverThisMeteoritePlayer::
    .string "{PLAYER}, ¿puedes esperarme\n"
    .string "un momento?\p"
    .string "…De hecho, ¿podrías hacerme\n"
    .string "un favor?\p"
    .string "La isla más cercana se llama\n"
    .string "ISLA SECUNDA.\p"
    .string "Ahí esta un tipo que maneja una\n"
    .string "SALA DE JUEGOS.\p"
    .string "Tiene una cosa por las rocas raras\n"
    .string "y las gemas.\p"
    .string "Estamos en contacto, pues ambos\n"
    .string "tenemos manías.\p"
    .string "Entonces, ¿podrías llevarle este\n"
    .string "METEORITO?$"

OneIsland_PokemonCenter_1F_Text_AcceptedMeteoriteFromBill::
    .string "{PLAYER} obtuvo el METEORITO\n"
    .string "de BILL.$"

OneIsland_PokemonCenter_1F_Text_CelioPleaseTakeThis::
    .string "CELIO: {PLAYER}, si vas a ir a la\n"
    .string "ISLA SECUNDA, lleva esto.$"

OneIsland_PokemonCenter_1F_Text_PassLetsYouTravelBetweenIslands::
    .string "Es un PASE para el servicio de\n"
    .string "barco de las islas locales.\p"
    .string "Te dejará viajar entre las\n"
    .string "ISLAS PRIMA, SECUNDA, Y TERA.\p"
    .string "Oh, también deberías tener esto.$"

OneIsland_PokemonCenter_1F_Text_ReceivedExtraPageForTownMap::
    .string "¡{PLAYER} recibió una página extra\n"
    .string "para el MAPA REGIONAL!$"

OneIsland_PokemonCenter_1F_Text_ReceivedTownMap::
    .string "¡{PLAYER} recibió un\n"
    .string "MAPA REGIONAL!$"

OneIsland_PokemonCenter_1F_Text_BillCatchYouLater::
    .string "BILL: ¡Te veo después!\n"
    .string "¡Saluda al tipo de mi parte!$"

OneIsland_PokemonCenter_1F_Text_HmmHowAboutLikeThis::
    .string "Hmm…\p"
    .string "Quizá si lo intentamos así…$"

OneIsland_PokemonCenter_1F_Text_GotPCWorkingStrollAWhileMore::
    .string "¡Oh, ey, {PLAYER}!\p"
    .string "¿Lo viste?\n"
    .string "¡Hicimos que la PC funcione!\p"
    .string "Tengo algunas cosas que enseñarle\n"
    .string "a CELIO.\p"
    .string "¿Podrías ir a caminar por un rato\n"
    .string "más?$"

OneIsland_PokemonCenter_1F_Text_SorryForBeingPoorHost::
    .string "Lo siento mucho por gastar tanto\n"
    .string "del tiempo de BILL.\p"
    .string "También lo siento por ser tan mal\n"
    .string "anfitrión durante tu visita.$"

OneIsland_PokemonCenter_1F_Text_UsualPCServicesUnavailable::
    .string "Los servicios de PC usuales no\n"
    .string "están disponibles…$"

OneIsland_PokemonCenter_1F_Text_BillOhHeyPlayer::
    .string "BILL: ¡Oh, ey!\n"
    .string "{PLAYER}!$"

OneIsland_PokemonCenter_1F_Text_BillWeGotItDone::
    .string "BILL: ¿Qué te tomo tanto tiempo?\n"
    .string "¿Pasaste un buen rato?\p"
    .string "Nosotros ya terminamos.\n"
    .string "¡Las PCs funcionan perfectamente!$"

OneIsland_PokemonCenter_1F_Text_CelioJobWentQuick::
    .string "CELIO: El trabajo fue bastante\n"
    .string "rápido.\p"
    .string "BILL es un tipo increíble…$"

OneIsland_PokemonCenter_1F_Text_BillYouveLearnedALot::
    .string "BILL: ¡No, no! lo que tuve que\n"
    .string "hacer fue muy poco.\p"
    .string "CELIO, el mérito es tuyo.\n"
    .string "Has aprendido mucho.$"

OneIsland_PokemonCenter_1F_Text_CelioOhReallyEhehe::
    .string "CELIO: ¿Oh, en serio?\n"
    .string "Ejeje…$"

OneIsland_PokemonCenter_1F_Text_BillWeShouldHeadBackToKanto::
    .string "BILL: Bueno, ya está.\n"
    .string "Terminamos el trabajo.\l"
    .string "Deberíamos volver a KANTO.\p"
    .string "CELIO, nos vemos.$"

OneIsland_PokemonCenter_1F_Text_CelioPromiseIllShowYouAroundSometime::
    .string "CELIO: {PLAYER}, siento mucho que\n"
    .string "te fueras solo hoy.\p"
    .string "Te prometo que te enseñaré estas\n"
    .string "islas en otra ocasión.$"

OneIsland_PokemonCenter_1F_Text_CelioImModifyingMyNetworkMachine::
    .string "CELIO: ¡Hola!\n"
    .string "Te vez ocupad{OA}, como siempre.\p"
    .string "¿Qué cómo me va?\p"
    .string "Bueno, estoy modificando mi\n"
    .string "Máquina de redes.\p"
    .string "Cuando termine la máquina, espero\n"
    .string "que seas {ELLA} primer{OA} en usarla,\l"
    .string "{PLAYER}.$"

OneIsland_PokemonCenter_1F_Text_CelioCaughtMoreMonMaybeICanBeUseful::
    .string "CELIO: ¿{PLAYER}, cómo te ha ido?\p"
    .string "Oh, ¿es eso cierto?\n"
    .string "Atrapaste más POKéMON.\p"
    .string "¿Sabes qué?\n"
    .string "Tal vez te pueda ser útil.$"

OneIsland_PokemonCenter_1F_Text_YoullBeTradingFromTrainersFarAway::
    .string "Estoy modificando la\n"
    .string "Máquina de redes justo ahora.\p"
    .string "La estoy ajustando para soportar\n"
    .string "intercambios por largas distancias.\p"
    .string "Cuando termine, podrás\n"
    .string "intercambiar POKéMON exóticos con\l"
    .string "ENTRENADORES de lugares lejanos.$"

OneIsland_PokemonCenter_1F_Text_NeedsSpecialGemstone::
    .string "Pero, hay un pequeño problema.\p"
    .string "Para que la conexión funcione, la\n"
    .string "máquina necesita una gema especial.\p"
    .string "Se supone que está en ISLA PRIMA,\n"
    .string "pero no la he encontrado aún.\p"
    .string "Nadie sabe donde podría estar.$"

OneIsland_PokemonCenter_1F_Text_TryingToFindGem::
    .string "Intente buscar la gema incluso\n"
    .string "mientras estudiaba.\p"
    .string "Como resultado, no hice progreso\n"
    .string "en mi busqueda, o en mis estudios…\p"
    .string "Si dependiera de BILL, no dudo\n"
    .string "que mi investigación avanzaría.\p"
    .string "Pero, esta vez quiero intentar\n"
    .string "hacerlo por mi cuenta.$"

OneIsland_PokemonCenter_1F_Text_OhThats::
    .string "¡Oh!\n"
    .string "E-eso…$"

OneIsland_PokemonCenter_1F_Text_HandedRubyToCelio::
    .string "{PLAYER} entregó el RUBÍ\n"
    .string "a CELIO.$"

OneIsland_PokemonCenter_1F_Text_MayIAskOneMoreFavor::
    .string "¡Gracias!\n"
    .string "{PLAYER}, eres increíble.\p"
    .string "… … …  … … …\p"
    .string "Um… ¿podrías hacerme un favor\n"
    .string "gigante más?$"

OneIsland_PokemonCenter_1F_Text_PleaseINeedYourHelp::
    .string "No… no es nada raro.\n"
    .string "Por favor, necesito tu ayuda.$"

OneIsland_PokemonCenter_1F_Text_AnotherGemstoneInSeviiIslands::
    .string "Mientras estudiaba gemas, descubrí\n"
    .string "algo importante.\p"
    .string "Hay otra gema que forma un par\n"
    .string "con este RUBÍ.\p"
    .string "Se supone que la otra gema está\n"
    .string "en las ISLAS SETE.\p"
    .string "{PLAYER}, por favor, necesito que\n"
    .string "vayas a encontrar la otra gema.\p"
    .string "¿{PLAYER}, me puedes dar tu PASE de\n"
    .string "transbordador y tu MAPA REGIONAL?$"

OneIsland_PokemonCenter_1F_Text_ReturnedTriPassForRainbowPass::
    .string "{PLAYER} regresó el TRI-PASE y\n"
    .string "recibió el PASE ARCOÍRIS.$"

OneIsland_PokemonCenter_1F_Text_ObtainedExtraMapPage::
    .string "¡{PLAYER} recibió una página extra\n"
    .string "para el MAPA REGIONAL!$"

OneIsland_PokemonCenter_1F_Text_PassLetYouGetToAllIslands::
    .string "Este es mi propio PASE.\p"
    .string "Te dejará llegar a todas las\n"
    .string "ISLAS SETE.\p"
    .string "{PLAYER}, por favor, no puedo\n"
    .string "hacerlo sin tu ayuda.$"

OneIsland_PokemonCenter_1F_Text_HandedSapphireToCelio::
    .string "{PLAYER} entregó el ZAFIRO\n"
    .string "a CELIO.$"

OneIsland_PokemonCenter_1F_Text_ThankYouGiveMeTime::
    .string "CELIO: Así que esta es la gema que\n"
    .string "forma un par con el RUBÍ…\p"
    .string "{PLAYER}, has pasado por mucho\n"
    .string "para obtener esto, ¿no es así?\p"
    .string "No tienes que decirmelo. Sé que\n"
    .string "no fue fácil.\p"
    .string "¡Muchas gracias!\p"
    .string "¡Ahora yo trabajaré para ti!\n"
    .string "Por favor, dame un momento.$"

OneIsland_PokemonCenter_1F_Text_OkayThisIsGood::
    .string "Bien, esto es bueno…$"

OneIsland_PokemonCenter_1F_Text_LinkedUpWithLanette::
    .string "¡Lo hice!\n"
    .string "¡Me conecté con LANETTE!$"

OneIsland_PokemonCenter_1F_Text_ManagedToLinkWithHoennThankYou::
    .string "{PLAYER}…\n"
    .string "¡{PLAYER}, lo logré!\p"
    .string "¡Logré conectarme con ENTRENADORES\n"
    .string "de la región de HOENN!\p"
    .string "¡Al fin, la Máquina de redes\n"
    .string "funciona perfectamente!\p"
    .string "¡{PLAYER}, te lo debo todo a ti!\p"
    .string "Gracias a ti, mi sueño se volvió\n"
    .string "realidad…$"

OneIsland_PokemonCenter_1F_Text_WishYouBestOfLuck::
    .string "Yo…\n"
    .string "No estoy llorando.\p"
    .string "¡Suficiente de mí!\p"
    .string "{PLAYER}, ¿vas a seguir buscando\n"
    .string "POKéMON exóticos, verdad?\p"
    .string "¡Te deseo la mejor de las suertes!$"

OneIsland_PokemonCenter_1F_Text_CelioHearingRumorsAboutYou::
    .string "CELIO: ¡Hola!\p"
    .string "{PLAYER}, he escuchado rumores\n"
    .string "sobre ti.$"

OneIsland_PokemonCenter_1F_Text_BillsFirstMonWasAbra::
    .string "{PLAYER}, ¿cúal es tu tipo de\n"
    .string "POKéMON favorito?\p"
    .string "BILL es un POKéMANIACO así que los\n"
    .string "adora a todos.\p"
    .string "Al parecer, el primero que atrapó\n"
    .string "era un ABRA.$"

OneIsland_PokemonCenter_1F_Text_BillsHometownInGoldenrod::
    .string "Por cierto, {PLAYER}, ¿tu eres de\n"
    .string "PUEBLO PALETA, cierto?\p"
    .string "Escuché que es un lugar tranquilo\n"
    .string "y agradable.\p"
    .string "BILL nació en CIUDAD VARA DE ORO,\n"
    .string "donde sigue viviendo su familia.\p"
    .string "He oído que es una ciudad festiva\n"
    .string "y animada.\p"
    .string "Me gustaría ir ahí algún día.$"

OneIsland_PokemonCenter_1F_Text_BillCantStomachMilk::
    .string "{PLAYER}, ¿hay algo que no puedas\n"
    .string "soportar?\p"
    .string "Al parecer, el estómago de BILL\n"
    .string "no puede tolerar la leche.$"

OneIsland_PokemonCenter_1F_Text_CameFromPalletDontKnowIt::
    .string "¡Oh, eres un{A} extrañ{OA}!\n"
    .string "¡Hola! ¿de dónde vienes?\p"
    .string "…¿PUEBLO PALETA?\n"
    .string "¡No lo conozco!$"

OneIsland_PokemonCenter_1F_Text_EnormousVolcanoOnIsland::
    .string "En esta isla hay un volcán enorme.\p"
    .string "No ha hecho erupción desde hace\n"
    .string "tiempo, ¿porque no disfrutar\l"
    .string "escalando?$"

OneIsland_PokemonCenter_1F_Text_WishICouldTradeWithBoyfriend::
    .string "Ojalá pudiera intercambiar POKéMON\n"
    .string "con mi novio, que vive muy lejos…$"

OneIsland_PokemonCenter_1F_Text_TradedWithFarAwayBoyfriend::
    .string "¡Intercambié POKéMON con mi novio\n"
    .string "que vive lejos!\p"
    .string "Todos dicen que es gracias a ti\n"
    .string "y a CELIO.\p"
    .string "¡Así que gracias!$"

OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment::
    .string "Máquina de redes\n"
    .string "Conexión de Nivel 0\p"
    .string "…Sistema de Almacenamiento de\n"
    .string "POKéMON bajo ajustes…$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKanto::
    .string "Máquina de redes\n"
    .string "Conexión de Nivel 1\p"
    .string "Conexión establecida con la región\n"
    .string "de KANTO.$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKantoAndHoenn::
    .string "Máquina de redes\n"
    .string "Conexión de Nivel 2\p"
    .string "Conexión establecida con las\n"
    .string "regiones de KANTO y HOENN.$"

OneIsland_PokemonCenter_1F_Text_ObtainedTriPass::
    .string "¡Obtuviste el TRI-PASE!$"

