SilphCo_4F_Text_CantYouSeeImHiding::
    .string "¡Sssh!\n"
    .string "¿No ves que me estoy escondiendo?$"

SilphCo_4F_Text_TeamRocketIsGone::
    .string "¿Huh?\n"
    .string "¿El EQUIPO ROCKET se fue?$"

SilphCo_4F_Text_Grunt1Intro::
    .string "¡El EQUIPO ROCKET tomó el control\n"
    .string "de SILPH S.A.!$"

SilphCo_4F_Text_Grunt1Defeat::
    .string "¡Arrgh!$"

SilphCo_4F_Text_Grunt1PostBattle::
    .string "¡Fuajajaja!\n"
    .string "¡Mi JEFE buscaba este lugar!$"

SilphCo_4F_Text_RodneyIntro::
    .string "Mi POKéMON es mi sirviente leal.$"

SilphCo_4F_Text_RodneyDefeat::
    .string "¡Rayos!\n"
    .string "¡Este POKéMON es débil!$"

SilphCo_4F_Text_RodneyPostBattle::
    .string "Las puertas están bloqueadas\n"
    .string "eléctronicamente.\p"
    .string "Se necesita una LLAVE MAGNÉTICA\n"
    .string "para abrir las puertas aquí.$"

SilphCo_4F_Text_Grunt2Intro::
    .string "¡Intrus{OA} avistad{OA}!$"

SilphCo_4F_Text_Grunt2Defeat::
    .string "¿Quíen eres?$"

SilphCo_4F_Text_Grunt2PostBattle::
    .string "¡Mejor le aviso al JEFE en el P11!$"

SilphCo_4F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P4$"

