PokemonMansion_1F_Text_TedIntro::
    .string "¿Quién eres?\n"
    .string "No debería haber nadie aquí.$"

PokemonMansion_1F_Text_TedDefeat::
    .string "¡Auch!$"

PokemonMansion_1F_Text_TedPostBattle::
    .string "¿Una llave? no se de que estás\n"
    .string "hablando.$"

PokemonMansion_1F_Text_JohnsonIntro::
    .string "¡G-g-guaa! ¡me asustaste!\n"
    .string "Pensé que eras un fantasma.$"

PokemonMansion_1F_Text_JohnsonDefeat::
    .string "¡Tch!\n"
    .string "No puedo ganar ni una vez.$"

PokemonMansion_1F_Text_JohnsonPostBattle::
    .string "Estaba explorando por mi cuenta,\n"
    .string "pero me estoy asustando.\p"
    .string "Creo que me iré pronto.$"

