FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
    .string "GUARDA: ¡Fif fuff fefifuu!\p"
    .string "A fof a fif ee afahi fo.\n"
    .string "¡Eff fi fuii!$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
    .string "¡Ah fafee oo foo!\n"
    .string "¡Eef ee afafi fo!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
    .string "¿Fa?\n"
    .string "¡Fe fofei feh fa oo ee fafeh!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
    .string "{PLAYER} le dió la DENTADURA DE ORO\n"
    .string "al GUARDA.$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
    .string "¡El GUARDA se puso sus dientes!$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
    .string "GUARDA: ¡Gracias, hijo!\n"
    .string "¡Eres un verdadero salvavidas!\p"
    .string "¡Nadie podía entender una palabra\n"
    .string "de lo que decía, ni una!\p"
    .string "Incluso el ir a la OFICINA me daba\n"
    .string "vergüenza.\p"
    .string "Déjame darte algo por tu esfuerzo.$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
    .string "GUARDA: ¡Gracias, señorita!\n"
    .string "¡Eres una verdadera salvavidas!\p"
    .string "¡Nadie podía entender una palabra\n"
    .string "de lo que decía, ni una!\p"
    .string "Incluso el ir a la OFICINA me daba\n"
    .string "vergüenza.\p"
    .string "Déjame darte algo por tu esfuerzo.$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
    .string "{PLAYER} recibió MO04\n"
    .string "del GUARDA.$"

FuchsiaCity_WardensHouse_Text_ExplainStrength::
    .string "GUARDA: Dentro de la MO04 se\n"
    .string "encuentra FUERZA.\p"
    .string "Le permite a un POKéMON mover\n"
    .string "piedras fuera de batalla.\p"
    .string "Ah sí, ¿encontraste la CASA\n"
    .string "SECRETA en la ZONA SAFARI?$"

@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
    .string "なんや　にもつ\n"
    .string "いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
    .string "Hay fotos y fósiles de POKéMON en\n"
    .string "exhibición.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
    .string "Hay vieja mercancía POKéMON en\n"
    .string "exhibición.$"

