SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
    .string "…¡Espera! ¡no digas una palabra!\p"
    .string "¡Tú querías esto!$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
    .string "{PLAYER} recibió MT29\n"
    .string "del SEÑOR PSÍQUICO.$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
    .string "¿Ya lo sabes, no?\n"
    .string "MT29 es PSÍQUICO.\p"
    .string "Es un ataque que puede reducir las\n"
    .string "estadísticas especiales del rival.$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
    .string "¿Dónde planeas guardar esto?\n"
    .string "No tienes espacio.$"

