RockTunnel_B1F_Text_SofiaIntro:: @ 8179657
    .string "¿Sabes como puedes evitar perderte\n"    /* (E) "Do you know how you can avoid\n" */
    .string "en las montañas?\p"                      /* (E) "getting lost in the mountains?\p" */
    .string "Puedes usar ramitas para marcar\n"       /* (E) "You can bend twigs as trail\n" */
    .string "tu camino.$"                             /* (E) "markers.$" */

RockTunnel_B1F_Text_SofiaDefeat:: @ 81796B9
    .string "¡Ohhh!\n"                                /* (E) "Ohhh!\n" */
    .string "¡Hice lo que pude!$"                     /* (E) "I did my best!$" */

RockTunnel_B1F_Text_SofiaPostBattle:: @ 81796CE
    .string "¡Quiero irme a casa!$"                   /* (E) "I want to go home!$" */

RockTunnel_B1F_Text_DudleyIntro:: @ 81796E1
    .string "¡Ja, ja, ja!\n"                          /* (E) "Hahaha!\n" */
    .string "¿Puedes vencer mi poder?$"               /* (E) "Can you beat my power?$" */

RockTunnel_B1F_Text_DudleyDefeat:: @ 8179700
    .string "¡Ups!\n"                                 /* (E) "Oops!\n" */
    .string "¡Me superaste!$"                         /* (E) "Outmuscled!$" */

RockTunnel_B1F_Text_DudleyPostBattle:: @ 8179712
    .string "Prefiero la fuerza, porque odio\n"       /* (E) "I go for power because I hate\n" */
    .string "pensar.$"                                /* (E) "thinking.$" */

RockTunnel_B1F_Text_CooperIntro:: @ 817973A
    .string "¿Tienes una POKéDEX?\n"                  /* (E) "You have a POKéDEX?\n" */
    .string "Yo también quiero una.$"                 /* (E) "I want one, too.$" */

RockTunnel_B1F_Text_CooperDefeat:: @ 817975F
    .string "¡Rayos!\n"                               /* (E) "Shoot!\n" */
    .string "¡Me das tanta envidia!$"                 /* (E) "I am so jealous!$" */

RockTunnel_B1F_Text_CooperPostBattle:: @ 8179777
    .string "Cuando termines con tu POKéDEX,\n"       /* (E) "When you finish your POKéDEX,\n" */
    .string "¿me la puedes dar?$"                     /* (E) "can I have it?$" */

RockTunnel_B1F_Text_SteveIntro:: @ 81797A4
    .string "Um… ¿Conoces el cosplay de\n"            /* (E) "Um… Do you know about POKéMON\n" */
    .string "POKéMON?$"                               /* (E) "cosplay?$" */

RockTunnel_B1F_Text_SteveDefeat:: @ 81797CB
    .string "Bueno, eso fue todo.$"                   /* (E) "Well, that's that.$" */

RockTunnel_B1F_Text_StevePostBattle:: @ 81797DE
    .string "Cosplay de POKéMON es disfrazarse\n"     /* (E) "POKéMON cosplay is dressing up as\n" */
    .string "de POKéMON por diversión.\p"             /* (E) "POKéMON for fun.\p" */
    .string "CLEFAIRY es un favorito para eso.$"      /* (E) "CLEFAIRY is a favorite.$" */

RockTunnel_B1F_Text_AllenIntro:: @ 8179829
    .string "¡Mis técnicas de POKéMON te\n"           /* (E) "My POKéMON techniques will leave\n" */
    .string "dejarán llorando!$"                      /* (E) "you crying!$" */

RockTunnel_B1F_Text_AllenDefeat:: @ 8179856
    .string "¡Me rindo!\n"                            /* (E) "I give!\n" */
    .string "¡Tus técnicas son mejores!$"             /* (E) "You're a better technician!$" */

RockTunnel_B1F_Text_AllenPostBattle:: @ 817987A
    .string "En las montañas es fácil encontrar\n"    /* (E) "In mountains, you'll often find\n" */
    .string "POKéMON de tipo ROCA.$"                  /* (E) "ROCK-type POKéMON.$" */

RockTunnel_B1F_Text_MarthaIntro:: @ 81798AD
    .string "No suelo venir aquí, pero lucharé\n"     /* (E) "I don't often come here, but I will\n" */
    .string "contigo.$"                               /* (E) "battle you.$" */

RockTunnel_B1F_Text_MarthaDefeat:: @ 81798DD
    .string "¡Oh!\n"                                  /* (E) "Oh!\n" */
    .string "¡Perdí!$"                                /* (E) "I lost!$" */

RockTunnel_B1F_Text_MarthaPostBattle:: @ 81798E9
    .string "Me gustan los POKéMON pequeños.\n"       /* (E) "I like tiny POKéMON.\n" */
    .string "¡Los grandes dan mucho miedo!$"          /* (E) "Big ones are too scary!$" */

RockTunnel_B1F_Text_EricIntro:: @ 8179916
    .string "¡Lánzame tu mejor ataque!$"              /* (E) "Hit me with your best shot!$" */

RockTunnel_B1F_Text_EricDefeat:: @ 8179932
    .string "¡Me venciste!$"                          /* (E) "Fired away!$" */

RockTunnel_B1F_Text_EricPostBattle:: @ 817993E
    .string "Criaré a mis POKéMON para vencer\n"      /* (E) "I'll raise my POKéMON to beat\n" */
    .string "a los tuyos, niñ{OA}.$"                  /* (E) "yours, kid.$" */

RockTunnel_B1F_Text_WinstonIntro:: @ 8179968
    .string "Dibujo a varios POKéMON cuando\n"        /* (E) "I draw illustrations of POKéMON\n" */
    .string "estoy en casa.$"                         /* (E) "when I'm home.$" */

RockTunnel_B1F_Text_WinstonDefeat:: @ 8179997
    .string "Fiu…\n"                                  /* (E) "Whew…\n" */
    .string "Estoy exhausto…$"                        /* (E) "I'm exhausted…$" */

RockTunnel_B1F_Text_WinstonPostBattle:: @ 81799AC
    .string "Soy un artista, no un luchador.\n"       /* (E) "I'm an artist, not a fighter.\n" */
    .string "Me iré a casa a dibujar.$"               /* (E) "I'll go home to draw.$" */

