CeladonCity_Condominiums_1F_Text_Meowth::
    .string "MEOWTH: ¡Meow!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "No deberías gastar todo tu dinero\n"
    .string "en bebidas.\p"
    .string "Mejor prueba esto.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "Nada vence a la sed como un TÉ\n"
    .string "caliente.\p"
    .string "Realmente es lo mejor.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .string "Mis queridos POKéMON me acompañan.\n"
    .string "¡MEOWTH hasta trae dinero a casa!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .string "Oh, hola, querid{OA}.\n"
    .string "¿Disfrutaste mi TÉ?\p"
    .string "Por cierto, querid{OA}. ¿Eres,\n"
    .string "por casualidad, de PUEBLO PALETA?\p"
    .string "Una chica del PUEBLO PALETA,\n"
    .string "DAISY, disfruta del TÉ cada día.\p"
    .string "Ella visita la TIENDA DEPARTAMENTAL\n"
    .string "PRISMA para comprar algo de TÉ.$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "CLEFAIRY: ¡Pi pippippi!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "NIDORAN♀: ¡Kya kyaoo!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .string "MANSIÓN PRISMA\n"
    .string "Suite presidencial$"

