CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
    .string "Una POKé FLAUTA despierta a los\n"
    .string "POKéMON dormidos. Ya sabes eso.\p"
    .string "Lo hace con un sonido que solo\n"
    .string "ellos pueden escuchar.$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
    .string "Pedaleé aquí desde FUCSIA.\p"
    .string "Es un viaje cuesta arriba en la\n"
    .string "CICLOVÍA, así que estoy exhausta.$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
    .string "¡Si tuviera una BICICLETA, iría\n"
    .string "a la CICLOVÍA!$"

