FuchsiaCity_Mart_Text_DontTheyHaveSafariZonePennants::
    .string "¿No tendrán algún banderín para\n"
    .string "promocionar la ZONA SAFARI?\p"
    .string "¿Qué tal unas linternas de papel?\n"
    .string "¿Tienen calendarios al menos?$"

FuchsiaCity_Mart_Text_DidYouTryXSpeed::
    .string "¿Probaste VELOCIDAD X?\n"
    .string "Aumenta la VELOCIDAD de un POKéMON\l"
    .string "en batalla.$"
