Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend::
    .string "Voy a ir a un relajante paseo en\n"
    .string "bicicleta con mi novia.$"

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes::
    .string "Vamos a pasear juntos con nuestras\n"
    .string "nuevas bicicletas.$"

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore::
    .string "Veamos lo que estos binoculares\n"
    .string "tienen para mostrar…\p"
    .string "¡Es la TIENDA DEPT. PRISMA!$"

Route16_NorthEntrance_2F_Text_LongPathOverWater::
    .string "Veamos lo que estos binoculares\n"
    .string "tienen para mostrar…\p"
    .string "Hay un largo camino sobre el agua\n"
    .string "a lo lejos.$"

Route16_NorthEntrance_2F_Text_GiveAmuletCoinIfCaught40::
    .string "¡Hola! ¿me recuerdas?\n"
    .string "Soy uno de los AYUDANTES del\l"
    .string "PROF. OAK.\p"
    .string "Si tu POKéDEX tiene datos completos\n"
    .string "de 40 especies, se supone que\l"
    .string "debería darte una recompensa.\p"
    .string "El PROF. OAK me encargo una\n"
    .string "MONEDA AMULETO para ti.\p"
    .string "Entonces, {PLAYER}, dime algo.\p"
    .string "¿Ya recolectaste datos de al menos\n"
    .string "40 tipos de POKéMON?$"

Route16_NorthEntrance_2F_Text_GreatHereYouGo::
    .string "¡Bien! ¡atrapaste u obtuviste\n"
    .string "{STR_VAR_3} tipos de POKéMON!\p"
    .string "¡Felicidades!\n"
    .string "¡Aquí tienes!$"

Route16_NorthEntrance_2F_Text_ReceivedAmuletCoinFromAide::
    .string "{PLAYER} recibió la MONEDA AMULETO\n"
    .string "del AYUDANTE.$"

Route16_NorthEntrance_2F_Text_ExplainAmuletCoin::
    .string "Las MONEDAS AMULETO son objetos\n"
    .string "que debe llevar un POKéMON.\p"
    .string "Si ganas una batalla y su portador\n"
    .string "participa, ganarás más dinero.$"
