FuchsiaCity_Text_DidYouTrySafariGame::
    .string "¿Probaste el JUEGO SAFARI?\p"
    .string "Hay algunos POKéMON raros que solo\n"
    .string "se pueden atrapar ahí.$"

FuchsiaCity_Text_SafariZoneZooInFront::
    .string "La ZONA SAFARI tiene un zoológico\n"
    .string "frente a la entrada.\p"
    .string "En la parte de atrás está el\n"
    .string "JUEGO SAFARI para atrapar POKéMON.$"

FuchsiaCity_Text_WheresSara::
    .string "ERIK: ¿Dónde está SARA?\n"
    .string "Dijo que la vería aquí.$"

FuchsiaCity_Text_ItemBallInThere::
    .string "Ese objeto redondo de ahí…\n"
    .string "¿Lo quieres?\p"
    .string "¡Yo también!\n"
    .string "…¿Ah? ¿es un POKéMON?$"

FuchsiaCity_Text_CitySign::
    .string "CIUDAD FUCSIA\n"
    .string "¡Observa! ¡es pasión rosa!$"

FuchsiaCity_Text_SafariZoneSign::
    .string "PARAÍSO POKéMON\n"
    .string "ZONA SAFARI$"

FuchsiaCity_Text_SafariGameSign::
    .string "JUEGO SAFARI\n"
    .string "¡ATRAPA-POKéMON!$"

FuchsiaCity_Text_WardensHomeSign::
    .string "ZONA SAFARI\n"
    .string "CASA DEL GUARDA$"

FuchsiaCity_Text_SafariZoneOfficeSign::
    .string "¡PARAÍSO POKéMON!\n"
    .string "¡BIENVENIDOS A LA ZONA SAFARI!\l"
    .string "OFICINA DE LA ZONA SAFARI$"

FuchsiaCity_Text_GymSign::
    .string "GIMNASIO POKéMON DE CIUDAD FUCSIA\n"
    .string "LÍDER: KOGA\l"
    .string "El venenoso maestro ninja$"

FuchsiaCity_Text_ChanseySign::
    .string "Nombre: CHANSEY\n"
    .string "Atrapar uno depende de la suerte.$"

FuchsiaCity_Text_VoltorbSign::
    .string "Nombre: VOLTORB\n"
    .string "La viva imagen de una POKÉBOLA.$"

FuchsiaCity_Text_KangaskhanSign::
    .string "Nombre: KANGASKHAN\p"
    .string "POKéMON maternal que cría a sus\n"
    .string "hijos en una bolsa en su vientre.$"

FuchsiaCity_Text_SlowpokeSign::
    .string "Nombre: SLOWPOKE\n"
    .string "Amigable y de movimiento lento.$"

FuchsiaCity_Text_LaprasSign::
    .string "Nombre: LAPRAS\n"
    .string "Tambíen conocido como el rey\l"
    .string "de los mares.$"

FuchsiaCity_Text_OmanyteSign::
    .string "Nombre: OMANYTE\n"
    .string "Un POKéMON extremadamente raro que\l"
    .string "fue regenerado de un fósil.$"

FuchsiaCity_Text_KabutoSign::
    .string "Nombre: KABUTO\n"
    .string "Un POKéMON extremadamente raro que\l"
    .string "fue regenerado de un fósil.$"

@ Unused. May have been meant to be the placeholder text for the zoo mons, similar to RB's "!" text
FuchsiaCity_Text_Ellipsis::
    .string "……$"

Text_SubstituteTeach::
    .string "Aww, quisiera ser un bebé de\n"
    .string "KANGASKHAN.\p"
    .string "Me encantaría sustituir a ese\n"
    .string "bebé…\p"
    .string "Y acurrucarme en la bolsa de la\n"
    .string "KANGASKHAN madre.\p"
    .string "Pero solo los POKéMON pueden usar\n"
    .string "técnicas como SUSTITUTO…\p"
    .string "¿Quieres que le enseñe SUSTITUTO a\n"
    .string "uno de tus POKéMON?$"

Text_SubstituteDeclined::
    .string "¿Oh, en serio?\n"
    .string "Si SUSTITUTO parece genial…$"

Text_SubstituteWhichMon::
    .string "¿Qué POKéMON quiere aprender\n"
    .string "SUSTITUTO?$"

Text_SubstituteTaught::
    .string "Lo que daría por meterme en la\n"
    .string "bolsa de un KANGASKHAN…$"

FuchsiaCity_Text_MyFatherIsGymLeader::
    .string "Mi padre es el LÍDER DE GIMNASIO\n"
    .string "de esta ciudad.\p"
    .string "Entreno para usar POKéMON de tipo\n"
    .string "VENENO tan bien como mi padre.$"

