ThreeIsland_DunsparceTunnel_Text_ProspectingForGold::
    .string "¡Hola!\n"
    .string "¿Cómo te va?\p"
    .string "¿Qué estoy haciendo aquí?\n"
    .string "¡Estoy excavando en busca de oro!\p"
    .string "Cuando me haga rico, compraré\n"
    .string "una casa en KANTO.$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou::
    .string "¡Hola! ¿cómo te va?\n"
    .string "¿Escuchaste? ¡encontré oro!\p"
    .string "¿Recuerdas que estaba excavando,\n"
    .string "cierto?\p"
    .string "No puedes empezar a imaginar\n"
    .string "lo feliz que estoy.\p"
    .string "¡Así que te lo mostraré!\n"
    .string "¡Esto es para ti!$"

ThreeIsland_DunsparceTunnel_Text_ThatsANugget::
    .string "¡Esa es una PEPITA!\p"
    .string "No puedo darte pepitas de\n"
    .string "sabiduría, ¡lo siento!$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull::
    .string "¡Ups, tu MOCHILA está llena!\n"
    .string "Te daré esto después.$"

