ThreeIsland_Text_IslandSign::
    .string "ISLA TERA\n"
    .string "Isla Familiar$"

ThreeIsland_Text_IslandBelongsToUs::
    .string "¡Yajuu!\p"
    .string "¡Desde este día, esta isla nos\n"
    .string "pertenece!$"

ThreeIsland_Text_GoBackToKanto::
    .string "¡No necesitamos que vengan aquí\n"
    .string "con su ruido y sus problemas!\p"
    .string "¡Les pedimos que regresen a KANTO!$"

ThreeIsland_Text_BossIsOnHisWay::
    .string "Ey, ve a llorar a otro lado.\n"
    .string "Nuestro jefe está en camino.\p"
    .string "¡Cuando llegue, les daremos un\n"
    .string "show de motocicletas que no\l"
    .string "podrán olvidar!$"

ThreeIsland_Text_GetOffIslandNow::
    .string "¿¡Q-qué!? ¡jámas!\n"
    .string "¡Sal de la isla ahora!$"

ThreeIsland_Text_WhosGonnaMakeMe::
    .string "¿Quién me va a obligar?$"

ThreeIsland_Text_AreYouBossGoBackToKanto::
    .string "¿Tu eres el jefe?\n"
    .string "¡Vuelvan a KANTO ahora mismo!$"

ThreeIsland_Text_JustGotHerePal::
    .string "¿Jah?\p"
    .string "Acabo de llegar, amigo.\p"
    .string "¿Por qué esa actitud hostil?\n"
    .string "¡Es muy frío de tu parte!$"

ThreeIsland_Text_FollowersRaisingHavoc::
    .string "Tus seguidores han creado caos\n"
    .string "con sus motocicletas.\p"
    .string "¿Tienes idea del problema que han\n"
    .string "causado en la isla?$"

ThreeIsland_Text_OughtToBeThankingUs::
    .string "No, viejo, no lo entiendo.\p"
    .string "Mira este lugar.\n"
    .string "¿Qué hacen para entretenerse?\p"
    .string "Deberían agradecernos por darle\n"
    .string "vida a esta aburrida isla.\p"
    .string "Pero, si insistes, puedes\n"
    .string "intentar obligarnos a irnos.$"

ThreeIsland_Text_YouCowardsToughInPack::
    .string "Grr… Cobardes…\n"
    .string "Tan rudos en grupo…$"

ThreeIsland_Text_WannaMakeSomethingOfYourStaring::
    .string "Tú, ¿qué estas mirando?\n"
    .string "¿No sabes que eso es grosero?\p"
    .string "¿Quieres hacer algo al respecto\n"
    .string "o qué?$"

ThreeIsland_Text_ThatsSmart::
    .string "Eres list{OA}.\n"
    .string "Mantente fuera de esto.$"

ThreeIsland_Text_Biker1Intro::
    .string "Jeh, me gusta tu valor.\n"
    .string "Aunque perderás tu dinero…$"

ThreeIsland_Text_Biker1Defeat::
    .string "Qu…\n"
    .string "¿¡Quién eres!?$"

ThreeIsland_Text_Biker1PostBattle::
    .string "Aww, hombre…\n"
    .string "¡No te atrevas a reirte!$"

ThreeIsland_Text_Biker2Intro::
    .string "¿No eres de KANTO?\n"
    .string "¡Deberías estar de nuestro lado!$"

ThreeIsland_Text_Biker2Defeat::
    .string "¡Basta de tonterías!$"

ThreeIsland_Text_Biker2PostBattle::
    .string "¿Qué pasa contigo, enojandote de\n"
    .string "esa forma?\p"
    .string "¡Eso no es nada genial!$"

ThreeIsland_Text_Biker3Intro::
    .string "¡Invitamos al jefe aquí, pero\n"
    .string "tenías que arruinarlo!\p"
    .string "¡Nos avergüenzas!$"

ThreeIsland_Text_Biker3Defeat::
    .string "… … …   … … …$"

ThreeIsland_Text_Biker3PostBattle::
    .string "¡Jefe, en serio, tiene que hacer\n"
    .string "algo con es{EA} niñ{OA}!$"

ThreeIsland_Text_PaxtonIntro::
    .string "Te estaba observando, y diría\n"
    .string "que has hecho demasiado.\p"
    .string "¿Qué eres tú, su amig{OA} o algo?\p"
    .string "Entonces, supongo que tendrás que\n"
    .string "enfrentarme en su lugar.$"

ThreeIsland_Text_PaxtonDefeat::
    .string "¡De acuerdo, es suficiente!\n"
    .string "¡Nos iremos como querían!\p"
    .string "¡Nos alegrará ver esta aburrida\n"
    .string "isla por última vez!$"

ThreeIsland_Text_PaxtonPostBattle::
    .string "¡Humph! ¡quédate un rato con estos\n"
    .string "aburridos!$"

ThreeIsland_Text_ThankYouOhYourMonGotHurt::
    .string "¡Gracias! esos tipos no eran más\n"
    .string "que un gran problema.\p"
    .string "Oh, tus POKéMON están heridos por\n"
    .string "mi culpa.$"

ThreeIsland_Text_GivenFullRestore::
    .string "{PLAYER} recibió un\n"
    .string "RESTAURA TODO.$"

ThreeIsland_Text_OhYourBagIsFull::
    .string "¿Oh?\n"
    .string "Tu MOCHILA está llena.$"

ThreeIsland_Text_YouveGotImpressiveMons::
    .string "Tienes unos POKéMON impresionantes\n"
    .string "contigo.$"

ThreeIsland_Text_LostelleWentOffTowardsBondBridge::
    .string "Sería fantastico si alguien tan\n"
    .string "fuerte como tú viviera aquí.\p"
    .string "Espero que al menos te quedes por\n"
    .string "un tiempo.\p"
    .string "…¿Perdón?\n"
    .string "¿Estás buscando a LOSTELLE?\p"
    .string "Hace tiempo se fue hacia el\n"
    .string "PUENTE UNIÓN.$"

ThreeIsland_Text_WouldntWantToSeeBikersHereAgain::
    .string "ISLA TERA es la isla más poblada\n"
    .string "en esta región.\p"
    .string "Aún así, podría ser más animada.\p"
    .string "Pero no quiero volver a ver a\n"
    .string "tipos como esos MOTORISTAS aquí.$"

ThreeIsland_Text_WhenDodouEvolvesGoingToPlayGame::
    .string "Voy a entrenar a mi DODUO en el\n"
    .string "BOSQUE BAYA.\p"
    .string "Cuando evolucione, voy a llevarlo\n"
    .string "a un juego en ISLA SECUNDA.$"

ThreeIsland_Text_Doduo::
    .string "DODUO: ¡Gigiih!$"

