CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji::
    .string "Es una foto de BLAINE y\n"
    .string "el SR. FUJI.\p"
    .string "Están de pie juntos con\n"
    .string "grandes sonrisas.$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
    .string "Estudiamos a los POKéMON de forma\n"
    .string "extensa todos los días.\p"
    .string "La gente suele traernos POKéMON\n"
    .string "raros para analizarlos.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
    .string "Una FOTO del fundador del\n"
    .string "LABORATORIO…\p"
    .string "¡¿El DR. FUJI?!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
    .string "LABORATORIO POKéMON\n"
    .string "Sala de reuniones$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
    .string "LABORATORIO POKéMON\n"
    .string "Sala de I y D$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
    .string "LABORATORIO POKéMON\n"
    .string "Sala de pruebas$"

