MtMoon_1F_Text_MarcosIntro:: @ 817279D
    .string "¡WHOA!\n"
    .string "¡Me sorprendiste!\l"
    .string "…Oh, ¡solo eres un{A} niñ{OA}!$"

MtMoon_1F_Text_MarcosDefeat:: @ 81727CB
    .string "¡Wow!\n"
    .string "¡Sorprendido otra vez!$"

MtMoon_1F_Text_MarcosPostBattle:: @ 81727DF
    .string "Niñ{OA}s cómo tu no deberían\n"
    .string "merodear por aquí.$"

MtMoon_1F_Text_JoshIntro:: @ 817281D
    .string "¿También viniste para explorar\n"
    .string "la cueva?$"

MtMoon_1F_Text_JoshDefeat:: @ 8172844
    .string "¡Perder apesta!\n"
    .string "Es de lo peor.$"

MtMoon_1F_Text_JoshPostBattle:: @ 8172863
    .string "Vine hasta aquí para impresionar\n"
    .string "a las chicas.$"

MtMoon_1F_Text_MiriamIntro:: @ 8172896
    .string "¡Wow! ¡Este lugar es mucho más\n"
    .string "grande de lo que creía!$"

MtMoon_1F_Text_MiriamDefeat:: @ 81728C3
    .string "¡Oh!\n"
    .string "¡Perdí la batalla!$"

MtMoon_1F_Text_MiriamPostBattle:: @ 81728D2
    .string "¿Cómo se sale de aquí?\n"
    .string "Es muy grande, tal vez me pierda.$"

MtMoon_1F_Text_JovanIntro:: @ 817290B
    .string "¡Eh!\n"
    .string "¡No intentes escabullirte!$"

MtMoon_1F_Text_JovanDefeat:: @ 8172927
    .string "¡Mis POKéMON no lo lograron!$"

MtMoon_1F_Text_JovanPostBattle:: @ 817293C
    .string "Debo encontrar POKéMON\n"
    .string "más fuertes. ¿Dónde estarán?$"

MtMoon_1F_Text_IrisIntro:: @ 8172972
    .string "¿Qué?\n"
    .string "Estoy esperando a que mis amigos\l"
    .string "me encuentren aquí.$"

MtMoon_1F_Text_IrisDefeat:: @ 81729A4
    .string "¿Perdí?$"

MtMoon_1F_Text_IrisPostBattle:: @ 81729AC
    .string "Vine porque escuche por aquí hay\n"
    .string "unos fósiles muy raros.$"

MtMoon_1F_Text_KentIntro:: @ 81729EA
    .string "Hay hombres sospechosos en la cueva.\n"
    .string "¿Qué hay de ti?$"

MtMoon_1F_Text_KentDefeat:: @ 8172A1A
    .string "¡Me venciste!$"

MtMoon_1F_Text_KentPostBattle:: @ 8172A26
    .string "¡Los ví!\n"
    .string "¡Estoy seguro de que son del\l"
    .string "EQUIPO ROCKET!$"

MtMoon_1F_Text_RobbyIntro:: @ 8172A55
    .string "Necesitas cruzar esta cueva para\n"
    .string "llegar a CIUDAD CELESTE.$"

MtMoon_1F_Text_RobbyDefeat:: @ 8172A8F
    .string "Perdí.$"

MtMoon_1F_Text_RobbyPostBattle:: @ 8172A97
    .string "¡ZUBAT is duro!\n"
    .string "Pero si atrapas uno, podrás contar\l"
    .string "con el.$"

MtMoon_1F_Text_ZubatIsABloodsucker:: @ 8172AE0
    .string "¡Cuidado!\n"
    .string "¡Los ZUBAT chupan sangre!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils:: @ 8172B00
    .string "Hola, estoy excavando para buscar\n"
    .string "fósiles aquí en el MONTE LUNA.\p"
    .string "A veces me ayuda BROCK,\n"
    .string "del GIMNASIO de PLATEADA.$"
