MtMoon_1F_Text_MarcosIntro::
    .string "¡WHOA!\n"
    .string "¡Me sorprendiste!\l"
    .string "…Oh, ¡solo eres un{A} niñ{OA}!$"

MtMoon_1F_Text_MarcosDefeat::
    .string "¡Wow!\n"
    .string "¡Sorprendido otra vez!$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "Niñ{OA}s cómo tu no deberían\n"
    .string "merodear por aquí.$"

MtMoon_1F_Text_JoshIntro::
    .string "¿También viniste para explorar\n"
    .string "la cueva?$"

MtMoon_1F_Text_JoshDefeat::
    .string "¡Perder apesta!\n"
    .string "Es de lo peor.$"

MtMoon_1F_Text_JoshPostBattle::
    .string "Vine hasta aquí para impresionar\n"
    .string "a las chicas.$"

MtMoon_1F_Text_MiriamIntro::
    .string "¡Wow! ¡Este lugar es mucho más\n"
    .string "grande de lo que creía!$"

MtMoon_1F_Text_MiriamDefeat::
    .string "¡Oh!\n"
    .string "¡Perdí la batalla!$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "¿Cómo se sale de aquí?\n"
    .string "Es muy grande, tal vez me pierda.$"

MtMoon_1F_Text_JovanIntro::
    .string "¡Eh!\n"
    .string "¡No intentes escabullirte!$"

MtMoon_1F_Text_JovanDefeat::
    .string "¡Mis POKéMON no lo lograron!$"

MtMoon_1F_Text_JovanPostBattle::
    .string "Debo encontrar POKéMON\n"
    .string "más fuertes. ¿Dónde estarán?$"

MtMoon_1F_Text_IrisIntro::
    .string "¿Qué?\n"
    .string "Estoy esperando a que mis amigos\l"
    .string "me encuentren aquí.$"

MtMoon_1F_Text_IrisDefeat::
    .string "¿Perdí?$"

MtMoon_1F_Text_IrisPostBattle::
    .string "Vine porque escuche por aquí hay\n"
    .string "unos fósiles muy raros.$"

MtMoon_1F_Text_KentIntro::
    .string "Hay hombres sospechosos en la cueva.\n"
    .string "¿Qué hay de ti?$"

MtMoon_1F_Text_KentDefeat::
    .string "¡Me venciste!$"

MtMoon_1F_Text_KentPostBattle::
    .string "¡Los ví!\n"
    .string "¡Estoy seguro de que son del\l"
    .string "EQUIPO ROCKET!$"

MtMoon_1F_Text_RobbyIntro::
    .string "Necesitas cruzar esta cueva para\n"
    .string "llegar a CIUDAD CELESTE.$"

MtMoon_1F_Text_RobbyDefeat::
    .string "Perdí.$"

MtMoon_1F_Text_RobbyPostBattle::
    .string "¡ZUBAT is duro!\n"
    .string "Pero si atrapas uno, podrás contar\l"
    .string "con el.$"

MtMoon_1F_Text_ZubatIsABloodsucker::
    .string "¡Cuidado!\n"
    .string "¡Los ZUBAT chupan sangre!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "Hola, estoy excavando para buscar\n"
    .string "fósiles aquí en el MONTE LUNA.\p"
    .string "A veces me ayuda BROCK,\n"
    .string "del GIMNASIO de PLATEADA.$"
