PokemonMansion_B1F_Text_LewisIntro::
    .string "Oh-oh…\n"
    .string "¿Dónde estoy ahora?$"

PokemonMansion_B1F_Text_LewisDefeat::
    .string "¡Auuu!$"

PokemonMansion_B1F_Text_LewisPostBattle::
    .string "Hay muchas cosas en el suelo.\p"
    .string "Seguro los que vivían aquí las\n"
    .string "dejaron.$"

PokemonMansion_B1F_Text_IvanIntro::
    .string "Este lugar es ideal para\n"
    .string "un laboratorio.\p"
    .string "Mira todo este espacio.$"

PokemonMansion_B1F_Text_IvanDefeat::
    .string "¿Para qué fue eso?$"

PokemonMansion_B1F_Text_IvanPostBattle::
    .string "Me gusta este lugar.\n"
    .string "Es favorable para mis estudios.$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
    .string "Diario: 1 de Septiembre\n"
    .string "MEWTWO es demasiado poderoso.\p"
    .string "Fallamos en frenar sus tendencias\n"
    .string "violentas…$"

