VermilionCity_PokemonFanClub_Text_AdmirePikachusTail:: @ 819446F
    .string "¿No quieres admirar la adorable\n"
    .string "cola de mi PIKACHU?$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute:: @ 819449C
    .string "¡Humph!\p"
    .string "¡Mi PIKACHU es el doble de lindo\n"
    .string "que ese!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel:: @ 81944CC
    .string "¡Simplemente adoro a mi SEEL!\n"
    .string "¡Es tan encantador!\p"
    .string "¡Chilla “Kyuuuh,” cúando lo\n"
    .string "abrazo!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive:: @ 8194518
    .string "¡Oh, querid{OA}!\p"
    .string "Mi SEEL es  mucho más atractivo.\n"
    .string "Incluso el doble de atractivo.$"

VermilionCity_PokemonFanClub_Text_Pikachu:: @ 819455A
    .string "PIKACHU: ¡Chu! ¡Pikachu!$"

VermilionCity_PokemonFanClub_Text_Seel:: @ 8194571
    .string "SEEL: ¡Kyuoo!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons:: @ 819457E
    .string "¡Soy PRESIDENTE del Club de Fans\n"
    .string "de POKéMON!\p"
    .string "¡He criado a más de cien\n"
    .string "POKéMON!\p"
    .string "¡Soy muy particular cúando se\n"
    .string "trata de POKéMON! ¡Sí que lo soy!\p"
    .string "Así que…\p"
    .string "¿Viniste de visita a escuchar\n"
    .string "sobre mis POKéMON?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory:: @ 8194628
    .string "¡Biem!\n"
    .string "¡Entonces escucha!\p"
    .string "Mi RAPIDASH favorito…\p"
    .string "Es…lindo…encantador…listo…\n"
    .string "y además…asombroso…¿no lo crees?…\l"
    .string "oh sí…es…impresionante…\l"
    .string "kindly…love it!\p"
    .string "Hug it…when…sleeping…warm\n"
    .string "and cuddly…spectacular…\l"
    .string "ravishing…\l"
    .string "…Oops! Look at the time!\l"
    .string "I kept you too long!\p"
    .string "Thanks for hearing me out!\n"
    .string "I want you to have this!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman:: @ 819474E
    .string "{PLAYER} received a BIKE VOUCHER\n"
    .string "from the CHAIRMAN.$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher:: @ 819477C
    .string "Take that BIKE VOUCHER to the\n"
    .string "BIKE SHOP in CERULEAN CITY.\p"
    .string "Exchange that for a BICYCLE\n"
    .string "free of charge!\p"
    .string "Don't worry, my favorite FEAROW\n"
    .string "will FLY me anywhere I need to go.\p"
    .string "So, I have no need for a BICYCLE.\p"
    .string "I hope you like cycling!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory:: @ 8194860
    .string "Oh. Come back when you want to\n"
    .string "hear my story!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain:: @ 819488E
    .string "Hello, {PLAYER}!\p"
    .string "Did you come see me about my\n"
    .string "POKéMON again?\p"
    .string "No?\n"
    .string "Too bad!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis:: @ 81948D2
    .string "Make room for this!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon:: @ 81948E6
    .string "Our CHAIRMAN is very vocal about\n"
    .string "POKéMON.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers:: @ 8194910
    .string "Let's all listen politely to other\n"
    .string "TRAINERS!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack:: @ 819493D
    .string "If someone brags, brag right back!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons:: @ 8194960
    .string "Our CHAIRMAN really does adore his\n"
    .string "POKéMON.\p"
    .string "But the person who is most liked by\n"
    .string "POKéMON is DAISY, I think.$"
