VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
    .string "¿No quieres admirar la adorable\n"
    .string "cola de mi PIKACHU?$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
    .string "¡Humph!\p"
    .string "¡Mi PIKACHU es el doble de lindo\n"
    .string "que ese!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
    .string "¡Simplemente adoro a mi SEEL!\n"
    .string "¡Es tan encantador!\p"
    .string "¡Chilla “Kyuuuh,” cúando lo\n"
    .string "abrazo!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
    .string "¡Oh, querid{OA}!\p"
    .string "Mi SEEL es  mucho más atractivo.\n"
    .string "Incluso el doble de atractivo.$"

VermilionCity_PokemonFanClub_Text_Pikachu::
    .string "PIKACHU: ¡Chu! ¡Pikachu!$"

VermilionCity_PokemonFanClub_Text_Seel::
    .string "SEEL: ¡Kyuoo!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
    .string "¡Soy PRESIDENTE del Club de Fans\n"
    .string "de POKéMON!\p"
    .string "¡He criado a más de cien\n"
    .string "POKéMON!\p"
    .string "¡Soy muy particular cúando se\n"
    .string "trata de POKéMON! ¡Sí que lo soy!\p"
    .string "Así que…\p"
    .string "¿Viniste de visita a escuchar\n"
    .string "sobre mis POKéMON?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
    .string "¡Bien!\n"
    .string "¡Entonces escucha!\p"
    .string "Mi RAPIDASH favorito…\p"
    .string "Es…lindo…encantador…listo…\n"
    .string "y además…asombroso…¿no lo crees?…\l"
    .string "oh sí…es…impresionante…\l"
    .string "amable…¡lo amo!\p"
    .string "Abrazarlo…cúando…duermo…cálido\n"
    .string "y suave…espectacular…\l"
    .string "maravilloso…\l"
    .string "…¡Ups! ¡Mira la hora!\l"
    .string "¡Te mantuve aquí por mucho tiempo!\p"
    .string "¡Gracias por escucharme!\n"
    .string "¡Quiero que tengas esto!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
    .string "{PLAYER} recibió un BONO BICICLETA\n"
    .string "del PRESIDENTE.$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
    .string "Lleva ese BONO a la TIENDA\n"
    .string "DE BICICLETAS en CIUDAD CELESTE.\p"
    .string "¡Cámbialo por una BICICLETA\n"
    .string "gratuita!\p"
    .string "No temas, mi FEAROW favorito me\n"
    .string "llevará VOLANDO adónde necesite.\p"
    .string "Así que, no necesito una BICI.\p"
    .string "¡Espero que te guste el ciclismo!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
    .string "Oh. ¡Vuelve cúando quieras\n"
    .string "escuchar mi historia!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
    .string "¡Hola, {PLAYER}!\p"
    .string "¿Viniste a escuchar sobre mis\n"
    .string "POKéMON otra vez?\p"
    .string "¿No?\n"
    .string "¡Qué mal!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
    .string "¡Haz espacio para esto!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
    .string "Nuestro PRESIDENTE es muy vocal\n"
    .string "sobre los POKéMON.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
    .string "¡Escuchemos todos a otros\n"
    .string "ENTRENADORES educadamente!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
    .string "Si alguien alardea, ¡alardea\n"
    .string "de vuelta!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
    .string "Nuestro PRESIDENTE realmente adora\n"
    .string "a sus POKéMON.\p"
    .string "Pero de todos, los POKéMON parecen\n"
    .string "preferir a DAISY.$"
