FuchsiaCity_House1_Text_WardenIsOldHasFalseTeeth::
    .string "El GUARDA de la ZONA SAFARI es\n"
    .string "viejo, pero sigue estando activo.\p"
    .string "Aunque sus dientes son postizos.$"

FuchsiaCity_House1_Text_BillIsMyGrandson::
    .string "¿Mmm?\n"
    .string "¿Conoces a BILL?\p"
    .string "¡Es mi nieto!\p"
    .string "¡Siempre le gustó coleccionar\n"
    .string "cosas, incluso de niño!$"

FuchsiaCity_House1_Text_BillFilesHisOwnMonData::
    .string "BILL registra los datos de sus\n"
    .string "POKéMON en su PC.\p"
    .string "¿Te los enseñó?$"

