SaffronCity_CopycatsHouse_1F_Text_DaughterIsSelfCentered::
    .string "Mi hija es muy egocéntrica.\n"
    .string "Tiene pocos amigos.$"

SaffronCity_CopycatsHouse_1F_Text_DaughterLikesToMimicPeople::
    .string "A mi hija le gusta imitar a otros.\n"
    .string "Es bastante molesto.\p"
    .string "Su mímica le dió el apodo de\n"
    .string "IMITADORA por aquí.$"

SaffronCity_CopycatsHouse_1F_Text_Chansey::
    .string "CHANSEY: ¡Chaan! ¡sii!$"

