PokemonTower_7F_Text_Grunt1Intro::
    .string "¿Qué quieres?\n"
    .string "¿Por qué estás aquí?$"

PokemonTower_7F_Text_Grunt1Defeat::
    .string "¡Me rindo!$"

PokemonTower_7F_Text_Grunt1PostBattle::
    .string "¡No olvidaré esto!$"

PokemonTower_7F_Text_Grunt2Intro::
    .string "Este viejo marchó directo hacia\n"
    .string "nuestra GUARIDA.\p"
    .string "Luego, empezó a decir que el\n"
    .string "EQUIPO ROCKET abusa a los POKéMON.\p"
    .string "Entonces, lo estamos resolviendo\n"
    .string "con palabras como adultos.$"

PokemonTower_7F_Text_Grunt2Defeat::
    .string "¡Por favor!\n"
    .string "¡Basta!$"

PokemonTower_7F_Text_Grunt2PostBattle::
    .string "Los POKéMON solo sirven para hacer\n"
    .string "dinero. ¿Por qué no usarlos?\p"
    .string "¡No te metas en nuestro negocio!$"

PokemonTower_7F_Text_Grunt3Intro::
    .string "¡No salvarás a nadie, niñ{OA}!$"

PokemonTower_7F_Text_Grunt3Defeat::
    .string "¡No luches contra nosotros, los ROCKET!$"

PokemonTower_7F_Text_Grunt3PostBattle::
    .string "¡No te saldrás con la tuya!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
    .string "MR. FUJI: ¿Eh?\n"
    .string "¿Viniste a salvarme?\p"
    .string "Gracias. Pero, estoy aquí por mi\n"
    .string "propia voluntad.\p"
    .string "Vine a calmar el espíritu de\n"
    .string "la madre de CUBONE.\p"
    .string "Creo que el espíritu de MAROWAK\n"
    .string "finalmente se ha ido.\p"
    .string "Debo agradecerte por tu amable\n"
    .string "preocupación.\p"
    .string "Sígueme a mi hogar, CASA POKéMON,\n"
    .string "al pie de esta torre.$"

