PewterCity_Museum_1F_Text_Its50YForChildsTicket:: @ 81904B5
    .string "Sí, sí.\n"
    .string "Son ¥50 por un boleto para niños.\p"
    .string "¿Te gustaría entrar?$"

PewterCity_Museum_1F_Text_ComeAgain:: @ 81904F9
    .string "¡Vuelva pronto!$"

PewterCity_Museum_1F_Text_Right50YThankYou:: @ 8190505
    .string "¡De acuerdo, ¥50!\n"
    .string "¡Gracias!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney:: @ 819051C
    .string "No tienes suficiente dinero.$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself:: @ 8190539
    .string "Disfruta tu visita.$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs:: @ 8190550
    .string "¡No puedes entar por detrás!\n"
    .string "Buen intento, niño, pero no.\p"
    .string "¡Oh, da igual!\n"
    .string "¿Sabes qué es el ÁMBAR?$"
 
PewterCity_Museum_1F_Text_AmberContainsGeneticMatter:: @ 81905B1
    .string "El ÁMBAR contiene el material\n"
    .string "genético de POKéMON antiguos.\p"
    .string "Hay un LABORATORIO en algún lugar\n"
    .string "que trata de revivir POKéMON\l"
    .string "a partir del ÁMBAR.$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap:: @ 8190627
    .string "El ÁMBAR en realidad es savia,\n"
    .string "esa cosa pegajosa que sale\l"
    .string "de los árboles.\p"
    .string "La savia antigua se fosilizo con\n"
    .string "el tiempo y se convirtio en ÁMBAR.$"

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround:: @ 81906A6
    .string "あちらへ　おまわりください$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife:: @ 81906B4
    .string "Deberia ser agradecido por mi\n"
    .string "larga vida.\p"
    .string "¡Nunca pensé que llegaría a ver\n"
    .string "los huesos de un dragón!$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined:: @ 8190717
    .string "¡Ssh! Escucha, necesito compartir\n"
    .string "un secreto con alguien.\p"
    .string "¡Creo que este pedazo de ÁMBAR\n"
    .string "contiene ADN de POKéMON!\p"
    .string "Seria un enorme progreso\n"
    .string "cientifico si se pudiera revivir\l"
    .string "a un POKéMON de el.\p"
    .string "Pero, mis compañeros solo ignoran\n"
    .string "lo que tengo que decir.\p"
    .string "Así que, ¡tengo un favor que pedirte!\p"
    .string "Quiero que lleves esto a analizar\n"
    .string "en algún CENTRO POKéMON.$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan:: @ 8190866
    .string "{PLAYER} recibio el ÁMBAR VIEJO\n"
    .string "del hombre.$"

PewterCity_Museum_1F_Text_GetOldAmberChecked:: @ 819088E
    .string "¡Ssh!\n"
    .string "¡Haz que analicen el ÁMBAR VIEJO!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis:: @ 81908AE
    .string "No tienes espacio para esto.$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit:: @ 81908CD
    .string "Tenemos los fósiles de dos POKéMON\n"
    .string "prehistóricos en excibición.$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber:: @ 819090A
    .string "Hay una hermosa pieza de ÁMBAR\n"
    .string "en un color dorado claro.$"

PewterCity_Museum_1F_Text_AerodactylFossil:: @ 8190945
    .string "Fósil de AERODACTYL.\n"
    .string "Un POKéMON raro y primitivo.$"

PewterCity_Museum_1F_Text_KabutopsFossil:: @ 8190975
    .string "Fósil de KABUTOPS.\n"
    .string "Un POKéMON raro y primitivo.$"
