VermilionCity_House3_Text_PidgeyFlyLetterToSaffron:: @ 81953AF
    .string "Haré que mi PIDGEY vuele con una\n"
    .string "carta a AZAFRÁN en el norte.$"

VermilionCity_House3_Text_Pidgey:: @ 81953EE
    .string "PIDGEY: ¡Kurukkuu!$"

VermilionCity_House3_Text_DearPippiLetter:: @ 8195400
    .string "Querido PIPPI,\n"
    .string "Espero verte pronto.\p"
    .string "Oí que AZAFRÁN tiene problemas con\n"
    .string "el EQUIPO ROCKET.\p"
    .string "CARMÍN parece ser segura.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom:: @ 8195471
    .string "Quiero intercambiar CORREO con\n"
    .string "todo tipo de personas.\p"
    .string "Envié a mi PIDGEY a una SALA UNIÓN\n"
    .string "para intercambiar CORREO por mi.$"

