VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "Haré que mi PIDGEY vuele con una\n"
    .string "carta a AZAFRÁN en el norte.$"

VermilionCity_House3_Text_Pidgey::
    .string "PIDGEY: ¡Kurukkuu!$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "Querido PIPPI,\n"
    .string "Espero verte pronto.\p"
    .string "Oí que AZAFRÁN tiene problemas con\n"
    .string "el EQUIPO ROCKET.\p"
    .string "CARMÍN parece ser segura.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
    .string "Quiero intercambiar CORREO con\n"
    .string "todo tipo de personas.\p"
    .string "Envié a mi PIDGEY a una SALA UNIÓN\n"
    .string "para intercambiar CORREO por mi.$"

