Route18_Text_WiltonIntro::
    .string "Siempre reviso áreas con hierba\n"
    .string "en busca de nuevos POKéMON.$"

Route18_Text_WiltonDefeat::
    .string "¡Tch!$"

Route18_Text_WiltonPostBattle::
    .string "¡Ojalá tuviera una BICICLETA!$"

Route18_Text_RamiroIntro::
    .string "¡Kurukukuuu!\n"
    .string "¿Qué te parece mi canto de ave?$"

Route18_Text_RamiroDefeat::
    .string "¡Lo que me pasa por molestarte!$"

Route18_Text_RamiroPostBattle::
    .string "Recojo POKéMON marinos los fines\n"
    .string "de semana, por la cercanía del mar.$"

Route18_Text_JacobIntro::
    .string "¡Esté es mi territorio!\n"
    .string "¡Fuera de aquí!$"

Route18_Text_JacobDefeat::
    .string "¡Rayos!$"

Route18_Text_JacobPostBattle::
    .string "Esta es mi área favorita para\n"
    .string "atrapar POKéMON.$"

Route18_Text_RouteSign::
    .string "RUTA 18\n"
    .string "CIUDAD PRISMA - CIUDAD FUCSIA$"

Route18_Text_CyclingRoadSign::
    .string "CICLOVÍA\n"
    .string "¡No se permiten peatones!$"

