Text_SeismicTossTeach:: @ 81909A3
    .string "Los secretos del espacio…\n"
    .string "Los misterios de la tierra…\p"
    .string "Hay tantas cosas de las que\n"
    .string "sabemos tan poco.\p"
    .string "Pero eso debería motivarnos a\n"
    .string "estudiar duro, no tirar la toalla.\p"
    .string "La unica cosa que deberias tirar…\p"
    .string "Bueno, ¿que tal TIRO SÍSMICO?\n"
    .string "¿Debería enseñarselo a un POKéMON?$"

Text_SeismicTossDeclined:: @ 8190AA9
    .string "¿Ah, no?\n"
    .string "Seguro de que volveras a pedirlo.$"

Text_SeismicTossWhichMon:: @ 8190AD5
    .string "¿Qué POKéMON quiere aprender\n"
    .string "TIRO SÍSMICO?$"

Text_SeismicTossTaught:: @ 8190B00
    .string "Espero que no tires la toalla.\n"
    .string "Sigue así.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone:: @ 8190B30
    .string "¿PIEDRA LUNAR, eh?\p"
    .string "¿Que tiene de especial?\n"
    .string "Solo veo una roca ordinaria.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding:: @ 8190B80
    .string "¡20 de Julio, 1969!\p"
    .string "Ese día, la humanidad pisó la luna\n"
    .string "por primera vez.\p"                   
    .string "Compré una TV a color solo para\n"
    .string "poder ver esa noticia.$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth:: @ 8190BF3
    .string "Tenemos una exibición del espacio\n"
    .string "este mes.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu:: @ 8190C1E
    .string "¡Quiero un PIKACHU!\n"
    .string "¡Es tan lindo!\p"
    .string "¡Le pedí a mi papi que me\n"
    .string "atrapara uno!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise:: @ 8190C60
    .string "¡Si, tendrás un PIKACHU pronto,\n"
    .string "lo prometo!$"

PewterCity_Museum_1F_Text_SpaceShuttle:: @ 8190C81
    .string "NAVE ESPACIAL$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon:: @ 8190C8F
    .string "Meteorito caído en el MONTE LUNA.\n"
    .string "Se cree que es una PIEDRA LUNAR.$"
