SafariZone_SecretHouse_Text_CongratsYouveWon::
    .string "¡Ah! ¡al fin!\p"
    .string "¡Eres la primera persona en llegar\n"
    .string "a la CASA SECRETA!\p"
    .string "Aunque hice una campaña para\n"
    .string "nuestra gran inauguración,\p"
    .string "empezaba a preocuparme la idea de\n"
    .string "que nadie ganaría nuestro premio.\p"
    .string "¡Felicidades!\n"
    .string "¡Ganaste!$"

SafariZone_SecretHouse_Text_ReceivedHM03FromAttendant::
    .string "¡{PLAYER} recibió MO03\n"
    .string "del empleado!$"

SafariZone_SecretHouse_Text_ExplainSurf::
    .string "MO03 es SURF.\p"
    .string "Un POKéMON usándola podrá llevarte\n"
    .string "a través del agua.\p"
    .string "Y esta MO no es desechable, así\n"
    .string "que puedes usarla una y otra vez.\p"
    .string "¡Eres súper afortunad{OA} por ganar\n"
    .string "este fabuloso premio!$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize::
    .string "¡No tienes espacio para este\n"
    .string "fabuloso premio!$"

