Route19_Text_RichardIntro::
    .string "Tengo que calentar antes de ir\n"
    .string "a nadar.$"

Route19_Text_RichardDefeat::
    .string "¡Ya estoy listo!$"

Route19_Text_RichardPostBattle::
    .string "¡Gracias, niñ{OA}!\n"
    .string "Estoy listo para nadar.$"

Route19_Text_ReeceIntro::
    .string "¡Espera! ¡detente!\n"
    .string "¡Te va a dar un ataque al corazón!$"

Route19_Text_ReeceDefeat::
    .string "¡Ooh!\n"
    .string "¡Qué frí{OA}!$"

Route19_Text_ReecePostBattle::
    .string "Cuidado con los TENTACOOL.\n"
    .string "Su picadura duele mucho.$"

Route19_Text_MatthewIntro::
    .string "¡Amo nadar!\n"
    .string "¿Y tú?$"

Route19_Text_MatthewDefeat::
    .string "¡Clavado!$"

Route19_Text_MatthewPostBattle::
    .string "Puedo ganarle a POKéMON marinos\n"
    .string "nadando.$"

Route19_Text_DouglasIntro::
    .string "¿Qué habrá más allá del horizonte?$"

Route19_Text_DouglasDefeat::
    .string "¡Glup!$"

Route19_Text_DouglasPostBattle::
    .string "¡Veo un par de islas a lo lejos!$"

Route19_Text_DavidIntro::
    .string "Intenté bucear en busca de\n"
    .string "POKéMON, pero no funciono.$"

Route19_Text_DavidDefeat::
    .string "¡Ayuda!$"

Route19_Text_DavidPostBattle::
    .string "Supongo tienes que pescar a los\n"
    .string "POKéMON del mar.$"

Route19_Text_TonyIntro::
    .string "Miro al mar para olvidar todas las\n"
    .string "cosas malas que pasaron.$"

Route19_Text_TonyDefeat::
    .string "¡Ooh!\n"
    .string "¡Qué traumático!$"

Route19_Text_TonyPostBattle::
    .string "¡Miro al mar para olvidar la cosa\n"
    .string "mala que pasó!$"

Route19_Text_AnyaIntro::
    .string "¡Oh, tu POKéMON es genial!\n"
    .string "¿Me lo puedo quedar si gano?$"

Route19_Text_AnyaDefeat::
    .string "¡Oh! ¡perdí!$"

Route19_Text_AnyaPostBattle::
    .string "Aún queda un largo camino hasta\n"
    .string "las ISLAS ESPUMA…\p"
    .string "Quiero regresar a FUCSIA…$"

Route19_Text_AliceIntro::
    .string "¡Nadar es genial!\n"
    .string "¡Quemarse por el sol no lo es!$"

Route19_Text_AliceDefeat::
    .string "¡Que horror!$"

Route19_Text_AlicePostBattle::
    .string "Mi novio quería nadar hasta\n"
    .string "las ISLAS ESPUMA.$"

Route19_Text_AxleIntro::
    .string "¡Ajoy!\n"
    .string "¡Estas aguas son traicioneras!$"

Route19_Text_AxleDefeat::
    .string "¡Ooh!\n"
    .string "¡Peligroso!$"

Route19_Text_AxlePostBattle::
    .string "¡Mis piernas! ¡Me dio un calambre!\n"
    .string "Glup, glup…$"

Route19_Text_ConnieIntro::
    .string "Nadé hasta aquí con mis amigos…\n"
    .string "Estoy cansada…$"

Route19_Text_ConnieDefeat::
    .string "Estoy exhausta…$"

Route19_Text_ConniePostBattle::
    .string "Si tuviera que ir sobre un POKéMON\n"
    .string "en el mar, elegiría a LAPRAS.\p"
    .string "Los LAPRAS son grandes, seguro me\n"
    .string "mantendría seca en el agua.$"

Route19_Text_RouteSign::
    .string "RUTA MARINA 19\n"
    .string "CIUDAD FUCSIA - ISLAS ESPUMA$"

Route19_Text_LiaIntro::
    .string "LIA: Estoy cuidando a mi hermano.\n"
    .string "Acaba de hacerse ENTRENADOR.$"

Route19_Text_LiaDefeat::
    .string "LIA: ¡Ésa no es forma de tratar\n"
    .string "a mi hermanito!$"

Route19_Text_LiaPostBattle::
    .string "LIA: ¿Tienes un hermano menor?\p"
    .string "Espero que le estes enseñando todo\n"
    .string "tipo de cosas.$"

Route19_Text_LiaNotEnoughMons::
    .string "LIA: Quiero luchar junto a mi\n"
    .string "hermanito.\p"
    .string "¿No tienes dos POKéMON?$"

Route19_Text_LucIntro::
    .string "LUC: Mi hermana mayor me enseño\n"
    .string "a nadar y a entrenar POKéMON.$"

Route19_Text_LucDefeat::
    .string "LUC: ¡Oh, guau!\n"
    .string "¡Eres más fuerte que mi hermana!$"

Route19_Text_LucPostBattle::
    .string "LUC: Mi hermana mayor es fuerte\n"
    .string "y amable. ¡Creo que es asombrosa!$"

Route19_Text_LucNotEnoughMons::
    .string "LUC: No quiero hacerlo si no puedo\n"
    .string "luchar junto a mi hermana mayor.\p"
    .string "¿No tienes dos POKéMON?$"
