VictoryRoad_1F_Text_NaomiIntro::
    .string "Me pregunto si eres lo bastante\n"
    .string "fuerte para mí.$"

VictoryRoad_1F_Text_NaomiDefeat::
    .string "Perdí…$"

VictoryRoad_1F_Text_NaomiPostBattle::
    .string "No quería perder contra nadie,\n"
    .string "menos contra alguien más joven…$"

VictoryRoad_1F_Text_RolandoIntro::
    .string "Puedo ver que eres buen{OA}.\n"
    .string "¡Veamos exactamente cuánto!$"

VictoryRoad_1F_Text_RolandoDefeat::
    .string "Tenía una oportunidad…$"

VictoryRoad_1F_Text_RolandoPostBattle::
    .string "¡Tch!\n"
    .string "¡Lo admito, eres mejor que yo!$"

