CeruleanCity_House1_Text_AnyInterestInBerries:: @ 8192F67
    .string "Yo preparo una variedad de\n"
    .string "medicinas con POLVO DE BAYA.\p"
    .string "Usando buen POLVO DE BAYA, puedo\n"
    .string "hacer cualquier tipo de medicina.\p"
    .string "Ahora dime, ¿tienes algún interés\n"
    .string "en las BAYAS?$"

CeruleanCity_House1_Text_HaveJustTheThing:: @ 8193003
    .string "¡Ah, bien! Entonces, para ti,\n"
    .string "tengo algo perfecto.$"

CeruleanCity_House1_Text_GoCrushBerriesAtDirectCorner:: @ 8193033
    .string "Hay algo nuevo en el segundo piso\n"
    .string "de los CENTROS POKéMON, en la\l"
    .string "ZONA DIRECTA.\p"
    .string "Instalaron una máquina del Conector\n"
    .string "Inalámbrico para machacar BAYAS.\p"
    .string "Aquí es donde entras tú.\p"
    .string "Tengo un favor que pedir, uno que\n"
    .string "solo te puedo confiar a ti.\p"
    .string "¿Podrías hacer POLVO DE BAYA para\n"
    .string "mí usando esa máquina?\p"
    .string "No te olvides, la máquina esta en\n"
    .string "la ZONA DIRECTA de los CENTROS POKéMON.\p"
    .string "Prepararé medicina para ti si me\n"
    .string "traes algo de POLVO DE BAYA.\p"
    .string "No lo olvides, machaca BAYAS para\n"
    .string "hacerlas POLVO DE BAYA y tráemelo.$"

CeruleanCity_House1_Text_WhyMustYouLieNoBerries:: @ 819321D
    .string "¿Por qué me mientes?\p"
    .string "¿Cuántas BAYAS tienes?\n"
    .string "¡Ni siquiera una!$"

CeruleanCity_House1_Text_TakeInterestInAllSortsOfThings:: @ 819325E
    .string "¿No tienes interés en las BAYAS?\p"
    .string "Jovencit{OA}, es importante que tomes\n"
    .string "un interés en todo tipo de cosas.$"

CeruleanCity_House1_Text_HaveYouBroughtBerryPowder:: @ 81932C5
    .string "¡Ahem! ¿Me trajiste algo de\n"
    .string "POLVO DE BAYA?$"

CeruleanCity_House5_Text_ExchangeWithWhat:: @ 81932F4
    .string "¿Por qué cosa quieres que te\n"
    .string "lo cambie?$"

CeruleanCity_House1_Text_YoullExchangeBerryPowderForItem:: @ 819331E
    .string "Bien, ¿cambiarás tu POLVO DE BAYA\n"
    .string "por {STR_VAR_1}?$"

CeruleanCity_House1_Text_DontHaveEnoughBerryPowder:: @ 8193352
    .string "¿Hm? No tienes suficiente\n"
    .string "POLVO DE BAYA.$"

CeruleanCity_House1_Text_TradeMoreBerryPowder:: @ 819337A
    .string "Este POLVO DE BAYA es muy bueno.\n"
    .string "Hará una excelente medicina.\p"
    .string "¿Quieres cambiar más POLVO DE BAYA\n"
    .string "por otra cosa?$"

CeruleanCity_House1_Text_HopeToSeeYouAgain:: @ 81933FB
    .string "Esta bien, entonces.\n"
    .string "Espero volverte a ver después.$"

CeruleanCity_House1_Text_SeeMeIfYoudLikeToTradePowder:: @ 819342F
    .string "Ven a verme si quieres cambiar tu\n"
    .string "POLVO DE BAYA.$"

