Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .string "Muchos POKéMON sólo viven en\n"
    .string "bosques y cuevas.\p"
    .string "Tienes que ser persistente y mirar\n"
    .string "en todos lados para conseguir\l"
    .string "especies diferentes.$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .string "¿Has visto los pequeños árboles\n"
    .string "en el camino?\p"
    .string "Puedes cortarlos con un movimiento\n"
    .string "especial de los POKéMON.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .string "¿Sabías que se puede cancelar\n"
    .string "la evolución de un POKéMON?\p"
    .string "Cuando un POKéMON está\n"
    .string "evolucionando, puedes parar\l"
    .string "el proceso.\p"
    .string "Es una tecnica para criar POKéMON\n" 
    .string "en su forma actual.$"
