Route20_Text_BarryIntro::
    .string "El agua es poco profunda aquí.\n"
    .string "Hay mucha gente nadando.$"

Route20_Text_BarryDefeat::
    .string "¡Splash!$"

Route20_Text_BarryPostBattle::
    .string "Ojalá pudiera subirme a mi POKéMON.\n"
    .string "Seguro tú no estas cansad{OA}.$"

Route20_Text_ShirleyIntro::
    .string "Las ISLAS ESPUMA son tranquilas.\n"
    .string "Estoy de vacaciones aquí.$"

Route20_Text_ShirleyDefeat::
    .string "¡Basta!$"

Route20_Text_ShirleyPostBattle::
    .string "Hay una enorme caverna debajo de\n"
    .string "esta isla.$"

Route20_Text_TiffanyIntro::
    .string "Me encanta flotar en las olas\n"
    .string "junto a los peces.$"

Route20_Text_TiffanyDefeat::
    .string "¡Yauch!$"

Route20_Text_TiffanyPostBattle::
    .string "¿Quieres flotar conmigo?$"

Route20_Text_IreneIntro::
    .string "¿También estás de vacaciones?$"

Route20_Text_IreneDefeat::
    .string "¡No tuviste piedad!$"

Route20_Text_IrenePostBattle::
    .string "En un pasado distante, las ISLAS\n"
    .string "ESPUMA solían ser una sola isla.$"

Route20_Text_DeanIntro::
    .string "¡Mira mis músculos!$"

Route20_Text_DeanDefeat::
    .string "¡Qué débil!$"

Route20_Text_DeanPostBattle::
    .string "¡Debería estar fortaleciendo a\n"
    .string "mi POKéMON, no a mí!$"

Route20_Text_DarrinIntro::
    .string "¿Por qué te subiste a un POKéMON?\n"
    .string "¿No sabes nadar?$"

Route20_Text_DarrinDefeat::
    .string "¡Auch!\n"
    .string "¡Me destruiste!$"

Route20_Text_DarrinPostBattle::
    .string "¡Subirse a un POKéMON parece\n"
    .string "divertido!$"

Route20_Text_RogerIntro::
    .string "Llegué aquí volando sobre mis\n"
    .string "POKéMON pájaros.$"

Route20_Text_RogerDefeat::
    .string "¡Oh, no!\n"
    .string "¿Que voy a hacer ahora?$"

Route20_Text_RogerPostBattle::
    .string "Mis pájaros están exhaustos.\n"
    .string "¡No podemos VOLAR de regreso!$"

Route20_Text_NoraIntro::
    .string "Mi novio me dio unas perlas\n"
    .string "grandes.$"

Route20_Text_NoraDefeat::
    .string "¡Oh, no!\n"
    .string "¡Mis perlas estaban en ellas!$"

Route20_Text_NoraPostBattle::
    .string "¿Crecerán mis perlas dentro de\n"
    .string "CLOYSTER?$"

Route20_Text_MissyIntro::
    .string "Nadé hasta aquí desde ISLA CANELA.\n"
    .string "No fue nada fácil.$"

Route20_Text_MissyDefeat::
    .string "¡Estoy tan decepcionada!$"

Route20_Text_MissyPostBattle::
    .string "Los POKéMON invadieron una mansión\n"
    .string "abandonada en ISLA CANELA.\p"
    .string "Ahora la llaman MANSIÓN POKéMON.$"

Route20_Text_MelissaIntro::
    .string "Al oeste de ISLA CANELA, hay un\n"
    .string "LABORATORIO POKéMON.\p"
    .string "Mi papi trabaja ahí.$"

Route20_Text_MelissaDefeat::
    .string "¡Espera!\n"
    .string "¡Se supone que debes esperarme!$"

Route20_Text_MelissaPostBattle::
    .string "CANELA es una isla volcánica.\p"
    .string "Se dice que salió del mar tras\n"
    .string "la erupción de un volcán.$"

Route20_Text_SeafoamIslands::
    .string "ISLAS ESPUMA$"

Route20_Text_MistyTrainsHere::
    .string "Hay muchos ENTRENADORES fuertes\n"
    .string "y POKéMON de tipo AGUA por aquí.\p"
    .string "Dicen que MISTY, del GIMNASIO\n"
    .string "de CELESTE, entrena aquí.$"
