SSAnne_Kitchen_Text_BusyOutOfTheWay:: @ 81733F8
    .string "¡Tú, mon petit!\n"
    .string "¡Estamos ocupados aquí!\l"
    .string "¡Fuera del camino!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash:: @ 8173429
    .string "Ví una BAYA extraña en la basura.\n"
    .string "Me pregunto, ¿de qué tipo era?$"

SSAnne_Kitchen_Text_SoBusyImDizzy:: @ 8173462
    .string "¡Estoy tan ocupado que me mareo!\n"
    .string "¡Tienes que darme espacio!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay:: @ 81734A0
    .string "Hum-de-hum-de-ho…\p"
    .string "I peel spuds every day!\n"
    .string "Hum-hum…$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton:: @ 81734D3
    .string "¿Has escuchado sobre SNORLAX?\n"
    .string "Es un glotón.\p"
    .string "¡No hay POKéMON que coma y duerme\n"
    .string "cómo lo hace SNORLAX!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions:: @ 817353E
    .string "Sniff… Sniff…\p"
    .string "Solo me dejan pelar cebollas…\n"
    .string "Sniff…$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs:: @ 8173570
    .string "¡Ejem!\n"
    .string "¡Claro que soy le CHEF!\p"
    .string "Le plato principal es:$"

SSAnne_Kitchen_Text_SalmonDuSalad:: @ 817359F
    .string "¡Ensalada du salmón!\p"
    .string "¡Aunque tal vez les invitados se\n"
    .string "quejen de que es pescado de nuevo!$"

SSAnne_Kitchen_Text_EelsAuBarbecue:: @ 81735DF
    .string "¡Anguilas au barbacoa!\p"
    .string "Me temo que les invitados harán\n"
    .string "un motín.$"

SSAnne_Kitchen_Text_PrimeBeefsteak:: @ 8173611
    .string "¡Bistec de primera clase!\p"
    .string "Pero, ¿tengo suficientes filetes\n"
    .string "du res?$"

