SSAnne_Kitchen_Text_BusyOutOfTheWay::
    .string "¡Tú, mon petit!\n"
    .string "¡Estamos ocupados aquí!\l"
    .string "¡Fuera del camino!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash::
    .string "Ví una BAYA extraña en la basura.\n"
    .string "Me pregunto, ¿de qué tipo era?$"

SSAnne_Kitchen_Text_SoBusyImDizzy::
    .string "¡Estoy tan ocupado que me mareo!\n"
    .string "¡Tienes que darme espacio!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay::
    .string "Jum-di-jum-di-jo…\p"
    .string "¡Yo pelo papas todos los días!\n"
    .string "Jum-jum…$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton::
    .string "¿Has escuchado sobre SNORLAX?\n"
    .string "Es un glotón.\p"
    .string "¡No hay POKéMON que coma y duerma\n"
    .string "cómo lo hace SNORLAX!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions::
    .string "Sniff… Sniff…\p"
    .string "Solo me dejan pelar cebollas…\n"
    .string "Sniff…$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs::
    .string "¡Ejem!\n"
    .string "¡Claro que soy le CHEF!\p"
    .string "Le plato principal es:$"

SSAnne_Kitchen_Text_SalmonDuSalad::
    .string "¡Ensalada du salmón!\p"
    .string "¡Aunque tal vez les invitados se\n"
    .string "quejen de que es pescado de nuevo!$"

SSAnne_Kitchen_Text_EelsAuBarbecue::
    .string "¡Anguilas au barbacoa!\p"
    .string "Me temo que les invitados harán\n"
    .string "un motín.$"

SSAnne_Kitchen_Text_PrimeBeefsteak::
    .string "¡Bistec de primera clase!\p"
    .string "Pero, ¿tengo suficientes filetes\n"
    .string "du res?$"

