SilphCo_2F_Text_ConnorIntro::
    .string "¡Ayuda!\n"
    .string "Soy un empleado de SILPH.$"

SilphCo_2F_Text_ConnorDefeat::
    .string "¿Cómo sabías que\n"
    .string "soy un ROCKET?$"

SilphCo_2F_Text_ConnorPostBattle::
    .string "Trabajo tanto para SILPH como para\n"
    .string "el EQUIPO ROCKET.$"

SilphCo_2F_Text_JerryIntro::
    .string "¡Aquí es fuera de límites!\n"
    .string "¡Vete a casa!$"

SilphCo_2F_Text_JerryDefeat::
    .string "Eres buen{OA}.$"

SilphCo_2F_Text_JerryPostBattle::
    .string "¿Puedes resolver este laberinto?\n"
    .string "¡Déjame decirtelo, no es fácil!$"

SilphCo_2F_Text_Grunt1Intro::
    .string "¡No se permiten niños aquí!$"

SilphCo_2F_Text_Grunt1Defeat::
    .string "¡Demasiado fuerte!$"

SilphCo_2F_Text_Grunt1PostBattle::
    .string "Las baldosas con forma de diamante\n" 
    .string "son puntos de teletransporte.\p"
    .string "Son medios de transporte para este\n"
    .string "edificio de alta tecnología.$"

SilphCo_2F_Text_Grunt2Intro::
    .string "¡Ey, niñ{OA}!\n"
    .string "¿Qué haces vagando por aquí?$"

SilphCo_2F_Text_Grunt2Defeat::
    .string "¡Me equivoqué!$"

SilphCo_2F_Text_Grunt2PostBattle::
    .string "¡SILPH S.A. será relacionada con\n"
    .string "el EQUIPO ROCKET!$"

Text_ThunderWaveTeach::
    .string "¡Socorro!\n"
    .string "¡No! ¡detente! ¡por favor!\p"
    .string "Oh, no estás con el EQUIPO ROCKET.\n"
    .string "Lo siento, pensaba que…\p"
    .string "¿Me perdonarías si te enseño la\n"
    .string "técnica ONDA TRUENO?$"

Text_ThunderWaveDeclined::
    .string "Oh…\n"
    .string "Pero ONDA TRUENO es útil…$"

Text_ThunderWaveWhichMon::
    .string "¿A qué POKéMON le debería enseñar\n"
    .string "ONDA TRUENO?$"

Text_ThunderWaveTaught::
    .string "ONDA TRUENO causa parálisis al\n"
    .string "objetivo.\p"
    .string "Puede que un POKéMON parálizado no\n"
    .string "sea capaz de moverse en batalla.\p"
    .string "Es un movimiento de tipo\n"
    .string "ELÉCTRICO, así que no funcionará\l"
    .string "en algunos POKéMON.$"

SilphCo_2F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P2$"

