Route21_South_Text_JackIntro::
	.string "Conseguí a mi POKéMON en el mar.$"

Route21_South_Text_JackDefeat::
	.string "¡¡Buzo!!\n"
	.string "¡¡Caído!!$"

Route21_South_Text_JackPostBattle::
	.string "¿Dónde atrapaste a tus POKéMON?$"

Route21_South_Text_JeromeIntro::
	.string "Estoy en un triatlón justo ahora.$"

Route21_South_Text_JeromeDefeat::
	.string "Ufff…\n"
	.string "Ufff… Ufff…$"

Route21_South_Text_JeromePostBattle::
	.string "¡Me venciste! ¡pero aún falta la\n"
	.string "parte del ciclismo y el maratón!$"

Route21_South_Text_RolandIntro::
	.string "¡Ahh!\n"
	.string "¡Siente el sol y el viento!$"

Route21_South_Text_RolandDefeat::
	.string "¡Yauu!\n"
	.string "¡Perdí!$"

Route21_South_Text_RolandPostBattle::
	.string "¡El sol me dejo quemado!$"

Route21_South_Text_ClaudeIntro::
	.string "¡Ey, no asustes a los peces!$"

Route21_South_Text_ClaudeDefeat::
	.string "¡Lo siento! es solo que estoy muy\n"
	.string "frustrado por no pescar nada.$"

Route21_South_Text_ClaudePostBattle::
	.string "Cielos, no he atrapado nada.\n"
	.string "¿Podría ser que este lugar es una\l"
	.string "piscina gigante o algo?$"

Route21_South_Text_NolanIntro::
	.string "Acompáñame hasta que consiga algo.$"

Route21_South_Text_NolanDefeat::
	.string "Eso mató algo de tiempo.$"

Route21_South_Text_NolanPostBattle::
	.string "¡Espera!\n"
	.string "¡Algo está picando! ¡sí!$"

Route21_North_Text_LilIntro::
	.string "LIL: ¿Uh? ¿una batalla?\n"
	.string "¿IAN, no podrías hacerlo solo?$"

Route21_North_Text_LilDefeat::
	.string "LIL: Oh, ¿ves?\n"
	.string "Perdimos. ¿Ya estás contento?$"

Route21_North_Text_LilPostBattle::
	.string "LIL: Estoy cansada.\n"
	.string "¿Nos podemos ir a casa ya?$"

Route21_North_Text_LilNotEnoughMons::
	.string "LIL: ¿Uh? ¿una batalla?\n"
	.string "Me da pereza hacerlo sola.\l"
	.string "¿Trae dos POKéMON, quieres?$"

Route21_North_Text_IanIntro::
	.string "IAN: Mi hermana necesita hacer\n"
	.string "más ejercicio, así que la traje.$"

Route21_North_Text_IanDefeat::
	.string "IAN: ¡Awww, hermana!\n"
	.string "¡Concéntrate!$"

Route21_North_Text_IanPostBattle::
	.string "IAN: ¡Vamos, hermana!\p"
	.string "¡Así no vas a bajar de peso!$"

Route21_North_Text_IanNotEnoughMons::
	.string "IAN: Queremos una batalla de dos\n"
	.string "contra dos. ¿Puedes traer dos POKéMON?$"
