FuchsiaCity_Gym_Text_KogaIntro::
    .string "¡KOGA: Fuajajaja!\p"
    .string "¿Un{A} simple niñ{OA} se atreve a\n"
    .string "desafiarme?\p"
    .string "¡La sola idea me hace temblar de\n"
    .string "la risa!\p"
    .string "Muy bien, te mostraré el verdadero\n"
    .string "terror como un maestro ninja.\p"
    .string "El veneno trae perdición constante.\n"
    .string "El sueño deja indefenso al rival.\p"
    .string "¡Sufre por el insidioso horror de\n"
    .string "mis POKéMON de tipo VENENO!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

FuchsiaCity_Gym_Text_KogaDefeat::
    .string "¡Humph!\n"
    .string "¡Has demostrado tu valor!\p"
    .string "¡Bien!\n"
    .string "¡Toma la MEDALLA ALMA!$"

FuchsiaCity_Gym_Text_KogaPostBattle::
    .string "Bajo los efectos de TÓXICO, un\n"
    .string "POKéMON sufre más y más.\p"
    .string "¡El daño que recibe empeora\n"
    .string "mientras más dura la batalla!\p"
    .string "¡Seguro que terrorizará a tus\n"
    .string "adversarios!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
    .string "Ahora que tienes la MEDALLA ALMA,\n"
    .string "la DEFENSA de tus POKéMON aumenta.\p"
    .string "Y podrás usar SURF fuera de las\n"
    .string "batallas.\p"
    .string "¡Ah!\n"
    .string "¡Toma esto también!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
    .string "{PLAYER} recibió MT06\n"
    .string "de KOGA.$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
    .string "¡Dentro de la MT06 se encuentra\n"
    .string "TÓXICO!\p"
    .string "Es una técnica secreta de hace más\n"
    .string "cuatrocientos años.$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
    .string "¡Haz espacio para esto, niñ{OA}!$"

FuchsiaCity_Gym_Text_KaydenIntro::
    .string "La fuerza no es la clave para los\n"
    .string "POKéMON.\p"
    .string "¿Entiendes eso?\p"
    .string "¡Los POKéMON tratan de estrategia!\p"
    .string "Te mostraré como la estrategia\n"
    .string "puede vencer a la fuerza bruta.$"

FuchsiaCity_Gym_Text_KaydenDefeat::
    .string "¿Qué?\n"
    .string "¡Extraordinario!$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
    .string "Entonces ¿mezclas fuerza con\n"
    .string "ingenio?\l"
    .string "¡Buena estrategia!\p"
    .string "Eso es notable para un{A}\n"
    .string "ENTRENADOR{AM} joven.$"

FuchsiaCity_Gym_Text_KirkIntro::
    .string "Fuí un mago una vez.\p"
    .string "Pero soñaba con convertirme en\n"
    .string "ninja, así que me uní a este GIMN.$"

FuchsiaCity_Gym_Text_KirkDefeat::
    .string "¡Estoy acabado!$"

FuchsiaCity_Gym_Text_KirkPostBattle::
    .string "Incluso si perdí, seguiré\n"
    .string "entrenando acorde a las enseñanzas\l"
    .string "de KOGA, mi maestro ninja.$"

FuchsiaCity_Gym_Text_NateIntro::
    .string "¡Veamos si superas mis técnicas\n"
    .string "especiales!$"

FuchsiaCity_Gym_Text_NateDefeat::
    .string "¡Me hiciste ver como un tonto!$"

FuchsiaCity_Gym_Text_NatePostBattle::
    .string "¡Me gustan las técnicas\n"
    .string "de envenenamiento y sueño,\l"
    .string "porque persisten tras la batalla!$"

FuchsiaCity_Gym_Text_PhilIntro::
    .string "¡Alto ahí!\p"
    .string "¿Te frustran los famosos muros\n"
    .string "invisibles del GIMNASIO de FUCSIA?$"

FuchsiaCity_Gym_Text_PhilDefeat::
    .string "¡Guau!\n"
    .string "¡Eres buen{OA}!$"

FuchsiaCity_Gym_Text_PhilPostBattle::
    .string "¡Me impresionaste!\n"
    .string "¡Ten una pista!\p"
    .string "¡Mira muy de cerca los muros\n"
    .string "invisibles en busca de huecos!$"

FuchsiaCity_Gym_Text_EdgarIntro::
    .string "¡Yo también estudio el camino del\n"
    .string "ninja con el Maestro KOGA!\p"
    .string "¡Los ninjas tienen una larga\n"
    .string "historia de usar animales!$"

FuchsiaCity_Gym_Text_EdgarDefeat::
    .string "¡Awoo!$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
    .string "Aún tengo mucho que aprender.$"

FuchsiaCity_Gym_Text_ShawnIntro::
    .string "El Maestro KOGA viene de un largo\n"
    .string "linaje de ninjas.\p"
    .string "¿Tú de donde desciendes?$"

FuchsiaCity_Gym_Text_ShawnDefeat::
    .string "¡Eres es más hábil de lo que\n"
    .string "pensaba!$"

FuchsiaCity_Gym_Text_ShawnPostBattle::
    .string "¡Cuando hay luz, hay sombra!\p"
    .string "¡Luz y sombra!\n"
    .string "¿Cuál eliges?$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
    .string "¡Yo!\n"
    .string "¡Futur{OA} campe{ONONA}!\p"
    .string "Este GIMNASIO tiene sus trucos.\n"
    .string "¡Está lleno de paredes invisibles!\p"
    .string "Puede que KOGA parezca estar\n"
    .string "cerca, pero los muros lo protegen.\p"
    .string "Tienes que encontrar huecos en los\n"
    .string "muros para llegar a él.$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
    .string "¡Es increíble como los ninjas\n"
    .string "pueden atemorizar, incluso ahora!$"

FuchsiaCity_Gym_Text_GymStatue::
    .string "GIMNASIO POKéMON DE FUCSIA\n"
    .string "LÍDER: KOGA\p"
    .string "ENTRENADORES VICTORIOSOS:\n"
    .string "{RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
    .string "GIMNASIO POKéMON DE FUCSIA\n"
    .string "LÍDER: KOGA\p"
    .string "ENTRENADORES VICTORIOSOS:\n"
    .string "{RIVAL}, {PLAYER}$"

