SafariZone_West_Text_RestHouse::
    .string "CASA DE DESCANSO$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
    .string "AVISO DE PETICIÓN\p"
    .string "Por favor encuentre la DENTADURA\n"
    .string "DE ORO del GUARDA del SAFARI.\l"
    .string "Está en alguna parte de esta zona.\p"
    .string "¡Se ofrece recompensa!\n"
    .string "Contáctese con el GUARDA.$"

SafariZone_West_Text_SearchForSecretHouse::
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "¡Campaña de exploración de ZONAS!\n"
    .string "¡La búsqueda de la CASA SECRETA!$"

SafariZone_West_Text_AreaSign::
    .string "ZONA 3\n"
    .string "ESTE: ZONA CENTRAL$"

