VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish::
    .string "¡Soy el GURÚ PESCADOR!\p"
    .string "¡Simplemente aaamo pescar!\n"
    .string "No soporto vivir sin ello.\p"
    .string "¿Dime, te gusta pescar?$"

VermilionCity_House1_Text_TakeThisAndFish::
    .string "¡Grandioso! Me gusta tu estilo.\n"
    .string "Creo que podemos ser amigos.\p"
    .string "¡Toma esto y pesca, joven amig{OA}!$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru::
    .string "{PLAYER} recibió una CAÑA VIEJA\n"
    .string "del GURÚ PESCADOR.$"

VermilionCity_House1_Text_FishingIsAWayOfLife::
    .string "¡Pescar es una forma de vida!\n"
    .string "Es cómo la más fina poesía.\p"
    .string "Desde mares a ríos, sal y atrapa a\n"
    .string "uno grande, mi amig{OA}.$"

VermilionCity_House1_Text_OhThatsSoDisappointing::
    .string "Oh…\n"
    .string "Eso es tan decepcionante…$"

VermilionCity_House1_Text_HowAreTheFishBiting::
    .string "¡Hola ahí, {PLAYER}!\p"
    .string "¿Cómo muerden los peces?$"

VermilionCity_House1_Text_NoRoomForNiceGift::
    .string "¡Oh, no!\p"
    .string "Tenía un bonito regalo para ti,\n"
    .string "¡pero no tienes espacio para eso!$"

