SSAnne_1F_Room6_Text_TakeAShortRest::
    .string "Te ves cansad{OA}. ¿Te gustaría\n"
    .string "tomar un pequeño descanso?$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed::
    .string "Me alegra ver que todos se ven\n"
    .string "refrescados y alegres.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother::
    .string "Oh, perdón por preocuparme así.\n"
    .string "Te ves como mi hermano pequeño…$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister::
    .string "Oh, perdón por preocuparme así.\n"
    .string "Te ves como mi hermana pequeña…$"

