SSAnne_1F_Room6_Text_TakeAShortRest:: @ 817445B
    .string "Te ves cansad{OA}. ¿Te gustaría\n"
    .string "tomar un pequeño descanso?$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed:: @ 8174490
    .string "Me alegra ver que todos se ven\n"
    .string "refrescados y alegres.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother:: @ 81744D0
    .string "Oh, perdón por preocuparme así.\n"
    .string "Te ves como mi hermano pequeño…$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister:: @ 8174515
    .string "Oh, perdón por preocuparme así.\n"
    .string "Te ves como mi hermana pequeña…$"

