CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
    .string "EEVEE puede evolucionar en tres\n"
    .string "tipos de POKéMON.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
    .string "Hay un correo electrónico.\p"
    .string "… … …\p"
    .string "Existen tres POKéMON que son\n"
    .string "aves legendarias.\p"
    .string "Son ARTICUNO, ZAPDOS, y MOLTRES.\p"
    .string "Sus ubicaciones son desconocidas.\p"
    .string "Planeamos explorar la cueva\n"
    .string "cercana a CIUDAD CELESTE.\p"
    .string "De: EQUIPO DE INVESTIGACIÓN\n"
    .string "POKéMON…$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
    .string "¡Una pipa de ámbar!$"

