Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou::
    .string "De acuerdo, pongo las seis\n"
    .string "POKé BOLAS en mi cinturón…\p"
    .string "Sí, eso basta. Como mucho, puedes\n"
    .string "llevar a 6 POKéMON en tu equipo.$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean::
    .string "El EQUIPO ROCKET ataca a\n"
    .string "ciudadanos de CELESTE…\p"
    .string "El EQUIPO ROCKET sale todos los\n"
    .string "días en las noticias.$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500::
    .string "HOMBRE: ¡Hola, amiguito!\n"
    .string "¡Tengo una oferta sólo para ti!\p"
    .string "Te daré a un POKéMON secreto\n"
    .string "- un MAGIKARP - ¡por solo ¥500!\p"
    .string "Así que, lo comprarás, ¿cierto?$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500::
    .string "HOMBRE: ¡Hola, señorita!\n"
    .string "¡Tengo una oferta sólo para ti!\p"
    .string "Te daré a un POKéMON secreto\n"
    .string "- un MAGIKARP - ¡por solo ¥500!\p"
    .string "Así que, lo comprarás, ¿cierto?$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp::
    .string "{PLAYER} pagó la excesiva cantidad\n"
    .string "de ¥500 y compró al MAGIKARP…$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou::
    .string "¿No? ¿dijiste que no? ¡Solo hago\n"
    .string "esto como un favor para tí!$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon::
    .string "Parece que no tienes espacio para\n"
    .string "más POKéMON.$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney::
    .string "¡Necesitas más dinero que eso!$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds::
    .string "HOMBRE: Bueno, no doy rembolsos.\n"
    .string "¡Tu sabías lo que ibas a obtener!$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC::
    .string "A veces, tendrás muchos POKéMON,\n"
    .string "y no podrás llevartelos a todos.\p"
    .string "En ese caso, deberías guardar\n"
    .string "algunos usando cualquier PC.$"

Route4_PokemonCenter_1F_Text_ItsANewspaper::
    .string "Es un periódico.$"

