PokemonLeague_BrunosRoom_Text_Intro::
    .string "¡Soy BRUNO, del ALTO MANDO!\p"
    .string "A través de entrenamientos\n"
    .string "rigurosos, la gente y los POKéMON\l"
    .string "pueden fortalecerse sin límites.\p"
    .string "¡Vivo y entreno con mis POKéMON\n"
    .string "de PELEA!\l"
    .string "¡Y eso nunca cambiará!\p"
    .string "¡{PLAYER}!\p"
    .string "¡Te destruiremos con nuestro poder\n"
    .string "superior!\p"
    .string "¡Jo jah!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_RematchIntro::
    .string "¡Soy BRUNO, del ALTO MANDO!\p"
    .string "A través de entrenamientos\n"
    .string "rigurosos, la gente y los POKéMON\l"
    .string "pueden fortalecerse sin límites.\p"
    .string "¡Vivo y entreno con mis POKéMON\n"
    .string "de PELEA!\l"
    .string "¡Y eso nunca cambiará!\p"
    .string "¡{PLAYER}!\p"
    .string "¡Te destruiremos con nuestro poder\n"
    .string "superior!\p"
    .string "¡Jo jah!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_Defeat::
    .string "¿Porqué?\n"
    .string "¿Cómo pude perder?$"

PokemonLeague_BrunosRoom_Text_PostBattle::
    .string "Mi trabajo terminó.\n"
    .string "Tu próximo desafío te espera.$"

