SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
    .string "CAPITÁN: Ooargh…\n"
    .string "Me siento horrible…\l"
    .string "¡Prrp! Mareado…$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
    .string "¡{PLAYER} frotó la espalda del\n"
    .string "CAPITÁN!\p"
    .string "Frota-frota…\n"
    .string "Frota-frota…$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
    .string "CAPITÁN: ¡Fiu! ¡Gracias!\n"
    .string "Me siento mucho mejor ahora.\p"
    .string "¿Quieres ver mi técnica oculta\n"
    .string "de CORTE?\p"
    .string "Te podría enseñar mi preciado\n"
    .string "CORTE si no estuviera tan enfermo…\p"
    .string "¡Ya sé! ¡Puedes tener esto!\n"
    .string "¡Esta MÁQUINA OCULTA!\p"
    .string "¡Enseñale CORTE a tu POKéMON, y\n"
    .string "podrás ver CORTE cuando quieras!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .string "¡{PLAYER} obtuvo la MO01\n"
    .string "del CAPITÁN!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
    .string "Usando CORTE, puedes derribar\n"
    .string "árboles pequeños.\p"
    .string "¿Porqué no lo intentas con los\n"
    .string "árboles en CIUDAD CARMÍN?$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .string "CAPITÁN: …¡Fiu!\p"
    .string "Ahora que ya no estoy enfermo,\n"
    .string "supongo que es hora.\p"
    .string "¡El SANTA ANA zarpará pronto!\p"
    .string "Me despido, ¡hasta nuestro regreso\n"
    .string "a CIUDAD CARMÍN!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
    .string "¡Oh, no!\n"
    .string "¡No tienes espacio para esto!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .string "¡Ack!\n"
    .string "¡No debí mirar!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
    .string "Como conquistar la enfermedad…\n"
    .string "¡El CAPITÁN esta leyendo esto!$"

