PalletTown_RivalsHouse_Text_HiBrothersAtLab::
    .string "DAISY: ¡Hola, {PLAYER}!\p"
    .string "Mi hermano, {RIVAL}, está en el\n"
    .string "LABORATORIO del abuelo.$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
    .string "DAISY: {PLAYER}, oí que tuviste\n"
    .string "una batalla contra {RIVAL}.\p"
    .string "¡Desearía haber visto eso!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
    .string "¿El abuelo te pidió un\n"
    .string "encargo?\p"
    .string "Vaya, eso es flojo de su parte.\n"
    .string "Ten, esto te ayudará.$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
    .string "{PLAYER} recibió un MAPA\n"
    .string "de DAISY.$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
    .string "No tienes espacio para esto en tu\n"
    .string "MOCHILA.$"

PalletTown_RivalsHouse_Text_ExplainTownMap::
    .string "Puedes usar el MAPA para\n"
    .string "encontrar donde estás, o revisar\l"
    .string "los nombres de lugares.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
    .string "DAISY: Los POKéMON son seres vivos,\n"
    .string "como las personas.\p"
    .string "Cuando se cansen, por favor\n"
    .string "déjalos descansar.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
    .string "Es un gran mapa de la región\n"
    .string "de KANTO. ¡Esto podría ser útil!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
    .string "Los estantes están llenos de\n"
    .string "libros sobre los POKéMON.$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
    .string "DAISY: ¡Hola, {PLAYER}!\n"
    .string "Viniste en un buen momento.\p"
    .string "Voy a tener algo de té.\n"
    .string "¿Te gustaría unirte?\p"
    .string "Oh, pero mira.\n"
    .string "Tus POKéMON están un poco sucios.\p"
    .string "¿Quieres que limpie a alguno?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
    .string "¿No necesitas que limpie a\n"
    .string "ningún POKéMON?\p"
    .string "De acuerdo, solo tendremos té.$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
    .string "¿A cúal debería limpiar?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
    .string "DAISY: Bien, haré que se vea bonito\n"
    .string "en poco tiempo.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
    .string "{FONT_NORMAL}{STR_VAR_1} se ve muy contento…\p"
    .string "{FONT_FEMALE}DAISY: ¡Ahí lo tienes! Todo listo.\n"
    .string "¿Ves? ¿Tiene un buen aspecto o no?\p"
    .string "Jiji…\n"
    .string "Es un POKéMON muy lindo..$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
    .string "Oh, lo siento. Honestamente no\n"
    .string "puedo limpiar a un HUEVO.$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
    .string "DAISY: Tus POKéMON aprenderán a\n"
    .string "quererte si los crias con amor.\p"
    .string "Por ejemplo, {PLAYER}, ¿puedo\n"
    .string "ver a tu primer POKéMON?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
    .string "No puede quererte más de lo que te\n"
    .string "quiere ahora.\p"
    .string "La felicidad de tu POKéMON esta\n"
    .string "más allá de las palabras.$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
    .string "Se ve muy feliz.\p"
    .string "Ojalá {RIVAL} pudiera ver esto y\n"
    .string "aprediera algo.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
    .string "Es muy amistoso contigo.\n"
    .string "¡Sigue haciéndolo bien!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
    .string "Te está tomando cariño.\n"
    .string "Su confianza en ti está creciendo.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
    .string "Aún no se adapta del todo a tí.\p"
    .string "Los POKéMON son bastante recelosos\n"
    .string "cuando los empiezas a conocer.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
    .string "{PLAYER}, no me gusta la forma en\n"
    .string "la que te mira.\p"
    .string "¿Podrías intentar ser más amable\n"
    .string "con el?$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
    .string "…Um, no es fácil para mi decir\n"
    .string "esto, pero…\p"
    .string "¿Hay alguna razón para qué tu\n"
    .string "POKéMON te odie tanto?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
    .string "“El cariñoso y dulce\n"
    .string "CLEFAIRY”$"

