PalletTown_RivalsHouse_Text_HiBrothersAtLab:: @ 818D58C
    .string "DAISY: ¡Hola, {PLAYER}!\p"
    .string "Mi hermano, {RIVAL}, está en el\n"
    .string "LABORATORIO del abuelo.$"
    
PalletTown_RivalsHouse_Text_HeardYouBattledRival:: @ 818D5C4
    .string "DAISY: {PLAYER}, oí que tuviste\n"
    .string "una batalla contra {RIVAL}.\p"
    .string "¡Desearía haber visto eso!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp:: @ 818D60A
    .string "¿El abuelo te pidió un\n"
    .string "encargo?\p"
    .string "Vaya, eso es flojo de su parte.\n"
    .string "Ten, esto te ayudará.$"
             
PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy:: @ 818D661
    .string "{PLAYER} recibió un MAPA\n"
    .string "de DAISY.$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis:: @ 818D684
    .string "No tienes espacio para esto en tu\n"
    .string "MOCHILA.$"

PalletTown_RivalsHouse_Text_ExplainTownMap:: @ 818D6AF
    .string "Puedes usar el MAPA para\n"
    .string "encontrar donde estás, o revisar\l"
    .string "los nombres de lugares.$"
             
PalletTown_RivalsHouse_Text_PleaseGiveMonsRest:: @ 818D701
    .string "DAISY: Los POKéMON son seres vivos,\n"
    .string "como las personas.\p"
    .string "Cuando se cansen, por favor\n"
    .string "déjalos descansar.$"
             
PalletTown_RivalsHouse_Text_ItsBigMapOfKanto:: @ 818D763
    .string "Es un gran mapa de la región\n"
    .string "de KANTO. ¡Esto podría ser útil!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks:: @ 818D7A1
    .string "Los estantes están llenos de\n"
    .string "libros sobre los POKéMON.$"
             
PalletTown_RivalsHouse_Text_LikeMeToGroomMon:: @ 818D7D3
    .string "DAISY: ¡Hola, {PLAYER}!\n"
    .string "Viniste en un buen momento.\p"
    .string "Voy a tener algo de té.\n"
    .string "¿Te gustaría unirte?\p"
    .string "Oh, pero mira.\n"
    .string "Tus POKéMON están un poco sucios.\p"
    .string "¿Quieres que limpie a alguno?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming:: @ 818D875
    .string "¿No necesitas que limpie a\n"
    .string "ningún POKéMON?\p"
    .string "De acuerdo, solo tendremos té.$"

PalletTown_RivalsHouse_Text_GroomWhichOne:: @ 818D8B2
    .string "¿A cúal debería limpiar?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime:: @ 818D8CC
    .string "DAISY: Bien, haré que se vea bonito\n"
    .string "en poco tiempo.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone:: @ 818D8FE
    .string "{SIZE}Á{STR_VAR_1} se ve muy contento…\p"
    .string "{SIZE}ÈDAISY: ¡Ahí lo tienes! Todo listo.\n"
    .string "¿Ves? ¿Tiene un buen aspecto o no?\p"
    .string "Jiji…\n"
    .string "Es un POKéMON muy lindo..$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg:: @ 818D97B
    .string "Oh, lo siento. Honestamente no\n"
    .string "puedo limpiar a un HUEVO.$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon:: @ 818D9A5
    .string "DAISY: Tus POKéMON aprenderán a\n"
    .string "quererte si los crias con amor.\p"
    .string "Por ejemplo, {PLAYER}, ¿puedo\n"
    .string "ver a tu primer POKéMON?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore:: @ 818DA16
    .string "No puede quererte más de lo que te\n"
    .string "quiere ahora.\p"
    .string "La felicidad de tu POKéMON esta\n"
    .string "más allá de las palabras.$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy:: @ 818DA73
    .string "Se ve muy feliz.\p"
    .string "Ojalá {RIVAL} pudiera ver esto y\n"
    .string "aprediera algo.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly:: @ 818DABE
    .string "Es muy amistoso contigo.\n"
    .string "¡Sigue haciéndolo bien!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou:: @ 818DAF3
    .string "Te está tomando cariño.\n"
    .string "Su confianza en ti está creciendo.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet:: @ 818DB2E
    .string "Aún no se adapta del todo a tí.\p"
    .string "Los POKéMON son bastante recelosos\n"
    .string "cuando los empiezas a conocer.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou:: @ 818DB88
    .string "{PLAYER}, no me gusta la forma en\n"
    .string "la que te mira.\p"
    .string "¿Podrías intentar ser más amable\n"
    .string "con el?$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch:: @ 818DBDD
    .string "…Um, no es fácil para mi decir\n"
    .string "esto, pero…\p"
    .string "¿Hay alguna razón para qué tu\n"
    .string "POKéMON te odie tanto?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy:: @ 818DC47
    .string "“El cariñoso y dulce\n"
    .string "CLEFAIRY”$"
