SilphCo_8F_Text_WonderIfSilphIsFinished::
    .string "Me pregunto si SILPH está acabada…$"

SilphCo_8F_Text_ThanksForSavingUs::
    .string "¡Gracias por salvarnos!$"

SilphCo_8F_Text_Grunt1Intro::
    .string "¡No podrás llegar más lejos!$"

SilphCo_8F_Text_Grunt1Defeat::
    .string "¡Te falta valor!$"

SilphCo_8F_Text_Grunt1PostBattle::
    .string "Si no retrocedes…\n"
    .string "¡Pediré refuerzos!$"

SilphCo_8F_Text_ParkerIntro::
    .string "¡Nos estás causando problemas!$"

SilphCo_8F_Text_ParkerDefeat::
    .string "¿Uh?\n"
    .string "¿Perdí?$"

SilphCo_8F_Text_ParkerPostBattle::
    .string "Así que, ¿que piensas del\n"
    .string "laberinto del EDIFICIO SILPH?$"

SilphCo_8F_Text_Grunt2Intro::
    .string "¡Soy uno de los cuatro HERMANOS\n"
    .string "ROCKET!$"

SilphCo_8F_Text_Grunt2Defeat::
    .string "¡Uoo!\n"
    .string "¡Oh, hermanos!$"

SilphCo_8F_Text_Grunt2PostBattle::
    .string "Te dejaré para mis hermanos.$"

SilphCo_8F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P8$"

SilphCo_8F_Text_ToRocketBossMonsAreTools::
    .string "¡El JEFE del EQUIPO ROCKET es\n"
    .string "terriblemente cruel!\p"
    .string "Para él, los POKéDEX solo son\n"
    .string "herramientas para ser usadas.\p"
    .string "Lo que pasaría si ese tirano se\n"
    .string "apodera de la compañia…$"
