SSAnne_2F_Room4_Text_LamarIntro:: @ 8173F07
    .string "¿Cuál te parecería mejor, un\n"
    .string "POKéMON fuerte o uno raro?$"

SSAnne_2F_Room4_Text_LamarDefeat:: @ 8173F42
    .string "¡Debo felicitarte!$"

SSAnne_2F_Room4_Text_LamarPostBattle:: @ 8173F55
    .string "Personalmente, prefiero a los\n"
    .string "POKéMON fuertes y raros.$"

SSAnne_2F_Room4_Text_DawnIntro:: @ 8173F83
    .string "No creo que te haya visto en la\n"
    .string "fiesta.$"

SSAnne_2F_Room4_Text_DawnDefeat:: @ 8173FAB
    .string "¡Relájate!$"

SSAnne_2F_Room4_Text_DawnPostBattle:: @ 8173FB9
    .string "¡Oh, adoro a tus fuertes POKéMON!\n"
    .string "¡Oh, cómo te envidio por ellos!$"

