SSAnne_2F_Room4_Text_LamarIntro::
    .string "¿Cuál te parecería mejor, un\n"
    .string "POKéMON fuerte o uno raro?$"

SSAnne_2F_Room4_Text_LamarDefeat::
    .string "¡Debo felicitarte!$"

SSAnne_2F_Room4_Text_LamarPostBattle::
    .string "Personalmente, prefiero a los\n"
    .string "POKéMON fuertes y raros.$"

SSAnne_2F_Room4_Text_DawnIntro::
    .string "No creo que te haya visto en la\n"
    .string "fiesta.$"

SSAnne_2F_Room4_Text_DawnDefeat::
    .string "¡Relájate!$"

SSAnne_2F_Room4_Text_DawnPostBattle::
    .string "¡Oh, adoro a tus fuertes POKéMON!\n"
    .string "¡Oh, cómo te envidio por ellos!$"

