SafariZone_East_Text_KeepAnyItemFoundOnSafari::
    .string "Puedes quedarte con cualquier\n"
    .string "objeto encontrado en las zonas.\p"
    .string "Pero te quedarás sin tiempo si\n"
    .string "intentas obtener todos de una vez.$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
    .string "Ve a la parte más profunda de la\n"
    .string "ZONA SAFARI. ¡Ganarás un premio!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
    .string "Mi EEVEE evolucionó en un FLAREON.\p"
    .string "Pero el EEVEE de un amigo se\n"
    .string "transformó en VAPOREON. ¿Por qué?$"

