ThreeIsland_PokemonCenter_1F_Text_PCNetworkCanLinkWithKanto::
    .string "Ey, ¿escuchaste la noticia?\p"
    .string "La red de PCs ahora se puede\n"
    .string "conectar con las PCs de KANTO.\p"
    .string "No sé como sucedio eso, ¡pero es\n"
    .string "fantástico!$"

ThreeIsland_PokemonCenter_1F_Text_ImpossibleToSurfBetweenIslands::
    .string "Es imposible SURFEAR entre las\n"
    .string "islas de esta área.\p"
    .string "Las olas son demasiado rápidas\n"
    .string "y peligrosas.$"

ThreeIsland_PokemonCenter_1F_Text_AlwaysBerriesInBerryForest::
    .string "¡Vamos a machacar BAYAS!\n"
    .string "…¿Qué sería un desperdicio?\p"
    .string "Siempre puedes encontrar algunas\n"
    .string "BAYAS en el suelo del BOSQUE BAYA.$"

