OneIsland_KindleRoad_Text_MariaIntro::
    .string "¡El clima es hermoso!\n"
    .string "¡Perfecto para una batalla!$"

OneIsland_KindleRoad_Text_MariaDefeat::
    .string "¡Ayiiiih!$"

OneIsland_KindleRoad_Text_MariaPostBattle::
    .string "¡Por favor, no mojes mi cara!\n"
    .string "Arruinarás el maquillaje.$"

OneIsland_KindleRoad_Text_AbigailIntro::
    .string "Me estoy empezando a quemar…$"

OneIsland_KindleRoad_Text_AbigailDefeat::
    .string "Oh, eres lo peor.$"

OneIsland_KindleRoad_Text_AbigailPostBattle::
    .string "Me gusta tu {RRASOM}.\n"
    .string "Tal vez debería llevar algo así…$"

OneIsland_KindleRoad_Text_FinnIntro::
    .string "Visto desde aquí, el MONTE BRASAS\n"
    .string "atraviesa el cielo.$"

OneIsland_KindleRoad_Text_FinnDefeat::
    .string "Bueno, eres dur{OA}.$"

OneIsland_KindleRoad_Text_FinnPostBattle::
    .string "El cielo aparenta ser inmenso en\n"
    .string "esta área.$"

OneIsland_KindleRoad_Text_GarrettIntro::
    .string "Me tome un descanso de nadar,\n"
    .string "¿y ahora me desafías?$"

OneIsland_KindleRoad_Text_GarrettDefeat::
    .string "Ey, pero que…\n"
    .string "¡Eres buen{OA}!$"

OneIsland_KindleRoad_Text_GarrettPostBattle::
    .string "En vez de usar SURF todo el\n"
    .string "tiempo, deberías nadar un poco.$"

OneIsland_KindleRoad_Text_TommyIntro::
    .string "¡Espera! ¡espera un segundo!\n"
    .string "¡Creo que atrapé algo grande!$"

OneIsland_KindleRoad_Text_TommyDefeat::
    .string "Lo perdí todo otra vez…$"

OneIsland_KindleRoad_Text_TommyPostBattle::
    .string "¡No solo perdí, esa cosa grande se\n"
    .string "escapó también!$"

OneIsland_KindleRoad_Text_SharonIntro::
    .string "¿Podrías ayudarme con mi\n"
    .string "entrenamiento?$"

OneIsland_KindleRoad_Text_SharonDefeat::
    .string "Lo hiciste mejor que yo.$"

OneIsland_KindleRoad_Text_SharonPostBattle::
    .string "Es claro que tienes habilidad.\n"
    .string "¡Me agradas!$"

OneIsland_KindleRoad_Text_TanyaIntro::
    .string "¡No hay un día donde no\n"
    .string "entrenemos!$"

OneIsland_KindleRoad_Text_TanyaDefeat::
    .string "¡Fuí una tonta!$"

OneIsland_KindleRoad_Text_TanyaPostBattle::
    .string "¡Ahora entrenaré aún más duro!$"

OneIsland_KindleRoad_Text_SheaIntro::
    .string "Cada mañana, antes de desayunar,\n"
    .string "nado alrededor de la isla.$"

OneIsland_KindleRoad_Text_SheaDefeat::
    .string "Uff…\n"
    .string "Uff…$"

OneIsland_KindleRoad_Text_SheaPostBattle::
    .string "Perdí porque estoy agotado por\n"
    .string "correr tanto…$"

OneIsland_KindleRoad_Text_HughIntro::
    .string "¡Vistete apropiadamente para\n"
    .string "la batalla!\p"
    .string "¡Abandona ese frívolo atuendo!$"

OneIsland_KindleRoad_Text_HughDefeat::
    .string "¡¿Porqué yo?!$"

OneIsland_KindleRoad_Text_HughPostBattle::
    .string "Incluso los artistas marciales\n"
    .string "tienen la moda en mente estos días…$"

OneIsland_KindleRoad_Text_BryceIntro::
    .string "Sabes, todo tiene buen sabor\n"
    .string "cuando estás en la naturaleza.$"

OneIsland_KindleRoad_Text_BryceDefeat::
    .string "¡Awww, me destrozaste!$"

OneIsland_KindleRoad_Text_BrycePostBattle::
    .string "El agua de las regiones volcánicas\n"
    .string "es deliciosa.$"

OneIsland_KindleRoad_Text_ClaireIntro::
    .string "Mi almuerzo nos llenó, ¿podríamos\n"
    .string "tener una batalla como ejercicio?$"

OneIsland_KindleRoad_Text_ClaireDefeat::
    .string "Eso me dejo sudando.$"

OneIsland_KindleRoad_Text_ClairePostBattle::
    .string "¿Qué debería hacer?\n"
    .string "Me siento hambrienta otra vez.$"

OneIsland_KindleRoad_Text_KiaIntro::
    .string "KIA: ¡Mi hermano mayor y yo\n"
    .string "hacemos una combinación asombrosa!$"

OneIsland_KindleRoad_Text_KiaDefeat::
    .string "KIA: ¡¿Huh?!\n"
    .string "¡No puedo creerlo!$"

OneIsland_KindleRoad_Text_KiaPostBattle::
    .string "KIA: ¿Cómo puede haber alguien\n"
    .string "mejor que mi hermano mayor?$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons::
    .string "KIA: Si quieres luchar con\n"
    .string "nosotros, tienes que traer al\l"
    .string "menos dos POKéMON contigo.$"

OneIsland_KindleRoad_Text_MikIntro::
    .string "MIK: ¡Junto con KIA, no le temo\n"
    .string "a nada!$"

OneIsland_KindleRoad_Text_MikDefeat::
    .string "MIK: ¡Woa!\n"
    .string "¡Eso es demasiado!$"

OneIsland_KindleRoad_Text_MikPostBattle::
    .string "MIK: ¿Cómo pudo fallar mi\n"
    .string "combinación con KIA?$"

OneIsland_KindleRoad_Text_MikNotEnoughMons::
    .string "MIK: ¿Ey, quieres luchar con\n"
    .string "nosotros?\p"
    .string "Entonces trae a dos o más POKéMON\n"
    .string "contigo.$"

OneIsland_KindleRoad_Text_RouteSign::
    .string "Este es el CAMINO CANDENTE.\p"
    .string "Va directo al MONTE BRASAS.$"

OneIsland_KindleRoad_Text_EmberSpaSign::
    .string "¡Enciende el fuego en tu corazón!\n"
    .string "SPA BRASAS$"

