PokemonTower_4F_Text_PaulaIntro::
    .string "¡Fantasma! ¡No!\n"
    .string "¡Waaah!$"

PokemonTower_4F_Text_PaulaDefeat::
    .string "¿Dónde esta el fantasma?$"

PokemonTower_4F_Text_PaulaPostBattle::
    .string "Debí estar soñando…$"

PokemonTower_4F_Text_LaurelIntro::
    .string "¡Únete a mi maldición!\n"
    .string "¡Waaah!$"

PokemonTower_4F_Text_LaurelDefeat::
    .string "¿Qué?$"

PokemonTower_4F_Text_LaurelPostBattle::
    .string "No podemos determinar la identidad\n"
    .string "de los fantasmas…$"

PokemonTower_4F_Text_JodyIntro::
    .string "Jujuju…\n"
    .string "¡No me vencerás!$"

PokemonTower_4F_Text_JodyDefeat::
    .string "¿Eh?\n"
    .string "¿Quién? ¿Qué?$"

PokemonTower_4F_Text_JodyPostBattle::
    .string "Que los POKéMON difuntos descansen\n"
    .string "en paz…$"

