CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel::
    .string "El SUPER REPELENTE mantiene lejos\n"
    .string "a POKéMON débiles…p"
    .string "Hmm, es un REPELENTE más poderoso.$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .string "Para viajes largos, deberías\n"
    .string "comprar REVIVIR.$"

CeladonCity_DepartmentStore_2F_Text_FloorSign::
    .string "¡Objetos de la mejor calidad para\n"
    .string "ENTRENADORES!\p"
    .string "P2: MERCADO DE ENTRENADORES$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
    .string "Tenemos un cliente, LANCE, que\n"
    .string "viene ocasionalmente.\p"
    .string "Él siempre compra capas.\p"
    .string "Me pregunto si… ¿tendrá muchas\n"
    .string "capas iguales en casa?$"
