SilphCo_5F_Text_RocketsInUproarAboutIntruder::
    .string "El EQUIPO ROCKET está haciendo\n"
    .string "alboroto por un{OA} intrus{OA}.\p"
    .string "¿Eres tú, verdad?$"

SilphCo_5F_Text_YoureOurHeroThankYou::
    .string "¡El EQUIPO ROCKET huyó!\n"
    .string "¡Eres nuestra h{ET}ro{E}{INAT}! ¡gracias!$"

SilphCo_5F_Text_Grunt1Intro::
    .string "Escuché que un{A} niñ{OA} estaba\n"
    .string "vagando por aquí.$"

SilphCo_5F_Text_Grunt1Defeat::
    .string "¡Bum!$"

SilphCo_5F_Text_Grunt1PostBattle::
    .string "¡Provocar al EQUIPO ROCKET no es\n"
    .string "algo muy inteligente!$"

SilphCo_5F_Text_BeauIntro::
    .string "Estudiamos la tecnología de las\n"
    .string "POKéBOLAS en este piso.$"

SilphCo_5F_Text_BeauDefeat::
    .string "¡Rayos!\n"
    .string "¡Maldita sea!$"

SilphCo_5F_Text_BeauPostBattle::
    .string "Trabajamos en una POKéBOLA\n"
    .string "que debería poder atraparlo todo.$"

SilphCo_5F_Text_DaltonIntro::
    .string "¿Queeé?\p"
    .string "¡No debería haber niños aquí!$"

SilphCo_5F_Text_DaltonDefeat::
    .string "¡Oh, cielos!$"

SilphCo_5F_Text_DaltonPostBattle::
    .string "Solo has llegado al PISO 5.\n"
    .string "¡Mi JEFE aún está muy lejos!$"

SilphCo_5F_Text_Grunt2Intro::
    .string "¡Muestra algo de respeto por el\n"
    .string "EQUIPO ROCKET!$"

SilphCo_5F_Text_Grunt2Defeat::
    .string "Cof…\n"
    .string "Cof…$"

SilphCo_5F_Text_Grunt2PostBattle::
    .string "Eso me recuerda…\p"
    .string "¡KOFFING evoluciona en WEEZING!$"

SilphCo_5F_Text_PorygonFirstVRMon::
    .string "¡Es un INFORME sobre los POKéMON!\p"
    .string "El LABORATORIO POKéMON creó a\n"
    .string "PORYGON, el primer POKéMON de\l"
    .string "realidad virtual.$"

SilphCo_5F_Text_Over350TechniquesConfirmed::
    .string "¡Es un INFORME sobre los POKéMON!\p"
    .string "Se han confirmado más de 350\n"
    .string "técnicas POKéMON.$"

SilphCo_5F_Text_SomeMonsEvolveWhenTraded::
    .string "¡Es un INFORME sobre los POKéMON!\p"
    .string "Se ha confirmado que algunos\n"
    .string "POKéMON evolucionan cuando son\l"
    .string "intercambiados.$"

SilphCo_5F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P5$"

SilphCo_5F_Text_RocketBossLookingForStrongMons::
    .string "Esos matones que invadieron\n"
    .string "nuestro edificio…\p"
    .string "Su JEFE dijo que buscaba POKéMON\n"
    .string "fuertes.\p"
    .string "Espero que nuestro PRESIDENTE haya\n"
    .string "logrado evitarse problemas…$"
