LavenderTown_Mart_Text_SearchingForStatRaiseItems::
    .string "Estoy buscando objetos que suben\n"
    .string "las estadísticas de los POKéMON.\p"
    .string "Son efectivos por la duración de\n"
    .string "una sola batalla.\p"
    .string "ATAQUE X, DEFENSA X, VELOCIDAD X\n"
    .string "y ATAQ. ESP. X son los que busco.\p"
    .string "¿Sabes donde puedo encontrarlos?$"

LavenderTown_Mart_Text_DidYouBuyRevives::
    .string "¿Compraste algunos REVIVIR?\n"
    .string "¡Reviven a cualquier POKéMON\l"
    .string "debilitado!$"

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
    .string "A veces, un dúo de ENTRENADORES\n"
    .string "te desafiarán con dos POKéMON\l"
    .string "al mismo tiempo.\p"
    .string "Si eso pasa, necesitas enviar\n"
    .string "dos POKéMON a la batalla también.$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
    .string "この　あいだ　やまおくで\n"
    .string "きんのたまを　ひろい　ましてね！\p"
    .string "つかえない　しなもの　ですが\n"
    .string "うったら　なんと　5000¥でした$"
