SaffronCity_Dojo_Text_MasterKoichiIntro::
    .string "¡Grr!\p"
    .string "¡Soy el MAESTRO DEL KÁRATE!\n"
    .string "¡Soy el LÍDER aquí!\p"
    .string "¿Nos quieres desafiar?\n"
    .string "¡No esperes piedad!\p"
    .string "¡Fuaaa!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat::
    .string "¡Hwa!\n"
    .string "¡Arrgh! ¡derrotado!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon::
    .string "¡Sí, perdí!\p"
    .string "Pero, te lo suplico, ¡no te lleves\n"
    .string "nuestro emblema como trofeo!\p"
    .string "¡En su lugar, te daré un valioso\n"
    .string "POKéMON de PELEA!\p"
    .string "¡Elige el que tú quieras!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs::
    .string "¡Grr!\n"
    .string "¡Quédate y entrena con nosotros!$"

SaffronCity_Dojo_Text_MikeIntro::
    .string "¡Joargh!\n"
    .string "¡Quítate los zapatos!$"

SaffronCity_Dojo_Text_MikeDefeat::
    .string "¡Me rindo!$"

SaffronCity_Dojo_Text_MikePostBattle::
    .string "¡Espera a ver a nuestro MAESTRO!\n"
    .string "¡No soy nadie comparado con él!$"

SaffronCity_Dojo_Text_HidekiIntro::
    .string "¡Escuché que eres buen{OA}!\n"
    .string "¡Muéstrame!$"

SaffronCity_Dojo_Text_HidekiDefeat::
    .string "¡Juez!\n"
    .string "¡Un punto!$"

SaffronCity_Dojo_Text_HidekiPostBattle::
    .string "Nuestro MAESTRO es un profesional.\n"
    .string "¡Prepárate para perder!$"

SaffronCity_Dojo_Text_AaronIntro::
    .string "¡Jaiyah!\n"
    .string "¡No tengo miedo de nada difícil!\p"
    .string "¡Destrozo rocas en mi\n"
    .string "entrenamiento todos los días!$"

SaffronCity_Dojo_Text_AaronDefeat::
    .string "¡Yau!\n"
    .string "¡Dedos golpeados!$"

SaffronCity_Dojo_Text_AaronPostBattle::
    .string "¡Lo único que nos asusta es el\n"
    .string "poder psíquico!$"

SaffronCity_Dojo_Text_HitoshiIntro::
    .string "¡Waah!\p"
    .string "¡Estás invadiendo nuestro DOJO\n"
    .string "DE PELEA!$"

SaffronCity_Dojo_Text_HitoshiDefeat::
    .string "¡Uf!\n"
    .string "¡Me rindo!$"

SaffronCity_Dojo_Text_HitoshiPostBattle::
    .string "Luchadores excelentes de todas\n"
    .string "partes entrenan aquí.$"

SaffronCity_Dojo_Text_YouWantHitmonlee::
    .string "¿Quieres las duras patadas de\n"
    .string "HITMONLEE?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster::
    .string "{PLAYER} recibió {STR_VAR_1}\n"
    .string "del MAESTRO DEL KÁRATE.$"

SaffronCity_Dojo_Text_YouWantHitmonchan::
    .string "¿Quieres los superpuños de\n"
    .string "HITMONLEE?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2::
    .string "{PLAYER}は　カラテ　だいおう　から\n"
    .string "{STR_VAR_1}を　もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy::
    .string "Mejor no ser codicios{OA}…$"

SaffronCity_Dojo_Text_EnemiesOnEverySide::
    .string "¡Enemigos en cada lado!$"

SaffronCity_Dojo_Text_GoesAroundComesAround::
    .string "Lo que se da se recibe.$"

SaffronCity_Dojo_Text_FightingDojo::
    .string "DOJO DE PELEA$"

