Aide_Text_HaventCaughtEnoughMonsForItem:: @ 81A58A7
	.string "Veamos…\n"
	.string "¡Oh-oh! ¡solo has atrapado\l"
	.string "{STR_VAR_3} tipos de POKéMON!\p"
	.string "Necesitas {STR_VAR_1} tipos\n"
	.string "si quieres {STR_VAR_2}.$"

Aide_Text_GetEnoughMonsComeBackForItem:: @ 81A5909
	.string "…Oh. Ya veo.\p"
	.string "Cuando tengas {STR_VAR_1} tipos de POKéMON,\n"
	.string "vuelve por {STR_VAR_2}.$"

Aide_Text_DontHaveAnyRoomForItem:: @ 81A594D
	.string "¡Oh! veo que no tienes espacio\n"
	.string "para guardar {STR_VAR_2}.$"
