@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "Está totalmente lleno de libros\n"
	.string "sobre POKéMON.$"

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "Un MAPA REGIONAL.$"

Text_PokeMartShelf::
	.string "¡Wow!\n"
	.string "¡Hay montones de cosas de POKéMON!$"

Text_DishesPlatesNeatlyLinedUp::
	.string "Los platos y bandejas están\n"
	.string "bien acomodados.$"

Text_Kitchen::
	.string "¡Huele delicioso!\n"
	.string "Alguien ha estado cocinando aquí.$"

Text_Dresser::
	.string "Es una cómoda bien hecha.\n"
	.string "Puede guardar muchas cosas.$"

Text_Snacks::
	.string "Hay una pila de bocadillos aquí.$"

Text_PokemartSign::
	.string "¡Todos los objetos que necesitas!\n"
	.string "TIENDA POKéMON$"

Text_PokecenterSign::
	.string "¡Cura a tus POKéMON!\n"
	.string "CENTRO POKéMON$"

Text_Indigo_UltimateGoal::
	.string "MESETA AÑIL\p"
	.string "¡La última meta para ENTRENADORES!\n"
	.string "CG de la LIGA POKéMON$"

Text_Indigo_HighestAuthority::
	.string "MESETA AÑIL\p"
	.string "¡La más alta autoridad en POKéMON!\n"
	.string "CG de la LIGA POKéMON$"

Text_Food::
	.string "Debería estar lleno de todo tipo\n"
	.string "de cosas deliciosas para comer.$"

Text_Blueprints::
	.string "Es algún tipo de plano.\n"
	.string "Está lleno de diagramas y texto.$"

Text_Painting::
	.string "Es una linda pintura de un POKéMON.\n"
	.string "Parece que se siente bien.$"

Text_PowerPlantMachine::
	.string "¿Qué podrá ser esta maquina?\n"
	.string "¡Será mejor no hacerle nada!$"

Text_Telephone::
	.string "Es un teléfono.\n"
	.string "Mejor no usarlo.$"

Text_Computer::
	.string "Solo hay palabras y números\n"
	.string "complicados que no tienen sentido…$"

Text_AdvertisingPoster::
	.string "Es un póster anunciando todo\n"
	.string "tipo de productos.$"

Text_TastyFood::
	.string "Oh, ¡eso huele bien!\n"
	.string "¡Puede que mi estómago gruña!$"

Text_TrashBin::
	.string "Aquí adentro…\n"
	.string "……\p"
	.string "¡No hay nada!$"

Text_Cup::
	.string "Es una taza con una marca de\n"
	.string "POKéMON en ella.$"

Text_PolishedWindow::
	.string "La ventana esta muy limpia.$"

Text_BeautifulSkyWindow::
	.string "Afuera de la ventana…\p"
	.string "El cielo se ve fantásticamente\n"
	.string "hermoso.$"

Text_BlinkingLights::
	.string "Luces de diferentes colores que se\n"
	.string "prenden y apagan.$"

Text_NeatlyLinedUpTools::
	.string "Todo tipo de herramientas que\n"
	.string "están bien alineadas.$"

Text_ImpressiveMachine::
	.string "Es algún tipo de máquina.\n"
	.string "Realmente es impresionante.$"

Text_VideoGame::
	.string "¡Es el videojuego de moda!\n"
	.string "¡Se ve divertido!$"

Text_Burglary::
	.string "Hay obvios signos de un robo aquí…$"

Text_PlayerFacingTVScreen::
	.string "¡Hay un POKéMON en la TV!\n"
	.string "Parece que se está divirtiendo.$"
