@ Flavor text for interacting with various background objects

Text_Bookshelf:: @ 81C0DB0
	.string "Está totalmente lleno de libros\n"
	.string "sobre POKéMON.$"

Text_NothingButPokemonBooks:: @ 81C0DD4
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap:: @ 81C0DF1
	.string "Un MAPA REGIONAL.$"

Text_PokeMartShelf:: @ 81C0DFD
	.string "¡Wow!\n"
	.string "¡Hay montones de cosas de POKéMON!$"

Text_DishesPlatesNeatlyLinedUp:: @ 81C0E19
	.string "Los platos y bandejas están\n"
	.string "bien acomodados.$"

Text_Kitchen:: @ 81C0E40
	.string "¡Huele delicioso!\n"
	.string "Alguien ha estado cocinando aquí.$"

Text_Dresser:: @ 81C0E73
	.string "Es una cómoda bien hecha.\n"
	.string "Puede guardar muchas cosas.$"

Text_Snacks:: @ 81C0EAC
	.string "Hay una pila de bocadillos aquí.$"

Text_PokemartSign:: @ 81C0ECB
	.string "¡Todos los objetos que necesitas!\n"
	.string "TIENDA POKéMON$"

Text_PokecenterSign:: @ 81C0EF7
	.string "¡Cura a tus POKéMON!\n"
	.string "CENTRO POKéMON$"

Text_Indigo_UltimateGoal:: @ 81C0F19
	.string "MESETA AÑIL\p"
	.string "¡La última meta para ENTRENADORES!\n"
	.string "CG de la LIGA POKéMON$"

Text_Indigo_HighestAuthority:: @ 81C0F59
	.string "MESETA AÑIL\p"
	.string "¡La más alta autoridad en POKéMON!\n"
	.string "CG de la LIGA POKéMON$"

Text_Food:: @ 81C0F99
	.string "Debería estar lleno de todo tipo\n"
	.string "de cosas deliciosas para comer.$"

Text_Blueprints:: @ 81C0FD8
	.string "Es algún tipo de plano.\n"
	.string "Está lleno de diagramas y texto.$"

Text_Painting:: @ 81C101B
	.string "Es una linda pintura de un POKéMON.\n"
	.string "Parece que se siente bien.$"

Text_PowerPlantMachine:: @ 81C1060
	.string "¿Qué podrá ser esta maquina?\n"
	.string "¡Será mejor no hacerle nada!$"

Text_Telephone:: @ 81C109C
	.string "Es un teléfono.\n"
	.string "Mejor no usarlo.$"

Text_Computer:: @ 81C10C1
	.string "Solo hay palabras y números\n"
	.string "complicados que no tienen sentido…$"

Text_AdvertisingPoster:: @ 81C10FC
	.string "Es un póster anunciando todo\n"
	.string "tipo de productos.$"

Text_TastyFood:: @ 81C1134
	.string "Oh, ¡eso huele bien!\n"
	.string "¡Puede que mi estómago gruña!$"

Text_TrashBin:: @ 81C116E
	.string "Aquí adentro…\n"
	.string "……\p"
	.string "¡No hay nada!$"

Text_Cup:: @ 81C1194
	.string "Es una taza con una marca de\n"
	.string "POKéMON en ella.$"

Text_PolishedWindow:: @ 81C11BA
	.string "La ventana esta muy limpia.$"

Text_BeautifulSkyWindow:: @ 81C11DC
	.string "Afuera de la ventana…\p"
	.string "El cielo se ve fantásticamente\n"
	.string "hermoso.$"

Text_BlinkingLights:: @ 81C1217
	.string "Luces de diferentes colores que se\n"
	.string "prenden y apagan.$"

Text_NeatlyLinedUpTools:: @ 81C124B
	.string "Todo tipo de herramientas que\n"
	.string "están bien alineadas.$"

Text_ImpressiveMachine:: @ 81C1273
	.string "Es algún tipo de máquina.\n"
	.string "Realmente es impresionante.$"

Text_VideoGame:: @ 81C12A7
	.string "¡Es el videojuego de moda!\n"
	.string "¡Se ve divertido!$"

Text_Burglary:: @ 81C12D6
	.string "Hay obvios signos de un robo aquí…$"

Text_PlayerFacingTVScreen:: @ 81C1300
	.string "¡Hay un POKéMON en la TV!\n"
	.string "Parece que se está divirtiendo.$"
