Trade_Text_LookingForMonWannaTradeForMon:: @ 81A597B
	.string "¡Estoy buscando al POKéMON\n"
	.string "{STR_VAR_1}!\p"
	.string "¿Quieres intercambiar uno por mi\n"
	.string "{STR_VAR_2}?$"

Trade_Text_AwwOhWell:: @ 81A59B6
	.string "¡Awww!\n"
	.string "Oh, bueno…$"

Trade_Text_WhatThatsNoMon:: @ 81A59C6
	.string "¿Qué?\n"
	.string "¡Eso no es un {STR_VAR_1}!$"

Trade_Text_HeyThanks:: @ 81A59DA
	.string "¡Ey, gracias!$"

Trade_Text_IsntMyOldMonGreat:: @ 81A59E7
	.string "¿No es mi {STR_VAR_2} genial?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon:: @ 81A59FE
	.string "¡Hola, tu! ¿Tendrás de casualidad\n"
	.string "a un {STR_VAR_1}?\p"
	.string "¿Querrías cambiarlo por mi\n"
	.string "{STR_VAR_2}?$"

Trade_Text_WellIfYouDontWantTo:: @ 81A5A4E
	.string "Bien, si es que no quieres…$"

Trade_Text_ThisIsntMon:: @ 81A5A6A
	.string "¿Hmmm?\n"
	.string "Esto no es un {STR_VAR_1}.\p"
	.string "Piensa en mí si encuentras uno.$"

Trade_Text_Thanks:: @ 81A5A9D
	.string "¡Gracias!$"

Trade_Text_HasTradedMonGrownStronger:: @ 81A5AA5
	.string "Ese {STR_VAR_2} que te dí,\n"
	.string "¿se ha vuelto más fuerte?$"

Trade_Text_DoYouHaveMonWantToTradeForMon:: @ 81A5AD6
	.string "¡Hola!\n"
	.string "¿Tienes un {STR_VAR_1}?\p"
	.string "¿Quieres intercambiarlo por mi\n"
	.string "{STR_VAR_2}?$"

Trade_Text_ThatsTooBad:: @ 81A5B08
	.string "Qué mal.$"

Trade_Text_ThisIsNoMon:: @ 81A5B18
	.string "…Este no es un {STR_VAR_1}.\p"
	.string "Si obtienes uno, cambia conmigo.$"

Trade_Text_ThanksYoureAPal:: @ 81A5B4A
	.string "¡Gracias, eres buen{OA} amig{OA}!$"

Trade_Text_HowIsMyOldMon:: @ 81A5B60
	.string "¿Cómo está mi viejo {STR_VAR_2}?\n"
	.string "¡A mi {STR_VAR_1} le va genial!$"
