Trade_Text_LookingForMonWannaTradeForMon::
	.string "¡Estoy buscando al POKéMON\n"
	.string "{STR_VAR_1}!\p"
	.string "¿Quieres intercambiar uno por mi\n"
	.string "{STR_VAR_2}?$"

Trade_Text_AwwOhWell::
	.string "¡Awww!\n"
	.string "Oh, bueno…$"

Trade_Text_WhatThatsNoMon::
	.string "¿Qué?\n"
	.string "¡Eso no es un {STR_VAR_1}!$"

Trade_Text_HeyThanks::
	.string "¡Ey, gracias!$"

Trade_Text_IsntMyOldMonGreat::
	.string "¿No es mi {STR_VAR_2} genial?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "¡Hola, tu! ¿Tendrás de casualidad\n"
	.string "a un {STR_VAR_1}?\p"
	.string "¿Querrías cambiarlo por mi\n"
    .string "{STR_VAR_2}?$"

Trade_Text_WellIfYouDontWantTo::
	.string "Bien, si es que no quieres…$"

Trade_Text_ThisIsntMon::
	.string "¿Hmmm?\n"
	.string "Esto no es un {STR_VAR_1}.\p"
	.string "Piensa en mí si encuentras uno.$"

Trade_Text_Thanks::
	.string "¡Gracias!$"

Trade_Text_HasTradedMonGrownStronger::
	.string "Ese {STR_VAR_2} que te dí,\n"
	.string "¿se ha vuelto más fuerte?$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "¡Hola!\n"
	.string "¿Tienes un {STR_VAR_1}?\p"
	.string "¿Quieres intercambiarlo por mi\n"
	.string "{STR_VAR_2}?$"

Trade_Text_ThatsTooBad::
	.string "Qué mal.$"

Trade_Text_ThisIsNoMon::
	.string "…Este no es un {STR_VAR_1}.\p"
	.string "Si obtienes uno, cambia conmigo.$"

Trade_Text_ThanksYoureAPal::
	.string "¡Gracias, eres buen{OA} amig{OA}!$"

Trade_Text_HowIsMyOldMon::
	.string "¿Cómo está mi viejo {STR_VAR_2}?\n"
	.string "¡A mi {STR_VAR_1} le va genial!$"
