gOtherText_NewName:: @ 81C574F
    .string "OTRO NOMBRE$"
             
gNameChoice_Green:: @ 81C5758
    .string "AZUL$"
             
gNameChoice_Red:: @ 81C575E
    .string "ROJO$"

gNameChoice_Leaf:: @ 81C5762
    .string "HOJA$"

gNameChoice_Fire:: @ 81C5767
    .string "FUEGO$"

gNameChoice_Gary:: @ 81C576C
    .string "GARY$"

gNameChoice_Kaz:: @ 81C5771
    .string "VERDE$"

gNameChoice_Toru:: @ 81C5775
    .string "TORU$"

gNameChoice_Ash:: @ 81C577A
    .string "ASH$"

gNameChoice_Kene:: @ 81C577E
    .string "KENE$"

gNameChoice_Geki:: @ 81C5783
    .string "GEKI$"

gNameChoice_Jak:: @ 81C5788
    .string "JAK$"

gNameChoice_Janne:: @ 81C578C
    .string "JANNE$"

gNameChoice_Jonn:: @ 81C5792
    .string "JONN$"

gNameChoice_Kamon:: @ 81C5797
    .string "KAMON$"

gNameChoice_Karl:: @ 81C579D
    .string "KARL$"

gNameChoice_Taylor:: @ 81C57A2
    .string "TAYLOR$"

gNameChoice_Oscar:: @ 81C57A9
    .string "OSCAR$"

gNameChoice_Hiro:: @ 81C57AF
    .string "HIRO$"

gNameChoice_Max:: @ 81C57B4
    .string "MAX$"

gNameChoice_Jon:: @ 81C57B8
    .string "JON$"

gNameChoice_Ralph:: @ 81C57BC
    .string "RALPH$"

gNameChoice_Kay:: @ 81C57C2
    .string "KAY$"

gNameChoice_Tosh:: @ 81C57C6
    .string "TOSH$"

gNameChoice_Roak:: @ 81C57CB
    .string "ROAK$"

gNameChoice_Omi:: @ 81C57D0
    .string "OMI$"

gNameChoice_Jodi:: @ 81C57D4
    .string "JODI$"

gNameChoice_Amanda:: @ 81C57D9
    .string "AMANDA$"

gNameChoice_Hillary:: @ 81C57E0
    .string "HILLARY$"

gNameChoice_Makey:: @ 81C57E8
    .string "MAKEY$"

gNameChoice_Michi:: @ 81C57EE
    .string "MICHI$"

gNameChoice_Paula:: @ 81C57F4
    .string "PAULA$"

gNameChoice_June:: @ 81C57FA
    .string "JUNE$"

gNameChoice_Cassie:: @ 81C57FF
    .string "CASSIE$"

gNameChoice_Rey:: @ 81C5806
    .string "REY$"

gNameChoice_Seda:: @ 81C580A
    .string "SEDA$"

gNameChoice_Kiko:: @ 81C580F
    .string "KIKO$"

gNameChoice_Mina:: @ 81C5814
    .string "MINA$"

gNameChoice_Norie:: @ 81C5819
    .string "NORIE$"

gNameChoice_Sai:: @ 81C581F
    .string "SAI$"

gNameChoice_Momo:: @ 81C5823
    .string "MOMO$"

gNameChoice_Suzi:: @ 81C5828
    .string "SUZI$"

gNewGame_HelpDocs1:: @ 81C582D
    .string "La explicación de los botones\n"
    .string "se dará por orden de importancia.$"

gNewGame_HelpDocs2:: @ 81C5875
    .string "Mueve al protagonista.\n"
    .string "También se usa para seleccionar\n"
    .string "opciones.$"

gNewGame_HelpDocs3:: @ 81C58BA
    .string "Confirma opciones, revisa\n"
    .string "cosas, chatea y lee texto.$"
             
gNewGame_HelpDocs4:: @ 81C58F9
    .string "Retrocede, cancela opciones\n"
    .string "y ayuda a salir de varios menús.$"
            
gNewGame_HelpDocs5:: @ 81C592B
    .string "Este botón abre el menú.$"

gNewGame_HelpDocs6:: @ 81C594F
    .string "Cambia objetos de lugar y usa\n"
    .string "el que se haya registrado.$"
             
gNewGame_HelpDocs7:: @ 81C5981
    .string "Si necesitas AYUDA jugando,\n"
    .string "presiona uno de estos botones.$"

gOakText_AskPlayerGender:: @ 81C59D5
    .string "Primero dime. ¿Eres un chico?\n"
    .string "¿O eres una chica?$"

gNewGameAdventureIntro1::
    .string "Estás a punto de sumergirte en un\n"
    .string "mundo de fantasía, donde serás\n"
    .string "protagonista de una gran aventura.\n"
    .string "\n"
    .string "Habla con la gente y revisa cosas\n"
    .string "estés donde estés, ya sea pueblos,\n"
    .string "caminos o cuevas. Reúne información\n"
    .string "y pistas de cada fuente.$"
             
gNewGameAdventureIntro2::
    .string "Nuevos caminos se abrirán al ayudar a\n"
    .string "gente necesitada, enfrentar desafíos\n"
    .string "y resolver misterios.\n"
    .string "\n"
    .string "A veces, otros te desafiarán y\n"
    .string "criaturas salvajes te atacarán.\n"
    .string "Se valiente y sigue adelante.$"
             
gNewGameAdventureIntro3::
    .string "Esperamos que durante tu aventura\n"
    .string "interactúes con todo tipo de gente\n"
    .string "y logres crecer como persona.\n"
    .string "Ese es nuestro objetivo principal.\n"
    .string "\n"
    .string "Presiona el Botón A, ¡y deja que\n"
    .string "tu aventura comience!$"
           
gOakText_WelcomeToTheWorld:: @ 81C5C78
    .string "¡Hola!\n"
    .string "¡Encantado de conocerte!\p¡Este es el mundo de POKéMON!\pMi nombre es OAK.\pPero la gente me llama\n"
    .string "PROFESOR POKéMON.\p$"
    
gOakText_WorldInhabited1:: @ 81C5D06
    .string "Este mundo…$"

gOakText_WorldInhabited2:: @ 81C5D12
    .string "…está habitado por unas\n"
    .string "criaturas llamadas POKéMON.\p$"
             
gOakText_PetsBattlingStudy:: @ 81C5D4B
    .string "Para algunos, los POKéMON son\n"
    .string "mascotas. Pero otros los usan\l"
    .string "para pelear.\pEn cuanto a mí…\pEstudio a los POKéMON como\n"
    .string "profesión.\p$"
                                           
gOakText_TellMeALittleAboutYourself:: @ 81C5DBD
    .string "Antes de seguir, cuéntame sobre ti.\p$"

gOakText_AskPlayerName:: @ 81C5DEA
    .string "Sigamos con tu nombre.\p$"

gOakText_FinalizePlayerName:: @ 81C5E13
    .string "Bien…\n"
    .string "Así que tu nombre es {PLAYER}.$"

gOakText_IntroduceRival:: @ 81C5E2E
    .string "Éste es mi nieto.\pHa sido tu rival desde que erán\n"
    .string "pequeños.\pMmm… ¿Cuál era su nombre?$"

gOakText_AskRivalName:: @ 81C5E91
    .string "¿Cuál era el nombre de tu rival?$"

gOakText_ConfirmRivalName:: @ 81C5EB5
    .string "…Eh, ¿era {RIVAL}?$"

gOakText_RememberRivalName:: @ 81C5EC5
    .string "¡Es verdad! ¡Ya lo recuerdo!\n"
    .string "¡Su nombre es {RIVAL}!\p$"

gOakText_LegendAboutToUnfold:: @ 81C5EF4
    .string "¡{PLAYER}!\p¡Tu propia leyenda POKéMON está\n"
    .string "apunto de comenzar!\p¡Te espera un mundo de sueños y\n"
    .string "aventuras con los POKéMON! ¡Vamos!$"
