Text_ObtainedTheX::
	.string "¡Obtuviste {STR_VAR_2}!$"

Text_BagIsFull::
	.string "La MOCHILA está llena…$"

Text_PutItemAway::
	.string "{PLAYER} puso {STR_VAR_2}\n"
	.string "en {STR_VAR_3}.$"

Text_FoundOneItem::
	.string "¡{PLAYER} encontró 1 {STR_VAR_2}!$"

Text_TooBadBagFull::
	.string "¡Que mal!\n"
	.string "La MOCHILA está llena…$"

Text_FoundXCoins::
	.string "¡{PLAYER} encontró\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase::
	.string "{PLAYER} puso las MONEDAS en el\n"
	.string "ESTUCHE DE MONEDAS.$"

Text_CoinCaseIsFull::
	.string "¡Que mal!\n"
	.string "El ESTUCHE DE MONEDAS está lleno…$"

Text_NothingToPutThemIn::
	.string "¡Que mal!\n"
	.string "No hay dónde poner esto…$"

Text_FoundXItems::
	.string "¡{PLAYER} encontró\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

Text_ObtainedTheDecor::
	.string "¡Obtuviste {STR_VAR_2}!$"

Text_NoRoomForAnotherDecor::
	.string "¡Que mal! no queda espacio para\n"
	.string "otro {STR_VAR_2}…$"

Text_DecorTransferredToPC::
	.string "{STR_VAR_2} se transfirió\n"
	.string "a tu PC.$"
