Text_ObtainedTheX:: @ 81A51F6
	.string "¡Obtuviste {STR_VAR_2}!$"

Text_BagIsFull:: @ 81A5207
	.string "La MOCHILA está llena…$"

Text_PutItemAway:: @ 81A5218
	.string "{PLAYER} puso {STR_VAR_2}\n"
	.string "en {STR_VAR_3}.$"

Text_FoundOneItem:: @ 81A5231
	.string "¡{PLAYER} encontró {STR_VAR_2}!$"

Text_TooBadBagFull:: @ 81A5242
	.string "¡Que mal!\n"
	.string "La MOCHILA está llena…$"

Text_FoundXCoins:: @ 81A525C
	.string "¡{PLAYER} encontró\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase:: @ 81A526C
	.string "{PLAYER} puso las MONEDAS en el\n"
	.string "ESTUCHE DE MONEDAS.$"

Text_CoinCaseIsFull:: @ 81A5294
	.string "¡Que mal!\n"
	.string "El ESTUCHE DE MONEDAS está lleno…$"

Text_NothingToPutThemIn:: @ 81A52B4
	.string "¡Que mal!\n"
	.string "No hay dónde poner esto…$"

Text_FoundXItems:: @ 81A52DD
	.string "¡{PLAYER} encontró\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

Text_ObtainedTheDecor:: @ 81A52F0
	.string "¡Obtuviste {STR_VAR_2}!$"

Text_NoRoomForAnotherDecor:: @ 81A5301
	.string "¡Que mal! no queda espacio para\n"
	.string "otro {STR_VAR_2}…$"

Text_DecorTransferredToPC:: @ 81A532F
	.string "{STR_VAR_2} se transfirió\n"
	.string "a tu PC.$"
