Text_BootedUpPC:: @ 81A5075
	.string "{PLAYER} encendió la PC.$"

Text_AccessWhichPC:: @ 81A508A
	.string "¿A qué PC quieres acceder?$"

Text_AccessedSomeonesPC:: @ 81A50A7
	.string "Accediste a la PC de Alguien.$"

Text_OpenedPkmnStorage:: @ 81A50BE
	.string "Acceso al Sistema de\n" 
	.string "Almacenamiento de POKéMON\l"
	.string "concedido.$"

Text_AccessedPlayersPC:: @ 81A50DD
	.string "Accediste a la PC de {PLAYER}.$"

Text_AccessedBillsPC:: @ 81A50EF
	.string "Accediste a la PC de BILL.$"
