Text_BootedUpPC::
	.string "{PLAYER} encendió la PC.$"

Text_AccessWhichPC::
	.string "¿A qué PC quieres acceder?$"

Text_AccessedSomeonesPC::
	.string "Accediste a la PC de Alguien.$"

Text_OpenedPkmnStorage::
	.string "Acceso al Sistema de\n"
	.string "Almacenamiento de POKéMON\l"
	.string "concedido.$"

Text_AccessedPlayersPC::
	.string "Accediste a la PC de {PLAYER}.$"

Text_AccessedBillsPC::
	.string "Accediste a la PC de BILL.$"
