Text_MonSentToBoxInSomeonesPC::
    .string "{STR_VAR_2} se transfirió a la\n"
    .string "PC de ALGUIEN.\p"
    .string "Terminó en la CAJA\n"
    .string "“{STR_VAR_1}.”$"

Text_MonSentToBoxInBillsPC::
    .string "{STR_VAR_2} se transfirió a la\n"
    .string "PC de BILL.\p"
    .string "Terminó en la CAJA\n"
    .string "“{STR_VAR_1}.”$"

Text_MonSentToBoxSomeonesBoxFull::
    .string "La CAJA “{STR_VAR_3}” en\n"
    .string "la PC de ALGUIEN está llena.\p"
    .string "{STR_VAR_2} se transfirió a\n"
    .string "la CAJA “{STR_VAR_1}.$"

Text_MonSentToBoxBillsBoxFull::
    .string "La CAJA “{STR_VAR_3}” en\n"
    .string "la PC de BILL está llena.\p"
    .string "{STR_VAR_2} se transfirió a\n"
    .string "la CAJA “{STR_VAR_1}.”$"

Text_PlayerObtainedTheMon::
    .string "¡{PLAYER} obtuvo\n"
    .string "{STR_VAR_1}!$"

@ Unused. Translated below
@ You cannot carry any more Pokemon, so {STR_VAR_2} was sent to PC Box {STR_VAR_1}!
Text_MonSentToBoxInPC::
    .string "ポケモンを　もちきれないので\n"
    .string "パソコンの　ボックス“{STR_VAR_1}”　に\l"
    .string "{STR_VAR_2}を　てんそうした！$"

Text_NoMoreRoomForPokemon::
    .string "¡No hay más espacio para POKéMON!\p"
    .string "¡Las CAJAS POKéMON están llenas\n"
    .string "y no pueden aceptar más!$"
