PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: ¡Es bueno verte!\n"
	.string "¿Cómo va tu POKéDEX?\p"
	.string "Déjame dar un vistazo.$"

PokedexRating_Text_SeenXOwnedY::
	.string "El progreso que has hecho en\n"
	.string "tu POKéDEX es:\p"
	.string "{STR_VAR_1} POKéMON vistos y\n"
	.string "{STR_VAR_2} POKéMON atrapados.\p"
	.string "{FONT_NORMAL}Evaluación del PROFESOR OAK:$"

PokedexRating_Text_LessThan10::
	.string "Aún tienes mucho que hacer.\p"
	.string "¡Ve a toda la hierba que veas\n"
	.string "y busca POKéMON!$"

PokedexRating_Text_LessThan20::
	.string "¡Parece que vas por el camino\n"
	.string "correcto!\p"
	.string "Le di una MO de DESTELLO a uno de\n"
	.string "mis AYUDANTES. ¡Ve a conseguirla!$"

PokedexRating_Text_LessThan30::
	.string "¡Tu POKéDEX podría usar algo más\n"
	.string "de volumen!\p"
	.string "¡Intenta atrapar otras especies\n"
	.string "de POKéMON!$"

PokedexRating_Text_LessThan40::
	.string "¡Bien, esta claro que estas\n"
	.string "trabajando duro!\p"
	.string "Le di un BUSCA OBJETOS a uno de\n"
	.string "mis AYUDANTES. ¡Ve a conseguirlo!$"

PokedexRating_Text_LessThan50::
	.string "¡Tu POKéDEX ha avanzado bastante\n"
	.string "bien!\p"
	.string "Le di una MONEDA AMULETO a uno de\n"
	.string "mis AYUDANTES. ¡Ve a conseguirla!$"

PokedexRating_Text_LessThan60::
	.string "¡Ah, finalmente superaste las\n"
	.string "50 especies!\p"
	.string "Le di un REPARTIR EXP. a uno de\n"
	.string "mis AYUDANTES. ¡Ve a conseguirlo!$"

PokedexRating_Text_LessThan70::
	.string "¡Jojo! ¡tu POKéDEX se esta\n"
	.string "volviendo bastante respetable!$"

PokedexRating_Text_LessThan80::
	.string "¡Muy bien!\p"
	.string "¡Creo que colectaras incluso más\n"
	.string "POKéMON si vas a pescar!$"

PokedexRating_Text_LessThan90::
	.string "¡Maravilloso! déjame adivinar… ¿te\n"
	.string "gusta coleccionar cosas, cierto?$"

PokedexRating_Text_LessThan100::
	.string "¡Estoy impresionado!\n"
	.string "¡Debío ser difícil hacer esto!$"

PokedexRating_Text_LessThan110::
	.string "¡Superaste las 100 especies!\n"
	.string "¡No puedo creer lo buen{OA} que eres!$"

PokedexRating_Text_LessThan120::
	.string "¡Incluso tienes las evoluciones de\n"
	.string "los POKéMON! ¡super!$"

PokedexRating_Text_LessThan130::
	.string "¡Excelente! ¡intercambia con\n"
	.string "amigos para conseguir algunos más!$"

PokedexRating_Text_LessThan140::
	.string "¡Espectacular!\p"
	.string "¡Te has convertido en un{A}\n"
	.string "verdader{OA} profesional en esto!$"

PokedexRating_Text_LessThan150::
	.string "¡No tengo nada más que decir!\n"
	.string "¡Ahora tu eres {ELLA}\l"
	.string "PROFESOR{AM} POKéMON!$"

PokedexRating_Text_Complete::
	.string "¡Tu POKéDEX está completa!\n"
	.string "¡¡Felicidades!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "Y tu POKéDEX NACIONAL es:\p"
	.string "{STR_VAR_1} POKéMON vistos y\n"
	.string "{STR_VAR_2} POKéMON capturados.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "¡Estaré esperando ver como llenas\n"
	.string "la POKéDEX NACIONAL!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Al fin…\p"
	.string "¡Finalmente completaste la\n"
	.string "POKéDEX!\p"
	.string "¡Es magnífica!\n"
	.string "¡Este es un logro increíble!$"

PokedexRating_Text_Wroooaaarrr::
	.string "¡Wroooooooaaaaaarrrr!$"

PokedexRating_Text_HaHa::
	.string "はあ はあ‥$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "¡Gracias, {PLAYER}!\n"
	.string "¡Sinceramente, gracias!\l"
	.string "¡Volviste mi sueño realidad!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: ¡Ah, bienvenid{OA}!\p"
	.string "Dime, ¿cómo ha avanzado tu\n"
	.string "POKéDEX?\p"
	.string "¡Wajaja!\p"
	.string "¡En realidad ya lo sé, pero me\n"
	.string "encanta verla de todos modos!\p"
	.string "Veamos…$"
