Text_MayIHelpYou::
	.string "¡Hola!\n"
	.string "¿Te puedo ayudar?$"

Text_FillOutQuestionnaire::
	.string "Hay un cuestionario.\n"
	.string "¿Quieres llenarlo?$"

Text_QuestionnaireThankYou::
	.string "Gracias por tomarte el tiempo de\n"
	.string "llenar el cuestionario.\p"
	.string "Tus respuestas serán usadas como\n"
	.string "referencia en el futuro.$"

Text_YouKnowThoseWords::
	.string "¡Oh, hola!\n"
	.string "¿Conoces estas palabras?\p"
	.string "Entonces debes conocer el\n"
	.string "REGALO MISTERIOSO.\p"
	.string "¡A partir de ahora, podrás recibir\n"
	.string "REGALOS MISTERIOSOS!$"

Text_YouCanAccessMysteryGift::
	.string "Una vez guardes tu partida, podrás\n"
	.string "acceder al REGALO MISTERIOSO.$"

Text_ThankYouForAccessingMysteryGift::
	.string "Gracias por acceder al sistema de\n"
	.string "REGALOS MISTERIOSOS.$"
