Text_OnlySkilledTrainersAllowedThrough::
	.string "Solo se permiten ENTRENADORES\n"
	.string "realmente buenos.\p"
	.string "¡Aún no tienes la\n"
	.string "{STR_VAR_1}!$"

Text_CantLetYouPass::
	.string "Las reglas son las reglas.\n"
	.string "No puedo dejarte pasar.$"

Text_OhThatsBadgeGoRightAhead::
	.string "¡Oh! Esa es la {STR_VAR_1}!\n"
	.string "Puedes pasar.$"

Text_OnlyPassWithBadgeDontHaveYet::
	.string "Solo puedes pasar aquí si tienes\n"
	.string "la {STR_VAR_1}.\p"
	.string "Aún no tienes la\n"
	.string "{STR_VAR_1}.\p"
	.string "Tienes que tenerla para ir a\n"
	.string "la LIGA POKéMON.$"

Text_OnlyPassWithBadgeOhGoAhead::
	.string "Solo puedes pasar aquí si tienes\n"
	.string "la {STR_VAR_1}.\p"
	.string "¡Oh! Esa es la {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "De acuerdo.\n"
	.string "Por favor, sigue adelante.$"
