Text_OnlySkilledTrainersAllowedThrough:: @ 81A572A
	.string "Solo se permiten ENTRENADORES\n"
	.string "realmente buenos.\p"
	.string "¡Aún no tienes la\n"
	.string "{STR_VAR_1}!$"

Text_CantLetYouPass:: @ 81A5776
	.string "Las reglas son las reglas.\n"
	.string "No puedo dejarte pasar.$"

Text_OhThatsBadgeGoRightAhead:: @ 81A579D
	.string "¡Oh! Esa es la {STR_VAR_1}!\n"
	.string "Puedes pasar.$"

Text_OnlyPassWithBadgeDontHaveYet:: @ 81A57C1
	.string "Solo puedes pasar aquí si tienes\n"
	.string "la {STR_VAR_1}.\p"
	.string "Aún no tienes la\n"
	.string "{STR_VAR_1}.\p"
	.string "Tienes que tenerla para ir a\n"
	.string "la LIGA POKéMON.$"

Text_OnlyPassWithBadgeOhGoAhead:: @ 81A5839
	.string "Solo puedes pasar aquí si tienes\n"
	.string "la {STR_VAR_1}.\p"
	.string "¡Oh! Esa es la {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "De acuerdo.\n"
	.string "Por favor, sigue adelante.$"
