gText_WouldYouLikeToSaveTheGame:: @ 81C55C9
	.string "¿Quieres guardar la partida?$"

gText_AlreadySaveFile_WouldLikeToOverwrite:: @ 81C55EA
	.string "Ya hay una partida guardada.\n"
	.string "¿Quieres sobrescribirla?$"

gText_SavingDontTurnOffThePower:: @ 81C5625
	.string "GUARDANDO…\n"
	.string "NO APAGUES LA CONSOLA.$"

gText_PlayerSavedTheGame:: @ 81C5647
	.string "{PLAYER} guardó la partida.$"

gText_SaveFailed::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile:: @ 81C566A
	.string "¡ADVERTENCIA!\p"
	.string "Ya hay una partida guardada.\n"
	.string "Si guardas ahora, perderás los\n"
	.string "datos de la otra partida,\l"
	.string "incluyendo objetos y POKéMON.\p"
	.string "¿Quieres guardar ahora y\n"
	.string "sobrescribir la otra partida?$"
