gText_WouldYouLikeToSaveTheGame::
	.string "¿Quieres guardar la partida?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "Ya hay una partida guardada.\n"
	.string "¿Quieres sobrescribirla?$"

gText_SavingDontTurnOffThePower::
	.string "GUARDANDO…\n"
	.string "NO APAGUES LA CONSOLA.$"

gText_PlayerSavedTheGame::
	.string "{PLAYER} guardó la partida.$"

gText_SaveFailed::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile::
	.string "¡ADVERTENCIA!\p"
	.string "Ya hay una partida guardada.\n"
	.string "Si guardas ahora, perderás los\n"
	.string "datos de la otra partida,\l"
	.string "incluyendo objetos y POKéMON.\p"
	.string "¿Quieres guardar ahora y\n"
	.string "sobrescribir la otra partida?$"
