@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight:: @ 81B1C8B
	.string "Mmm…\n"
	.string "Qué curioso…$"

PalletTown_Text_OhLookLook:: @ 81B1C9F
	.string "¡Oh!\n"
	.string "¡Mira, mira!$"

PalletTown_Text_ReadItReadIt:: @ 81B1CAF
	.string "¡Leelo, leelo!$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu:: @ 81B1CC1
	.string "CONSEJOS PARA ENTRENADORES\p"
	.string "¡Presiona START para abrir el MENÚ!$"

PalletTown_Text_SignsAreUsefulArentThey:: @ 81B1CEC
	.string "Los carteles son útiles, ¿verdad?$"

PalletTown_Text_LookCopiedTrainerTipsSign:: @ 81B1D0B
	.string "¡Mira, mira!\p"
	.string "¡Copie lo que decia en uno de esos\n"
	.string "carteles de CONSEJOS PARA\l"
	.string "ENTRENADORES!$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy:: @ 81B1D51
	.string "¡CONSEJOS PARA ENTRENADORES!\p"
	.string "¡Presiona START para abrir el MENÚ!$"
