@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight::
	.string "Mmm…\n"
	.string "Qué curioso…$"

PalletTown_Text_OhLookLook::
	.string "¡Oh!\n"
	.string "¡Mira, mira!$"

PalletTown_Text_ReadItReadIt::
	.string "¡Leelo, leelo!$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu::
	.string "CONSEJOS PARA ENTRENADORES\p"
	.string "¡Presiona START para abrir el MENÚ!$"

PalletTown_Text_SignsAreUsefulArentThey::
	.string "Los carteles son útiles, ¿verdad?$"

PalletTown_Text_LookCopiedTrainerTipsSign::
	.string "¡Mira, mira!\p"
	.string "¡Copie lo que decia en uno de esos\n"
	.string "carteles de CONSEJOS PARA\l"
	.string "ENTRENADORES!$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy::
	.string "¡CONSEJOS PARA ENTRENADORES!\p"
	.string "¡Presiona START para abrir el MENÚ!$"
