	.string "{PKMN} TRAINER$", 13
	.string "{PKMN} TRAINER$", 13
	.string "AQUA LEADER$", 13
	.string "TEAM AQUA$", 13
	.string "SEÑORITA AROMA$", 13
	.string "RUINAMANÍACO$", 13
	.string "INTERVIEWER$", 13
	.string "PLAYERO$", 13
	.string "PLAYERA$", 13
	.string "ENTRENADOR GENIAL$", 13
	.string "BRUJA MANÍACA$", 13
	.string "SEÑORITA$", 13
	.string "BELLA$", 13
	.string "RICH BOY$", 13
	.string "POKéMANÍACO$", 13
	.string "NADADOR$", 13
	.string "CINTA NEGRA$", 13
	.string "GUITARIST$", 13
	.string "KINDLER$", 13
	.string "CAMPISTA$", 13
	.string "BUG MANIAC$", 13
	.string "PSÍQUICO$", 13
	.string "CABALLERO$", 13
	.string "ALTO MANDO$", 13
	.string "LÍDER$", 13
	.string "SCHOOL KID$", 13
	.string "SR. AND JR.$", 13
	.string "POKéFAN$", 13
	.string "EXPERT$", 13
	.string "JOVEN$", 13
	.string "CAMPEÓN$", 13
	.string "PESCADOR$", 13
	.string "TRIATHLETE$", 13
	.string "DRAGON TAMER$", 13
	.string "CRIA AVES$", 13
	.string "NINJA BOY$", 13
	.string "BATTLE GIRL$", 13
	.string "PARASOL LADY$", 13
	.string "NADADORA$", 13
	.string "CHICA PÍCNIC$", 13
	.string "GEMELAS$", 13
	.string "MARINERO$", 13
	.string "BOARDER$", 13
	.string "COLLECTOR$", 13
	.string "{PKMN} TRAINER$", 13
	.string "CRIA{PKMN}$", 13
	.string "{PKMN} RANGER$", 13
	.string "MAGMA LEADER$", 13
	.string "TEAM MAGMA$", 13
	.string "CHICA$", 13
	.string "CAZA BICHOS$", 13
	.string "MONTAÑERO$", 13
	.string "PAREJA JOVEN$", 13
	.string "OLD COUPLE$", 13
	.string "HERMANOS$", 13
	.string "AQUA ADMIN$", 13
	.string "MAGMA ADMIN$", 13
	.string "JOVEN$", 13
	.string "CAZA BICHOS$", 13
	.string "CHICA$", 13
	.string "MARINERO$", 13
	.string "CAMPISTA$", 13
	.string "CHICA PÍCNIC$", 13
	.string "POKéMANIACO$", 13
	.string "CEREBRITO$", 13
	.string "MONTAÑERO$", 13
	.string "MOTORISTA$", 13
	.string "LADRÓN$", 13
	.string "MECÁNICO$", 13
	.string "PESCADOR$", 13
	.string "NADADOR$", 13
	.string "RAPADO$", 13
	.string "JUGADOR$", 13
	.string "BELLA$", 13
	.string "NADADORA$", 13
	.string "PSÍQUICA$", 13
	.string "TÉCNICO$", 13
	.string "MALABARISTA$", 13
	.string "DOMADOR$", 13
	.string "CRIA AVES$", 13
	.string "CINTA NEGRA$", 13
	.string "RIVAL$", 13
	.string "CIENTÍFICO$", 13
	.string "JEFE$", 13
	.string "LÍDER$", 13
	.string "EQUIPO ROCKET$", 13
	.string "ENTRENADORA GENIAL$", 13
	.string "ALTO MANDO$", 13
	.string "CABALLERO$", 13
	.string "RIVAL$", 13
	.string "CAMPEÓN$", 13
	.string "CHAMÁN$", 13
	.string "GEMELAS$", 13
	.string "PAREJA GENIAL$", 13
	.string "PAREJA JOVEN", 13
	.string "DÚO FUERTE$", 13
	.string "HERMANOS$", 13
	.string "PROF. {PKMN}$", 13
	.string "PLAYER$", 13
	.string "CHICA FUERTE$", 13
	.string "TUBER$", 13
	.string "CRIA{PKMN}$", 13
	.string "{PKMN} RANGER$", 13
	.string "SEÑORITA AROMA$", 13
	.string "RUINAMANIACO$", 13
	.string "SEÑORITA$", 13
	.string "PINTORA$", 13
