Text_FirstShouldRestoreMonsHealth:: @ 81A5E89
	.string "Primero, debemos restaurar\n"
	.string "la salud de tus POKéMON.$"

Text_MonsHealedShouldBuyPotions:: @ 81A5EC0
	.string "Tus POKéMON han sido sanados por\n"
	.string "completo.\p"
	.string "Si la energía (PS) de tus POKéMON\n"
	.string "bajan, por favor ven a vernos.\p"
	.string "Si planeas llegar lejos, deberías\n"
	.string "comprar algunas POCIONES en\l"
	.string "una TIENDA.\p"
	.string "¡Te deseamos lo mejor!$"

Text_MonsHealed:: @ 81A5F9B
	.string "Tus POKéMON han sido sanados por\n"
	.string "completo.\p"
	.string "¡Te deseamos lo mejor!$"

Text_HadQuiteAnExperienceTakeRest:: @ 81A5FDF
	.string "MAMÁ: ¡{PLAYER}!\n"
	.string "Bienvenid{OA} a casa.\p"
	.string "It sounds like you had quite\n"
	.string "an experience.\p"
	.string "Tal vez deberías tomarte un\n"
	.string "pequeño descanso.$"

Text_MomExplainHPGetPotions:: @ 81A6046
	.string "MAMÁ: ¡Oh, bien! tú y tus POKéMON\n"
	.string "parecen estar mejor.\p"
	.string "Acabo de hablar con el PROF. OAK.\p"
	.string "Dijo que la energía de un POKéMON\n"
	.string "se mide en PS.\p"
	.string "Si tus POKéMON pierden PS,\n"
	.string "puedes restaurarlos en cualquier\l"
	.string "CENTRO POKéMON.\p"
	.string "En el caso de un viaje lejano,\n"
	.string "un ENTRENADOR listo compra\l"
	.string "POCIONES en una TIENDA POKéMON.\p"
	.string "¡Hazme sentir orgullosa, cariño!\p"
	.string "¡Cuídate!$"

Text_WhitedOutLostMoney:: @ 81A6197
	.string "¡{PLAYER} se quedo sin\n"
	.string "POKéMON!\p"
	.string "{PLAYER} entro en pánico y perdió\n"
	.string "¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "¡{PLAYER} esta fuera de combate!!$"

Text_WhitedOut:: @ 81A61E5
	.string "¡{PLAYER} se quedo sin\n"
	.string "POKéMON!\p"
	.string "¡{PLAYER} esta fuera de combate!!$"
