OneIsland_Text_BillLetsGoSeeCelio::
    .string "BILL: ¡Aquí estamos!\n"
    .string "Esta es ISLA PRIMA.\p"
    .string "Hay varias islas por aquí, y esta\n"
    .string "es una de ellas.\p"
    .string "Mi amigo CELIO envió el barco para\n"
    .string "dejarnos aquí.\p"
    .string "Él esta a cargo de la red de PC\n"
    .string "de la isla por su cuenta.\p"
    .string "…¿Porqué te cuento esto ahora?\n"
    .string "¡Vamos a ver a CELIO!$"

Text_WhereDoYouWantToSail::
    .string "¡Ahoy!\n"
    .string "¿A dónde quieres navegar?$"

OneIsland_Text_LuckyToHaveCelioHere::
    .string "Vivimos en una isla en el medio\n"
    .string "de la nada.\p"
    .string "Tenemos suerte de tener a un joven\n"
    .string "honorable como CELIO aquí.\p"
    .string "Mi nieta estaba bastante\n"
    .string "emocionada por el amigo de CELIO.\p"
    .string "Dijo algo de que es un famoso\n"
    .string "POKéMANÍACO…\p"
    .string "No sé que significa, ¡pero CELIO\n"
    .string "es un hombre ejemplar!$"

OneIsland_Text_HavePCLinkageWithKanto::
    .string "Mi nieta estaba bastante\n"
    .string "emocionada por un avance reciente.\p"
    .string "Dijo que ahora tenemos conexión\n"
    .string "con la gente de KANTO via PC.\p"
    .string "No sé que significa, ¡pero CELIO\n"
    .string "es un hombre ejemplar!$"

OneIsland_Text_HavePCLinkageWithHoenn::
    .string "Mi nieta estaba bastante\n"
    .string "emocionada por un avance reciente.\p"
    .string "Dijo que ahora tenemos conexión\n"
    .string "con la gente de HOENN via PC.\p"
    .string "No sé que significa, pero CELIO\n"
    .string "es un hombre ejemplar.\p"
    .string "¡Sería un buen esposo para\n"
    .string "mi nieta!$"

OneIsland_Text_IslandSign::
    .string "ISLA PRIMA\n"
    .string "Los amigos se unen en la ISLA NUDO.$"

OneIsland_Text_PokemonNetCenterSign::
    .string "¡Expandiendo el Mundo POKéMON!\n"
    .string "CENTRO DE RED POKéMON$"

@ Unused
OneIsland_Text_ReturnToCinnabar::
    .string "グレンタウンに　もどりますか？$"

OneIsland_Text_IsntWarmClimateHereGreat::
    .string "Hola, ¿disfrutas del paisaje?\n"
    .string "El clima cálido es fabuloso, ¿eh?$"

