LavenderTown_Text_DoYouBelieveInGhosts::
    .string "¿Crees en fantasmas?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "¿En serio?\n"
    .string "Entonces hay creyentes…$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "Jajaja, supongo que no.\p"
    .string "Esa mano blanca en tu hombro…\n"
    .string "Solo la estoy imaginando.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "Este pueblo es conocido como el\n"
    .string "cementerio de POKéMON.\p"
    .string "Los servicios funerarios se llevan\n"
    .string "a cabo en la TORRE POKéMON.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "Aparecieron fantasmas en la\n"
    .string "TORRE POKéMON.\p"
    .string "Creo que son espíritus de POKéMON\n"
    .string "que los ROCKETS mataron.$"

LavenderTown_Text_TownSign::
    .string "PUEBLO LAVANDA\n"
    .string "El noble pueblo púrpura$"

LavenderTown_Text_SilphScopeNotice::
    .string "¡El nuevo VISOR SILPH!\n"
    .string "¡Hace visible lo invisible!\p"
    .string "SILPH S.A.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "CASA POKéMON DE VOLUNTARIOS\n"
    .string "DE LAVANDA$"

LavenderTown_Text_PokemonTowerSign::
    .string "TORRE POKéMON\n"
    .string "Calma los espíritus de los POKéMON"

