PokemonMansion_Text_PressSecretSwitchJP::
    .string "ひみつの　スイッチが　ある！\p"
    .string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt::
    .string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
    .string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro::
    .string "¡Este lugar es gigantesco!$"

PokemonMansion_1F_Text_SimonDefeat::
    .string "¡Ayah!$"

PokemonMansion_1F_Text_SimonPostBattle::
    .string "Me pregunto adónde fue mi\n"
    .string "compañero.$"

PokemonMansion_1F_Text_BraydonIntro::
    .string "Mi mentor vivío aquí hace tiempo.$"

PokemonMansion_1F_Text_BraydonDefeat::
    .string "¡Uau!\n"
    .string "¡Me aplastaste!$"

PokemonMansion_1F_Text_BraydonPostBattle::
    .string "Entonces, ¿estás atrapad{OA}?\n"
    .string "¡Intenta saltar por ahí!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
    .string "Diario: 6 de Febrero\n"
    .string "MEW dio a luz.\p"
    .string "Llamamos al recién nacido: MEWTWO.$"

