LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney::
    .string "¡El EQUIPO ROCKET haría lo que sea\n"
    .string "por dinero!\p"
    .string "¡No hay trabajo sucio, acto atroz,\n"
    .string "o crimen horrible que sean\l"
    .string "incapaces de hacer!$"

LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets::
    .string "Vi a la madre de CUBONE intentando\n"
    .string "escapar del EQUIPO ROCKET.\p"
    .string "Murió mientras intentaba escapar…$"

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls::
    .string "¿Sabes que los CUBONE llevan\n"
    .string "cráneos puestos, verdad?\p"
    .string "Hay gente que paga mucho por uno.$"

