Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
    .string "¡Hola! ¿me recuerdas?\n"
    .string "Soy un AYUDANTE del PROF. OAK.\p"
    .string "Si tu POKéDEX tiene datos completos\n"
    .string "de 10 especies, se supone que\l"
    .string "debería darte una recompensa.\p"
    .string "El PROF. OAK me encargo la\n"
    .string "MO05 para ti.\p"
    .string "Entonces, {PLAYER}, dime algo.\p"
    .string "¿Ya recolectaste datos de al menos\n"
    .string "10 tipos de POKéMON?$"

Route2_EastBuilding_Text_GreatHereYouGo::
    .string "¡Bien! ¡atrapaste u obtuviste\n"
    .string "{STR_VAR_3} tipos de POKéMON!\p"
    .string "¡Felicidades!\n"
    .string "¡Aquí tienes!$"

Route2_EastBuilding_Text_ReceivedHM05FromAide::
    .string "{PLAYER} recibió MO05\n"
    .string "del AYUDANTE.$"

Route2_EastBuilding_Text_ExplainHM05::
    .string "MO05 contiene el movimiento oculto\n"
    .string "DESTELLO.\p"
    .string "DESTELLO ilumina incluso las\n"
    .string "cuevas y mazmorras más oscuras.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
    .string "Una vez que un POKéMON aprenda\n"
    .string "DESTELLO, podrás atravesar el\l"
    .string "TÚNEL ROCA.$"

