Route17_Text_RaulIntro::
    .string "El luchar contra niños no deja\n"
    .string "mucho dinero.$"

Route17_Text_RaulDefeat::
    .string "¡Agotado!$"

Route17_Text_RaulPostBattle::
    .string "Puedes encontrar cosas buenas por\n"
    .string "la CICLOVÍA.\p"
    .string "El recogerlas y venderlas puede\n"
    .string "dejar un buen dinero.$"

Route17_Text_IsaiahIntro::
    .string "Estoy muy orgulloso de mi cuerpo,\n"
    .string "niñ{OA}.\p"
    .string "¡Vamos!$"

Route17_Text_IsaiahDefeat::
    .string "¡Woo!$"

Route17_Text_IsaiahPostBattle::
    .string "¡Podría sacarte de aquí con mi\n"
    .string "panza!$"

Route17_Text_VirgilIntro::
    .string "¿Te diriges a FUCSIA?$"

Route17_Text_VirgilDefeat::
    .string "¡Destrozado y quemado!$"

Route17_Text_VirgilPostBattle::
    .string "¡Amo las carreras cuesta abajo!$"

Route17_Text_BillyIntro::
    .string "¡Somos MOTORISTAS!\n"
    .string "¡Dominamos los caminos, viejo!$"

Route17_Text_BillyDefeat::
    .string "¡Quedé ahumado!$"

Route17_Text_BillyPostBattle::
    .string "¿Estás buscando aventuras?$"

Route17_Text_NikolasIntro::
    .string "¡Deja que VOLTORB te electrifique!$"

Route17_Text_NikolasDefeat::
    .string "¡Su electricidad fue a la tierra!$"

Route17_Text_NikolasPostBattle::
    .string "Obtuve a mis VOLTORB en la\n"
    .string "CENTRAL DE ENERGÍA abandonada.$"

Route17_Text_ZeekIntro::
    .string "Subí de nivel a mi POKéMON, pero\n"
    .string "no evoluciona. ¿Por qué?$"

Route17_Text_ZeekDefeat::
    .string "¡Ah, tú!$"

Route17_Text_ZeekPostBattle::
    .string "Tal vez algunos POKéMON necesitan\n"
    .string "PIEDRAS elementales para\l"
    .string "evolucionar.$"

Route17_Text_JamalIntro::
    .string "¡Necesito un poco de ejercicio!$"

Route17_Text_JamalDefeat::
    .string "¡Fiu!\n"
    .string "¡Buen entrenamiento!$"

Route17_Text_JamalPostBattle::
    .string "¡Estoy seguro de que bajé de peso!$"

Route17_Text_CoreyIntro::
    .string "¡Sé rebelde!$"

Route17_Text_CoreyDefeat::
    .string "¡Aaaargh!$"

Route17_Text_CoreyPostBattle::
    .string "¡Prepárate para luchar por tus\n"
    .string "creencias!$"

Route17_Text_JaxonIntro::
    .string "¡Bonita BICI!\n"
    .string "¿Qué tan bien se maneja?$"

Route17_Text_JaxonDefeat::
    .string "¡Rayos!$"

Route17_Text_JaxonPostBattle::
    .string "La pendiente dificulta el manejo.$"

Route17_Text_WilliamIntro::
    .string "¡Piérdete, niñ{OA}!\n"
    .string "¡Estoy agotado!$"

Route17_Text_WilliamDefeat::
    .string "¿Estás satisfech{OA}?$"

Route17_Text_WilliamPostBattle::
    .string "¡Necesito dormir un poco!$"

Route17_Text_WatchOutForDiscardedItems::
    .string "Es un aviso.\p"
    .string "Ten cuidado con los objetos\n"
    .string "desechados.$"

Route17_Text_SameSpeciesGrowDifferentRates::
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "Todos los POKéMON son únicos.\p"
    .string "Incluso POKéMON del mismo tipo y\n"
    .string "nivel crecen a ritmos diferentes.$"

Route17_Text_PressBToStayInPlace::
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "Presiona el Botón B para quedarte\n"
    .string "quieto en una pendiente.$"

Route17_Text_RouteSign::
    .string "RUTA 17\n"
    .string "CIUDAD PRISMA - CIUDAD FUCSIA$"

Route17_Text_DontThrowGameThrowBalls::
    .string "Es un aviso.\p"
    .string "¡No lanzes tu juego, mejor lanza\n"
    .string "POKéBOLAS!$"

Route17_Text_CyclingRoadSign::
    .string "CICLOVÍA\n"
    .string "¡El descenso acaba aquí!$"

