Route5_PokemonDayCare_Text_WantMeToRaiseMon:: @ 819DD66
	.string "Soy el encargado de la GUARDERÍA.\p"
	.string "¿Te gustaría que cuide a uno\n"
	.string "de tus POKéMON?$"

Route5_PokemonDayCare_Text_ComeAgain:: @ 819DDB2
	.string "Vuelve pronto.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise:: @ 819DDBE
	.string "¿A qué POKéMON debería cuidar?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike:: @ 819DDDC
	.string "Bien.\n"
	.string "Vuelve cuándo quieras.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile:: @ 819DDF9
	.string "Bien, vigilaré a tu\n"
	.string "{STR_VAR_1} por un rato.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile:: @ 819DE24
	.string "Ven a verme luego.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime:: @ 819DE3C
	.string "¿Regresaste tan pronto?\p"
	.string "Tu {STR_VAR_1} necesita estar\n"
	.string "un poco más de tiempo conmigo.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn:: @ 819DE80
	.string "Me debes ¥{STR_VAR_2} por el\n"
	.string "retorno de este POKéMON.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon:: @ 819DEAF
	.string "¡Gracias!\n"
	.string "Aquí esta tu POKéMON.$"

Route5_PokemonDayCare_Text_PlayerGotMonBack:: @ 819DECF
	.string "{PLAYER} obtuvo a {STR_VAR_1} de\n"
	.string "vuelta del HOMBRE de la GUARDERÍA.$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou:: @ 819DEF5
	.string "¿Oh? Solo tienes un POKéMON\n"
	.string "contigo.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith:: @ 819DF1D
	.string "Si me dejas a ese POKéMON,\n"
	.string "¿con qué vas a luchar?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels:: @ 819DF56
	.string "Tu {STR_VAR_1} ha crecido mucho.\n"
	.string "Sí, bastante, diría yo.\p"
	.string "Déjame ver…\n"
	.string "Por nivel, subió {STR_VAR_2}.\p"
	.string "¿No soy genial?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt:: @ 819DFC2
	.string "No puedes llevarte a ese POKéMON\n"
	.string "de vuelta si no tienes espacio.$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney:: @ 819E001
	.string "No tienes suficiente dinero.$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours:: @ 819E01E
    .string "きみの\n"
    .string "みてみるかね？$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM:: @ 819E02A
    .string "わるいけど　ひでんのわざを　もった\n"
    .string "ポケモンは　あずかれないなぁ$"
