Route5_PokemonDayCare_Text_WantMeToRaiseMon::
	.string "Soy el encargado de la GUARDERÍA.\p"
	.string "¿Te gustaría que cuide a uno\n"
	.string "de tus POKéMON?$"

Route5_PokemonDayCare_Text_ComeAgain::
	.string "Vuelve pronto.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
	.string "¿A qué POKéMON debería cuidar?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
	.string "Bien.\n"
	.string "Vuelve cuándo quieras.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
	.string "Bien, vigilaré a tu\n"
	.string "{STR_VAR_1} por un rato.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
	.string "Ven a verme luego.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
	.string "¿Regresaste tan pronto?\p"
	.string "Tu {STR_VAR_1} necesita estar\n"
	.string "un poco más de tiempo conmigo.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
	.string "Me debes ¥{STR_VAR_2} por el\n"
	.string "retorno de este POKéMON.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon::
	.string "¡Gracias!\n"
	.string "Aquí esta tu POKéMON.$"

Route5_PokemonDayCare_Text_PlayerGotMonBack::
	.string "{PLAYER} obtuvo a {STR_VAR_1} de\n"
	.string "vuelta del HOMBRE de la GUARDERÍA.$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
	.string "¿Oh? Solo tienes un POKéMON\n"
	.string "contigo.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
	.string "Si me dejas a ese POKéMON,\n"
	.string "¿con qué vas a luchar?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
	.string "Tu {STR_VAR_1} ha crecido mucho.\n"
	.string "Sí, bastante, diría yo.\p"
	.string "Déjame ver…\n"
	.string "Por nivel, subió {STR_VAR_2}.\p"
	.string "¿No soy genial?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
	.string "No puedes llevarte a ese POKéMON\n"
	.string "de vuelta si no tienes espacio.$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
	.string "No tienes suficiente dinero.$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
    .string "きみの\n"
    .string "みてみるかね？$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
    .string "わるいけど　ひでんのわざを　もった\n"
    .string "ポケモンは　あずかれないなぁ$"
