Route12_Text_MonSprawledOutInSlumber::
    .string "Un POKéMON está tumbado en un\n"
    .string "cómodo y profundo sueño.$"

Text_SnorlaxWokeUp::
    .string "¡SNORLAX se despertó!\p"
    .string "¡Ataca con gran ira!$"

Text_SnorlaxReturnedToMountains::
    .string "SNORLAX se calmó.\n"
    .string "Pegó un gran bostezo…\l"
    .string "Y regresó a las montañas.$"

Text_WantToUsePokeFlute::
    .string "¿Quieres usar la POKé FLAUTA?$"

Text_PlayedPokeFlute::
    .string "{PLAYER} tocó la POKé FLAUTA.$"

Route12_Text_NedIntro::
    .string "¡Sí!\n"
    .string "¡Algo está picando!$"

Route12_Text_NedDefeat::
    .string "¡Tch!\n"
    .string "Solo un pequeñin…$"

Route12_Text_NedPostBattle::
    .string "¡Espera!\n"
    .string "¡Mi sedal se atoró!$"

Route12_Text_ChipIntro::
    .string "Ten paciencia.\n"
    .string "La pesca es un juego de esperar.$"

Route12_Text_ChipDefeat::
    .string "¡Ese se escapó!$"

Route12_Text_ChipPostBattle::
    .string "Con una mejor CAÑA, podría atrapar\n"
    .string "mejores POKéMON…$"

Route12_Text_JustinIntro::
    .string "Estoy buscando una PIEDRA LUNAR.\n"
    .string "¿Has encontrado una?$"

Route12_Text_JustinDefeat::
    .string "¡Auch!$"

Route12_Text_JustinPostBattle::
    .string "Con una PIEDRA LUNAR, podría hacer\n"
    .string "que mis POKéMON evolucionaran.\p"
    .string "Apuesto que entonces ganaría.$"

Route12_Text_LucaIntro::
    .string "La electricidad es mi especialidad.\p"
    .string "Aunque no sé nada sobre los\n"
    .string "POKéMON del mar.$"

Route12_Text_LucaDefeat::
    .string "¡Desconectado!$"

Route12_Text_LucaPostBattle::
    .string "El agua conduce electricidad, así\n"
    .string "que podrías electrocutar POKéMON\l"
    .string "marinos.$"

Route12_Text_HankIntro::
    .string "¡El PESCADOR TONTO contra {ELLA} NIÑ{OAM}\n"
    .string "POKéMON!$"

Route12_Text_HankDefeat::
    .string "¡Eso fue demasiado!$"

Route12_Text_HankPostBattle::
    .string "Supongo que tu logras ser buen{OA}\n"
    .string "en lo que te gusta.\p"
    .string "Bueno, me vences con los POKéMON,\n"
    .string "pero no me puedes ganar en\l"
    .string "la pesca.$"

Route12_Text_ElliotIntro::
    .string "Amo pescar, no me malentiendas.\p"
    .string "Pero sería mejor si también\n"
    .string "tuviera más trabajo.$"

Route12_Text_ElliotDefeat::
    .string "No es fácil…$"

Route12_Text_ElliotPostBattle::
    .string "Está bien.\n"
    .string "El perder ya no me molesta.$"

Route12_Text_AndrewIntro::
    .string "¿Qué pesco?\p"
    .string "¡Nunca sabes lo que puedes pescar!$"

Route12_Text_AndrewDefeat::
    .string "¡Lo perdí!$"

Route12_Text_AndrewPostBattle::
    .string "¿Qué, MAGIKARP?\p"
    .string "Seguro, los pesco todo el tiempo.\n"
    .string "Pero, si que son debiluchos.$"

Route12_Text_RouteSign::
    .string "RUTA 12\n"
    .string "LAVANDA, al norte$"

Route12_Text_SportfishingArea::
    .string "ZONA DE PESCA DEPORTIVA$"

Route12_Text_JesIntro::
    .string "JES: Si gano, le pediré matrimonio\n"
    .string "a GIA.$"

Route12_Text_JesDefeat::
    .string "JES: ¿Oh, por favor, por qué no\n"
    .string "podías dejarnos ganar?$"

Route12_Text_JesPostBattle::
    .string "JES: ¡Oh, GIA, perdóname, mi amor!$"

Route12_Text_JesNotEnoughMons::
    .string "JES: GIA y yo, estaremos juntos\n"
    .string "para siempre.\p"
    .string "No lucharemos, a menos que tengas\n"
    .string "dos POKéMON.$"

Route12_Text_GiaIntro::
    .string "GIA: Ey, JES…\p"
    .string "¡Si ganamos, me casaré contigo!$"

Route12_Text_GiaDefeat::
    .string "GIA: ¿Oh, pero por qué?$"

Route12_Text_GiaPostBattle::
    .string "GIA: ¡JES, qué tonto!\n"
    .string "¡Arruinaste esto!$"

Route12_Text_GiaNotEnoughMons::
    .string "GIA: ¡No soportaría luchar sin mi\n"
    .string "JES!\p"
    .string "¿No tienes un POKéMON más?$"
