SaffronCity_Gym_Text_SabrinaIntro::
    .string "Tuve una visión de tu llegada.\p"
    .string "He tenido poderes psíquicos desde\n"
    .string "que era una niña.\p"
    .string "Empezó con una cuchara que lanzé\n"
    .string "y torcí sin pensarlo.\p"
    .string "No me gusta luchar, pero si lo\n"
    .string "deseas, ¡te mostraré mis poderes!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

SaffronCity_Gym_Text_SabrinaDefeat::
    .string "¡Esta derrota me impresiona!\n"
    .string "Pero, una derrota es una derrota.\p"
    .string "Lo admito, no me esforcé lo\n"
    .string "suficiente como para ganar.\p"
    .string "Tu victoria te ha otorgado la\n"
    .string "MEDALLA PANTANO.$"

SaffronCity_Gym_Text_SabrinaPostBattle::
    .string "El poder psíquico no es algo que\n"
    .string "solo pocas personas tienen.\p"
    .string "Todos tienen poder psíquico.\n"
    .string "Solo que la gente no se da cuenta.$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
    .string "La MEDALLAPANTANO hace que todo\n"
    .string "POKéMON hasta el Nv. 70 obedezca.\p"
    .string "POKéMON más fuertes se volverán\n"
    .string "salvajes, ignorando tus órdenes\l"
    .string "en batalla.\p"
    .string "Solo evita fortalecer demasiado a\n"
    .string "tus POKéMON para evitar eso.\p"
    .string "Espera, por favor toma esta MT.$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .string "{PLAYER} recibió MT04 de\n"
    .string "SABRINA.$"

SaffronCity_Gym_Text_ExplainTM04::
    .string "La MT04 es PAZ MENTAL.\p"
    .string "Hace que el POKéMON se concentre\n"
    .string "para aumentar tanto la DEF. ESP.\l"
    .string "como el ATQ. ESP.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .string "Tu MOCHILA está llena de objetos.$"

SaffronCity_Gym_Text_AmandaIntro::
    .string "SABRINA es mucho más joven que yo,\n"
    .string "pero se ha ganado mi respeto.$"

SaffronCity_Gym_Text_AmandaDefeat::
    .string "¡No soy lo suficientemente buena!$"

SaffronCity_Gym_Text_AmandaPostBattle::
    .string "En una batalla igualada, el que\n"
    .string "tenga la voluntad más fuerte gana.\p"
    .string "Si deseas vencer a SABRINA,\n"
    .string "concéntrate en tu voluntad para\l"
    .string "llegar a la victoria.$"

SaffronCity_Gym_Text_JohanIntro::
    .string "¿Te asusta nuestro poder oculto?$"

SaffronCity_Gym_Text_JohanDefeat::
    .string "¡Nunca predije esto!$"

SaffronCity_Gym_Text_JohanPostBattle::
    .string "¡Los POKéMON PSÍQUICOS solo le\n"
    .string "temen a los fantasmas e insectos!$"

SaffronCity_Gym_Text_StacyIntro::
    .string "Los POKéMON se parecen a sus\n"
    .string "ENTRENADORES.\p"
    .string "¡Entonces tus POKéMON deben ser\n"
    .string "fuertes!$"

SaffronCity_Gym_Text_StacyDefeat::
    .string "¡Lo sabía!$"

SaffronCity_Gym_Text_StacyPostBattle::
    .string "Aún tengo mucho que aprender…\p"
    .string "Debo dominar PSÍQUICO y enseñarlo\n"
    .string "a mis POKéMON…$"

SaffronCity_Gym_Text_TyronIntro::
    .string "¿Lo entiendes, verdad?\p"
    .string "¿Qué el poder no basta para ganar\n"
    .string "en el mundo de los POKéMON?$"

SaffronCity_Gym_Text_TyronDefeat::
    .string "¡No puedo creerlo!$"

SaffronCity_Gym_Text_TyronPostBattle::
    .string "SABRINA le ganó al MAESTRO\n"
    .string "DEL KÁRATE de al lado.$"

SaffronCity_Gym_Text_TashaIntro::
    .string "¡Tú y yo, nuestros POKéMON\n"
    .string "lucharán!$"

SaffronCity_Gym_Text_TashaDefeat::
    .string "¡Perdí después de todo!$"

SaffronCity_Gym_Text_TashaPostBattle::
    .string "Sabía que esto iba a ocurrir.$"

SaffronCity_Gym_Text_CameronIntro::
    .string "SABRINA es joven, pero también es\n"
    .string "nuestra hábil LÍDER.\p"
    .string "¡No llegarás a ella fácilmente!$"

SaffronCity_Gym_Text_CameronDefeat::
    .string "¡Au!\n"
    .string "¡Caído y fuera!$"

SaffronCity_Gym_Text_CameronPostBattle::
    .string "Habían dos GIMNASIOS POKéMON\n"
    .string "en AZAFRÁN.\p"
    .string "Aunque el DOJO DE PELEA de al lado\n"
    .string "perdió su condición de GIMNASIO.\p"
    .string "Simplemente los aplastamos cuando\n"
    .string "decidimos que solo habría un GIMN.$"

SaffronCity_Gym_Text_PrestonIntro::
    .string "El GIMNASIO POKéMON de AZAFRÁN es\n"
    .string "famoso por entrenar psíquicos.\p"
    .string "¿Quieres ver a SABRINA, no es así?\n"
    .string "¡Puedo verlo!$"

SaffronCity_Gym_Text_PrestonDefeat::
    .string "¡Arrrgh!$"

SaffronCity_Gym_Text_PrestonPostBattle::
    .string "¡Es verdad! ¡usé telepatía para\n"
    .string "leer tu mente!$"

SaffronCity_Gym_Text_GymGuyAdvice::
    .string "¡Yo!\n"
    .string "¡Futur{OA} campe{ONONA}!\p"
    .string "Los POKéMON de SABRINA usan poder\n"
    .string "psíquico en lugar de la fuerza.\p"
    .string "Los POKéMON de tipo PELEA son\n"
    .string "especialmente débiles contra los\l"
    .string "POKéMON PSÍQUICOS.\p"
    .string "¡Serán destruidos antes de que\n"
    .string "puedan apuntar para un golpe!$"

SaffronCity_Gym_Text_GymGuyPostVictory::
    .string "¿Poder psíquico, eh?\p"
    .string "¡Si tuviera eso, ganaría una\n"
    .string "fortuna en las tragamonedas!$"

SaffronCity_Gym_Text_GymStatue::
    .string "GIMNASIO POKéMON DE AZAFRÁN\n"
    .string "LÍDER: SABRINA\p"
    .string "ENTRENADORES VICTORIOSOS:\n"
    .string "{RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .string "GIMNASIO POKéMON DE AZAFRÁN\n"
    .string "LÍDER: SABRINA\p"
    .string "ENTRENADORES VICTORIOSOS:\n"
    .string "{RIVAL}, {PLAYER}$"

