PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy:: @ 81914DE
    .string "¡Un viejo misterioso me estafo\n"
    .string "con un extraño pez POKéMON!\p"
    .string "¡Es súper débil y costo ¥500!$"

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently:: @ 8191541
    .string "Pueden pasar cosas buenas si crias\n"
    .string "a tus POKéMON con persistencia.\p"
    .string "Incluso los debiles pueden\n"
    .string "sorprenderte si no los abandonas.$"
