PokemonTower_6F_Text_AngelicaIntro::
    .string "Da…me…\n"
    .string "sangre…$"

PokemonTower_6F_Text_AngelicaDefeat::
    .string "¡Grrr!$"

PokemonTower_6F_Text_AngelicaPostBattle::
    .string "Me siento anémica y débil…$"

PokemonTower_6F_Text_EmiliaIntro::
    .string "Urff…\n"
    .string "¡Guaa!$"

PokemonTower_6F_Text_EmiliaDefeat::
    .string "¡Algo se cayó!$"

PokemonTower_6F_Text_EmiliaPostBattle::
    .string "¡Mi cabello no se cayó!\n"
    .string "¡Era un espíritu malvado!$"

PokemonTower_6F_Text_JenniferIntro::
    .string "¡Ki…ki…ki…\n"
    .string "ki…ki…ki!$"

PokemonTower_6F_Text_JenniferDefeat::
    .string "¡Kiii!$"

PokemonTower_6F_Text_JenniferPostBattle::
    .string "¿Qué está pasando aquí?$"

PokemonTower_6F_Text_BeGoneIntruders::
    .string "Fuera…\n"
    .string "Intrusos…$"

PokemonTower_6F_Text_GhostWasCubonesMother::
    .string "¡Ese fantasma era el espíritu sin\n"
    .string "descanso de la madre de CUBONE!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
    .string "El espíritu de la madre se calmó.\p"
    .string "Partió al más allá…$"

