VermilionCity_Mart_Text_TeamRocketAreWickedPeople:: @ 8194A77
    .string "Hay gente perversa que usa POKéMON\n"
    .string "para actos criminales.\p"
    .string "El EQUIPO ROCKET trafica con\n"
    .string "POKéMON raros, por ejemplo.\p"
    .string "También abandonan POKéMON que ven\n"
    .string "como poco populares o inútiles.\p"
    .string "Ese es el tipo de gente horrible\n"
    .string "que son, el EQUIPO ROCKET.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer:: @ 8194B65
    .string "Creo que un POKéMON puede ser malo\n"
    .string "o bueno. Depende del ENTRENADOR.$"

