SSAnne_B1F_Room4_Text_LeonardIntro::
    .string "¡Ya sabes lo que dicen sobre los\n"
    .string "marineros y las batallas!$"

SSAnne_B1F_Room4_Text_LeonardDefeat::
    .string "¡Bien!\n"
    .string "¡Buena batalla, compañer{OA}!$"

SSAnne_B1F_Room4_Text_LeonardPostBattle::
    .string "¡Jajaja!\n"
    .string "¿Te interesa ser mariner{OA}?$"

SSAnne_B1F_Room4_Text_DuncanIntro::
    .string "¡Ven aquí, entonces! ¡Mi orgullo\n"
    .string "de marinero está en juego!$"

SSAnne_B1F_Room4_Text_DuncanDefeat::
    .string "¡Tú spíritu me hundió!$"

SSAnne_B1F_Room4_Text_DuncanPostBattle::
    .string "¿Viste al GURÚ PESCADOR en\n"
    .string "CIUDAD CARMÍN?$"

