SSAnne_B1F_Room4_Text_LeonardIntro:: @ 8174315
    .string "¡Ya sabes lo que dicen sobre los\n"
    .string "marineros y las batallas!$"

SSAnne_B1F_Room4_Text_LeonardDefeat:: @ 8174348
    .string "¡Bien!\n"
    .string "¡Buena batalla, compañer{OA}!$"

SSAnne_B1F_Room4_Text_LeonardPostBattle:: @ 8174362
    .string "¡Jajaja!\n"
    .string "¿Te interesa ser mariner{OA}?$"

SSAnne_B1F_Room4_Text_DuncanIntro:: @ 8174385
    .string "¡Ven aquí, entonces! ¡Mi orgullo\n"
    .string "de marinero está en juego!$"

SSAnne_B1F_Room4_Text_DuncanDefeat:: @ 81743B3
    .string "¡Tú spíritu me hundió!$"

SSAnne_B1F_Room4_Text_DuncanPostBattle:: @ 81743C8
    .string "¿Viste al GURÚ PESCADOR en\n"
    .string "CIUDAD CARMÍN?$"

