Text_RockSlideTeach::
    .string "En montañas rocosas como esta,\n"
    .string "hay peligro de desprendimientos.\p"
    .string "¿Puedes imaginarlo?\n"
    .string "¿Rocas cayendo hacia tí?\p"
    .string "Eso sería, cómo, ¡aaaaaaaaaaah!\n"
    .string "¡Terror total!\p"
    .string "No pareces tener miedo.\n"
    .string "¿Quieres aprender AVALANCHA?$"

Text_RockSlideDeclined::
    .string "Oh, entonces si tenías miedo.$"

Text_RockSlideWhichMon::
    .string "¿Qué POKéMON quiere aprender\n"
    .string "AVALANCHA?$"

Text_RockSlideTaught::
    .string "Puede que de miedo usar eso en\n"
    .string "este túnel…$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
    .string "Pista: Las rocas pueden cambiar\n"
    .string "el flujo del agua.$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
    .string "PELIGRO\n"
    .string "¡Corriente rápida!$"

