CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
    .string "¿Yo?\n"
    .string "¡Soy el programador!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
    .string "¡Soy el diseñador gráfico!\n"
    .string "¡Yo te dibujé!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
    .string "¡Yo escribí la historia!\n"
    .string "¿Verdad que ERIKA es linda?\p"
    .string "¡También me gusta mucho MISTY!\n"
    .string "¡Oh, y también me gusta SABRINA!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
    .string "¿Sabes?\p"
    .string "¡Soy el diseñador del juego!\p"
    .string "¡Completar la POKéDEX es duro,\n"
    .string "pero no te rindas!\p"
    .string "¡Cuándo la termines, ven a verme!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
    .string "¡Wow! ¡Excelente!\n"
    .string "¡Completaste tu POKéDEX!\l"
    .string "¡Felicidades!\l"
    .string "…$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
    .string "¡Es el programa del juego!\n"
    .string "¡Tocarlo podría causar un error!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
    .string "¡Alguien está jugando en vez de\n"
    .string "trabajar!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
    .string "¡Es el guión!\n"
    .string "¡Es mejor no mirar el final!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
    .string "Sala de desarollo de GAME FREAK$"

