CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .string "Los aumentadores de estadísticas\n"
    .string "de POKéMON solo se venden aquí.\p"
    .string "MÁS PS aumenta los PS base de un\n"
    .string "POKéMON.\p"
    .string "El CALCIO sube el ATQ. ESP. base\n"
    .string "de un POKéMON.\p"
    .string "El ZINC incrementa la DEF. ESP.\n"
    .string "base de un POKéMON.\p"
    .string "El CARBURANTE mejora la VELOCIDAD\n"
    .string "base de un POKéMON.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .string "Estoy aquí por aumentadores\n"
    .string "de estadísticas de POKéMON.\p"
    .string "La PROTEÍNA sube el poder ATAQUE\n"
    .string "base.\p"
    .string "El HIERRO incrementa la DEFENSA\n"
    .string "base.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .string "P5: FARMACIA$"

