SilphCo_7F_Text_HaveMonForSavingUs::
    .string "¡Oh! ¡Hola! ¡No eres un{OA} ROCKET!\n"
    .string "¿Viniste a salvarnos?\l"
    .string "¡Gracias!\p"
    .string "Quiero que tengas a este POKéMON\n"
    .string "por salvarnos.$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
    .string "¡{PLAYER} recibió un LAPRAS del\n"
    .string "empleado de SILPH!$"

SilphCo_7F_Text_ExplainLapras::
    .string "Es un LAPRAS.\n"
    .string "Es un POKéMON muy inteligente.\p"
    .string "Lo teníamos en el laboratorio,\n"
    .string "pero estaría mucho mejor contigo.\p"
    .string "¡Creo que serás un{A} buen{A}\n"
    .string "ENTRENADOR{AM} para LAPRAS!\p"
    .string "Es buen nadador.\n"
    .string "¡Te llevará a través del agua!$"

SilphCo_7F_Text_RocketBossWentToBoardroom::
    .string "¡El JEFE del EQUIPO ROCKET fue a\n"
    .string "la sala de juntas!\p"
    .string "¿Nuestro PRESIDENTE está bien?\n"
    .string "Estoy preocupado.$"

SilphCo_7F_Text_OhNo::
    .string "あ‥　もう　もてないぞ$"

SilphCo_7F_Text_SavedAtLast::
    .string "たすかったよ　ありがと！$"

SilphCo_7F_Text_RocketsAfterMasterBall::
    .string "El EQUIPO ROCKET estaba tras la\n"
    .string "BOLA MAESTRA, que atrapa a\l"
    .string "cualquier POKéMON.$"

SilphCo_7F_Text_CanceledMasterBallProject::
    .string "Cancelamos el proyecto de la BOLA\n"
    .string "MAESTRA gracias al EQUIPO ROCKET.$"

SilphCo_7F_Text_BadIfTeamRocketTookOver::
    .string "Sería malo si los ROCKET se quedan\n"
    .string "con SILPH o con nuestros POKéMON.$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
    .string "¡Guau!\p"
    .string "¿Ahuyentaste al EQUIPO ROCKET por\n"
    .string "tu cuenta?$"

SilphCo_7F_Text_ReallyDangerousHere::
    .string "¡Tú!\n"
    .string "¡Este lugar es muy peligroso!\p"
    .string "¿Viniste a salvarme?\n"
    .string "¡No puedes!$"

SilphCo_7F_Text_ThankYouSoMuch::
    .string "¡Muchas gracias!$"

SilphCo_7F_Text_Grunt3Intro::
    .string "¡Oh-oh!\n"
    .string "¡Huelo a un{A} pequeñ{OA} rat{ONONA}!$"

SilphCo_7F_Text_Grunt3Defeat::
    .string "¡Luces fuera!$"

SilphCo_7F_Text_Grunt3PostBattle::
    .string "¡No encontrarás a mi JEFE si solo\n"
    .string "corres por todos lados!$"

SilphCo_7F_Text_JoshuaIntro::
    .string "¡Jeje!\p"
    .string "¿Me confundiste con un empleado de\n"
    .string "SILPH?$"

SilphCo_7F_Text_JoshuaDefeat::
    .string "¡Estoy acabado!$"

SilphCo_7F_Text_JoshuaPostBattle::
    .string "¡A pesar de tu edad, eres un{A}\n"
    .string "ENTRENADOR{AM} hábil!$"

SilphCo_7F_Text_Grunt1Intro::
    .string "¡Soy uno de los cuatro HERMANOS\n"
    .string "ROCKET!$"

SilphCo_7F_Text_Grunt1Defeat::
    .string "¡Aack!\n"
    .string "¡Hermanos, perdí!$"

SilphCo_7F_Text_Grunt1PostBattle::
    .string "No importa.\n"
    .string "¡Mis hermanos devolverán el favor!$"

SilphCo_7F_Text_Grunt2Intro::
    .string "¿Un{A} niñ{OA} intrus{OA}?\n"
    .string "¡Debe tratarse de tí!$"

SilphCo_7F_Text_Grunt2Defeat::
    .string "¡Bien!\n"
    .string "¡Perdí!$"

SilphCo_7F_Text_Grunt2PostBattle::
    .string "¡Vete a casa antes de que mi JEFE\n"
    .string "se enoje!$"

SilphCo_7F_Text_RivalWhatKeptYou::
    .string "{RIVAL}: ¿Qué te atrasó, {PLAYER}?$"

SilphCo_7F_Text_RivalIntro::
    .string "{RIVAL}: ¡Jajaja! ¡pensé que\n"
    .string "aparecerías si esperaba aquí!\p"
    .string "¡Supongo que el EQUIPO ROCKET te\n"
    .string "retrasó! ¡Aunque no me importa!\p"
    .string "Te ví en AZAFRÁN, ¡así que decidí\n"
    .string "ver si mejoraste!$"

SilphCo_7F_Text_RivalDefeat::
    .string "¡Ajá!\n"
    .string "¡Entonces, estás list{OA} para el\l"
    .string "JEFE de los ROCKET!$"

SilphCo_7F_Text_RivalVictory::
    .string "{RIVAL}“おまえなあ‥\p"
    .string "こんな　うでまえじゃ\n"
    .string "まだまだ‥\l"
    .string "いちにんまえ　とは　いえないぜ$"

SilphCo_7F_Text_RivalPostBattle::
    .string "¡Bueno, {PLAYER}!\n"
    .string "¡Estoy mejorando y avanzando!\p"
    .string "¡Al revisar mi POKéDEX, empiezo a\n"
    .string "ver cúales son fuertes y cómo\l"
    .string "evolucionan!\p"
    .string "¿Soy un genio o qué?\p"
    .string "Iré a la LIGA POKéDEX a aplastar\n"
    .string "al ALTO MANDO.\p"
    .string "¡Me convertiré en el ENTRENADOR\n"
    .string "más poderoso del mundo!\p"
    .string "¡{PLAYER}, buena suerte para tí!\n"
    .string "¡No te esfuerces de más!\l"
    .string "¡Hasta nunca!$"

SilphCo_7F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P7$"

