Route8_WestEntrance_Text_ThirstyOnGuardDuty::
    .string "Estoy en mi turno de guarda.\n"
    .string "Pero, ¡estoy sediento!\p"
    .string "Espera, el camino está cerrado.$"

Route8_WestEntrance_Text_ThatTeaLooksTasty::
    .string "Oh, ese TÉ…\n"
    .string "Se ve delicioso…$"

Route8_WestEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "¿Eh? ¿Que me lo puedo tomar?\n"
    .string "¡Vaya, gracias!\l"
    .string "… …\l"
    .string "Glug, glug…\l"
    .string "… …\l"
    .string "Gulp…\l"
    .string "Si quieres ir a CIUDAD\l"
    .string "AZAFRÁN…\l"
    .string "… …\l"
    .string "Puedes pasar.\p"
    .string "¡Compartiré este TÉ con los otros\n"
    .string "guardas!$"

Route8_WestEntrance_Text_HiHowsItGoing::
    .string "Hola, ¿cómo te va?$"

