ViridianCity_Gym_Text_GiovanniIntro::
    .string "¡Fuajajaja!\n"
    .string "¡Bienvenid{OA} a mi guarida!\p"
    .string "Estaré aquí hasta que pueda\n"
    .string "resturar al EQUIPO ROCKET a su\l"
    .string "gloria pasada.\p"
    .string "Pero me encontraste otra vez.\n"
    .string "Que así sea.\l"
    .string "¡Esta vez, no me contendré!\p"
    .string "¡Una vez más, te enfrentarás a\n"
    .string "GIOVANNI, el mejor ENTRENADOR!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

ViridianCity_Gym_Text_GiovanniDefeat::
    .string "¡Ja!\n"
    .string "Fue una batalla intensa.\l"
    .string "¡Ganaste!\p"
    .string "¡Como prueba, toma la\n"
    .string "MEDALLA TIERRA!{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_GiovanniPostBattle::
    .string "Tras perder de esta manera,\n"
    .string "no puedo mirar a mis seguidores.\l"
    .string "He roto su confianza.\p"
    .string "¡A partir de hoy, el EQUIPO ROCKET\n"
    .string "se acabó para siempre!\p"
    .string "En cuanto a mi, dedicaré mi vida a\n"
    .string "ser ENTRENADOR nuevamente.\p"
    .string "¡Espero que nos volvamos a ver!\n"
    .string "¡Adiós!$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
    .string "La MEDALLATIERRA hace que\n"
    .string "cualquier POKéMON obedezca.\p"
    .string "Es evidencia de tu maestría como\n"
    .string "ENTRENADOR{AM} POKéMON.\p"
    .string "Con ella, podrás desafiar a la\n"
    .string "LIGA POKéMON.\p"
    .string "Toma esta MT también.\p"
    .string "Considérala un regalo para\n"
    .string "tu desafío de la LIGA POKéMON.$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
    .string "{PLAYER} recibió la MT26\n"
    .string "de GIOVANNI.$"

ViridianCity_Gym_Text_ExplainTM26::
    .string "La MT26 contiene TERREMOTO.\p"
    .string "Es un ataque poderoso que causa\n"
    .string "un temblor masivo.\p"
    .string "La creé cuando dirigía este\n"
    .string "GIMNASIO, hace ya mucho tiempo…$"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
    .string "¡No tienes espacio para esto!$"

ViridianCity_Gym_Text_YujiIntro::
    .string "¡Je!\n"
    .string "¡Ya debes estar con poca energía!$"

ViridianCity_Gym_Text_YujiDefeat::
    .string "¡Me quedé sin combustible!$"

ViridianCity_Gym_Text_YujiPostBattle::
    .string "Necesitarás poder para luchar\n"
    .string "contra nuesto LÍDER de GIMNASIO.$"

ViridianCity_Gym_Text_AtsushiIntro::
    .string "¡Rrrroar!\n"
    .string "¡Me estoy enfureciendo!$"

ViridianCity_Gym_Text_AtsushiDefeat::
    .string "¡Wargh!$"

ViridianCity_Gym_Text_AtsushiPostBattle::
    .string "¡Aún no soy digno!$"

ViridianCity_Gym_Text_JasonIntro::
    .string "¡Mis POKéMON y yo hacemos música\n"
    .string "maravillosa!$"

ViridianCity_Gym_Text_JasonDefeat::
    .string "¡Estás en perfecta armonía!$"

ViridianCity_Gym_Text_JasonPostBattle::
    .string "¿Conoces la identidad de nuestro\n"
    .string "LÍDER de GIMNASIO?$"

ViridianCity_Gym_Text_KiyoIntro::
    .string "¡El kárate es la forma definitiva\n"
    .string "de las artes marciales!$"

ViridianCity_Gym_Text_KiyoDefeat::
    .string "¡Aiyah!$"

ViridianCity_Gym_Text_KiyoPostBattle::
    .string "Si mis POKéMON fueran tan buenos\n"
    .string "en el kárate como yo…$"

ViridianCity_Gym_Text_WarrenIntro::
    .string "Los más hábiles ganan con estilo.$"

ViridianCity_Gym_Text_WarrenDefeat::
    .string "¡Perdí el control!$"

ViridianCity_Gym_Text_WarrenPostBattle::
    .string "El LÍDER va a gritarme por\n"
    .string "perder así…$"

ViridianCity_Gym_Text_TakashiIntro::
    .string "¡Soy el REY DEL KÁRATE!\n"
    .string "¡Tu destino depende de mí!$"

ViridianCity_Gym_Text_TakashiDefeat::
    .string "¡Ayah!$"

ViridianCity_Gym_Text_TakashiPostBattle::
    .string "¿La LIGA POKéMON?\n"
    .string "¿Tú? ¡no seas engreíd{OA}!$"

ViridianCity_Gym_Text_ColeIntro::
    .string "¡Tus POKéMON se acobardarán con un\n"
    .string "chasquido de mi látigo!$"

ViridianCity_Gym_Text_ColeDefeat::
    .string "¡Yauch!\n"
    .string "¡Qué sorpresa!$"

ViridianCity_Gym_Text_ColePostBattle::
    .string "¡Espera!\n"
    .string "¡Solo me descuidé!$"

ViridianCity_Gym_Text_SamuelIntro::
    .string "El GIMNASIO de VERDE estuvo\n"
    .string "cerrado por un largo tiempo.\p"
    .string "¡Pero ahora, nuestro LÍDER regresó!$"

ViridianCity_Gym_Text_SamuelDefeat::
    .string "¿Fuí derrotado?$"

ViridianCity_Gym_Text_SamuelPostBattle::
    .string "¡Solo puedes pasar a la LIGA\n"
    .string "POKéMON si derrotas a nuestro\l"
    .string "LÍDER de GIMNASIO!$"

ViridianCity_Gym_Text_GymGuyAdvice::
    .string "¡Yo!\n"
    .string "¡Futur{OA} campe{ONONA}!\p"
    .string "Ni siquiera yo conozco la identidad\n"
    .string "del LÍDER de este GIMNASIO.\p"
    .string "Pero una cosa es segura.\n"
    .string "Este será el más duro de todos los\l"
    .string "LÍDERES de GIMNASIO.\p"
    .string "Dicen que estos ENTRENADORES usan\n"
    .string "POKéMON del tipo TIERRA.$"

ViridianCity_Gym_Text_GymGuyPostVictory::
    .string "¡Qué sorpresa! ¿GIOVANNI era\n"
    .string "el LÍDER de GIMNASIO de VERDE?$"

ViridianCity_Gym_Text_GymStatue::
    .string "GIMNASIO POKéMON DE VERDE\n"
    .string "LÍDER: ¿?\p"
    .string "ENTRENADORES VICTORIOSOS:\n"
    .string "{RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .string "GIMNASIO POKéMON DE VERDE\n"
    .string "LÍDER: GIOVANNI\p"
    .string "ENTRENADORES VICTORIOSOS:\n"
    .string "{RIVAL}, {PLAYER}$"

