RocketHideout_B1F_Text_Grunt1Intro::
    .string "¿Quien eres?\n"
    .string "¿Cómo llegaste aquí?$"

RocketHideout_B1F_Text_Grunt1Defeat::
    .string "¡Auch!\n"
    .string "¡Derrotado!$"

RocketHideout_B1F_Text_Grunt1PostBattle::
    .string "Rayos… ¿le faltas el respeto al\n"
    .string "EQUIPO ROCKET, eh?$"

RocketHideout_B1F_Text_Grunt2Intro::
    .string "¿Irrumpiste en la operación del\n"
    .string "EQUIPO ROCKET? ¡que atrevid{OA}!$"

RocketHideout_B1F_Text_Grunt2Defeat::
    .string "¡Bum!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
    .string "¡No te saldrás con la tuya,\n"
    .string "mocos{OA}!$"

RocketHideout_B1F_Text_Grunt3Intro::
    .string "¡Alerta de intruso!$"

RocketHideout_B1F_Text_Grunt3Defeat::
    .string "¡No puedo hacerlo!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
    .string "¿VISOR SILPH? ¡Humph!\n"
    .string "No se donde está eso.$"

RocketHideout_B1F_Text_Grunt4Intro::
    .string "¿Porqué llegaste aquí?$"

RocketHideout_B1F_Text_Grunt4Defeat::
    .string "¡Esto no basta!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
    .string "Bien, hablaré…\n"
    .string "Usa el ascensor para ver al JEFE.$"

RocketHideout_B1F_Text_Grunt5Intro::
    .string "¿Te perdiste, pequeñ{OA} rat{ONONA}?$"

RocketHideout_B1F_Text_Grunt5Defeat::
    .string "¿Por qué…?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
    .string "¡Oh-oh, ese alboroto de algún modo\n"
    .string "abrío la puerta!$"

