RocketHideout_B4F_Text_GiovanniIntro::
    .string "Debo decir, estoy impresionado de\n"
    .string "que llegarás aquí.\p"
    .string "El EQUIPO ROCKET captura POKéMON\n"
    .string "alrededor del mundo.\p"
    .string "Son herramientas importantes para\n"
    .string "mantener nuestra empresa criminal\l"
    .string "a flote.\p"
    .string "¡Yo soy el líder, GIOVANNI!\p"
    .string "¡Por tu insolencia, sentirás\n"
    .string "un mundo de dolor!$"

RocketHideout_B4F_Text_GiovanniDefeat::
    .string "¡QUÉ!\n"
    .string "¡Esto no es posible!$"

RocketHideout_B4F_Text_GiovanniPostBattle::
    .string "Veo que crías a tus POKéMON con\n"
    .string "el mayor cuidado.\p"
    .string "Un{A} niñ{OA} como tú jamás entendería\n"
    .string "lo que aspiro a lograr.\p"
    .string "¡Me haré a un lado esta vez!\p"
    .string "Espero que nos volvamos a ver…$"

RocketHideout_B4F_Text_Grunt2Intro::
    .string "¡Te conozco!\p"
    .string "¡Arruinaste nuestros planes en el\n"
    .string "MONTE LUNA!$"

RocketHideout_B4F_Text_Grunt2Defeat::
    .string "¡Humillado de nuevo!$"

RocketHideout_B4F_Text_Grunt2PostBattle::
    .string "¿Tienes algo en contra del EQUIPO\n"
    .string "ROCKET?$"

RocketHideout_B4F_Text_Grunt3Intro::
    .string "¿Cómo no puedes ver la belleza de\n"
    .string "nuestra maldad?$"

RocketHideout_B4F_Text_Grunt3Defeat::
    .string "¡Ayaya!$"

RocketHideout_B4F_Text_Grunt3PostBattle::
    .string "¡JEFE!\n"
    .string "¡Lamento haberle fallado!$"

RocketHideout_B4F_Text_Grunt1Intro::
    .string "¿El ascensor no funciona?\n"
    .string "¿Quien tiene la LLAVE?$"

RocketHideout_B4F_Text_Grunt1Defeat::
    .string "¡No!$"

RocketHideout_B4F_Text_Grunt1PostBattle::
    .string "¡Oh, no!\n"
    .string "¡Solté la LLAVE del ASCENSOR!$"

