SafariZone_North_Text_RestHouse::
    .string "CASA DE DESCANSO$"

SafariZone_North_Text_SecretHouseStillAhead::
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "La CASA SECRETA aún está adelante.$"

SafariZone_North_Text_Area2::
    .string "ZONA 2$"

SafariZone_North_Text_ZigzagThroughTallGrass::
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "Los POKéMON se esconden en la\n"
    .string "hierba alta.\p"
    .string "Zigzaguea por zonas de hierba para\n"
    .string "hacerlos salir.$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "Gana una MO gratis por encontrar\n"
    .string "la CASA SECRETA.$"

