VictoryRoad_2F_Text_DawsonIntro::
    .string "Si logras pasar por aquí, podrás\n"
    .string "enfrentarte al ALTO MANDO.$"

VictoryRoad_2F_Text_DawsonDefeat::
    .string "¡No!\n"
    .string "¡Increíble!$"

VictoryRoad_2F_Text_DawsonPostBattle::
    .string "¡Puedo vencerte en cuanto a\n"
    .string "conocimientos sobre los POKéMON!$"

VictoryRoad_2F_Text_DaisukeIntro::
    .string "Este es el CAMINO VICTORIA.\p"
    .string "¡Es la prueba final para los\n"
    .string "ENTRENADORES!$"

VictoryRoad_2F_Text_DaisukeDefeat::
    .string "¡Ayyyy!$"

VictoryRoad_2F_Text_DaisukePostBattle::
    .string "Intenta mover algunas rocas si\n"
    .string "no puedes avanzar más.$"

VictoryRoad_2F_Text_NelsonIntro::
    .string "¿Ah, así que quieres desafiar al\n"
    .string "ALTO MANDO?$"

VictoryRoad_2F_Text_NelsonDefeat::
    .string "¡Me ganaste!$"

VictoryRoad_2F_Text_NelsonPostBattle::
    .string "{RIVAL} también vino por aquí.$"

VictoryRoad_2F_Text_VincentIntro::
    .string "¡Vamos!\n"
    .string "¡Te daré una paliza!$"

VictoryRoad_2F_Text_VincentDefeat::
    .string "¡Me diste una paliza!$"

VictoryRoad_2F_Text_VincentPostBattle::
    .string "Te ganaste el derecho de estar en\n"
    .string "el CAMINO VICTORIA…$"

VictoryRoad_2F_Text_GregoryIntro::
    .string "¿El CAMINO VICTORIA es muy duro?$"

VictoryRoad_2F_Text_GregoryDefeat::
    .string "¡Bien hecho!$"

VictoryRoad_2F_Text_GregoryPostBattle::
    .string "Muchos ENTRENADORES dejan\n"
    .string "el desafío y se rinden aquí.$"

@ Unused, old text for Moltres
VictoryRoad_2F_Text_Gyaoo::
    .string "ギヤーオ！$"

