SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
    .string "¿La ZONA SAFARI es enorme, no lo\n"
    .string "crees?\p"
    .string "El LÍDER DE GIMN. de FUCSIA, KOGA,\n"
    .string "patrulla cada cierto tiempo.\p"
    .string "Gracias a él, podemos jugar aquí\n"
    .string "sabiendo que estamos seguros.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
    .string "Puede que lanzarles ROCAS a los\n"
    .string "POKéMON hace que corran, pero\l"
    .string "serán más fáciles de atrapar.$"

SafariZone_West_Text_BaitMakesMonStickAround::
    .string "Usar CEBO hará más probable que\n"
    .string "los POKéMON se queden si se ocupan\l"
    .string "comiendo.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
    .string "Caminé un montón, pero no encontré\n"
    .string "a ningún POKéMON que quería.$"

