SSAnne_Deck_Text_ShipDepartingSoon::
    .string "La fiesta se acabó.\n"
    .string "El barco zarpará pronto.$"

SSAnne_Deck_Text_ScrubbingDecksHardWork::
    .string "¡Fiu! ¡Fregar las cubiertas es\n"
    .string "un trabajo duro!$"

SSAnne_Deck_Text_FeelSeasick::
    .string "Urf… Me siento mal…\p"
    .string "Estoy mareado, así que salí a\n"
    .string "tomar algo de aire…$"

SSAnne_Deck_Text_EdmondIntro::
    .string "¡Ey, compañer{OA}!\p"
    .string "¡Bailemos un poco!$"

SSAnne_Deck_Text_EdmondDefeat::
    .string "¡Eres impresionante!$"

SSAnne_Deck_Text_EdmondPostBattle::
    .string "¿Cuántos tipos de POKéMON crees\n"
    .string "que existan en este gran mundo?$"

SSAnne_Deck_Text_TrevorIntro::
    .string "¡Ahoy, tú!\n"
    .string "¿Estás maread{OA}?$"

SSAnne_Deck_Text_TrevorDefeat::
    .string "¡No estaba atento!$"

SSAnne_Deck_Text_TrevorPostBattle::
    .string "Mi pa dijo que hay 100 tipos de\n"
    .string "POKéMON. Yo creo que hay más.$"

