SSAnne_Deck_Text_ShipDepartingSoon:: @ 817326F
    .string "La fiesta se acabó.\n"
    .string "El barco zarpará pronto.$"

SSAnne_Deck_Text_ScrubbingDecksHardWork:: @ 81732A2
    .string "¡Fiu! ¡Fregar las cubiertas es\n"
    .string "un trabajo duro!$"

SSAnne_Deck_Text_FeelSeasick:: @ 81732C6
    .string "Urf… Me siento mal…\p"
    .string "Estoy mareado, así que salí a\n"
    .string "tomar algo de aire…$"

SSAnne_Deck_Text_EdmondIntro:: @ 8173308
    .string "¡Ey, compañer{OA}!\p"
    .string "¡Bailemos un poco!$"

SSAnne_Deck_Text_EdmondDefeat:: @ 817332B
    .string "¡Eres impresionante!$"

SSAnne_Deck_Text_EdmondPostBattle:: @ 817333E
    .string "¿Cuántos tipos de POKéMON crees\n"
    .string "que existan en este gran mundo?$"

SSAnne_Deck_Text_TrevorIntro:: @ 8173382
    .string "¡Ahoy, tú!\n"
    .string "¿Estás maread{OA}?$"

SSAnne_Deck_Text_TrevorDefeat:: @ 81733A0
    .string "¡No estaba atento!$"

SSAnne_Deck_Text_TrevorPostBattle:: @ 81733B5
    .string "Mi pa dijo que hay 100 tipos de\n"
    .string "POKéMON. Yo creo que hay más.$"

