CeruleanCity_House2_Text_RocketsStoleTMForDig:: @ 8191E13
    .string "¡Esos miserables ROCKETS!\p"
    .string "¡Mira lo que le hicieron a\n"
    .string "mi casa!\p"
    .string "¡Robaron una MT para enseñar\n"
    .string "POKéMON a CAVAR agujeros!\p"
    .string "Iba a usarla en un MANKEY\n" 
    .string "o en un SANDSHREW…\p"
    .string "¡Y esa MT me costó mucho!$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM:: @ 8191ED8
    .string "Creo que lo se perdió se perdió.\p"
    .string "Decidí que le enseñaré a DIGLETT\n"
    .string "cómo CAVAR sin una MT.$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood:: @ 8191F2A
    .string "¡El EQUIPO ROCKET está intentando\n"
    .string "CAVAR su camino hacia una maldad!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut:: @ 8191F64
    .string "¡El EQUIPO ROCKET dejó una salida!$"

