SilphCo_1F_Text_WelcomePresidentInBoardroom::
    .string "Bienvenida{OA}.\p"
    .string "El PRESIDENTE está en la sala de\n"
    .string "juntas en el PISO 11.$"

@ Tentative translation. Unknown origin
SilphCo_1F_Text_DestroyedWontBeFixedForWhile::
    .string "めちゃめちゃに　こわされてる\n"
    .string "とうぶん　なおりそうに　ない‥$"

SilphCo_1F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P1$"

