LavenderTown_House1_Text_Cubone::
    .string "CUBONE: ¡Kyarugoo!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother::
    .string "¡Esos horribles ROCKETS!\n"
    .string "¡No merecen piedad!\p"
    .string "La pobre madre de ese CUBONE…\p"
    .string "Murió tratando de escapar del\n"
    .string "EQUIPO ROCKET.$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone::
    .string "¡El fantasma de la TORRE POKéMON\n"
    .string "se fué!\p"
    .string "¡Alguien debe de haber calmado su\n"
    .string "espíritu atormentado!$"

