SaffronCity_House_Text_DontLookAtMyLetter::
    .string "…Gracias por escribir.\n"
    .string "¡Espero verte pronto!\p"
    .string "…¡Ey!\n"
    .string "¡No mires mi carta!$"

SaffronCity_House_Text_Pidgey::
    .string "PIDGEY: ¡Kurukkoo!$"

SaffronCity_House_Text_GettingCopycatPokeDoll::
    .string "¡La IMITADORA es linda!\n"
    .string "Le voy a comprar un POKé MUÑECO.$"

SaffronCity_House_Text_ExplainPPUp::
    .string "Me dieron un MÁS PP como regalo.\p"
    .string "Se usa para aumentar los PP del\n"
    .string "movimiento de un POKéMON.\p"
    .string "Debería usarlo en un movimiento\n"
    .string "poderoso que tenga pocos PP.$"

