SSAnne_2F_Room2_Text_BrooksIntro::
    .string "Competir contra la juventud me\n"
    .string "mantiene joven.$"

SSAnne_2F_Room2_Text_BrooksDefeat::
    .string "¡Buena batalla!\n"
    .string "¡Ah, me siento joven otra vez!$"

SSAnne_2F_Room2_Text_BrooksPostBattle::
    .string "¡Hace quince años, hubiera\n"
    .string "ganado!$"

SSAnne_2F_Room2_Text_DaleIntro::
    .string "¡Mira lo que acabo de pescar!$"

SSAnne_2F_Room2_Text_DaleDefeat::
    .string "¡Me quede sin nada!$"

SSAnne_2F_Room2_Text_DalePostBattle::
    .string "¿Fiesta?\p"
    .string "La fiesta del crucero ya se debió\n"
    .string "de haber acabado.$"

