SSAnne_2F_Room2_Text_BrooksIntro:: @ 8173D63
    .string "Competir contra la juventud me\n"
    .string "mantiene joven.$"

SSAnne_2F_Room2_Text_BrooksDefeat:: @ 8173D92
    .string "¡Buena batalla!\n"
    .string "¡Ah, me siento joven otra vez!$"

SSAnne_2F_Room2_Text_BrooksPostBattle:: @ 8173DB6
    .string "¡Hace quince años, hubiera\n"
    .string "ganado!$"

SSAnne_2F_Room2_Text_DaleIntro:: @ 8173DDB
    .string "¡Mira lo que acabo de pescar!$"

SSAnne_2F_Room2_Text_DaleDefeat:: @ 8173DF7
    .string "¡Me quede sin nada!$"

SSAnne_2F_Room2_Text_DalePostBattle:: @ 8173E04
    .string "¿Fiesta?\p"
    .string "La fiesta del crucero ya se debió\n"
    .string "de haber acabado.$"

