Route4_Text_TrippedOverGeodude:: @ 81838D7
    .string "¡Ouch! ¡Tropecé con un POKéMON\n"
    .string "rocoso, GEODUDE!$"

Route4_Text_CrissyIntro:: @ 8183906
    .string "I came to MT. MOON in search of\n"
    .string "mushroom POKéMON.$"

Route4_Text_CrissyDefeat:: @ 8183938
    .string "After all I did to catch them!$"

Route4_Text_CrissyPostBattle:: @ 8183957
    .string "There might not be any more\n"
    .string "mushrooms here.\p"
    .string "I think I got them all.$"

Route4_Text_MtMoonEntrance:: @ 818399B
    .string "MONTE LUNA\n"
    .string "Entrada al túnel$"

Route4_Text_RouteSign:: @ 81839B4
    .string "RUTA 4\n"
    .string "MONTE LUNA - CIUDAD CELESTE$"

Text_MegaPunchTeach:: @ 81839D5
    .string "¡Un puño de ferocidad rugiente!\p"
    .string "¡Lleno de poder destructivo!\p"
    .string "¡Cuando no queda energía,\n"
    .string "MEGA PUÑO es el ataque definitivo!\l"
    .string "¿Estás de acuerdo?\p"
    .string "¡Ahora!\n" 
    .string "¡Déjame enseñarselo a un POKéMON!$"

Text_MegaPunchDeclined:: @ 8183A83
    .string "Regresarás cuando entiendas el\n"
    .string "valor del MEGA PUÑO.$"

Text_MegaPunchWhichMon:: @ 8183ABF
    .string "¡Bien!\n"
    .string "¿Qué POKéMON quiere aprenderlo?$"

Text_MegaPunchTaught:: @ 8183AE2
    .string "¡Ahora somos camaradas en el\n"
    .string "camino del puño!\p"
    .string "Deberías irte antes de que te vea\n"
    .string "ese bobo malencaminado de ahí que\l"
    .string "solo entrena sus tontas patadas.$"

Text_MegaKickTeach:: @ 8183B74
    .string "¡Una patada de ferocidad brutal!\p"
    .string "¡Llena de poder destructivo!\p"
    .string "Cuando quieres ser direct{OA},\n"
    .string "MEGA PATADA es el ataque definitivo!\l"
    .string "¿No estás de acuerdo?\p"
    .string "¡Bien!\n"
    .string "¡Déjame enseñarselo a un POKéMON!$"

Text_MegaKickDeclined:: @ 8183C25
    .string "Vendrás arrastrandote cuando\n"
    .string "entiendas el valor de MEGA PATADA.$"

Text_MegaKickWhichMon:: @ 8183C68
    .string "¡De acuerdo!\n"
    .string "¿Qué POKéMON quiere aprenderla?$"

Text_MegaKickTaught:: @ 8183C94
    .string "¡Ahora somos almas gemelas en el\n"
    .string "camino de las patadas!\p"
    .string "Deberías correr antes de que seas\n"
    .string "vist{OA} por ese iluso de ahí que\l"
    .string "solo entrena sus simples puños.$"

Route4_Text_PeopleLikeAndRespectBrock:: @ 8183D26
    .string "¡Vaya, esa es la MEDALLA ROCA!\n"
    .string "Te la dio BROCK, ¿cierto?\p"
    .string "Brock es además de fuerte, genial.\n"
    .string "Todos lo respetan y admiran.\p"
    .string "Quiero convertirme en\n"
    .string "LÍDER de GIMNASIO como él.$"
