VermilionCity_Text_GrimerMultipliesInSludge:: @ 817F723
    .string "Somos cuidadosos con la polución.\p"
    .string "Escuchamos que GRIMER se\n"
    .string "multiplica en desechos tóxicos.$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor:: @ 817F776
    .string "¿Viste al SANTA ANA amarrado en\n"
    .string "el puerto?$"

VermilionCity_Text_SSAnneHasDepartedForYear:: @ 817F7A6
    .string "Así que, ¿el SANTA ANA ya partió?\p"
    .string "Volvera a CARMÍN cerca de esta\n"
    .string "fecha el próximo año.$"

VermilionCity_Text_BuildingOnThisLand:: @ 817F7FD
    .string "Pondré un edificio en esta parcela\n"
    .string "de tierra. Es de mi propiedad.\p"
    .string "Mi POKéMON esta apisonando la\n"
    .string "tierra para sentar la fundación.$"

VermilionCity_Text_Machop:: @ 817F871
    .string "MACHOP: ¡Guoh! ¡Gogogoh!$"

VermilionCity_Text_MachopStompingLandFlat:: @ 817F888
    .string "Un MACHOP aplana la tierra.$"

VermilionCity_Text_SSAnneVisitsOnceAYear:: @ 817F8AC
    .string "El SANTA ANA es un famoso crusero\n"
    .string "de lujo.\p"
    .string "Visita CARMÍN una vez al año.$"

VermilionCity_Text_CitySign:: @ 817F8FB
    .string "CIUDAD CARMÍN\n"
    .string "El puerto de los ocasos exquisitos$"

VermilionCity_Text_SnorlaxBlockingRoute12:: @ 817F928
    .string "¡AVISO!\p"
    .string "La RUTA 12 puede estar bloqueada\n"
    .string "por un POKéMON durmiente.\p"
    .string "Tome el desvío a través del\n"
    .string "TÚNEL ROCA al PUEBLO LAVANDA.\p"
    .string "POLICIA DE CARMÍN$"

VermilionCity_Text_PokemonFanClubSign:: @ 817F9A1
    .string "CLUB DE FANS DE POKéMON\n"
    .string "¡Se acepta a todo fan de POKéMON!$"

VermilionCity_Text_GymSign:: @ 817F9CC
    .string "GIMNASIO POKéMON de CIUDAD CARMÍN\n"
    .string "LÍDER: TENIENTE SURGE\l"
    .string "¡El Rayo americano!$"

VermilionCity_Text_VermilionHarbor:: @ 817FA11
    .string "PUERTO CARMÍN$"

VermilionCity_Text_WelcomeToTheSSAnne:: @ 817FA22
    .string "¡Bienvenid{OA} al SANTA ANA!$"

VermilionCity_Text_DoYouHaveATicket:: @ 817FA3C
    .string "¡Bienvenid{OA} al SANTA ANA!\p"
    .string "Disculpe, ¿tiene un boleto?$"

VermilionCity_Text_FlashedSSTicket:: @ 817FA77
    .string "{SIZE}Á¡{PLAYER} dió el BOLETO SANTA ANA!\p"
    .string "{SIZE}Ç¡Muy bien!\n"
    .string "¡Bienvenid{OA} al SANTA ANA!$"

VermilionCity_Text_DontHaveNeededSSTicket:: @ 817FABA
    .string "{SIZE}Á{PLAYER} no tiene el BOLETO\n"
    .string "SANTA ANA requerido.\p"
    .string "{SIZE}Ç¡Lo siento!\p"
    .string "Necesitas boleto para ir a bordo.$"

VermilionCity_Text_TheShipSetSail:: @ 817FB10
    .string "El barco zarpó.$"

VermilionCity_Text_BoardSeagallopTriPass:: @ 817FB23
    .string "Ah, así que tienes un TRI-PASE.\p"
    .string "¿Te gustaría ir a bordo de\n"
    .string "un barco Surcarmar?$"

VermilionCity_Text_Seagallop7Departing:: @ 817FB67
    .string "De acuerdo, todo esta en orden.\p"
    .string "El Surcarmar Veloce 7 partirá\n"
    .string "inmediatamente.$"

VermilionCity_Text_BoardSeagallopRainbowPass:: @ 817FBB8
    .string "Ah, tienes un PASE ARCOÍRIS.\p"
    .string "¿Te gustaría ir a bordo de\n"
    .string "un barco Surcarmar?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock:: @ 817FC00
    .string "¡Oh! ¡Ese es un BOLETO MÍSTICO!\n"
    .string "Eso es raro de ver.\p"
    .string "Estaríamos felices de llevarte a\n"
    .string "ROCA OMBLIGO cuándo quieras.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland:: @ 817FC5F
    .string "¡Oh! ¡Ese es un BOLETO AURORA!\n"
    .string "Eso es raro de ver.\p"
    .string "Estaríamos felices de llevarte a\n"
    .string "ISLA ORIGEN cuándo quieras.$"

VermilionCity_Text_BoardSeagallopFerry:: @ 817FCC1
    .string "¿Te gustaría ir a bordo de\n"
    .string "un barco Surcarmar?$"

VermilionCity_Text_Seagallop10Departing:: @ 817FCEC
    .string "Bien, todo esta en orden para que\n"
    .string "abordes un barco especial.\p"
    .string "El Surcarmar Veloce 10 partirá\n"
    .string "inmediatamente.$"

VermilionCity_Text_Seagallop12Departing:: @ 817FD5F
    .string "Bien, todo esta en orden para que\n"
    .string "abordes un barco especial.\p"
    .string "El Surcarmar Veloce 12 partirá\n"
    .string "inmediatamente.$"

VermilionCity_Text_Route2AideHasPackageForYou:: @ 817FDD2
    .string "Oh, ¡hola, {PLAYER}!\n"
    .string "¿Cómo te va?\p"
    .string "Soy yo, un AYUDANTE del PROF. OAK.\p"
    .string "¿Conociste al otro AYUDANTE?\p"
    .string "Él tenía un paquete del PROF. OAK\n"
    .string "para tí, {PLAYER}.\p"
    .string "Dijo que te buscaría cerca de la\n"
    .string "RUTA 2, {PLAYER}.\p"
    .string "Si estás cerca de la RUTA 2,\n"
    .string "por favor búscalo.$"

