PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow:: @ 81917E4
    .string "Los POKéMON aprenden tecnicas\n"
    .string "nuevas a medida que crecen.\p"
    .string "Pero algunos movimientos tienen\n"
    .string "que ser enseñados por personas.$"

PewterCity_House2_Text_MonsEasierCatchIfStatused:: @ 8191840
    .string "Un POKéMON se vuelve más fácil\n"
    .string "de atrapar si tiene un problema\l"
    .string "de estado.\p"
    .string "El sueño, veneno, quemaduras,\n"
    .string "o la paralisis…\l"
    .string "Todo eso es efectivo.\p"
    .string "¡Pero atrapar POKéMON nunca es\n"
    .string "cosa segura!$"
