PokemonLeague_LoreleisRoom_Text_Intro::
    .string "Bienvenid{OA} a la LIGA POKéMON.\p"
    .string "Soy LORELEI, del ALTO MANDO.\p"
    .string "Nadie me supera cuando se trata de\n"
    .string "POKéMON de hielo.\p"
    .string "Los movimientos helados son\n"
    .string "muy poderosos.\p"
    .string "Tus POKéMON estarán a mi merced\n"
    .string "cuando estén congelados.\p"
    .string "¡Jajaja!\n"
    .string "¿Estás list{OA}?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "Bienvenid{OA} a la LIGA POKéMON.\p"
    .string "¡Yo, LORELEI del ALTO MANDO,\n"
    .string "he regresado!\p"
    .string "Ya sabes el resto.\n"
    .string "Nadie me supera cuando se trata de\n"
    .string "POKéMON de hielo.\p"
    .string "Los movimientos helados son\n"
    .string "muy poderosos.\p"
    .string "Tus POKéMON estarán a mi merced\n"
    .string "cuando estén congelados.\p"
    .string "¡Jajaja!\n"
    .string "¿Estás list{OA}?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "…¡Esto no debería ser así!$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "Eres mejor de lo que pensé.\n"
    .string "Sigue adelante.\p"
    .string "Solo has probado una parte del\n"
    .string "poder de la LIGA POKéMON.$"

