CeladonCity_Gym_Text_ErikaIntro::
    .string "Hola…\n"
    .string "Hermoso clima, ¿no es así?\l"
    .string "Es tan agradable…\p"
    .string "…Oh, cielos…\n"
    .string "Debí dormirme. Bienvenid{OA}.\p"
    .string "Mi nombre es ERIKA.\n"
    .string "Soy la LÍDER del GIMNASIO PRISMA.\p"
    .string "Soy una estudiante en el arte del\n"
    .string "arreglo floral.\p"
    .string "Mis POKéMON son únicamente del\n"
    .string "tipo PLANTA.\p"
    .string "…Oh, lo siento, no tenía idea de\n"
    .string "que deseabas desafiarme.\p"
    .string "Muy bien, pero no perderé.{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

CeladonCity_Gym_Text_ErikaDefeat::
    .string "¡Oh!\n"
    .string "Admito la derrota.\l"
    .string "Eres notablemente fuerte.\p"
    .string "Debo otorgarte la MEDALLA ARCOÍRIS.$"

CeladonCity_Gym_Text_ErikaPostBattle::
    .string "¿Estás catalogando POKéMON?\n"
    .string "Debo decir que estoy impresionada.\p"
    .string "Nunca coleccionaria POKéMON que\n"
    .string "sean poco atractivos.$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis::
    .string "La MEDALLAARCOÍRIS hace que todo\n"
    .string "POKéMON hasta el Nv. 50 obedezca.\p"
    .string "También permite usar el movimiento\n"
    .string "FUERZA fuera de las batallas.\p"
    .string "También lleva esto contigo.$"

CeladonCity_Gym_Text_ReceivedTM19FromErika::
    .string "{PLAYER} recibió MT19\n"
    .string "de ERIKA.$"

CeladonCity_Gym_Text_ExplainTM19::
    .string "MT19 contiene GIGA DRENADO.\p"
    .string "La mitad del daño que ejerce\n"
    .string "se drena para curar a tu POKéMON.\p"
    .string "¿No estás de acuerdo en que es un\n"
    .string "movimiento maravilloso?$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
    .string "Deberías hacer espacio para esto.$"

CeladonCity_Gym_Text_KayIntro::
    .string "Debes saber algo de este GIMNASIO.\p"
    .string "¡Solo se permiten señoritas de verdad\n"
    .string "aquí!$"

CeladonCity_Gym_Text_KayDefeat::
    .string "¡Eres demasiado fuerte!$"

CeladonCity_Gym_Text_KayPostBattle::
    .string "¡Buaah!\n"
    .string "¡Espero que ERIKA te aniquile!$"

CeladonCity_Gym_Text_BridgetIntro::
    .string "Oh, bienvenid{OA}.\n"
    .string "Me estaba aburriendo.$"

CeladonCity_Gym_Text_BridgetDefeat::
    .string "¡Mi maquillaje!$"

CeladonCity_Gym_Text_BridgetPostBattle::
    .string "Los POKéMON de tipo PLANTA son\n"
    .string "fuertes contra los de tipo AGUA.\p"
    .string "También tienen ventaja contra los\n"
    .string "del tipo ROCA y del tipo TIERRA.$"

CeladonCity_Gym_Text_TinaIntro::
    .string "…¿No estabas espiando este lugar\n"
    .string "antes?$"

CeladonCity_Gym_Text_TinaDefeat::
    .string "¡Me abriste los ojos!$"

CeladonCity_Gym_Text_TinaPostBattle::
    .string "Oh, estabas mirando a ERIKA…\n"
    .string "No me mirabas a mí…$"

CeladonCity_Gym_Text_TamiaIntro::
    .string "¡Mira, mira!\n"
    .string "¡Ve a mis POKéMON!\p"
    .string "Me gustan los de tipo PLANTA.\n"
    .string "Me gusta que son fáciles de criar.$"

CeladonCity_Gym_Text_TamiaDefeat::
    .string "¡No!$"

CeladonCity_Gym_Text_TamiaPostBattle::
    .string "Solo usamos POKéMON de tipo PLANTA\n"
    .string "en nuestro GIMNASIO.\p"
    .string "¿Por qué? ¡también los usamos para\n"
    .string "hacer arreglos florales!$"

CeladonCity_Gym_Text_LisaIntro::
    .string "¡Oh, ey!\p"
    .string "¡Aquí no nos gustan los POKéMON\n"
    .string "de tipo INSECTO o FUEGO!$"

CeladonCity_Gym_Text_LisaDefeat::
    .string "¡Oh!\n"
    .string "¡Tú!$"

CeladonCity_Gym_Text_LisaPostBattle::
    .string "Puede que nuestra líder ERIKA sea\n"
    .string "callada, pero es famosa por aquí.$"

CeladonCity_Gym_Text_LoriIntro::
    .string "Encantada de conocerte.\n"
    .string "Mi pasatiempo es entrenar POKéMON.$"

CeladonCity_Gym_Text_LoriDefeat::
    .string "¡Oh!\n"
    .string "¡Espléndido!$"

CeladonCity_Gym_Text_LoriPostBattle::
    .string "Tendré una cita a ciegas pronto.\n"
    .string "Tengo que aprender a ser cortés,\l"
    .string "en especial si tendré que luchar.$"

CeladonCity_Gym_Text_MaryIntro::
    .string "¡Bienvenid{OA} al GIMNASIO PRISMA!\p"
    .string "Será mejor que no subestimes a las\n"
    .string "amables señoritas de este lugar.$"

CeladonCity_Gym_Text_MaryDefeat::
    .string "¡Oh!\n"
    .string "¡Vencida!$"

CeladonCity_Gym_Text_MaryPostBattle::
    .string "No traje a mis mejores POKéMON.\n"
    .string "¡Espera la próxima vez!$"

CeladonCity_Gym_Text_GymStatue::
    .string "GIMNASIO POKéMON DE PRISMA\n"
    .string "LÍDER: ERIKA\p"
    .string "ENTRENADORES VICTORIOSOS:\n"
    .string "{RIVAL}$"

CeladonCity_Gym_Text_GymStatuePlayerWon::
    .string "GIMNASIO POKéMON DE PRISMA\n"
    .string "LÍDER: ERIKA\p"
    .string "ENTRENADORES VICTORIOSOS:\n"
    .string "{RIVAL}, {PLAYER}$"

