CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink::
    .string "¡Estoy sedienta!\n"
    .string "¡Quiero algo de beber!\p"
    .string "{FONT_NORMAL}¿Darle una bebida?$"

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink::
    .string "¿Cúal bebida?$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis::
    .string "¡Yey!\p"
    .string "¡AGUA FRESCA!\p"
    .string "¡Gracias!\n"
    .string "¡Puedes tener esto!$"

Text_ReceivedItemFromLittleGirl::
    .string "{PLAYER} recibió {STR_VAR_2}\n"
    .string "de la pequeña niña.$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16::
    .string "MT16 contiene PANTALLA DE LUZ.\p"
    .string "Es un movimiento que debilita\n"
    .string "los ataques especiales enemigos.$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis::
    .string "¡Yey!\p"
    .string "¡SODA!\p"
    .string "¡Gracias!\n"
    .string "¡Puedes tener esto!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20::
    .string "MT20 contiene SALVAGUARDA.\p"
    .string "El movimiento previene problemas\n"
    .string "de estado entre tus POKéMON.$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis::
    .string "¡Yey!\p"
    .string "¡LIMONADA!\p"
    .string "¡Gracias!\n"
    .string "¡Puedes tener esto!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33::
    .string "MT33 contiene REFLEJO.\p"
    .string "Es un movimiento que debilita\n"
    .string "los ataques físicos enemigos.$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis::
    .string "¡No tienes espacio para esto!$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll::
    .string "¡No, gracias!\n"
    .string "¡No tengo sed después de todo!$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature::
    .string "Mi hermana es una ENTRENADORA,\n"
    .string "lo creas o no.\p"
    .string "Pero es tan inmadura, ¡me vuelve\n"
    .string "loca!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink::
    .string "¡Estoy sedienta!\n"
    .string "¡Quiero algo de beber!$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign::
    .string "AZOTEA:\n"
    .string "MÁQUINAS EXPENDEDORAS$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave::
    .string "¡Una máquina expendedora!\n"
    .string "¿Qué es lo que tiene?$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney::
    .string "¡Ups, falta dinero!$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut::
    .string "¡Salió una lata de {STR_VAR_1}!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff::
    .string "¡Ya no hay espacio para cosas!$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty::
    .string "¡Sin sed!$"

