SSAnne_1F_Room2_Text_TylerIntro::
    .string "¡Amo a los POKéMON!\n"
    .string "¿Y tú?$"

SSAnne_1F_Room2_Text_TylerDefeat::
    .string "¡Wow! \n"
    .string "¡Eres genial!$"

SSAnne_1F_Room2_Text_TylerPostBattle::
    .string "¡Escucha, escucha!\n"
    .string "Déjame ser tu amigo, ¿sí?\p"
    .string "Entonces podemos intercambiar\n"
    .string "POKéMON y hacer cosas.$"

SSAnne_1F_Room2_Text_AnnIntro::
    .string "¡He coleccionado a estos POKéMON\n"
    .string "de todas partes del mundo!$"

SSAnne_1F_Room2_Text_AnnDefeat::
    .string "¡Oh, no!\n"
    .string "¡Di la vuelta al mundo por estos!$"

SSAnne_1F_Room2_Text_AnnPostBattle::
    .string "¡Lastimaste a mis pobres POKéMON!\p"
    .string "¡Exijo que los cures en\n"
    .string "un CENTRO POKéMON!$"

SSAnne_1F_Room2_Text_CruisingAroundWorld::
    .string "Mis niños y yo estamos navegando\n"
    .string "por el mundo.$"

