SSAnne_1F_Room2_Text_TylerIntro:: @ 8173999
    .string "¡Amo a los POKéMON!\n"
    .string "¿Y tú?$"

SSAnne_1F_Room2_Text_TylerDefeat:: @ 81739B1
    .string "¡Wow! \n"
    .string "¡Eres genial!$"

SSAnne_1F_Room2_Text_TylerPostBattle:: @ 81739C5
    .string "¡Escucha, escucha!\n"
    .string "Déjame ser tu amigo, ¿sí?\p"
    .string "Entonces podemos intercambiar\n"
    .string "POKéMON y hacer cosas.$"

SSAnne_1F_Room2_Text_AnnIntro:: @ 8173A1A
    .string "¡He coleccionado a estos POKéMON\n"
    .string "de todas partes del mundo!$"

SSAnne_1F_Room2_Text_AnnDefeat:: @ 8173A4F
    .string "¡Oh, no!\n"
    .string "¡Di la vuelta al mundo por estos!$"

SSAnne_1F_Room2_Text_AnnPostBattle:: @ 8173A7A
    .string "¡Lastimaste a mis pobres POKéMON!\p"
    .string "¡Exijo que los cures en\n"
    .string "un CENTRO POKéMON!$"

SSAnne_1F_Room2_Text_CruisingAroundWorld:: @ 8173AC5
    .string "Mis niños y yo estamos navegando\n"
    .string "por el mundo.$"

