FuchsiaCity_House2_Text_DoYouLikeToFish::
    .string "Soy el hermano mayor del\n"
    .string "GURÚ DE LA PESCA.\p"
    .string "¡Simplemente aaamo pescar!\n"
    .string "No soporto vivir sin ello.\p"
    .string "¿Dime, te gusta pescar?$"

FuchsiaCity_House2_Text_LikeYourStyleTakeThis::
    .string "¡Grandioso! Me gusta tu estilo.\n"
    .string "Creo que podemos ser amigos.\p"
    .string "¡Toma esto y pesca, joven amig{OA}!$"

FuchsiaCity_House2_Text_ReceivedGoodRod::
    .string "{PLAYER} recibió una CAÑA BUENA\n"
    .string "del hermano del GURÚ DE LA PESCA.$"

FuchsiaCity_House2_Text_GoodRodCanCatchBetterMons::
    .string "¡Pescar es una forma de vida!\n"
    .string "Es cómo la más fina poesía.\p"
    .string "¿Una CAÑA VIEJA solo puede atrapar\n"
    .string "MAGIKARP, cierto?\p"
    .string "Pero con una CAÑA BUENA, puedes\n"
    .string "atrapar POKéMON mucho mejores.$"

FuchsiaCity_House2_Text_OhThatsDisappointing::
    .string "Oh…\n"
    .string "Eso es tan decepcionante…$"

FuchsiaCity_House2_Text_HowAreTheFishBiting::
    .string "¡Hola ahí, {PLAYER}!\p"
    .string "¿Cómo muerden los peces?$"

FuchsiaCity_House2_Text_YouHaveNoRoomForGift::
    .string "¡Oh, no!\p"
    .string "Tenía un regalo para ti,\n"
    .string "¡pero no tienes espacio para eso!$"

