IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .string "¡Yo!\n"
    .string "¡Futur{OA} campe{ONONA}!\p"
    .string "En la LIGA POKéMON, tendrás que\n"
    .string "enfrentarte a todos los miembros\l"
    .string "del ALTO MANDO, uno tras otro.\p"
    .string "¡Si pierdes, tendrás que volver\n"
    .string "a empezar!\p"
    .string "¡Eso es todo!\n"
    .string "¡Adelante!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck::
    .string "Si avanzas, te enfrentarás al\n"
    .string "ALTO MANDO, uno por uno.\p"
    .string "Si ganas, se abrirá una puerta al\n"
    .string "siguiente ENTRENADOR.\p"
    .string "¡Buena suerte!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .string "Lo siento mucho, pero perdiste\n"
    .string "tu tiempo viniendo aquí.\p"
    .string "Verás, LORELEI del ALTO MANDO\n"
    .string "está ausente.\p"
    .string "Como resultado, la LIGA POKéMON\n"
    .string "está cerrada por el momento.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
    .string "Los POKéMON de tipo FANTASMA de\n"
    .string "AGATHA son escalofriantemente\l"
    .string "fuertes.\p"
    .string "Críe a mis POKéMON de tipo PELEA\n"
    .string "hasta el límite.\p"
    .string "Fuí contra AGATHA lleno\n"
    .string "de confianza, pero nos destrozó.\p"
    .string "Además, la señora tiene un\n"
    .string "temperamento explosivo.\p"
    .string "No tienes que hacer mucho para\n"
    .string "que esa señora aterradora grite.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
    .string "Tal vez ser miembro del ALTO MANDO\n"
    .string "esta en la sangre.\p"
    .string "Por lo que sé, LANCE tiene una\n"
    .string "prima que es LÍDER de GIMNASIO en\l"
    .string "algún lugar lejano.$"

