Text_MetronomeTeach::
    .string "¡Tac-tac-tac!\n"
    .string "Te enseñaré un movimiento genial.\p"
    .string "Enseñaselo a un POKéMON,\n"
    .string "¡y admira la diversión!\p"
    .string "Se llama METRÓNOMO.\n"
    .string "¿Te interesa?$"

Text_MetronomeDeclined::
    .string "¡Vamos, es muy divertido!$"

Text_MetronomeWhichMon::
    .string "¡Bien!\n"
    .string "¿A qué POKéMON le voy a enseñar?$"

Text_MetronomeTaught::
    .string "¡Tac-tac-tac!\n"
    .string "Ese es el sonido de un METRÓNOMO.\p"
    .string "Altera el cerebro de tu POKéMON\n"
    .string "y lo lleva a usar movimientos que\l"
    .string "ni siquiera conoce.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe::
    .string "¡Hola!\p"
    .string "Soy doctor importante.\n"
    .string "Sí, mucho, sí.\p"
    .string "Aquí, estudio fósiles de POKéMON\n"
    .string "raros.\p"
    .string "Todo el tiempo, estudio.\p"
    .string "¡Tú!\n"
    .string "¿Tienes tú un fósil para mí?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
    .string "¡No!\n"
    .string "¡Qué mal!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP::
    .string "ちょっと　じかん　かかるよ！\p"
    .string "そこらへんを　すこし\n"
    .string "ブラブラ　してくると　よろしー！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
    .string "Tú tarde.\n"
    .string "¿Donde estabas?\p"
    .string "¡Tú fósil volvió a la vida!\n"
    .string "¡Era {STR_VAR_1} como creía!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
    .string "{PLAYER} recibió {STR_VAR_1}\n"
    .string "del doctor.$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon::
    .string "ポケモン　いっぱいで　もてないね！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
    .string "¡Oh!\n"
    .string "¡Esto es {STR_VAR_2}, lo es!\p"
    .string "¡Es un fósil de {STR_VAR_1},\n" 
    .string "un POKéMON ya extinto!\p"
    .string "¡Mi máquina de resurrección hará\n"
    .string "que este POKéMON viva otra vez!$"

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
    .string "¡Entonces!\n"
    .string "¡Apresúrate y dame eso!\p"
    .string "{FONT_2}{PLAYER} le entregó\n"
    .string "{STR_VAR_2} al extraño doctor.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
    .string "¡Tardaré un poco!\n"
    .string "¡Tú ve a caminar un rato!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
    .string "¡Aiyah!\n"
    .string "¡Ven de nuevo!$"

