Route21_North_Text_RonaldIntro::
	.string "¿Quieres saber si los peces están\n"
	.string "picando?$"

Route21_North_Text_RonaldDefeat::
	.string "¡Rayos!$"

Route21_North_Text_RonaldPostBattle::
	.string "No puedo atrapar nada bueno.\n"
	.string "¡No tengo ni un POKéMON bueno!$"

Route21_North_Text_WadeIntro::
	.string "¡Tengo una gran captura!\n"
	.string "¿Quierer ver?$"

Route21_North_Text_WadeDefeat::
	.string "Jeje, los MAGIKARP no son\n"
	.string "suficiente, ¿verdad?$"

Route21_North_Text_WadePostBattle::
	.string "¡Parece que solo atrapo MAGIKARP!$"

Route21_North_Text_SpencerIntro::
	.string "¡El mar limpia mi cuerpo y mi\n"
	.string "alma!$"

Route21_North_Text_SpencerDefeat::
	.string "¡Ayah!$"

Route21_North_Text_SpencerPostBattle::
	.string "El mar es genial y todo, pero\n"
	.string "también me gustan las montañas.$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro::
	.string "おれだって　たまには\n"
	.string "およぎに　くるぜ！$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat::
	.string "ぐわわ！$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle::
	.string "うきやすそう　だと？\n"
	.string "うるせー　おおきな　おせわだッ！$"
