Route15_Text_KindraIntro::
    .string "Acabo de obtener algunos POKéMON\n"
    .string "en intercambios.\p"
    .string "¿Puedo probarlos contigo?$"

Route15_Text_KindraDefeat::
    .string "¡No fue suficiente!$"

Route15_Text_KindraPostBattle::
    .string "No puedes cambiar los apodos de\n"
    .string "POKéMON obtenidos en intercambios.\p"
    .string "Solo su ENTRENADOR ORIGINAL puede\n"
    .string "cambiarle el apodo.$"

Route15_Text_BeckyIntro::
    .string "Parecer ser suave, creo que puedo\n"
    .string "vencerte.\p"
    .string "¡Lo intentaré!$"

Route15_Text_BeckyDefeat::
    .string "¡No, mal!$"

Route15_Text_BeckyPostBattle::
    .string "Los MOTORISTAS me dan miedo. ¡Son\n"
    .string "tan feos y crueles!$"

Route15_Text_EdwinIntro::
    .string "Puedo llamar a POKéMON pájaros\n"
    .string "silbando.$"

Route15_Text_EdwinDefeat::
    .string "¡Auch!\n"
    .string "¡Qué tragedia!$"

Route15_Text_EdwinPostBattle::
    .string "Tal vez no estoy hecho para las\n"
    .string "batallas.\p"
    .string "No soy del tipo correcto, supongo.$"

Route15_Text_ChesterIntro::
    .string "¿Hmm? ¡mis aves están temblando!\n"
    .string "¿Eres buen{OA}, verdad?$"

Route15_Text_ChesterDefeat::
    .string "¡Justo como creí!$"

Route15_Text_ChesterPostBattle::
    .string "Esto es tan obvio, debes de\n"
    .string "saberlo, pero…\p"
    .string "Ataques como TERREMOTO y FISURA no\n"
    .string "tienen efecto en POKéMON pájaros.$"

Route15_Text_GraceIntro::
    .string "¡Oh, eres tan tierno!\n"
    .string "¡Que POKéMON tan encantador!$"

Route15_Text_GraceDefeat::
    .string "¡Tú también eres lind{OA}!$"

Route15_Text_GracePostBattle::
    .string "Te perdono.\n"
    .string "Puedo soportarlo.\l"
    .string "Soy una chica grande.$"

Route15_Text_OliviaIntro::
    .string "Crío POKéMON por protección,\n"
    .string "porque vivo sola.$"

Route15_Text_OliviaDefeat::
    .string "Los POKéMON no tratan de ganar o\n"
    .string "perder para mí.$"

Route15_Text_OliviaPostBattle::
    .string "Amo que mis POKéMON me den la\n"
    .string "bienvenida cuando regreso a casa.\p"
    .string "Es muy reconfortante.$"

Route15_Text_ErnestIntro::
    .string "¡Ey, niñ{OA}! ¡ven!\p"
    .string "¡Acabo de quitarle estos a algún\n"
    .string "perdedor!$"

Route15_Text_ErnestDefeat::
    .string "¿Por qué no?$"

Route15_Text_ErnestPostBattle::
    .string "La vida es muy corta.\n"
    .string "Vivir como un forajido es genial.\l"
    .string "¡EL EQUIPO ROCKET MANDA!$"

Route15_Text_AlexIntro::
    .string "¡Entrega todo tu dinero cuando\n"
    .string "pierdas contra mi, niñ{OA}!$"

Route15_Text_AlexDefeat::
    .string "¡Esto no puede ser verdad!$"

Route15_Text_AlexPostBattle::
    .string "Estaba bromeando sobre el dinero.\n"
    .string "No me tomes tan en serio.$"

Route15_Text_CeliaIntro::
    .string "¿Qué es algo genial y de moda?\n"
    .string "¡Intercambiar POKéMON!$"

Route15_Text_CeliaDefeat::
    .string "¡Dije intercambiar!$"

Route15_Text_CeliaPostBattle::
    .string "Intercambio POKéMON con mis amigos\n"
    .string "todo el tiempo.$"

Route15_Text_YazminIntro::
    .string "¿Quieres jugar con mis POKéMON?$"

Route15_Text_YazminDefeat::
    .string "¡Fui demasiado impaciente!$"

Route15_Text_YazminPostBattle::
    .string "Iré a entrenar con gente más débil.$"

Route15_Text_RouteSign::
    .string "RUTA 15\n"
    .string "Al oeste de CIUDAD FUCSIA$"

Route15_Text_MyaIntro::
    .string "MYA: Eres {ELLA} indicad{OA}.\p"
    .string "¿Me ayudas a entrenar a mi\n"
    .string "hermanito?$"

Route15_Text_MyaDefeat::
    .string "MYA: ¡RON, debes concentrarte!\n"
    .string "¡Concéntrate en lo que haces!$"

Route15_Text_MyaPostBattle::
    .string "MYA: Bien, mejoraremos.\p"
    .string "¡Te añadiré a nuestro menú de\n"
    .string "entrenamientos!$"

Route15_Text_MyaNotEnoughMons::
    .string "MYA: ¿Quieres desafiarnos?\n"
    .string "Necesitas dos POKéMON.$"

Route15_Text_RonIntro::
    .string "RON: Mi hermana se asusta cuando\n"
    .string "perdemos.$"

Route15_Text_RonDefeat::
    .string "RON: Oh, no, no…\n"
    .string "¡Hermana, lo siento!$"

Route15_Text_RonPostBattle::
    .string "RON: Oh, bleh…\n"
    .string "Quisiera tener una hermana amable…$"

Route15_Text_RonNotEnoughMons::
    .string "RON: ¿Quieres luchar con mi\n"
    .string "hermana y conmigo?\p"
    .string "Entonces necesitas dos POKéMON.$"
