CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor::
    .string "¡Bienvenid{OA}!\p"
    .string "Puedes cambiar tus MONEDAS por\n"
    .string "fabulosos premios al lado.$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins::
    .string "¡Bienvenid{OA} a la SALA DE JUEGOS\n"
    .string "ROCKET!\p"
    .string "¿Necesitas MONEDAS del juego?\n"
    .string "¿Te gustaría comprar algunas?$"

CeladonCity_GameCorner_Text_ComePlaySometime::
    .string "¿No?\n"
    .string "¡Por favor, ven a jugar luego!$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase::
    .string "Oh, lo siento.\n"
    .string "No tienes un MONEDERO.$"

CeladonCity_GameCorner_Text_CoinCaseIsFull::
    .string "¡Wups!\n"
    .string "Tu MONEDERO está lleno.$"

CeladonCity_GameCorner_Text_CantAffordCoins::
    .string "No puedes costear las MONEDAS.$"

CeladonCity_GameCorner_Text_HereAreYourCoins::
    .string "Gracias.\n"
    .string "¡Aquí están tus MONEDAS!$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace::
    .string "Guárdame un secreto.\p"
    .string "Se rumorea que este lugar es\n"
    .string "manejado por el EQUIPO ROCKET.$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds::
    .string "Creo que estas máquinas tienen\n"
    .string "probabilidades distintas de ganar.$"

CeladonCity_GameCorner_Text_DoYouWantToPlay::
    .string "¿Niñ{OA}, quieres jugar?$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan::
    .string "{PLAYER} recibió 10 MONEDAS\n"
    .string "del hombre.$"

CeladonCity_GameCorner_Text_DontNeedMyCoins::
    .string "¡No necesitas mis MONEDAS!$"

CeladonCity_GameCorner_Text_WinsComeAndGo::
    .string "Las victorias vienen y van.\n"
    .string "Nada está asegurado.$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck::
    .string "Estos juegos de azar…\n"
    .string "Ganar o perder, es solo suerte.$"

CeladonCity_GameCorner_Text_GymGuyAdvice::
    .string "¡Ey!\p"
    .string "¡Tienes mejores cosas que hacer,\n"
    .string "futur{OA} campe{ONONA}!\p"
    .string "ERIKA lidera el GIMNASIO PRISMA.\p"
    .string "Es una usuaria de POKéMON tipo\n"
    .string "PLANTA, unida a la naturaleza.\p"
    .string "Puede parecer dócil debido a\n"
    .string "su arreglo floral…\p"
    .string "¡Pero no es alguien que debas\n"
    .string "tomar a la ligera!$"

CeladonCity_GameCorner_Text_RareMonsForCoins::
    .string "Aquí ofrecen POKéMON raros que\n"
    .string "te dan a cambio de tus MONEDAS.\p"
    .string "¡Pero no logro ganar!$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked::
    .string "¡Los juegos son aterradores!\n"
    .string "¡Engancharse a ellos es muy fácil!$"

CeladonCity_GameCorner_Text_WantSomeCoins::
    .string "¿Que pasa?\n"
    .string "¿Quieres algunas MONEDAS?$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy::
    .string "{PLAYER} recibió 20 MONEDAS\n"
    .string "del buen tipo.$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins::
    .string "¡Tienes muchas MONEDAS!$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant::
    .string "¡Rayos! ¡necesito más MONEDAS para\n"
    .string "el POKéMON que quiero!$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo::
    .string "¿Ey, qué? ¡me desconcentras!\n"
    .string "¡Aquí hay unas MONEDAS, así que shu!$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan::
    .string "{PLAYER} recibió 20 MONEDAS\n"
    .string "del hombre.$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins::
    .string "¡Ya tienes muchas MONEDAS propias!$"

CeladonCity_GameCorner_Text_WatchReelsClosely::
    .string "Es truco está en mirar las\n"
    .string "pantallas de cerca.$"

CeladonCity_GameCorner_Text_GruntIntro::
    .string "¡Vigilo este cartel!\n"
    .string "¡Lárgate, o verás!$"

CeladonCity_GameCorner_Text_GruntDefeat::
    .string "¡Demonios!$"

CeladonCity_GameCorner_Text_GruntPostBattle::
    .string "¡Puede que la GUARIDA del EQUIPO\n"
    .string "ROCKET sea descubierta!\p"
    .string "¡Debo decírselo al JEFE!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt::
    .string "¡Ey!\p"
    .string "¡¿Un interruptor bajo el cartel!?\n"
    .string "¡A presionarlo!$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired::
    .string "Se requiere un MONEDERO…$"

CeladonCity_GameCorner_Text_DontHaveCoinCase::
    .string "¡Ups!\n"
    .string "¡No tienes el MONEDERO!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay::
    .string "¡Una máquina tragamonedas!\n"
    .string "¿Quieres jugar?$"

CeladonCity_GameCorner_Text_OutOfOrder::
    .string "FUERA DE SERVICIO\n"
    .string "Está rota.$"

CeladonCity_GameCorner_Text_OutToLunch::
    .string "SALÍ A COMER\n"
    .string "Esta está reservada.$"

CeladonCity_GameCorner_Text_SomeonesKeys::
    .string "¡Las llaves de alguien!\n"
    .string "Volverán por ellas.$"

