CinnabarIsland_Text_DoorIsLocked::
    .string "La puerta está cerrada…$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab::
    .string "BLAINE, del GIMNASIO de CANELA,\n"
    .string "es un tipo bastante raro.\p"
    .string "Vive en la isla desde antes de que\n"
    .string "se construyera el LABORATORIO.$"

CinnabarIsland_Text_ScientistsExperimentInMansion::
    .string "Hay cientificos que experimentan\n"
    .string "en el edificio quemado.\p"
    .string "Ya sabes, ese que llaman\n"
    .string "MANSIÓN POKéMON.$"

CinnabarIsland_Text_IslandSign::
    .string "ISLA CANELA\n"
    .string "El feroz pueblo del ardiente deseo$"

CinnabarIsland_Text_PokemonLab::
    .string "LABORATORIO POKéMON$"

CinnabarIsland_Text_GymSign::
    .string "GIMNASIO POKéMON DE ISLA CANELA\n"
    .string "LÍDER: BLAINE\l"
    .string "¡Exaltado maestro de los acertijos!$"

CinnabarIsland_Text_HeyIfItIsntPlayer::
    .string "¿Uh?\n"
    .string "¡Ey, si eres {PLAYER}!$"

CinnabarIsland_Text_ComeWithMeToOneIsland::
    .string "Soy yo, BILL.\n"
    .string "¡Cuanto tiempo sin vernos!\p"
    .string "Espero que sigas usando mi sistema\n"
    .string "para PC.\p"
    .string "Bueno, ya que nos estamos aquí,\n"
    .string "¿qué tal si pasas un rato conmigo?\p"
    .string "Hay una pequeña isla hacia el sur\n"
    .string "llamada ISLA PRIMA.\p"
    .string "Un amigo me invitó a ir, así que\n"
    .string "estoy por partir.\p"
    .string "¿Qué te parece?\n"
    .string "¿Quieres ir conmigo?$"

CinnabarIsland_Text_AllRightLetsGo::
    .string "De acuerdo.\n"
    .string "¡Vamos!$"

CinnabarIsland_Text_IllBeWaitingInPokeCenter::
    .string "¿Qué, estas muy ocupad{OA}?\p"
    .string "Bueno, está bien.\n"
    .string "El bote no ha llegado aún.\p"
    .string "Estaré esperando en el\n"
    .string "CENTRO POKéMON de ahí.\p"
    .string "Ven a verme cuando termines con\n"
    .string "tus asuntos.$"

CinnabarIsland_Text_MyPalsBoatArrived::
    .string "Parece que el bote de mi amigo\n"
    .string "también llegó.\p"
    .string "Él lo envió especialmente a CANELA\n"
    .string "para recogerme.$"

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain::
    .string "Ey, ¿no fue ese un viaje largo?\p"
    .string "Parece que mi compañero, CELIO,\n"
    .string "disfrutó de tu compañia.\p"
    .string "Estoy seguro de que te dará la\n"
    .string "bienvenida si lo visitas otra vez.\p"
    .string "Si tienes un TRI-PASE, puedes\n"
    .string "subirte a un transbordador en\l"
    .string "el PUERTO CARMÍN cuando quieras.\p"
    .string "¡Bien, gracias por tu compañia!$"

