CinnabarIsland_Text_DoorIsLocked::
    .string "La puerta está cerrada…$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab::
    .string "BLAINE, del GIMNASIO de CANELA,\n"
    .string "es un tipo bastante raro.\p"
    .string "Vive en la isla desde antes de que\n"
    .string "se construyera el LABORATORIO.$"

CinnabarIsland_Text_ScientistsExperimentInMansion::
    .string "Hay cientificos que experimentan\n"
    .string "en el edificio quemado.\p"
    .string "Ya sabes, ese que llaman\n"
    .string "MANSIÓN POKéMON.$"

CinnabarIsland_Text_IslandSign::
    .string "ISLA CANELA\n"
    .string "El feroz pueblo del ardiente deseo$"

CinnabarIsland_Text_PokemonLab::
    .string "LABORATORIO POKéMON$"

CinnabarIsland_Text_GymSign::
    .string "GIMNASIO POKéMON DE ISLA CANELA\n"
    .string "LÍDER: BLAINE\l"
    .string "¡Exaltado maestro de los acertijos!$"

CinnabarIsland_Text_HeyIfItIsntPlayer::
    .string "Huh?\n"
    .string "Hey, if it isn't {PLAYER}!$"

CinnabarIsland_Text_ComeWithMeToOneIsland::
    .string "Look, it's me, BILL.\n"
    .string "Long time no see!\p"
    .string "I hope you're still using my\n"
    .string "PC system.\p"
    .string "Well, listen, since we met up here,\n"
    .string "how about spending time with me?\p"
    .string "There's this little island in the far\n"
    .string "south called ONE ISLAND.\p"
    .string "A friend invited me, so I'm on my\n"
    .string "way out there.\p"
    .string "How about it?\n"
    .string "Do you feel like coming with me?$"

CinnabarIsland_Text_AllRightLetsGo::
    .string "All right, then.\n"
    .string "Let's go!$"

CinnabarIsland_Text_IllBeWaitingInPokeCenter::
    .string "What, are you too busy?\p"
    .string "Well, all right.\n"
    .string "The boat hasn't arrived yet anyway.\p"
    .string "I'll be waiting at the POKéMON\n"
    .string "CENTER over there.\p"
    .string "Come see me when you're done with\n"
    .string "your business here.$"

CinnabarIsland_Text_MyPalsBoatArrived::
    .string "Looks like my pal's boat arrived,\n"
    .string "too.\p"
    .string "He sent it specially here to\n"
    .string "CINNABAR to pick me up.$"

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain::
    .string "Hey, wasn't that a long cruise?\p"
    .string "My buddy CELIO seemed to enjoy\n"
    .string "your company.\p"
    .string "I'm sure he'd welcome you if you\n"
    .string "were to visit him again.\p"
    .string "If you have a TRI-PASS, you can\n"
    .string "always take a ferry there from\l"
    .string "VERMILION PORT.\p"
    .string "All right, thanks for your company!$"

