OneIsland_KindleRoad_EmberSpa_Text_WaterWarmsMeToCore::
    .string "¡Hm!\n"
    .string "¡Jaaaaaaaaaaah!\p"
    .string "¡Aaaah! ¡esto es divino!\n"
    .string "¡El agua me calienta por completo!\p"
    .string "Deberías entrar, también.\p"
    .string "Entra, relajate, ¡y disfruta del\n"
    .string "calor!$"

OneIsland_KindleRoad_EmberSpa_Text_EnjoyBowlOfChowder::
    .string "Mi parte favorita del baño viene\n"
    .string "después de esto.\p"
    .string "¡Disfruto de un plato de sopa\n"
    .string "de pescado para estar caliente\l"
    .string "por dentro, también!$"

OneIsland_KindleRoad_EmberSpa_Text_WaterExquisiteFullyRefreshed::
    .string "El agua está perfectamente cálida.\n"
    .string "Se siente maravillosa…\p"
    .string "¡{PLAYER} y sus POKéMON\n"
    .string "se curaron por completo!$"

OneIsland_KindleRoad_EmberSpa_Text_HotSpringIsTherapeutic::
    .string "La gente dice que los baños en\n"
    .string "aguas termales son terapéuticos.$"

OneIsland_KindleRoad_EmberSpa_Text_SeeHowSmoothMySkinIs::
    .string "Dale un vistazo a mi cara.\n"
    .string "¿Ves lo suave que es mi piel?\p"
    .string "Las aguas termales mantienen\n"
    .string "mi piel joven.$"

OneIsland_KindleRoad_EmberSpa_Text_BrunoVisitsSpaOnOccasion::
    .string "Después de un día de duro\n"
    .string "entrenamiento, no hay nada como\l"
    .string "un baño en las aguas termales.\p"
    .string "BRUNO, que es superior a mí,\n"
    .string "visita el SPA ocasionalmente.\p"
    .string "Viene para rehabilitación, tanto\n"
    .string "para él como para sus POKéMON.$"

OneIsland_KindleRoad_EmberSpa_Text_UsedThisToMakeEmberSpa::
    .string "Las aguas termales tienen una\n"
    .string "relación estrecha con los volcanes.\p"
    .string "Este SPA BRASAS, bueno, lo hice\n"
    .string "hace años.\p"
    .string "Tallé la piscina directo de\n"
    .string "una roca gigante a mano.\p"
    .string "Estaba usando esto en ese tiempo.\n"
    .string "Supongo que puedo dejarlo ir.$"

OneIsland_KindleRoad_EmberSpa_Text_ExplainHM06::
    .string "Eso destroza rocas como si fueran\n"
    .string "galletas.$"
