SilphCo_6F_Text_RocketsTookOverBuilding::
    .string "¡Los ROCKET llegaron y se\n"
    .string "apoderaron del edificio!$"

SilphCo_6F_Text_BetterGetBackToWork::
    .string "Bueno, mejor vuelvo a trabajar.$"

SilphCo_6F_Text_HelpMePlease::
    .string "Oh querida, querida.\n"
    .string "¡Ayúdame, por favor!$"

SilphCo_6F_Text_WeGotEngaged::
    .string "Estamos comprometidos.\n"
    .string "¡Jeje!$"

SilphCo_6F_Text_ThatManIsSuchACoward::
    .string "Este hombre a mi lado…\n"
    .string "¡Es un cobarde!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim::
    .string "Es tan indefenso, que necesita\n"
    .string "a alguien como yo que lo cuide.$"

SilphCo_6F_Text_RocketsTryingToConquerWorld::
    .string "El EQUIPO ROCKET intenta\n"
    .string "conquistar al mundo con POKéMON.$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
    .string "¡El EQUIPO ROCKET escapó, y todo\n"
    .string "es gracias a ti!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
    .string "Debieron haber elegido a SILPH por\n"
    .string "nuestros productos POKéMON.$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
    .string "Ven a trabajar para SILPH cuando\n"
    .string "crezcas.$"

SilphCo_6F_Text_Grunt1Intro::
    .string "¡Soy uno de los cuatro HERMANOS\n"
    .string "ROCKET!$"

SilphCo_6F_Text_Grunt1Defeat::
    .string "¡Fracasé!$"

SilphCo_6F_Text_Grunt1PostBattle::
    .string "¡No importa!\n"
    .string "¡Mis hermanos me vengarán!$"

SilphCo_6F_Text_TaylorIntro::
    .string "¡Ese podrido PRESIDENTE!\p"
    .string "¡Se lo merece por enviarme a la\n"
    .string "SUCURSAL TIKSI!\p"
    .string "¡Es por eso que el EQUIPO ROCKET\n"
    .string "vino tras nosotros, estoy seguro!$"

SilphCo_6F_Text_TaylorDefeat::
    .string "¡Rayos!$"

SilphCo_6F_Text_TaylorPostBattle::
    .string "¿La SUCURSAL TIKSI?\n"
    .string "¡Es una tierra de nadie en Rusia!$"

SilphCo_6F_Text_Grunt2Intro::
    .string "¿Traicionas al EQUIPO ROCKET?$"

SilphCo_6F_Text_Grunt2Defeat::
    .string "¡Traidor{OA}!$"

SilphCo_6F_Text_Grunt2PostBattle::
    .string "¡Si apoyas la justicia, nos\n"
    .string "traicionas a nosotros, los malos!$"

SilphCo_6F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P6$"

