ThreeIsland_House2_Text_CantMakeThisSpoonBend::
    .string "Urrrrrrrrgggghhhh…\n"
    .string "¡Fwaaaaah!\p"
    .string "…¡Es inútil! no puedo doblar esta\n"
    .string "cuchara con mi mente.\p"
    .string "Puede que en realidad no tenga\n"
    .string "poderes psíquicos.$"

ThreeIsland_House2_Text_IAdmireSabrina::
    .string "¿Conoces a una chica LÍDER\n"
    .string "de GIMNASIO en CIUDAD AZAFRÁN?\p"
    .string "Usa POKéMON del tipo PSÍQUICO,\n"
    .string "¿verdad?\p"
    .string "Yo la admiro, realmente la admiro.\p"
    .string "Escuché que es buena cliente y\n"
    .string "además, hermosa.$"

