FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon::
    .string "No puedes ser un{A} gran ENTRENADOR{AM}\n"
    .string "con solo un POKéMON fuerte.\p"
    .string "Aunque criar muchos POKéMON por\n"
    .string "igual tampoco es fácil.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian::
    .string "Hay un camino estrecho al oeste\n"
    .string "de CIUDAD VERDE.\p"
    .string "Lleva al SC de la LIGA POKéMON.\p"
    .string "La SEDE CENTRAL gobierna a\n"
    .string "todos los ENTRENADORES.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex::
    .string "Si trabajas en una POKéDEX,\n"
    .string "visita la ZONA SAFARI.\p"
    .string "Se crían todo tipo de POKéMON\n"
    .string "raros allí.$"

