CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons:: @ 8191FFB
    .string "¡Ese BILL!\p"
    .string "He oído que haría lo que fuera\n"
    .string "para obtener POKéMON raros.\p"
    .string "Escuche que no le molesta hacer\n"
    .string "todo tipo de cosas.$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac:: @ 8192079
    .string "¿Has escuchado sobre BILL?\p"
    .string "¡Todos lo llaman POKéMANÍACO!\p"
    .string "Aunque, creo que la gente solo\n"
    .string "tiene celos de BILL.\p"
    .string "¿Quién no querría presumir sobre\n"
    .string "sus POKéMON?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons:: @ 8192116
    .string "¡BILL tiene montones de POKéMON!\n"
    .string "¡También colecciona a los raros!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs:: @ 819214C
    .string "¿Porque no vas arriba a\n"
    .string "intercambiar POKéMON con amigos?\p"
    .string "Podrías tener mucha más variedad\n"
    .string "al intercambiar.\p"
    .string "Además, los POKéMON obtenidos por\n"
    .string "intercambio crecen rápidamente.$"

