SaffronCity_Text_WhatDoYouWantGetLost::
    .string "¿Qué es lo que quieres?\n"
    .string "¡Piérdete!$"

SaffronCity_Text_BossTakeTownForTeamRocket::
    .string "¡El JEFE dijo que tomará este\n"
    .string "lugar en nombre del EQUIPO ROCKET!$"

SaffronCity_Text_DontGetDefiantOrIllHurtYou::
    .string "¡No te hagas {ELLA} rebelde!\n"
    .string "¡O tendré que lastimarte!$"

SaffronCity_Text_SaffronBelongsToTeamRocket::
    .string "¡AZAFRÁN pertenece a los ROCKET!$"

SaffronCity_Text_CriminalLifeMakesMeFeelAlive::
    .string "¡Mi vida como criminal me hace\n"
    .string "sentir tan vivo!$"

SaffronCity_Text_WatchWhereYoureWalking::
    .string "¡Auch!\n"
    .string "¡Mira por dónde caminas!$"

SaffronCity_Text_WeCanExploitMonsAroundWorld::
    .string "¡Con SILPH bajo control, podemos\n"
    .string "explotar POKéMON en todo el mundo!\p"
    .string "¡Seremos súper ricos, yiajaja!$"

SaffronCity_Text_YouBeatTeamRocket::
    .string "¿Venciste al EQUIPO ROCKET sol{OA}?\n"
    .string "¡Eso es increíble!$"

SaffronCity_Text_SafeToGoOutAgain::
    .string "¡Sí! ¡el EQUIPO ROCKET se fue!\n"
    .string "¡Salir es seguro de nuevo!$"

SaffronCity_Text_PeopleComingBackToSaffron::
    .string "La gente huyó en masa cuando\n"
    .string "llegaron los ROCKET.\p"
    .string "Deberían estar por volver a\n"
    .string "AZAFRÁN.$"

SaffronCity_Text_FlewHereOnPidgeot::
    .string "Volé aquí en mi PIDGEOT cuando leí\n"
    .string "lo de SILPH.\p"
    .string "¿Qué ya se acabó?\n"
    .string "Me perdí la acción…$"

SaffronCity_Text_Pidgeot::
    .string "PIDGEOT: ¡Bi bibii!$"

SaffronCity_Text_SawRocketBossEscaping::
    .string "Ví al JEFE de los ROCKET escapar\n"
    .string "del edificio de SILPH.$"

SaffronCity_Text_ImASecurityGuard::
    .string "Soy un guardia de seguridad.\p"
    .string "¡No doy pase a niños sospechosos!$"

SaffronCity_Text_HesTakingASnooze::
    .string "…\n"
    .string "Ronquido…\p"
    .string "¡Ah! ¡está tomando una siesta!$"

SaffronCity_Text_CitySign::
    .string "CIUDAD AZAFRÁN\n"
    .string "La brillante tierra dorada del\l"
    .string "comercio.$"

SaffronCity_Text_FightingDojo::
    .string "DOJO DE PELEA$"

SaffronCity_Text_GymSign::
    .string "GIMNASIO POKéMON de CIUDAD AZAFRÁN\n"
    .string "LÍDER: SABRINA\l"
    .string "¡Maestra de los POKéMON PSÍQUICOS!$"

SaffronCity_Text_FullHealCuresStatus::
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "CURA TOTAL soluciona males como\n"
    .string "quemaduras, parálisis, sueño,\l"
    .string "congelamiento, y envenenamiento.\p"
    .string "Es un poco cara, pero conviene\n"
    .string "más que comprar otros objetos.$"

SaffronCity_Text_GreatBallImprovedCatchRate::
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "La nueva SÚPERBOLA ofrece una tasa\n"
    .string "de captura mejorada.\p"
    .string "Pruébala en esos POKéMON difíciles\n"
    .string "de atrapar.$"

SaffronCity_Text_SilphCoSign::
    .string "EDIFICIO DE OFICINAS DE SILPH S.A.$"

SaffronCity_Text_MrPsychicsHouse::
    .string "CASA DEL SEÑOR PSÍQUICO$"

SaffronCity_Text_SilphsLatestProduct::
    .string "¡Lo último de SILPH!\n"
    .string "Lanzamiento indeterminado…$"

SaffronCity_Text_TrainerFanClubSign::
    .string "CLUB DE FANS DE ENTRENADORES\n"
    .string "POKéMON\p"
    .string "En este cartel hay garabateados\n"
    .string "muchos nombres de ENTRENADORES.$"

SaffronCity_Text_HowCanClubNotRecognizeLance::
    .string "Este CLUB DE FANS…\n"
    .string "¡Nadie ahí tiene idea de nada!\p"
    .string "¿Cómo es que no pueden reconocer\n"
    .string "lo brillante que es LANCE?\p"
    .string "¡Él representa la justicia!\n"
    .string "¡Es genial, y también apasionado!\l"
    .string "¡Es el mejor, LANCE!$"
