TwoIsland_Text_IslandSign::
    .string "ISLA SECUNDA\n"
    .string "Isla ideal para dos$"

TwoIsland_Text_JoyfulGameCornerSign::
    .string "¡Salta y muerde!\n"
    .string "SALA DE JUEGOS ALEGRE$"

TwoIsland_Text_DangerFastCurrent::
    .string "¡PELIGRO! ¡CORRIENTE RÁPIDA!\n"
    .string "¡Prohibido pescar y surfear!$"

TwoIsland_Text_WelcomeToShopMerchandiseLimited::
    .string "¡Oh!\n"
    .string "Hola, ¡bienvenid{OA} a mi tienda!\p"
    .string "La abrimos recientemente.\p"
    .string "Nuestra mercancía es limitada,\n"
    .string "pero espero que te pueda ser útil.$"

TwoIsland_Text_AddedMerchandiseForLostelle::
    .string "No puedo decir lo agradecido que\n"
    .string "estoy por tu rescate de LOSTELLE.\p"
    .string "Gracias a tu hazaña, la gente de\n"
    .string "ISLA TERA ha cambiado su actitud\l"
    .string "con a la gente de KANTO.\p"
    .string "Y, verás, yo soy de KANTO.\p"
    .string "La gente de ISLA TERA me ayudó a\n"
    .string "aumentar mi mercancía.$"

TwoIsland_Text_HopeYouGiveItYourBest::
    .string "¡Hola! estoy dando lo mejor de\n"
    .string "mi mismo aquí.\p"
    .string "Espero que tu hagas lo mismo,\n"
    .string "{PLAYER}.$"

TwoIsland_Text_BringingItemsFromDistantLands::
    .string "¡Oh, hola, {PLAYER}!\n"
    .string "¡Bienvenid{OA}!\p"
    .string "Empecé a traer objetos de tierras\n"
    .string "distantes.\p"
    .string "También tengo algunos objetos\n"
    .string "raros.\p"
    .string "Por favor, ¡ten un vistazo!$"

TwoIsland_Text_FellowMovedFromCeladonCity::
    .string "Ese tipo de ahí, se mudó desde\n"
    .string "CIUDAD PRISMA.\p"
    .string "Inició una tienda con su hermano\n"
    .string "menor.\p"
    .string "Me pregunto si sabía en que se\n"
    .string "estaba metiendo.$"

TwoIsland_Text_ShopkeepersBrotherWorksGameCorner::
    .string "El hermano del tendero tomó un\n"
    .string "trabajo en la SALA DE JUEGOS.\p"
    .string "Intenta juntar dinero para que\n"
    .string "puedan comprar más mercancía.$"

TwoIsland_Text_BrunoCameToIslandWhileBack::
    .string "Oye, oye.\n"
    .string "¿Sabes una cosa?\p"
    .string "Un ENTRENADOR famoso vino a la\n"
    .string "ISLA hace poco.\p"
    .string "Era un miembro del ALTO MANDO.\n"
    .string "Se llama BRUNO.\p"
    .string "Se fue decepcionado cuando se\n"
    .string "enteró que ya no quedaban\l"
    .string "Pasteles de Furia.$"

TwoIsland_Text_BuyRareItemsHere::
    .string "¡Los ENTRENADORES expertos compran\n"
    .string "objetos extraños aquí!$"

TwoIsland_Text_OldWomanLivesOutOnCape::
    .string "Hay una señora mayor que vive en\n"
    .string "una cabaña en el cabo.\p"
    .string "Mira fijamente a los POKéMON.\n"
    .string "Es algo inquietante.$"

TwoIsland_Text_HaveYouTriedJumpingGame::
    .string "¡Boing! ¡boing!\n"
    .string "¿Has probado el juego de saltos?\p"
    .string "Los POKéMON que pueden participar…\n"
    .string "¡Boing!\p"
    .string "¡Algunos hacen boing!\p"
    .string "¡Y algunos hacen boooooooing!\p"
    .string "¿Sabías eso?\n"
    .string "¡Boing!$"

