TwoIsland_PokemonCenter_1F_Text_HaveYouVisitedGameCorner::
    .string "¿Ya visitaste la SALA DE JUEGOS?\p"
    .string "No sirve ir solo.\n"
    .string "Tienes que llevar a un amigo.$"

TwoIsland_PokemonCenter_1F_Text_OldLadyLivesOutOnCape::
    .string "No muchas personas viven en\n"
    .string "ISLA SECUNDA.\p"
    .string "Hay una señora mayor que vive en\n"
    .string "una cabaña.\p"
    .string "No sé cuanto tiempo lleva viviendo\n"
    .string "ahí.$"

