Aide_EventScript_HaventCaughtEnough::
	msgbox Aide_Text_HaventCaughtEnoughMonsForItem
	release
	end

Aide_EventScript_NoRoomForItem::
	msgbox Aide_Text_DontHaveAnyRoomForItem
	release
	end

Aide_EventScript_DeclineCheckMons::
	msgbox Aide_Text_GetEnoughMonsComeBackForItem
	release
	end


Aide_EventScript_HaventCaughtEnough_Exp::
	msgbox Aide_Text_HaventCaughtEnoughMonsForItem_Exp
	release
	end

Aide_EventScript_NoRoomForItem_Exp::
	msgbox Aide_Text_DontHaveAnyRoomForItem_Exp
	release
	end

Aide_EventScript_DeclineCheckMons_Exp::
	msgbox Aide_Text_GetEnoughMonsComeBackForItem_Exp
	release
	end
