Route16_Text_LaoIntro::
    .string "¿Qué es lo que quieres?$"

Route16_Text_LaoDefeat::
    .string "¡No te atrevas a reírte!$"

Route16_Text_LaoPostBattle::
    .string "Solo nos gusta estar aquí.\n"
    .string "¿A ti qué te pasa?$"

Route16_Text_KojiIntro::
    .string "¡Bonita BICICLETA!\n"
    .string "¡Dámela!$"

Route16_Text_KojiDefeat::
    .string "¡Fuera de combate!$"

Route16_Text_KojiPostBattle::
    .string "¡Olvídalo, nadie necesita tu BICI!$"

Route16_Text_LukeIntro::
    .string "¡Ven y sal a jugar, ratoncit{OA}!$"

Route16_Text_LukeDefeat::
    .string "¡Pequeña rata!$"

Route16_Text_LukePostBattle::
    .string "¡Odio perder!\n"
    .string "¡Sal de mi vista!$"

Route16_Text_HideoIntro::
    .string "¡Oye, chocaste conmigo!$"

Route16_Text_HideoDefeat::
    .string "¡Kabum!$"

Route16_Text_HideoPostBattle::
    .string "Siempre estaremos por aquí incluso\n"
    .string "si no te gusta.\p"
    .string "También puedes llegar a FUCSIA\n"
    .string "desde CARMÍN, yendo por la costa.$"

Route16_Text_CamronIntro::
    .string "¡Me siento hambriento y rudo!\n"
    .string "¡Necesito un saco de boxeo!$"

Route16_Text_CamronDefeat::
    .string "¡Mal, mal, mal!$"

Route16_Text_CamronPostBattle::
    .string "Si voy a tener POKéMON, lo mejor\n"
    .string "es que sean feroces.\p"
    .string "Los usaría para hacer trizas a mis\n"
    .string "enemigos.$"

Route16_Text_RubenIntro::
    .string "¡Ey, tú!\n"
    .string "¡Pasemos un buen rato!$"

Route16_Text_RubenDefeat::
    .string "¡No me hagas enojar!$"

Route16_Text_RubenPostBattle::
    .string "Disfruto el acosar personas con\n"
    .string "mis POKéMON apestosos.\p"
    .string "Son buenos para sobresaltar gente.\n"
    .string "Y también muerden.$"

Route16_Text_MonSprawledOutInSlumber::
    .string "Un POKéMON está tumbado en un\n"
    .string "cómodo y profundo sueño.$"

Route16_Text_CyclingRoadSign::
    .string "¡Disfruta el descenso!\n"
    .string "CICLOVÍA$"

Route16_Text_RouteSign::
    .string "RUTA 16\n"
    .string "CIUDAD PRISMA - CIUDAD FUCSIA$"

Route16_Text_JedIntro::
    .string "JED: Nuestro amor no conoce\n"
    .string "barreras.\p"
    .string "¡Estamos enamorados y lo\n"
    .string "demostramos!$"

Route16_Text_JedDefeat::
    .string "JED: ¡Oh, no!\n"
    .string "¡Mi amor me vió como un perdedor!$"

Route16_Text_JedPostBattle::
    .string "JED: Escucha, LEA.\n"
    .string "Necesitas enfocarte menos en mí.$"

Route16_Text_JedNotEnoughMons::
    .string "JED: ¿Solo tienes un POKéMON?\n"
    .string "¿Acaso no hay amor en tu corazón?$"

Route16_Text_LeaIntro::
    .string "LEA: A veces, la intensidad de\n"
    .string "nuestro amor me asusta.$"

Route16_Text_LeaDefeat::
    .string "LEA: ¡Ohh! ¡pero JED se ve genial\n"
    .string "incluso al perder!$"

Route16_Text_LeaPostBattle::
    .string "LEA: Ejeje, lo siento.\n"
    .string "JED es tan genial.$"

Route16_Text_LeaNotEnoughMons::
    .string "LEA: Oh, ¿no tienes dos POKéMON\n"
    .string "contigo?\p"
    .string "¿No se sienten solitarios tú o\n"
    .string "tu POKéMON?$"
