Route16_Text_LaoIntro::
    .string "What do you want?$"

Route16_Text_LaoDefeat::
    .string "Don't you dare laugh!$"

Route16_Text_LaoPostBattle::
    .string "We like just hanging here.\n"
    .string "What's it to you?$"

Route16_Text_KojiIntro::
    .string "Nice BIKE!\n"
    .string "Hand it over!$"

Route16_Text_KojiDefeat::
    .string "Knockout!$"

Route16_Text_KojiPostBattle::
    .string "Forget it, who needs your BIKE!$"

Route16_Text_LukeIntro::
    .string "Come out and play, little mouse!$"

Route16_Text_LukeDefeat::
    .string "You little rat!$"

Route16_Text_LukePostBattle::
    .string "I hate losing!\n"
    .string "Get out of my face!$"

Route16_Text_HideoIntro::
    .string "Hey, you just bumped me!$"

Route16_Text_HideoDefeat::
    .string "Kaboom!$"

Route16_Text_HideoPostBattle::
    .string "We'll always be hanging around here\n"
    .string "even if you don't like it.\p"
    .string "You can detour to VERMILION from\n"
    .string "FUCHSIA going along the coast.$"

Route16_Text_CamronIntro::
    .string "I'm feeling hungry and mean!\n"
    .string "I need a punching bag!$"

Route16_Text_CamronDefeat::
    .string "Bad, bad, bad!$"

Route16_Text_CamronPostBattle::
    .string "If I'm going to have POKéMON, they\n"
    .string "may as well be ferocious.\p"
    .string "I'd use them to leave my enemies\n"
    .string "in tatters.$"

Route16_Text_RubenIntro::
    .string "Hey, there!\n"
    .string "Let's have ourselves a good time!$"

Route16_Text_RubenDefeat::
    .string "Don't make me mad!$"

Route16_Text_RubenPostBattle::
    .string "I get my kicks by harassing people\n"
    .string "with my stinking POKéMON.\p"
    .string "They're great for startling people.\n"
    .string "And, they bite, too.$"

Route16_Text_MonSprawledOutInSlumber::
    .string "A POKéMON is sprawled out in\n"
    .string "a deep and comfortable slumber.$"

Route16_Text_CyclingRoadSign::
    .string "¡Disfruta el descenso!\n"
    .string "CICLOVÍA$"

Route16_Text_RouteSign::
    .string "RUTA 16\n"
    .string "CIUDAD PRISMA - CIUDAD FUCSIA$"

Route16_Text_JedIntro::
    .string "JED: Nuestro amor no conoce\n"
    .string "barreras.\p"
    .string "¡Estamos enamorados y lo\n"
    .string "demostramos!$"

Route16_Text_JedDefeat::
    .string "JED: ¡Oh, no!\n"
    .string "¡Mi amor me vió como un perdedor!$"

Route16_Text_JedPostBattle::
    .string "JED: Escucha, LEA.\n"
    .string "Necesitas enfocarte menos en mí.$"

Route16_Text_JedNotEnoughMons::
    .string "JED: ¿Solo tienes un POKéMON?\n"
    .string "¿Acaso no hay amor en tu corazón?$"

Route16_Text_LeaIntro::
    .string "LEA: A veces, la intensidad de\n"
    .string "nuestro amor me asusta.$"

Route16_Text_LeaDefeat::
    .string "LEA: ¡Ohh! ¡pero JED se ve genial\n"
    .string "incluso al perder!$"

Route16_Text_LeaPostBattle::
    .string "LEA: Ejeje, lo siento.\n"
    .string "JED es tan genial.$"

Route16_Text_LeaNotEnoughMons::
    .string "LEA: Oh, ¿no tienes dos POKéMON\n"
    .string "contigo?\p"
    .string "¿No se sienten solitarios tú o\n"
    .string "tu POKéMON?$"
