Route6_Text_RickyIntro::
    .string "¿Quién esta ahí?\n"
    .string "¡Deja de espiarnos!$"

Route6_Text_RickyDefeat::
    .string "¡No puedo ganar!$"

Route6_Text_RickyPostBattle::
    .string "Susurro…\n"
    .string "Susurro…$"

Route6_Text_NancyIntro::
    .string "¡Disculpa!\n"
    .string "¡Esta es una conversación privada!$"

Route6_Text_NancyDefeat::
    .string "¡Agh!\n"
    .string "Odio perder.$"

Route6_Text_NancyPostBattle::
    .string "Susurro…\n"
    .string "Susurro…$"

Route6_Text_KeigoIntro::
    .string "No hay muchos insectos por aquí.$"

Route6_Text_KeigoDefeat::
    .string "¡No!\n"
    .string "¡Estas bromeando!$"

Route6_Text_KeigoPostBattle::
    .string "Me gustan los insectos, así que\n"
    .string "voy a volver al BOSQUE VERDE.$"

Route6_Text_JeffIntro::
    .string "¿Uh?\n"
    .string "¿Quieres hablarme?$"

Route6_Text_JeffDefeat::
    .string "Esto apesta…\n"
    .string "No pude vencer tu desafío…$"

Route6_Text_JeffPostBattle::
    .string "Debería traer más POKéMON conmigo.\n"
    .string "Así me sentiré más seguro.$"

Route6_Text_IsabelleIntro::
    .string "¿Yo?\n"
    .string "Bueno, de acuerdo. ¡Jugaré!$"

Route6_Text_IsabelleDefeat::
    .string "Las cosas no funcionaron…$"

Route6_Text_IsabellePostBattle::
    .string "Quiero volverme más fuerte.\n"
    .string "¿Cuál es tu secreto?$"

Route6_Text_ElijahIntro::
    .string "Nunca te he visto por aquí.\n"
    .string "¿Eres buen{OA}?$"

Route6_Text_ElijahDefeat::
    .string "¡Eres demasiado buen{OA}!$"

Route6_Text_ElijahPostBattle::
    .string "¿Son mis POKéMON débiles?\n"
    .string "O, ¿solo soy malo?\l"
    .string "¿Tú que crees?$"

Route6_Text_UndergroundPathSign::
    .string "VÍA SUBTERRÁNEA\n"
    .string "CIUDAD CELESTE - CIUDAD CARMÍN$"

