Route6_Text_RickyIntro:: @ 8183E04
    .string "¿Quién esta ahí?\n"
    .string "¡Deja de espiarnos!$"

Route6_Text_RickyDefeat:: @ 8183E2A
    .string "¡No puedo ganar!$"

Route6_Text_RickyPostBattle:: @ 8183E3C
    .string "Susurro…\n"
    .string "Susurro…$"

Route6_Text_NancyIntro:: @ 8183E4E
    .string "¡Disculpa!\n"
    .string "¡Esta es una conversación privada!$"

Route6_Text_NancyDefeat:: @ 8183E79
    .string "¡Agh!\n"
    .string "Odio perder.$"

Route6_Text_NancyPostBattle:: @ 8183E8D
    .string "Susurro…\n"
    .string "Susurro…$"

Route6_Text_KeigoIntro:: @ 8183E9F
    .string "No hay muchos bichos por aquí.$"

Route6_Text_KeigoDefeat:: @ 8183EC0
    .string "¡No!\n"
    .string "¡Estas bromeando!$"

Route6_Text_KeigoPostBattle:: @ 8183ED4
    .string "Me gustan los bichos, así que voy\n"
    .string "a volver al BOSQUE VERDE.$"

Route6_Text_JeffIntro:: @ 8183F07
    .string "¿Uh?\n"
    .string "¿Quieres hablarme?$"

Route6_Text_JeffDefeat:: @ 8183F24
    .string "Esto apesta…\n"
    .string "No pude vencer tu desafío…$"

Route6_Text_JeffPostBattle:: @ 8183F51
    .string "Debería traer más POKéMON conmigo.\n"
    .string "Así me sentiré más seguro.$"

Route6_Text_IsabelleIntro:: @ 8183F90
    .string "¿Yo?\n"
    .string "Bueno, de acuerdo. ¡Jugaré!$"

Route6_Text_IsabelleDefeat:: @ 8183FAB
    .string "Las cosas no funcionaron…$"

Route6_Text_IsabellePostBattle:: @ 8183FC4
    .string "Quiero volverme más fuerte.\n"
    .string "¿Cuál es tu secreto?$"

Route6_Text_ElijahIntro:: @ 8183FF0
    .string "Nunca te he visto por aquí.\n"
    .string "¿Eres buen{OA}?$"

Route6_Text_ElijahDefeat:: @ 818401A
    .string "¡Eres demasiado buen{OA}!$"

Route6_Text_ElijahPostBattle:: @ 818402B
    .string "¿Son mis POKéMON débiles?\n"
    .string "O, ¿solo soy malo?\l"
    .string "¿Tú que crees?$"

Route6_Text_UndergroundPathSign:: @ 8184067
    .string "VÍA SUBTERRÁNEA\n"
    .string "CIUDAD CELESTE - CIUDAD CARMÍN$"

