CeruleanCity_House1_Text_BadgesHaveAmazingSecrets:: @ 81918E7
    .string "Solo los ENTRENADORES hábiles\n"
    .string "pueden reunir MEDALLAS POKéMON.\p"
    .string "Veo que al menos tienes una.\p"
    .string "Esas MEDALLAS tienen secretos\n"
    .string "increíbles, ¿lo sabías?$"

CeruleanCity_House1_Text_DescribeWhichBadge:: @ 8191967
    .string "Ahora…\p"
    .string "¿Cuál de las ocho MEDALLAS quieres\n"
    .string "que describa?$"

CeruleanCity_House1_Text_ComeVisitAnytime:: @ 819199E
    .string "Ven a visitarme cuando quieras.$"

CeruleanCity_House1_Text_AttackStatFlash:: @ 81919BE
    .string "El ATAQUE de todos tus POKéMON\n"
    .string "aumenta un poco.\p"
    .string "También te deja usar el movimiento\n"
    .string "DESTELLO fuera de las batallas.$"

CeruleanCity_House1_Text_ObeyLv30Cut:: @ 8191A31
    .string "Todos los POKéMON hasta de Nv. 30\n"
    .string "te obedecerán.\p"
    .string "Eso incluso incluye a los que\n"
    .string "obtengas en intercambios.\p"
    .string "Aunque los POKéMON de niveles más\n"
    .string "altos desobedecerán en batalla.\p"
    .string "También te deja usar el movimiento\n"
    .string "CORTE fuera de las batallas.$"

CeruleanCity_House1_Text_SpeedStatFly:: @ 8191AF9
    .string "La VELOCIDAD de todos tus POKéMON\n"
    .string "aumenta un poco.\p"
    .string "También te deja usar el movimiento\n"
    .string "VUELO fuera de las batallas.$"

CeruleanCity_House1_Text_ObeyLv50Strength:: @ 8191B69
    .string "Todos los POKéMON hasta de Nv. 50\n"
    .string "te obedecerán.\p"
    .string "Eso incluso incluye a los que\n"
    .string "obtengas en intercambios.\p"
    .string "Aunque los POKéMON de niveles más\n"
    .string "altos desobedecerán en batalla.\p"
    .string "También te deja usar el movimiento\n"
    .string "FUERZA fuera de las batallas.$"

CeruleanCity_House1_Text_DefenseStatSurf:: @ 8191C36
    .string "La DEFENSA de todos tus POKéMON\n"
    .string "aumenta un poco.\p"
    .string "También te deja usar el movimiento\n"
    .string "SURF fuera de las batallas.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash:: @ 8191CA9
    .string "Todos los POKéMON hasta de Nv. 70\n"
    .string "te obedecerán.\p"
    .string "Eso incluso incluye a los que\n"
    .string "obtengas en intercambios.\p"
    .string "Aunque los POKéMON de niveles más\n"
    .string "altos desobedecerán en batalla.\p"
    .string "También te deja usar el movimiento\n"
    .string "ROMPE ROCAS fuera de las batallas.$"

CeruleanCity_House1_Text_SpStatsWaterfall:: @ 8191D78
    .string "El ATQ. ESP y la DEF. ESP de todos\n"
    .string "tus POKéMON aumentan un poco.\p"
    .string "También te deja usar el movimiento\n"
    .string "CASCADA fuera de las batallas.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou:: @ 8191DF8
    .string "¡Todos los POKéMON te obedecerán!$"

