ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Puedes usar esa PC en la esquina\n"
    .string "tanto como quieras.\p"
    .string "Me lo dijo la recepcionista.\n"
    .string "¡Eso es muy amable de su parte!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "Hay un CENTRO POKéMON en todos\n"
    .string "los pueblos y ciudades.\p"
    .string "Todos son gratuitos, así que\n"
    .string "no temas curar a tus POKéMON.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "Los CENTROS POKéMON curan a tus\n"
    .string "POKéMON cansados, heridos\l"
    .string "o debilitados.\p"
    .string "Dejan a todos los POKéMON\n"
    .string "completamente sanos.$"
