Route3_Text_TunnelFromCeruleanTiring:: @ 8183491
    .string "Uff… Será mejor que descanse…\n"
    .string "Agh…\p"
    .string "¡Ese túnel desde CELESTE te quita\n"
    .string "mucha energía!$"

Route3_Text_ColtonIntro:: @ 81834E6
    .string "¡Hey!\n"
    .string "¡Te ví en el BOSQUE VERDE!$"

Route3_Text_ColtonDefeat:: @ 8183509
    .string "¡Me venciste otra vez!$"

Route3_Text_ColtonPostBattle:: @ 818351C
    .string "Hay otros tipos de POKéMON\n"
    .string "diferentes a los del bosque.$"

Route3_Text_BenIntro:: @ 8183560
    .string "¡Hola!\n"
    .string "¡Me gustan los pantalones cortos!\p"
    .string "¡Soy muy comodos y\n"
    .string "fáciles de usar!$"

Route3_Text_BenDefeat:: @ 81835A0
    .string "¡No lo puedo creer!$"

Route3_Text_BenPostBattle:: @ 81835B4
    .string "¿Estas usando la PC de un CENTRO\n"
    .string "POKéMON para guardar POKéMON?\p"
    .string "Cada CAJA puede guardar hasta\n"
    .string "30 POKéMON.$"

Route3_Text_JaniceIntro:: @ 8183616
    .string "¡Disculpa!\n"
    .string "¿Me miraste, ¿verdad?$"

Route3_Text_JaniceDefeat:: @ 818363F
    .string "¡Eres groser{OA}!$"

Route3_Text_JanicePostBattle:: @ 818364C
    .string "¡Deja de mirarme si no quieres\n"
    .string "una batalla!$"

Route3_Text_GregIntro:: @ 8183682
    .string "¿Eres un{A} ENTRENADOR{AM}?\n"
    .string "¡Luchemos de una vez!$"

Route3_Text_GregDefeat:: @ 81836B3
    .string "¡Si tuviera nuevos POKéMON\n"
    .string "te habría ganado!$"

Route3_Text_GregPostBattle:: @ 81836D9
    .string "¡Si una CAJA de POKéMON en la PC\n"
    .string "está llena, solo cambia de CAJA!$"

Route3_Text_SallyIntro:: @ 818371B
    .string "Esa mirada que me diste…\n"
    .string "¡Fue muy intrigante!$"

Route3_Text_SallyDefeat:: @ 8183746
    .string "¡Sé amable!$"

Route3_Text_SallyPostBattle:: @ 818374F
    .string "Puedes evitar batallas si evitas\n"
    .string "que otros ENTRENADORES te vean.$"

Route3_Text_CalvinIntro:: @ 8183786
    .string "¡Oye! ¡No llevas pantalón corto!\n"
    .string "¿Qué pasa contigo?$"

Route3_Text_CalvinDefeat:: @ 81837BD
    .string "¡Perdí!\n"
    .string "¡Perdí! ¡Perdí!$"

Route3_Text_CalvinPostBattle:: @ 81837CF
    .string "Siempre uso pantalones cortos,\n"
    .string "incluso en invierno.$"

Route3_Text_JamesIntro:: @ 8183807
    .string "Lucharas contra mis nuevos\n"
    .string "POKéMON.$"

Route3_Text_JamesDefeat:: @ 8183837
    .string "¡Estoy acabado!$"

Route3_Text_JamesPostBattle:: @ 8183849
    .string "Los POKéMON entrenados son más\n"
    .string "fuertes que los salvajes.$"

Route3_Text_RobinIntro:: @ 818387A
    .string "¡Ay!\n"
    .string "¿Me tocaste?$"

Route3_Text_RobinDefeat:: @ 8183891
    .string "¿Eso es todo?$"

Route3_Text_RobinPostBattle:: @ 818389C
    .string "La RUTA 4 está al pie del\n"
    .string "MONTE LUNA.$"

Route3_Text_RouteSign:: @ 81838C0
    .string "RUTA 3\n"
    .string "MONTE LUNA ADELANTE$"
