Route3_Text_TunnelFromCeruleanTiring::
    .string "Uff… Será mejor que descanse…\n"
    .string "Agh…\p"
    .string "¡Ese túnel desde CELESTE te quita\n"
    .string "mucha energía!$"

Route3_Text_ColtonIntro::
    .string "¡Hey!\n"
    .string "¡Te ví en el BOSQUE VERDE!$"

Route3_Text_ColtonDefeat::
    .string "¡Me venciste otra vez!$"

Route3_Text_ColtonPostBattle::
    .string "Hay otros tipos de POKéMON\n"
    .string "diferentes a los del bosque.$"

Route3_Text_BenIntro::
    .string "¡Hola!\n"
    .string "¡Me gustan los pantalones cortos!\p"
    .string "¡Soy muy comodos y\n"
    .string "fáciles de usar!$"

Route3_Text_BenDefeat::
    .string "¡No lo puedo creer!$"

Route3_Text_BenPostBattle::
    .string "¿Estas usando la PC de un CENTRO\n"
    .string "POKéMON para guardar POKéMON?\p"
    .string "Cada CAJA puede guardar hasta\n"
    .string "30 POKéMON.$"

Route3_Text_JaniceIntro::
    .string "¡Disculpa!\n"
    .string "¿Me miraste, ¿verdad?$"

Route3_Text_JaniceDefeat::
    .string "¡Eres groser{OA}!$"

Route3_Text_JanicePostBattle::
    .string "¡Deja de mirarme si no quieres\n"
    .string "una batalla!$"

Route3_Text_GregIntro::
    .string "¿Eres un{A} ENTRENADOR{AM}?\n"
    .string "¡Luchemos de una vez!$"

Route3_Text_GregDefeat::
    .string "¡Si tuviera nuevos POKéMON\n"
    .string "te habría ganado!$"

Route3_Text_GregPostBattle::
    .string "¡Si una CAJA de POKéMON en la PC\n"
    .string "está llena, solo cambia de CAJA!$"

Route3_Text_SallyIntro::
    .string "Esa mirada que me diste…\n"
    .string "¡Fue muy intrigante!$"

Route3_Text_SallyDefeat::
    .string "¡Sé amable!$"

Route3_Text_SallyPostBattle::
    .string "Puedes evitar batallas si evitas\n"
    .string "que otros ENTRENADORES te vean.$"

Route3_Text_CalvinIntro::
    .string "¡Oye! ¡No llevas pantalón corto!\n"
    .string "¿Qué pasa contigo?$"

Route3_Text_CalvinDefeat::
    .string "¡Perdí!\n"
    .string "¡Perdí! ¡Perdí!$"

Route3_Text_CalvinPostBattle::
    .string "Siempre uso pantalones cortos,\n"
    .string "incluso en invierno.$"

Route3_Text_JamesIntro::
    .string "Lucharas contra mis nuevos\n"
    .string "POKéMON.$"

Route3_Text_JamesDefeat:: @ 8183837
    .string "¡Estoy acabado!$"

Route3_Text_JamesPostBattle::
    .string "Los POKéMON entrenados son más\n"
    .string "fuertes que los salvajes.$"

Route3_Text_RobinIntro::
    .string "¡Ay!\n"
    .string "¿Me tocaste?$"

Route3_Text_RobinDefeat::
    .string "¿Eso es todo?$"

Route3_Text_RobinPostBattle::
    .string "La RUTA 4 está al pie del\n"
    .string "MONTE LUNA.$"

Route3_Text_RouteSign::
    .string "RUTA 3\n"
    .string "MONTE LUNA ADELANTE$"

