Text_DoubleEdgeTeach::
    .string "Deberías estar orgullos{OA} de ti\n"
    .string "mism{OA}, por abrirte paso por el\l"
    .string "CAMINO VICTORIA con tanta valentía.\p"
    .string "Como reconocimiento a tu hazaña,\n"
    .string "te enseñaré DOBLE FILO.\p"
    .string "¿Quieres aprender esa técnica?$"

Text_DoubleEdgeDeclined::
    .string "Te enseñaré la técnica cuando\n"
    .string "quieras.$"

Text_DoubleEdgeWhichMon::
    .string "¿A qué POKéMON le debería enseñar\n"
    .string "DOBLE FILO?$"

Text_DoubleEdgeTaught::
    .string "¡Sigue así cuando llegues a la\n"
    .string "LIGA POKéMON!\p"
    .string "¡Da tu mejor esfuerzo y acaba con\n"
    .string "ellos!$"

VictoryRoad_3F_Text_GeorgeIntro::
    .string "Escuché rumores de un{A} niñ{OA}\n"
    .string "prodigio.$"

VictoryRoad_3F_Text_GeorgeDefeat::
    .string "¡Los rumores eran ciertos!$"

VictoryRoad_3F_Text_GeorgePostBattle::
    .string "¿Entonces, tú derrotaste a\n"
    .string "GIOVANNI del EQUIPO ROCKET?$"

VictoryRoad_3F_Text_AlexaIntro::
    .string "Los ENTRENADORES viven para buscar\n"
    .string "oponentes fuertes.$"

VictoryRoad_3F_Text_AlexaDefeat::
    .string "¡Oh!\n"
    .string "¡Eres tan fuerte!$"

VictoryRoad_3F_Text_AlexaPostBattle::
    .string "Librar batallas duras te hará más\n"
    .string "fuerte.$"

VictoryRoad_3F_Text_CarolineIntro::
    .string "¡Te demostraré lo débil que eres\n"
    .string "en verdad!$"

VictoryRoad_3F_Text_CarolineDefeat::
    .string "¡Estoy furiosa!$"

VictoryRoad_3F_Text_CarolinePostBattle::
    .string "Solo demostré lo débil que soy\n"
    .string "en verdad…$"

VictoryRoad_3F_Text_ColbyIntro::
    .string "¡Solo los elegidos pueden pasar!$"

VictoryRoad_3F_Text_ColbyDefeat::
    .string "¡No puedo creerlo!$"

VictoryRoad_3F_Text_ColbyPostBattle::
    .string "Todos los ENTRENADORES que están\n"
    .string "aquí se dirigen a la LIGA POKéMON.\p"
    .string "No bajes la guardia.$"

VictoryRoad_3F_Text_RayIntro::
    .string "RAY: ¡Juntos, nosotros dos estamos\n"
    .string "destinados a la grandeza!$"

VictoryRoad_3F_Text_RayDefeat::
    .string "RAY: ¡Absurdo!\n"
    .string "¡Esto no puede ser verdad!$"

VictoryRoad_3F_Text_RayPostBattle::
    .string "RAY: Nos venciste.\n"
    .string "La grandeza se escapa…$"

VictoryRoad_3F_Text_RayNotEnoughMons::
    .string "RAY: Juntos, los dos tratamos de\n"
    .string "alcanzar la cima.\p"
    .string "Necesitamos que tengas dos POKéMON\n"
    .string "para que luches con nosotros.$"

VictoryRoad_3F_Text_TyraIntro::
    .string "TYRA: Intentamos convertirnos en\n"
    .string "campeones juntos.$"

VictoryRoad_3F_Text_TyraDefeat::
    .string "TYRA: Oh, pero…$"

VictoryRoad_3F_Text_TyraPostBattle::
    .string "TYRA: Me enseñaste que la fuerza\n"
    .string "es infinita.$"

VictoryRoad_3F_Text_TyraNotEnoughMons::
    .string "TYRA: No puedes luchar contra\n" 
    .string "nosotros si solo tienes un POKéMON.$"

