ViridianForest_Text_FriendsItchingToBattle:: @ 8172255
    .string "¡Vine aquí con unos amigos para\n"
    .string "atrapar POKéMON de tipo BICHO!\p"
    .string "¡Todos ellos están buscando\n"
    .string "batallas POKéMON!$"

ViridianForest_Text_RickIntro:: @ 81722C7
    .string "¡Eh! Tú tienes POKéMON!\n"
    .string "¡Vamos!\l"
    .string "¡Hay que hacer que luchen!$"

ViridianForest_Text_RickDefeat:: @ 81722F9
    .string "¡No!\n¡CATERPIE no pudo lograrlo!$"

ViridianForest_Text_RickPostBattle:: @ 8172315
    .string "¡Ssh! Vas a espantar a los bichos.\n"
    .string "¿En otra ocasión, de acuerdo?$"

ViridianForest_Text_DougIntro:: @ 817234A
    .string "¡Hey!\n"
    .string "Si eres un{A} ENTRENADOR{AM} POKéMON,\l"
    .string "¡no puedes negarte a una batalla!$"

ViridianForest_Text_DougDefeat:: @ 817237D
    .string "¿Oh?\n"
    .string "¡Ya no me quedan más POKéMON!$"

ViridianForest_Text_DougPostBattle:: @ 8172398
    .string "¡Esto apesta! ¡Voy a atrapar unos\n"
    .string "POKéMON más fuertes!$"

ViridianForest_Text_SammyIntro:: @ 81723D4
    .string "¡Eh, espera!\n"
    .string "¿Por qué tienes tanta prisa?$"

ViridianForest_Text_SammyDefeat:: @ 8172402
    .string "¡Me rindo!\n"
    .string "¡Eres buen{OA} en esto!$"

ViridianForest_Text_SammyPostBattle:: @ 817241F
    .string "A veces, puedes encontrar cosas\n"
    .string "en el suelo.\p"
    .string "Estoy buscando las cosas que tiré.\n"
    .string "¿Me puedes ayudar?$"

ViridianForest_Text_AnthonyIntro:: @ 8172482
    .string "¡Puede que sea pequeño, pero no\n"
    .string "quiero que me lo dejes fácil!$"

ViridianForest_Text_AnthonyDefeat:: @ 81724BF
    .string "Oh, vaya.\n"
    .string "Nada salió bien.$"

ViridianForest_Text_AnthonyPostBattle:: @ 81724DC
    .string "Perdí parte de mi mesada…$"

ViridianForest_Text_CharlieIntro:: @ 81724F9
    .string "¿Sabías que los POKéMON\n"
    .string "evolucionan?$"

ViridianForest_Text_CharlieDefeat:: @ 817251B
    .string "¡Oh!\n"
    .string "¡Perdí!$"

ViridianForest_Text_CharliePostBattle:: @ 8172527
    .string "Los POKéMON BICHO evolucionan\n"
    .string "rápido. ¡Son muy divertidos!$"

ViridianForest_Text_RanOutOfPokeBalls:: @ 8172559
    .string "Estaba lanzando POKéBOLAS para\n"
    .string "atrapar POKéMON, y se me acabaron.\p"
    .string "Es por eso que nunca puedes tener\n"
    .string "demasiadas POKéBOLAS.$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak:: @ 81725C7
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "Si tus POKéMON son débiles y\n"
    .string "quieres evitar las batallas,\l"
    .string "¡aléjate de las zonas de hierba!$"

ViridianForest_Text_UseAntidoteForPoison:: @ 8172629
    .string "¡Para el veneno, usa ANTÍDOTO!\n"
    .string "¡Consíguelo en TIENDAS POKéMON!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex:: @ 817265C
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "¡Contacta al PROF. OAK vía PC para\n"
    .string "que tu POKéDEX sea evaluada!$"

ViridianForest_Text_CantCatchOwnedMons:: @ 81726A3
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "No puedes atrapar a un POKéMON que\n"
    .string "le pertenece a alguien más.\p"
    .string "¡Atrapa sólo a los POKéMON\n"
    .string "salvajes con las POKéBOLAS!$"

ViridianForest_Text_WeakenMonsBeforeCapture:: @ 817271D
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "¡Debilita a los POKéMON antes\n"
    .string "de intentar atraparlos!\p"
    .string "¡Si están sanos, podrían escapar!$"

ViridianForest_Text_LeavingViridianForest:: @ 8172773
    .string "SALIENDO DEL BOSQUE VERDE\n"
    .string "CIUDAD PLATEADA ADELANTE$"  
