MtMoon_B2F_Text_MiguelIntro::
    .string "¡Ey, detente!\p"
    .string "¡Yo encontré estos fósiles!\n"
    .string "¡Ambos son míos!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "¡De acuerdo!\n"
    .string "¡Compartiré!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "¡Cada uno tomará un fósil!\n"
    .string "¡Nada de ser avariciosos!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "De acuerdo.\n"
    .string "¡Entonces este fósil is mío!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "Muy lejos, en la ISLA CANELA, hay\n"
    .string "un LABORATORIO de POKéMON.\p"
    .string "Ahí hacen investigaciones sobre\n"
    .string "cómo regenerar a los fósiles.$"

MtMoon_B2F_Text_Grunt1Intro::
    .string "¡Nosotros, el EQUIPO ROCKET,\n"
    .string "encontraremos los fósiles!\p"
    .string "¡El revivir a los POKéMON en ellos\n"
    .string "nos dará enormes riquezas!$"

MtMoon_B2F_Text_Grunt1Defeat::
    .string "¡Argh!\n"
    .string "¡Ahora estoy enojado!$"

MtMoon_B2F_Text_Grunt1PostBattle::
    .string "¡Me hiciste enfadar! ¡Estarás en\n"
    .string "la lista negra del EQUIPO ROCKET!$"

MtMoon_B2F_Text_Grunt2Intro::
    .string "¡Nosotros, el EQUIPO ROCKET, somos\n"
    .string "gángsters de POKéMON!\l"
    .string "¡Causamos terror con nuestra fuerza!$"

MtMoon_B2F_Text_Grunt2Defeat::
    .string "¡Lo arruiné!$"

MtMoon_B2F_Text_Grunt2PostBattle::
    .string "¡Demonios!\n"
    .string "¡Mis asociados no soportarán esto!$"

MtMoon_B2F_Text_Grunt3Intro::
    .string "¡Nuestro trabajo aquí es enorme!\n"
    .string "¡Piérdete, niñ{OA}!$"

MtMoon_B2F_Text_Grunt3Defeat::
    .string "Así que, eres buen{OA}…$"

MtMoon_B2F_Text_Grunt3PostBattle::
    .string "Si encuentras un fósil, ¡dámelo\n"
    .string "y lárgate!$"

MtMoon_B2F_Text_Grunt4Intro::
    .string "¡Los niños pequeños no deberían\n"
    .string "molestar a los adultos!\p"
    .string "¡Podrían pasar cosas malas!$"

MtMoon_B2F_Text_Grunt4Defeat::
    .string "¡Estoy enfadado!$"

MtMoon_B2F_Text_Grunt4PostBattle::
    .string "Los POKéMON vivían aquí mucho\n"
    .string "antes de que llegara la gente.$"

MtMoon_B2F_Text_YouWantDomeFossil::
    .string "¿Quieres el FÓSIL DOMO?$"

MtMoon_B2F_Text_YouWantHelixFossil::
    .string "¿Quieres el FÓSIL HÉLIX?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
    .string "¡Obtuviste el FÓSIL HÉLIX!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
    .string "¡Obtuviste el FÓSIL DOMO!$"

