MtMoon_B2F_Text_MiguelIntro:: @ 8172B64
    .string "¡Ey, detente!\p"
    .string "¡Yo encontré estos fósiles!\n"
    .string "¡Ambos son míos!$"

MtMoon_B2F_Text_MiguelDefeat:: @ 8172B99
    .string "¡De acuerdo!\n"
    .string "¡Compartiré!$"

MtMoon_B2F_Text_WellEachTakeAFossil:: @ 8172BAB
    .string "¡Cada uno tomará un fósil!\n"
    .string "¡Nada de ser avariciosos!$"

MtMoon_B2F_Text_ThenThisFossilIsMine:: @ 8172BD6
    .string "De acuerdo.\n"
    .string "¡Entonces este fósil is mío!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils:: @ 8172BFB
    .string "Muy lejos, en la ISLA CANELA, hay\n"
    .string "un LABORATORIO de POKéMON.\p"
    .string "Ahí hacen investigaciones sobre\n"
    .string "cómo regenerar a los fósiles.$"

MtMoon_B2F_Text_Grunt1Intro:: @ 8172C5A
    .string "¡Nosotros, el EQUIPO ROCKET,\n"
    .string "encontraremos los fósiles!\p"
    .string "¡El revivir a los POKéMON en ellos\n"
    .string "nos dará enormes riquezas!$"

MtMoon_B2F_Text_Grunt1Defeat:: @ 8172CB8
    .string "¡Argh!\n"
    .string "¡Ahora estoy enojado!$"

MtMoon_B2F_Text_Grunt1PostBattle:: @ 8172CCB
    .string "¡Me hiciste enfadar! ¡Estarás en\n"
    .string "la lista negra del EQUIPO ROCKET!$"

MtMoon_B2F_Text_Grunt2Intro:: @ 8172CFC
    .string "¡Nosotros, el EQUIPO ROCKET, somos\n"
    .string "gángsters de POKéMON!\l"
    .string "¡Causamos terror con nuestra fuerza!$"

MtMoon_B2F_Text_Grunt2Defeat:: @ 8172D46
    .string "¡Lo arruiné!$"

MtMoon_B2F_Text_Grunt2PostBattle:: @ 8172D51
    .string "¡Demonios!\n"
    .string "¡Mis asociados no soportarán esto!$"

MtMoon_B2F_Text_Grunt3Intro:: @ 8172D82
    .string "¡Nuestro trabajo aquí es enorme!\n"
    .string "¡Piérdete, niñ{OA}!$"

MtMoon_B2F_Text_Grunt3Defeat:: @ 8172DAF
    .string "Así que, eres buen{OA}…$"

MtMoon_B2F_Text_Grunt3PostBattle:: @ 8172DC1
    .string "Si encuentras un fósil, ¡dámelo\n"
    .string "y lárgate!$"

MtMoon_B2F_Text_Grunt4Intro:: @ 8172DF0
    .string "¡Los niños pequeños no deberían\n"
    .string "molestar a los adultos!\p"
    .string "¡Podrían pasar cosas malas!$"

MtMoon_B2F_Text_Grunt4Defeat:: @ 8172E3E
    .string "¡Estoy enfadado!$"

MtMoon_B2F_Text_Grunt4PostBattle:: @ 8172E4B
    .string "Los POKéMON vivían aquí mucho\n"
    .string "antes de que llegara la gente.$"

MtMoon_B2F_Text_YouWantDomeFossil:: @ 8172E77
    .string "¿Quieres el FÓSIL DOMO?$"

MtMoon_B2F_Text_YouWantHelixFossil:: @ 8172E94
    .string "¿Quieres el FÓSIL HÉLIX?$"

MtMoon_B2F_Text_ObtainedHelixFossil:: @ 8172EB2
    .string "¡Obtuviste el FÓSIL HÉLIX!$"

MtMoon_B2F_Text_ObtainedDomeFossil:: @ 8172ECD
    .string "¡Obtuviste el FÓSIL DOMO!$"
