TwoIsland_JoyfulGameCorner_Text_WhereHasLostelleGottenTo::
    .string "¿A dónde se habrá ido LOSTELLE\n"
    .string "hoy?\p"
    .string "Siempre me trae el almuerzo todos\n"
    .string "los días a esta hora…$"

TwoIsland_JoyfulGameCorner_Text_PleaseHelpFindLostelle::
    .string "¿Hm? ¡Tú!\n"
    .string "¿Eres un{A} amig{OA} de LOSTELLE?\p"
    .string "¿La has visto?\n"
    .string "No sé dónde podría estar.\l"
    .string "Debería estar aquí desde hace\n"
    .string "mucho.\p"
    .string "LOSTELLE es una lindura - se\n"
    .string "parece a mí - entonces si alguien…\p"
    .string "¡¿Qué tal si le paso algo a\n"
    .string "mi LOSTELLE?!\p"
    .string "¡Por favor, ayúdame a encontrarla!\n"
    .string "¡Por favor busca en la ISLA TERA!$"

TwoIsland_JoyfulGameCorner_Text_IsThisOnlyThreeIsland::
    .string "¿Jah? ¿qué es esta SALA DE JUEGOS?\n"
    .string "¿Qué tan triste se puede poner?\p"
    .string "Esos payasos…\p"
    .string "Dijeron que estarían esperando en\n"
    .string "la isla, ¿dónde estan?\p"
    .string "¡Ey, tú! ¿es esta la única\n"
    .string "ISLA TERA por aquí?$"

TwoIsland_JoyfulGameCorner_Text_ThisIsTwoIslandMoveIt::
    .string "Intenta despertar antes de que te\n"
    .string "arrastres de tu cama, vándalo.\p"
    .string "¡Esta es la ISLA SECUNDA!\p"
    .string "¡Vete! ¡saca tu sucia motocicleta\n"
    .string "de este lugar!$"

TwoIsland_JoyfulGameCorner_Text_TheseIslandsAreConfusing::
    .string "Huh…\n"
    .string "Oh, oh, entiendo.\p"
    .string "Tch…\n"
    .string "Estas islas son confusas…$"

TwoIsland_JoyfulGameCorner_Text_PunkScuffedUpMyFloor::
    .string "Mira eso.\n"
    .string "Ese vándalo rayó mi piso.$"

TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland::
    .string "¡Ey, pero escucha! te lo suplico,\n"
    .string "tienes que ir a la ISLA TERA.\p"
    .string "Si algo le fuera a pasar a mi\n"
    .string "LOSTELLE…\p"
    .string "Mi hogar es la casa con el techo\n"
    .string "rojo en ISLA TERA.\p"
    .string "Puede que ella aparezca aquí, así\n"
    .string "que no puedo salir corriendo.\p"
    .string "Es por eso que necesito que me\n"
    .string "hagas este gran favor.$"

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday::
    .string "Lo siento.\n"
    .string "Los juegos estan cerrados hoy.$"

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon::
    .string "¡Haremos que los juegos funcionen\n"
    .string "pronto para ti!$"

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle::
    .string "¿Rescataste a LOSTELLE?\n"
    .string "¿Cómo puedo agradecerte?\p"
    .string "¡LOSTELLE, querida, perdóname!\p"
    .string "¡Papi no sabía que estabas\n"
    .string "asustada y en problemas!$"

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy::
    .string "LOSTELLE: Esta bien, Papi.\n"
    .string "¡Ahora soy amiga de {PLAYER}!$"

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe::
    .string "¿Oh, qué es eso?\n"
    .string "¿Dices que esto es para mi?\p"
    .string "¿Cómo sabías que amo las rocas\n"
    .string "raras y las gemas?\p"
    .string "Sí que sabes como hacer felices\n"
    .string "a otros.$"

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy::
    .string "{PLAYER} entregó el METEORITO\n"
    .string "al papá de LOSTELLE.$"

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill::
    .string "¡Oh, ya veo, esto viene de BILL!\n"
    .string "¡Tienes que agradecerle de mi\n"
    .string "parte!\p"
    .string "Sabes, has sido fantástic{OA}.\n"
    .string "Quiero que tengas esto.$"

TwoIsland_JoyfulGameCorner_Text_ReceivedMoonStoneFromLostellesDaddy::
    .string "{PLAYER} recibió una PIEDRA LUNAR\n"
    .string "del papá de LOSTELLE.$"

TwoIsland_JoyfulGameCorner_Text_NotGoingToFitInBag::
    .string "A tu MOCHILA ya no le queda\n"
    .string "espacio para otra cosa…$"

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning::
    .string "De acuerdo, haré que la SALA\n"
    .string "DE JUEGOS funcione de inmediato.\p"
    .string "Tienes que venir a visitarnos con\n"
    .string "un amigo.$"

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool::
    .string "¡Escucha, escucha!\p"
    .string "¡Por favor se genial otra vez!$"

