Route22_Text_EarlyRivalIntro:: @ 8188890
	.string "{RIVAL}: ¡Hey! ¡{PLAYER}!\p"
	.string "¿Piensas ir a la LIGA POKéMON?\n"
	.string "¡Olvídalo!\p"
	.string "Problemente no tienes ninguna\n"
	.string "MEDALLA, ¿verdad?\p"
	.string "El guardia no te dejará pasar\n"
	.string "sin ellas.\p"
	.string "Por cierto, ¿tus POKéMON se han\n"
	.string "vuelto más fuertes?$"

Route22_Text_EarlyRivalDefeat:: @ 8188959
	.string "¡Auuu!\n"
	.string "¡Sólo tuviste suerte!$"

Route22_Text_EarlyRivalPostBattle:: @ 8188974
	.string "Escuché que la LIGA POKéMON está\n"
	.string "llena de ENTRENADORES fuertes.\p"
	.string "Tengo que buscar una forma\n"
	.string "de superarlos.\p"
	.string "¡Deberías dejar de perder\n"
	.string "el tiempo y empezar a moverte!$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons:: @ 8188A07
	.string "{RIVAL}“なんだ？\n"
	.string "ポケモン　2ひきも\l"
	.string "もってるの　なぜか　だって？\p"
	.string "おまえも\n"
	.string "つかまえれば　いい　じゃん！$"

Route22_Text_LateRivalIntro:: @ 8188A3C
	.string "{RIVAL}: What? {PLAYER}!\n"
	.string "What a surprise to see you here!\p"
	.string "So you're going to the POKéMON\n"
	.string "LEAGUE?\p"
	.string "You collected all the BADGES, too?\n"
	.string "That's cool!\p"
	.string "Then I'll whip you, {PLAYER}, as a\n"
	.string "warm-up for the POKéMON LEAGUE!\p"
	.string "Come on!$"

Route22_Text_LateRivalDefeat:: @ 8188B08
	.string "What!?\p"
	.string "I was just careless, you!$"

Route22_Text_LateRivalPostBattle:: @ 8188B29
	.string "That loosened me up.\n"
	.string "I'm ready for the POKéMON LEAGUE!\p"
	.string "{PLAYER}, you need more practice.\p"
	.string "But hey, you know that!\n"
	.string "I'm out of here. Smell ya!$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory:: @ 8188BAF
	.string "{RIVAL}“ひゃははッ　{PLAYER}ー！\n"
	.string "それで　がんばってるのかよ！\l"
	.string "おれの　さいのうに　くらべりゃ\l"
	.string "{PLAYER}は　まだまだ　だな！\p"
	.string "もっと　れんしゅう　こいよ！\n"
	.string "あははーッ！$"

Route22_Text_LeagueGateSign:: @ 8188BFF
	.string "LIGA POKéMON\n"
	.string "Entrada Frontal$"
