Route22_Text_EarlyRivalIntro::
	.string "{RIVAL}: ¡Hey! ¡{PLAYER}!\p"
	.string "¿Piensas ir a la LIGA POKéMON?\n"
	.string "¡Olvídalo!\p"
	.string "Problemente no tienes ninguna\n"
	.string "MEDALLA, ¿verdad?\p"
	.string "El guardia no te dejará pasar\n"
	.string "sin ellas.\p"
	.string "Por cierto, ¿tus POKéMON se han\n"
	.string "vuelto más fuertes?$"

Route22_Text_EarlyRivalDefeat::
	.string "¡Auuu!\n"
	.string "¡Sólo tuviste suerte!$"

Route22_Text_EarlyRivalPostBattle::
	.string "Escuché que la LIGA POKéMON está\n"
	.string "llena de ENTRENADORES fuertes.\p"
	.string "Tengo que buscar una forma\n"
	.string "de superarlos.\p"
	.string "¡Deberías dejar de perder\n"
	.string "el tiempo y empezar a moverte!$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}“なんだ？\n"
	.string "ポケモン　2ひきも\l"
	.string "もってるの　なぜか　だって？\p"
	.string "おまえも\n"
	.string "つかまえれば　いい　じゃん！$"

Route22_Text_LateRivalIntro::
	.string "{RIVAL}: ¿Qué? ¿{PLAYER}!\n"
	.string "¡Qué sorpresa verte aquí!\p"
	.string "¿Así que vas a la LIGA POKéMON?\p"
	.string "¿Y obtuviste todas las MEDALLAS?\n"
	.string "¡Genial!\p"
	.string "¡Entonces te venceré, {PLAYER},\n"
	.string "como calentamiento para la\l"
	.string "LIGA POKéMON!\p"
	.string "¡Vamos!$"

Route22_Text_LateRivalDefeat::
	.string "¿¡Qué!?\p"
	.string "¡Solo fui descuidado!$"

Route22_Text_LateRivalPostBattle::
	.string "Eso me sirvió para calentar.\n"
	.string "¡Estoy listo para la LIGA POKéMON!\p"
	.string "{PLAYER}, necesitas más práctica.\p"
	.string "¡Aunque ya lo sabías!\n"
	.string "Me voy. ¡Hasta nunca!$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory::
	.string "{RIVAL}“ひゃははッ　{PLAYER}ー！\n"
	.string "それで　がんばってるのかよ！\l"
	.string "おれの　さいのうに　くらべりゃ\l"
	.string "{PLAYER}は　まだまだ　だな！\p"
	.string "もっと　れんしゅう　こいよ！\n"
	.string "あははーッ！$"

Route22_Text_LeagueGateSign::
	.string "LIGA POKéMON\n"
	.string "Entrada Frontal$"

