OneIsland_TreasureBeach_Text_AmaraIntro::
    .string "Dejarse llevar por las olas…\n"
    .string "Es exquisito.$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
    .string "Perdí…\n"
    .string "Se siente horrible.$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
    .string "El mar tiene una temperatura\n"
    .string "cálida en esta zona.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
    .string "La marea trae cosas buenas a\n"
    .string "esta playa.\p"
    .string "Es por eso que suelo venir a\n"
    .string "buscar algo de valor.$"

