ViridianCity_House1_Text_NicknamingIsFun:: @ 818F292
    .string "Inventar apodos es divertido, pero\n"
    .string "no es nada facíl.\p"
    .string "Un nombre ingenioso esta bien,\n"
    .string "pero es más fácil recordar\l"
    .string "los nombres simples.$"

ViridianCity_House1_Text_MyDaddyLovesMonsToo:: @ 818F30F
    .string "A mi papá también le encantan los\n"
    .string "POKéMON.$"

ViridianCity_House1_Text_Speary:: @ 818F32C
    .string "SPEARY: ¡Pío!$"

ViridianCity_House1_Text_SpearowNameSpeary:: @ 818F33D
    .string "SPEAROW\n"
    .string "Nombre: SPEARY$"
