ViridianCity_House1_Text_NicknamingIsFun::
    .string "Inventar apodos es divertido, pero\n"
    .string "no es nada facíl.\p"
    .string "Un nombre ingenioso esta bien,\n"
    .string "pero es más fácil recordar\l"
    .string "los nombres simples.$"

ViridianCity_House1_Text_MyDaddyLovesMonsToo::
    .string "A mi papá también le encantan los\n"
    .string "POKéMON.$"

ViridianCity_House1_Text_Speary::
    .string "SPEARY: ¡Pío!$"

ViridianCity_House1_Text_SpearowNameSpeary::
    .string "SPEAROW\n"
    .string "Nombre: SPEARY$"
