SilphCo_11F_Text_ThanksForSavingMeDearBoy::
    .string "PRESIDENTE: ¡Oh, querido niño!\n"
    .string "Gracias por salvar a SILPH.\p"
    .string "Nunca olvidaré que nos salvaste en\n"
    .string "un momento de grave peligro.\p"
    .string "Debo agradecerte de alguna forma.\p"
    .string "Como soy rico, puedo darte lo que\n"
    .string "sea.\p"
    .string "Ten, quizás esto te interese.$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
    .string "PRESIDENTE: ¡Oh, querida niña!\n"
    .string "Gracias por salvar a SILPH.\p"
    .string "Nunca olvidaré que nos salvaste en\n"
    .string "un momento de grave peligro.\p"
    .string "Debo agradecerte de alguna forma.\p"
    .string "Como soy rico, puedo darte lo que\n"
    .string "sea.\p"
    .string "Ten, quizás esto te interese.$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
    .string "¡{PLAYER} recibió una BOLA MAESTRA\n"
    .string "del PRESIDENTE!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
    .string "PRESIDENTE: No puedes comprar eso\n"
    .string "en ninguna parte.\p"
    .string "Es nuestro prototipo secreto de la\n"
    .string "BOLA MAESTRA.\p"
    .string "¡Atrapará a cualquier POKéMON sin\n"
    .string "falla!\p"
    .string "Aunque sería mejor que la uses en\n"
    .string "secreto.$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
    .string "No tienes espacio para esto.$"

SilphCo_11F_Text_ThanksForRescuingUs::
    .string "SECRETARIA: Gracias por\n"
    .string "rescatarnos a todos.\p"
    .string "Todos, incluyendo el PRESIDENTE,\n"
    .string "estamos en deuda contigo.$"

SilphCo_11F_Text_GiovanniIntro::
    .string "¡Ah, {PLAYER}!\n"
    .string "¡Así que nos volvemos a ver!\p"
    .string "El PRESIDENTE y yo discutimos\n"
    .string "una propuesta de negocios vital.\p"
    .string "Alejate de los asuntos de gente\n"
    .string "adulta…\p"
    .string "O, ¡experimenta un mundo de dolor!$"

SilphCo_11F_Text_GiovanniDefeat::
    .string "¡¡Arrgh!!\n"
    .string "¿¡Perdí otra vez!?$"

SilphCo_11F_Text_GiovanniPostBattle::
    .string "¡Maldita sea!\n"
    .string "¡Arruinaste los planes para SILPH!\p"
    .string "¡Pero el EQUIPO ROCKET nunca\n"
    .string "caerá!\p"
    .string "¡{PLAYER}! ¡nunca olvides que\n"
    .string "todos los POKéMON existen para el\l"
    .string "EQUIPO ROCKET!\p"
    .string "¡Debo irme, pero volveré!$"

SilphCo_11F_Text_Grunt2Intro::
    .string "¡Detente justo ahí!\n"
    .string "¡No te muevas!$"

SilphCo_11F_Text_Grunt2Defeat::
    .string "No lo hagas…\n"
    .string "¡Por favor!$"

SilphCo_11F_Text_Grunt2PostBattle::
    .string "¿Así que quieres ver a mi JEFE?$"

SilphCo_11F_Text_Grunt1Intro::
    .string "¡Alto! ¿tienes una cita con mi\n"
    .string "JEFE?$"

SilphCo_11F_Text_Grunt1Defeat::
    .string "¡Gaah!\n"
    .string "¡Demolido!$"

SilphCo_11F_Text_Grunt1PostBattle::
    .string "Cuida tus pasos…\n"
    .string "¡Mi JEFE prefiere POKéMON fuertes!$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
    .string "¡El monitor muestra unos POKéMON!$"

SilphCo_11F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P11$"

