PokemonMansion_Text_PressSecretSwitch::
    .string "¡Un botón secreto!\p"
    .string "¿Quieres presionarlo?$"

PokemonMansion_Text_WhoWouldnt::
    .string "¿Quién no lo haría?$"

PokemonMansion_Text_NotQuiteYet::
    .string "¡Todavía no!$"

PokemonMansion_1F_Text_ArnieIntro::
    .string "¡No puedo salir! Este viejo lugar\n"
    .string "es un rompecabezas enorme.$"

PokemonMansion_1F_Text_ArnieDefeat::
    .string "¡Oh, no!\n"
    .string "¡Mi botín!$"

PokemonMansion_1F_Text_ArniePostBattle::
    .string "Los botones alternan entre abrir\n"
    .string "y cerrar los grupos de puertas.$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle::
    .string "Diario: 5 de Julio\n"
    .string "Guyana, Sudamérica\p"
    .string "Un nuevo POKéMON fue descubierto\n"
    .string "en lo profundo de la selva.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
    .string "Diario: 10 de Julio\n"
    .string "Nombramos al POKéMON recién\l"
    .string "descubierto como MEW.$"

