CinnabarIsland_Gym_Text_BlaineIntro::
    .string "¡Ja!\p"
    .string "¡Yo soy BLAINE, el LÍDER del\n"
    .string "GIMNASIO de CANELA!\p"
    .string "¡Mis feroces POKéMON son fuertes y\n"
    .string "están listos con calor intenso!\p"
    .string "¡Incinerarán a cualquier rival!\p"
    .string "¡Ja!\n"
    .string "¡Ojalá tengas ANTIQUEMADURAS!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CinnabarIsland_Gym_Text_BlaineDefeat::
    .string "¡Me quemé hasta no dejar nada!\n"
    .string "¡Ni siquiera quedan cenizas!\p"
    .string "Te ganaste la MEDALLA VOLCÁN.$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
    .string "LLAMARADA es la técnica de fuego\n"
    .string "definitiva.\p"
    .string "No la gastes en POKéMON de AGUA.$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
    .string "¡Ja!\p"
    .string "La MEDALLAVOLCÁN aumenta las\n"
    .string "estadísticas ESPECIALES de tus\l"
    .string "POKéMON.\p"
    .string "¡Mira, también te daré esto!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
    .string "{PLAYER} recibió la MT38\n"
    .string "de BLAINE.$"

CinnabarIsland_Gym_Text_BlainePostBattle::
    .string "La MT38 contiene LLAMARADA.\n"
    .string "Enséñasela a POKéMON de FUEGO.\p"
    .string "VULPIX o CHARMELEON serían ideales\n"
    .string "para ese movimiento.$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
    .string "¡Haz espacio para esto, niñ{OA}!$"

CinnabarIsland_Gym_Text_ErikIntro::
    .string "¿Sabes que tan caliente puede ser\n"
    .string "el aliento de fuego de un POKéMON?$"

CinnabarIsland_Gym_Text_ErikDefeat::
    .string "¡Ay!\n"
    .string "¡Quema, quema, quema!$"

CinnabarIsland_Gym_Text_ErikPostBattle::
    .string "Fuego, o para ser más preciso,\n"
    .string "combustión…\p"
    .string "…Oxígeno en el aire…\n"
    .string "Bla, bla, bla, bla…$"

CinnabarIsland_Gym_Text_QuinnIntro::
    .string "Yo era ladrón, pero me convertí en\n"
    .string "un ENTRENADOR honrado.$"

CinnabarIsland_Gym_Text_QuinnDefeat::
    .string "¡Me rindo!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
    .string "Tengo un deseo incontrolable de\n"
    .string "robar los POKéMON de los demás.$"

CinnabarIsland_Gym_Text_AveryIntro::
    .string "He estudiado a los POKéMON\n"
    .string "cuidadosamente.\p"
    .string "¡No puedes ganar!$"

CinnabarIsland_Gym_Text_AveryDefeat::
    .string "¡Waa!\n"
    .string "¡Mis estudios no bastaron!$"

CinnabarIsland_Gym_Text_AveryPostBattle::
    .string "Mis teorías son demasiado\n"
    .string "complicadas para tu entendimiento.$"

CinnabarIsland_Gym_Text_RamonIntro::
    .string "Me gusta usar POKéMON de FUEGO.\n"
    .string "Solo eso.$"

CinnabarIsland_Gym_Text_RamonDefeat::
    .string "¡Demasiado caliente!$"

CinnabarIsland_Gym_Text_RamonPostBattle::
    .string "Ojalá hubiera un POKéMON ladrón.\n"
    .string "¡Usaría ese!$"

CinnabarIsland_Gym_Text_DerekIntro::
    .string "Yo sé porqué BLAINE se convirtió\n"
    .string "en ENTRENADOR.$"

CinnabarIsland_Gym_Text_DerekDefeat::
    .string "¡Au!$"

CinnabarIsland_Gym_Text_DerekPostBattle::
    .string "Nuestro LÍDER, BLAINE, se perdió\n"
    .string "en las montañas.\p"
    .string "La noche llegaba cuando un ave\n"
    .string "POKéMON de fuego apareció.\p"
    .string "Su luz le permitió a BLAINE\n"
    .string "encontrar un camino seguro.$"

CinnabarIsland_Gym_Text_DustyIntro::
    .string "Estuve en muchos GIMNASIOS, pero\n"
    .string "este se ajusta más a mi estilo.$"

CinnabarIsland_Gym_Text_DustyDefeat::
    .string "¡Auch!\n"
    .string "¡Demasiado caliente!$"

CinnabarIsland_Gym_Text_DustyPostBattle::
    .string "PONYTA, NINETALES…\n"
    .string "Son POKéMON de FUEGO populares.$"

CinnabarIsland_Gym_Text_ZacIntro::
    .string "El fuego es débil contra el H2O.$"

CinnabarIsland_Gym_Text_ZacDefeat::
    .string "¡Oh!\n"
    .string "¡Me apagaste!$"

CinnabarIsland_Gym_Text_ZacPostBattle::
    .string "El agua vence al fuego, claro.\p"
    .string "Pero el fuego derrite al hielo,\n"
    .string "así que los POKéMON de tipo FUEGO\l"
    .string "vencen a los de tipo HIELO.$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
    .string "¡Yo!\n"
    .string "¡Futur{OA} campe{ONONA}!\p"
    .string "BLAINE es un profesional de los\n"
    .string "POKéMON de tipo FUEGO.\p"
    .string "¡Baja sus ánimos con agua!\p"
    .string "Será mejor que también lleves unas\n"
    .string "ANTIQUEMADURAS.$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
    .string "¡{PLAYER}!\n"
    .string "¡Venciste a esa antorcha!$"

CinnabarIsland_Gym_Text_GymStatue::
    .string "GIMNASIO POKéMON DE CANELA\n"
    .string "LÍDER BLAINE\p"
    .string "ENTRENADORES VICTORIOSOS:\n"
    .string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
    .string "GIMNASIO POKéMON DE CANELA\n"
    .string "LÍDER BLAINE\p"
    .string "ENTRENADORES VICTORIOSOS:\n"
    .string "{RIVAL}, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
    .string "¡Concurso POKéMON!\p"
    .string "Si aciertas, la puerta a la\n"
    .string "siguiente habitación se abrirá.\p"
    .string "¡Si fallas, lucharás contra\n"
    .string "un ENTRENADOR!\p"
    .string "Si quieres reservar tus POKéMON\n"
    .string "para el LÍDER de GIMNASIO…\p"
    .string "¡Hazlo bien!\n"
    .string "¡Allá vamos!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
    .string "¿CATERPIE evoluciona en METAPOD?$"

CinnabarIsland_Gym_Text_QuizQuestion2::
    .string "¿Hay 9 MEDALLAS certificadas de la\n"
    .string "LIGA POKéMON?$"

CinnabarIsland_Gym_Text_QuizQuestion3::
    .string "¿POLIWAG evoluciona tres veces?$"

CinnabarIsland_Gym_Text_QuizQuestion4::
    .string "¿Los movimientos ELÉCTRICOS\n"
    .string "afectan a los POKéMON de\l"
    .string "tipo TIERRA?$"

CinnabarIsland_Gym_Text_QuizQuestion5::
    .string "¿Los POKéMON del mismo tipo\n"
    .string "y nivel son distintos?$"

CinnabarIsland_Gym_Text_QuizQuestion6::
    .string "¿La MT28 contiene TUMBA PIEDRA?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
    .string "¡Tienes toda la razón!\p"
    .string "¡Adelante!$"

CinnabarIsland_Gym_Text_SorryBadCall::
    .string "¡Lo siento!\n"
    .string "¡Te equivocaste!$"

