PewterCity_Museum_1F_Text_TeamRocketMtMoonImOnPhone:: @ 81916A9
    .string "¿¡Qué!?\p"
    .string "¿El EQUIPO ROCKET está en\n"
    .string "el MONTE LUNA?\p"
    .string "¿Huh?\p"
    .string "¡Estoy en el teléfono!\n"
    .string "¡Largo!$"

PewterCity_Museum_1F_Text_Jigglypuff:: @ 81916EA
    .string "JIGGLYPUFF: ¡Puu pupuu!$"

PewterCity_Museum_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy:: @ 8191701
    .string "¡Aaah!\p"
    .string "Cuando JIGGLYPUFF canta, los\n"
    .string "POKéMON se duermen…\p"
    .string "…Y yo, también…\n"
    .string "Jjrrrrr…$"

PewterCity_Museum_1F_Text_TradingMyClefairyForPikachu:: @ 8191743
    .string "Quiero un PIKACHU, así que voy a\n"
    .string "intercambiar a mi CLEFAIRY por uno.$"

PewterCity_Museum_1F_Text_TradingPikachuWithKid:: @ 8191780
    .string "Estoy intercambiando POKéMON con\n"
    .string "ese niño de ahí.\p"
    .string "Como tenía dos PIKACHU, pense que\n"
    .string "no haría daño pasarle uno.$"
