PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
    .string "¿¡Qué!?\p"
    .string "¿El EQUIPO ROCKET está en\n"
    .string "el MONTE LUNA?\p"
    .string "¿Huh?\p"
    .string "¡Estoy en el teléfono!\n"
    .string "¡Largo!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
    .string "JIGGLYPUFF: ¡Puu pupuu!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
    .string "¡Aaah!\p"
    .string "Cuando JIGGLYPUFF canta, los\n"
    .string "POKéMON se duermen…\p"
    .string "…Y yo, también…\n"
    .string "Jjrrrrr…$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
    .string "Quiero un PIKACHU, así que voy a\n"
    .string "intercambiar a mi CLEFAIRY por uno.$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
    .string "Estoy intercambiando POKéMON con\n"
    .string "ese niño de ahí.\p"
    .string "Como tenía dos PIKACHU, pense que\n"
    .string "no haría daño pasarle uno.$"

