SSAnne_B1F_Room1_Text_PhillipIntro::
    .string "Chiquill{OA}, ¡caminarás por\n"
    .string "el tablón si pierdes!$"

SSAnne_B1F_Room1_Text_PhillipDefeat::
    .string "¡Argh!\n"
    .string "¡Vencido por un{A} niñ{OA}!$"

SSAnne_B1F_Room1_Text_PhillipPostBattle::
    .string "Cuando estamos en el mar, a veces\n"
    .string "POKéMON medusa pasan cerca.$"

SSAnne_B1F_Room1_Text_BarnyIntro::
    .string "¡Hola, extrañ{OA}!\p"
    .string "No sé si eres de los mares o de\n"
    .string "las montañas, pero ven a charlar.\p"
    .string "Todos mis POKéMON vienen del mar.$"

SSAnne_B1F_Room1_Text_BarnyDefeat::
    .string "¡Rayos!\n"
    .string "¡Deje que ese se escapara!$"

SSAnne_B1F_Room1_Text_BarnyPostBattle::
    .string "¡Y también te iba a hacer mi\n"
    .string "asistente!$"

