Route25_SeaCottage_Text_ImBillHelpMeOutPal:: @ 819FDFA
    .string "¡Hola! soy un POKéMON…\n"
    .string "…¡No, no lo soy!\p"
    .string "¡Llámame BILL!\n"
    .string "¡Soy un verdadero POKéMANÍACO!\p"
    .string "¡Ey!\n"
    .string "¿Por qué esa mirada escéptica?\p"
    .string "No te bromeo, amigo.\p"
    .string "¡Arruiné un experimento y terminé\n"
    .string "combinado con un POKéMON!\p"
    .string "Y, ¿que piensas?\n"
    .string "¡Sácame de esta!$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady:: @ 819FEE6
    .string "¡Hola! soy un POKéMON…\n"
    .string "…¡No, no lo soy!\p"
    .string "¡Llámame BILL!\n"
    .string "¡Soy un verdadero POKéMANÍACO!\p"
    .string "¡Ey!\n"
    .string "¿Por qué esa mirada escéptica?\p"
    .string "No te bromeo, señorita.\p"
    .string "¡Arruiné un experimento y terminé\n"
    .string "combinado con un POKéMON!\p"
    .string "Y, ¿que piensas?\n"
    .string "¡Sácame de esta!$"

Route25_SeaCottage_Text_RunCellSeparationOnPC:: @ 819FFD3
    .string "Espera hasta que entre al\n"
    .string "TELETRANSPORTADOR.\p"
    .string "Cuando entre, ve a mi PC y ejecuta\n"
    .string "el Sistema de Separación Celular.$"

Route25_SeaCottage_Text_NoPleaseChief:: @ 81A0035
    .string "¿¡No!?\n"
    .string "¡No seas tan frio ahora!\p"
    .string "Vamos, ¡tienes que ayudar a un\n"
    .string "chico en un gran, gran problema!\p"
    .string "¿Que dices, amigo?\n"
    .string "¿Por favor?\l"
    .string "¿Si?\l"
    .string "¡De acuerdo!$"

Route25_SeaCottage_Text_NoPleaseBeautiful:: @ 81A00B6
    .string "¿¡No!?\n"
    .string "¡No seas tan fria ahora!\p"
    .string "Vamos, ¡tienes que ayudar a un\n"
    .string "chico en un gran, gran problema!\p"
    .string "¿Que dices, dulzura?\n"
    .string "¿Por favor?\l"
    .string "¿Si?\l"
    .string "¡De acuerdo!$"

Route25_SeaCottage_Text_ThanksBudTakeThis:: @ 81A013B
    .string "BILL: Yeehah!\n"
    .string "Thanks, bud! I owe you one!\p"
    .string "So, did you come to see my\n"
    .string "POKéMON collection?\p"
    .string "You didn't?\n"
    .string "That's a bummer.\p"
    .string "I've got to thank you…\n"
    .string "Oh, here, maybe this'll do.$"

Route25_SeaCottage_Text_ThanksLadyTakeThis:: @ 81A01E4
    .string "BILL: Yeehah!\n"
    .string "Thanks, lady! I owe you one!\p"
    .string "So, did you come to see my\n"
    .string "POKéMON collection?\p"
    .string "You didn't?\n"
    .string "That's a bummer.\p"
    .string "I've got to thank you…\n"
    .string "Oh, here, maybe this'll do.$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill:: @ 81A028E
    .string "{PLAYER} received an S.S. TICKET\n"
    .string "from BILL.$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff:: @ 81A02B4
    .string "You've got too much stuff!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead:: @ 81A02CF
    .string "That cruise ship S.S. ANNE is in\n"
    .string "VERMILION CITY.\p"
    .string "I hear there are lots of TRAINERS\n"
    .string "on board, too.\p"
    .string "They invited me to their party, but\n"
    .string "I can't stand fancy do's.\p"
    .string "Why don't you go instead of me?\n"
    .string "Go on and have a good time.$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC:: @ 81A03AB
    .string "BILL: Feel like checking out some\n"
    .string "of my rare POKéMON on my PC?\p"
    .string "Go on, check out my PC.$"

Route25_SeaCottage_Text_TeleporterIsDisplayed:: @ 81A0402
    .string "TELEPORTER is displayed on the PC\n"
    .string "monitor.$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator:: @ 81A042D
    .string "{PLAYER} inició el Separador\n"
    .string "Celular del TELETRANSPORTADOR.$"

Route25_SeaCottage_Text_BillsFavoriteMonList:: @ 81A045B
    .string "BILL's favorite POKéMON list!$"

Route25_SeaCottage_Text_SeeWhichMon:: @ 81A0479
    .string "Which POKéMON do you want to see?$"

