Route25_SeaCottage_Text_ImBillHelpMeOutPal::
    .string "¡Hola! soy un POKéMON…\n"
    .string "…¡No, no lo soy!\p"
    .string "¡Llámame BILL!\n"
    .string "¡Soy un verdadero POKéMANÍACO!\p"
    .string "¡Ey!\n"
    .string "¿Por qué esa mirada escéptica?\p"
    .string "No te bromeo, amigo.\p"
    .string "¡Arruiné un experimento y terminé\n"
    .string "combinado con un POKéMON!\p"
    .string "Y, ¿que piensas?\n"
    .string "¡Sácame de esta!$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
    .string "¡Hola! soy un POKéMON…\n"
    .string "…¡No, no lo soy!\p"
    .string "¡Llámame BILL!\n"
    .string "¡Soy un verdadero POKéMANÍACO!\p"
    .string "¡Ey!\n"
    .string "¿Por qué esa mirada escéptica?\p"
    .string "No te bromeo, señorita.\p"
    .string "¡Arruiné un experimento y terminé\n"
    .string "combinado con un POKéMON!\p"
    .string "Y, ¿que piensas?\n"
    .string "¡Sácame de esta!$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
    .string "Espera hasta que entre al\n"
    .string "TELETRANSPORTADOR.\p"
    .string "Cuando entre, ve a mi PC y ejecuta\n"
    .string "el Sistema de Separación Celular.$"

Route25_SeaCottage_Text_NoPleaseChief::
    .string "¿¡No!?\n"
    .string "¡No seas tan frio ahora!\p"
    .string "Vamos, ¡tienes que ayudar a un\n"
    .string "chico en un gran, gran problema!\p"
    .string "¿Que dices, amigo?\n"
    .string "¿Por favor?\l"
    .string "¿Si?\l"
    .string "¡De acuerdo!$"

Route25_SeaCottage_Text_NoPleaseBeautiful::
    .string "¿¡No!?\n"
    .string "¡No seas tan fria ahora!\p"
    .string "Vamos, ¡tienes que ayudar a un\n"
    .string "chico en un gran, gran problema!\p"
    .string "¿Que dices, dulzura?\n"
    .string "¿Por favor?\l"
    .string "¿Si?\l"
    .string "¡De acuerdo!$"

Route25_SeaCottage_Text_ThanksBudTakeThis::
    .string "BILL: ¡Yiijah!\n"
    .string "¡Gracias, amigo! ¡Te debo una!\p"
    .string "Así que, ¿viniste a ver mi\n"
    .string "colección de POKéMON?\p"
    .string "¿No lo hiciste?\n"
    .string "Eso es una pena.\p"
    .string "Tengo que agradecerte…\n"
    .string "Oh, aquí, puede que esto sirva.$"

Route25_SeaCottage_Text_ThanksLadyTakeThis::
    .string "BILL: ¡Yiijah!\n"
    .string "¡Gracias, señorita! ¡Te debo una!\p"
    .string "Así que, ¿viniste a ver mi\n"
    .string "colección de POKéMON?\p"
    .string "¿No lo hiciste?\n"
    .string "Eso es una pena.\p"
    .string "Tengo que agradecerte…\n"
    .string "Oh, aquí, puede que esto sirva.$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
    .string "{PLAYER} recibió un BOLETO SANTA\n"
    .string "ANA de BILL.$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff::
    .string "¡Llevas demasiadas cosas!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
    .string "Ese crucero llamado SANTA ANA\n"
    .string "está en CIUDAD CARMÍN.\p"
    .string "También oí que hay muchos\n"
    .string "ENTRENADORES a bordo.\p"
    .string "Me invitaron a la fiesta, pero no\n"
    .string "soporto los eventos lujosos.\p"
    .string "¿Por qué no vas en mi lugar?\n"
    .string "Ve y ten un buen rato.$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
    .string "BILL: ¿Quieres ver algunos de mis\n"
    .string "POKéMON raros en mi PC?\p"
    .string "Adelante, revisa mi PC.$"

Route25_SeaCottage_Text_TeleporterIsDisplayed::
    .string "En el monitor de la PC aparece\n"
    .string "el texto: TELETRANSPORTADOR$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
    .string "{PLAYER} inició el Separador\n"
    .string "Celular del TELETRANSPORTADOR.$"

Route25_SeaCottage_Text_BillsFavoriteMonList::
    .string "¡La lista de POKéMON favoritos\n"
    .string "de BILL!$"

Route25_SeaCottage_Text_SeeWhichMon::
    .string "¿A qué POKéMON quieres ver?$"

