@ Male and female text identical, differ (presumably) in JP
Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale::
    .string "Las cenizas de mi POKéMON están\n"
    .string "guardadas en la TORRE POKéMON.\p"
    .string "Puedes tener esta MT.\n"
    .string "Ya no la necesito…$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale::
    .string "Las cenizas de mi POKéMON están\n"
    .string "guardadas en la TORRE POKéMON.\p"
    .string "Puedes tener esta MT.\n"
    .string "Ya no la necesito…$"

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl::
    .string "{PLAYER} recibió MT27\n"
    .string "de la pequeña niña.$"

Route12_NorthEntrance_2F_Text_ExplainTM27::
    .string "MT27 contiene RETRIBUCIÓN…\p"
    .string "Si tratas bien a tu POKéMON,\n"
    .string "regresará tu amor al darlo todo\l"
    .string "en batalla.$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis::
    .string "No tienes espacio para esto.$"

Route12_NorthEntrance_2F_Text_TheresManFishing::
    .string "Veamos lo que estos binoculares\n"
    .string "tienen para mostrar…\p"
    .string "¡Hay un hombre pescando!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
    .string "Veamos lo que estos binoculares\n"
    .string "tienen para mostrar…\p"
    .string "¡Es la TORRE POKéMON!$"

