CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked::
    .string "Vine a visitar el GIMNASIO de\n"
    .string "CANELA, pero la puerta está\l"
    .string "cerrada.\p"
    .string "Debe haber una llave en algún\n"
    .string "lado.\p"
    .string "¿Estará en esa mansión quemada?\p"
    .string "Se dice que un amigo del LÍDER\n"
    .string "de GIMNASIO solía vivir ahí.$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom::
    .string "¿Tienes muchos amigos?\p"
    .string "Conectarte con tus amigos\n"
    .string "de siempre es divertido, claro.\p"
    .string "Pero, ¿qué tal si visitas la\n"
    .string "SALA UNIÓN de vez en cuando?\p"
    .string "Quién sabe, tal vez termines\n"
    .string "haciendo nuevos amigos.\p"
    .string "Creo que valdría la pena que\n"
    .string "probaras la SALA UNIÓN.$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves::
    .string "Los POKéMON pueden seguir\n"
    .string "aprendiendo técnicas tras cancelar\l"
    .string "su evolución.\p"
    .string "ELa evolución puede esperar hasta\n"
    .string "que aprendan nuevos movimientos.$"

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland::
    .string "BILL: ¡Ey, me dejaste esperando!\n"
    .string "¿List{OA} para ir a la ISLA PRIMA?$"

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet::
    .string "Oh, ¿aún no estás list{OA}?$"

CinnabarIsland_PokemonCenter_1F_Text_LetsGo::
    .string "Bien, estamos listos.\n"
    .string "¡Vamos!$"
