PokemonTower_2F_Text_RivalIntro::
    .string "{RIVAL}: ¡Ey, {PLAYER}!\n"
    .string "¿Qué haces por aquí?\l"
    .string "¿Están tus POKéMON muertos?\p"
    .string "¡Ey! ¡están vivos!\p"
    .string "¡Al menos puedo debilitarlos!\n"
    .string "¡Vamos!$"

PokemonTower_2F_Text_RivalDefeat::
    .string "¿Qué?\n"
    .string "¡Rayos!\p"
    .string "¡Te lo estaba dejando fácil!$"

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory::
    .string "{RIVAL}“あーあ‥！\n"
    .string "ほんとに　くたばっちまったぞ！\l"
    .string "よわいなー！\l"
    .string "もっと　ちゃんと　そだてて　やれよ$"

PokemonTower_2F_Text_RivalPostBattle::
    .string "¿Cómo va tu POKéDEX?\n"
    .string "¡Acabo de atrapar a un CUBONE!\p"
    .string "Aún no encuentro un MAROWAK.\n"
    .string "¿Donde podrían estar?\p"
    .string "¡Apuesto que ya no queda ninguno!\p"
    .string "Bueno, será mejor que me vaya.\n"
    .string "Me queda mucho que lograr,\l"
    .string "no como tú.\p"
    .string "¡Hasta nunca!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
    .string "Ni siquiera nosotros podemos\n"
    .string "identificar a los fantasmas.\p"
    .string "Tal vez un VISOR SILPH podría\n"
    .string "desenmascararlos.$"

