SSAnne_1F_Corridor_Text_LeStrongSilentType::
    .string "¡Bonjour!\n"
    .string "¡Soy el camarero de este barco!\p"
    .string "¡Estaré feliz de servirte lo\n"
    .string "que desees!\p"
    .string "… … …\p"
    .string "¡Ah! ¡Eres del tipo fuerte y\n"
    .string "silencioso!$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
    .string "Los pasajeros estan inquietos por\n"
    .string "este largo viaje.\p"
    .string "¡Puede que seas desafiad{OA} por\n"
    .string "los que están más aburridos!$"

