Route5_SouthEntrance_Text_ThirstyOnGuardDuty::
    .string "Estoy en mi deber como guardia.\n"
    .string "Pero uff, ¡estoy sediento!\p"
    .string "Oh, espera, el camino fue cerrado.$"

Route5_SouthEntrance_Text_ThatTeaLooksTasty::
    .string "Oh, ese TÉ…\n"
    .string "Parece que está delicioso…$"

Route5_SouthEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "¿Uh? ¿Me das la bebida?\n"
    .string "ey, ¡gracias!\l"
    .string "… …\l"
    .string "Glug, glug…\l"
    .string "… …\l"
    .string "Gulp…\l"
    .string "Si quieres ir a CIUDAD\l"
    .string "AZAFRÁN…\l"
    .string "… …\l"
    .string "Puedes pasar.\p"
    .string "¡Compartiré este TÉ con los otros\n"
    .string "guardias!$"

Route5_SouthEntrance_Text_HiHowsItGoing::
    .string "¿Hola, como te va?$"

