CeruleanCity_Gym_Text_MistyIntro::
    .string "¡Hola, eres una cara nueva!\p"
    .string "Necesitas una estrategia con los\n"
    .string "POKéMON para volverte profesional.\p"
    .string "¿Cuál es tu plan al atrapar y\n"
    .string "entrenar POKéMON?\p"
    .string "¡Mi estrategia es la ofensiva\n"
    .string "total con POKéMON de tipo AGUA!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "MT03 enseña PULSO AGUA.\p"
    .string "¡Úsala en un POKéMON acuático!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .string "La MEDALLA CASCADA hace que todo\n"
    .string "POKéMON hasta el Nv. 30 obedezca.\p"
    .string "Eso incluso incluye a los que\n"
    .string "obtengas en intercambios.\p"
    .string "Hay más. Puedes usar CORTE cuándo\n"
    .string "sea, incluso fuera de batalla.\p"
    .string "Puedes cortar pequeños árboles\n"
    .string "para abrir nuevos caminos.\p"
    .string "Tambíen te daré mi MT favorita.$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "{PLAYER} recibió MT03\n"
    .string "de MISTY.$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "¡Mejor haz espacio para esto!$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "¡Wow!\n"
    .string "¡Eres demasiado!\p"
    .string "¡De acuerdo!\p"
    .string "Puedes tener la MEDALLA CASCADA\n"
    .string "para mostrar que me venciste.$"

CeruleanCity_Gym_Text_DianaIntro::
    .string "¿Qué? ¿Tú?\n"
    .string "¡Soy demasiado buena para tí!\p"
    .string "MISTY no tendrá que molestarse.$"

CeruleanCity_Gym_Text_DianaDefeat::
    .string "¡Me aplastaste!$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "Tienes que luchar contra otros\n"
    .string "ENTRENADORES para ver que tan\l"
    .string "buen{OA} eres realmente.$"

CeruleanCity_Gym_Text_LuisIntro::
    .string "¡Splash!\p"
    .string "¡Soy el primero!\n"
    .string "¡Hagámoslo!$"

CeruleanCity_Gym_Text_LuisDefeat::
    .string "¡No puede ser!$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "MISTY es una ENTRENADORA que va\n"
    .string "a seguir mejorando.\p"
    .string "¡No perderá contra alguien cómo tú!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
    .string "¡Yo!\n"
    .string "¡Futur{OA} campe{ONONA}!\p"
    .string "¡Dejáme darte un consejo!\p"
    .string "La LÍDER, MISTY, es una profesional\n"
    .string "que usa POKéMON de tipo AGUA.\p"
    .string "Puedes drenar toda su agua con\n"
    .string "POKéMON de tipo PLANTA.\p"
    .string "¡O, puedes usar POKéMON de tipo\n"
    .string "ELÉCTRICO para dejarlos fritos!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
    .string "¡Venciste a MISTY!\n"
    .string "¿Ves, que te dije?\p"
    .string "¡Tú y yo, niñ{OA}, hacemos un\n"
    .string "equipo bastante bueno!$"

CeruleanCity_Gym_Text_GymStatue::
    .string "GIMNASIO POKéMON DE CELESTE\n"
    .string "LÍDER: MISTY\p"
    .string "ENTRENADORES VICTORIOSOS:\n"
    .string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "GIMNASIO POKéMON DE CELESTE\n"
    .string "LÍDER: MISTY\p"
    .string "ENTRENADORES VICTORIOSOS:\n"
    .string "{RIVAL}, {PLAYER}$"

