FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .string "Uh…\n"
    .string "Oh, sí, soy el OLVIDA MOVIMIENTOS.\p"
    .string "Puedo hacer que los POKéMON\n"
    .string "olviden sus movimientos.\p"
    .string "¿Quieres que haga eso?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
    .string "¿Qué POKéMON debería olvidar un\n"
    .string "movimiento?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
    .string "¿Qué movimiento debería olvidar?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
    .string "Parece que {STR_VAR_1} solo conoce\n"
    .string "un movimiento…$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
    .string "¡Hm! ¿{STR_VAR_2} de\n"
    .string "{STR_VAR_1}?\p"
    .string "¿Debería olvidar ese movimiento?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
    .string "¡Funcionó a la perfección!\p"
    .string "{STR_VAR_1} olvidó\n"
    .string "{STR_VAR_2} por completo.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
    .string "Ven de nuevo si hace falta olvidar\n"
    .string "más movimientos.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
    .string "¿Qué?\n"
    .string "Ningún HUEVO debería conocer un\l"
    .string "movimiento.$"

