Text_DreamEaterTeach::
    .string "¡Uaaaahuuh!\n"
    .string "Debí haberme dormido al sol.\p"
    .string "Tuvé este sueño raro sobre un\n"
    .string "DROWZEE comiendose mi sueño.\p"
    .string "Y…\n"
    .string "Aprendí como comer sueños…\p"
    .string "¡Agh, esto es demasiado aterrador!\p"
    .string "¡Dejame enseñarselo a un POKéMON\n"
    .string "para que pueda olvidarlo!$"

Text_DreamEaterDeclined::
    .string "…Jjrrrrr…$"

Text_DreamEaterWhichMon::
    .string "¿Qué POKéMON quiere aprender\n"
    .string "COME SUEÑOS?$"

Text_DreamEaterTaught::
    .string "…ZZZ…\n"
    .string "No…puedo comer…más…$"

PewterCity_Text_ClefairyCameFromMoon::
    .string "Hay un rumor que dice que los\n"
    .string "CLEFAIRY vienen de la luna.\p"
    .string "Aparecieron tras la caída de\n"
    .string "PIEDRAS LUNARES en el MONTE LUNA.$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "No hay muchos ENTRENADORES de\n"
    .string "POKéMON serios aquí.\p"
    .string "Todos son como los CAZA INSECTOS,\n"
    .string "tú sabes, solo aficionados.\p"
    .string "Pero BROCK, del GIMNASIO de\n"
    .string "PLATEADA no es así, ni un poco.$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "¿Has estado en el MUSEO?$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "¿No eran geniales esos fósiles\n"
    .string "del MONTE LUNA?$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "¿En serio?\n"
    .string "¡Pues tienes que ir!$"

PewterCity_Text_ThisIsTheMuseum::
    .string "Este es el MUSEO.\p"
    .string "Tienes que pagar para entrar, pero\n"
    .string "vale la pena. ¡Te veo luego!$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "¡Pssss!\n"
    .string "¿Sabes que estoy haciendo?$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "¡Es verdad!\n"
    .string "¡Es un trabajo duro!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "¡Estoy rociando REPELENTE para\n"
    .string "echar a los POKéMON de mi jardín!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
    .string "¿Eres un{A} ENTRENADOR{AM}, cierto?\p"
    .string "BROCK está buscando a nuevos\n"
    .string "adversarios. ¡Sígueme!$"

PewterCity_Text_GoTakeOnBrock::
    .string "¡Si eres valiente,\n"
    .string "enfréntate a BROCK!$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "Todo POKéMON que luche en batalla\n"
    .string "ganará PUNTOS DE EXPERIENCIA.$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "¡AVISO!\p"
    .string "¡Unos ladrones han estado robando\n"
    .string "fósiles del MONTE LUNA!\p"
    .string "Por favor llama a la POLICÍA de\n"
    .string "CIUDAD PLATEADA si sabes algo.$"

PewterCity_Text_MuseumOfScience::
    .string "MUSEO DE LA CIENCIA DE\n"
    .string "CIUDAD PLATEADA$"

PewterCity_Text_GymSign::
    .string "LÍDER de GIMNASIO POKéMON\n"
    .string "de CIUDAD PLATEADA: BROCK\l"
    .string "¡El ENTRENADOR duro como roca!$"

PewterCity_Text_CitySign::
    .string "CIUDAD PLATEADA\n"
    .string "Una ciudad de roca grisácea.$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
    .string "あッれー！\n"
    .string "その　ジムバッジ‥‥\l"
    .string "すげえな　タケシに　かったのかよ！\p"
    .string "かんどう　したから\n"
    .string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully::
    .string "なかには　きのみが　はいってるぜ\p"
    .string "やくに　たつ　きのみも\n"
    .string "はいって　いるから\l"
    .string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
    .string "ポケモンに　きのみを\n"
    .string "もたせて　おけば\l"
    .string "たたかっている　ときに\l"
    .string "かってに　つかって　くれるんだ\p"
    .string "キズぐすり　とか　どくけし　より\n"
    .string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer::
    .string "¡Oh, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis::
    .string "Menos mal que te alcancé.\n"
    .string "Soy un AYUDANTE del PROFESOR OAK.\p"
    .string "Me pidieron que te diera esto,\n"
    .string "aquí tienes.$"

PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "{PLAYER} recibió las\n"
    .string "DEPORTIVAS del AYUDANTE.$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "{PLAYER} se puso las\n"
    .string "DEPORTIVAS.$"

PewterCity_Text_ExplainRunningShoes::
    .string "Presiona el Botón B para correr.\n"
    .string "¡Pero sólo donde haya espacio!$"

PewterCity_Text_MustBeGoingBackToLab::
    .string "Bueno, debo regresar al\n"
    .string "LABORATORIO.\p"
    .string "¡Hasta luego!$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "Hay una nota pegada…\p"
    .string "Querid{OA} {PLAYER},\p"
    .string "Aquí hay un par de DEPORTIVAS\n"
    .string "para mi amad{OA} retador{A}.\p"
    .string "Recuerda, ¡siempre te daré ánimos!\n"
    .string "¡Nunca te rindas!\p"
    .string "Mamá$"

