PokemonTower_3F_Text_HopeIntro::
    .string "Arrg… Awaa…\n"
    .string "Juju… Graa…$"

PokemonTower_3F_Text_HopeDefeat::
    .string "¡Wa!\n"
    .string "¡Me salvé!$"

PokemonTower_3F_Text_HopePostBattle::
    .string "Los fantasmas pueden ser\n"
    .string "identificados con el VISOR SILPH.$"

PokemonTower_3F_Text_CarlyIntro::
    .string "Jejeje…\n"
    .string "¡Waaah!$"

PokemonTower_3F_Text_CarlyDefeat::
    .string "¿Hmm?\n"
    .string "¿Qué estoy haciendo?$"

PokemonTower_3F_Text_CarlyPostBattle::
    .string "¡Lo siento!\n"
    .string "¡Estaba poseída!$"

PokemonTower_3F_Text_PatriciaIntro::
    .string "¡Largo!\n"
    .string "¡Espíritu maligno!$"

PokemonTower_3F_Text_PatriciaDefeat::
    .string "¡Fíu!\n"
    .string "¡El espíritu se fue!$"

PokemonTower_3F_Text_PatriciaPostBattle::
    .string "Las otras arriba…\n"
    .string "Seguro fueron poseídas.$"

