Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough::
    .string "¡Hola! ¿me recuerdas?\n"
    .string "Soy uno de los AYUDANTES del\l"
    .string "PROF. OAK.\p"
    .string "Si tu POKéDEX tiene datos completos\n"
    .string "de {STR_VAR_1} especies, se supone que\l"
    .string "debería darte una recompensa.\p"
    .string "El PROF. OAK me encargo un\n"
    .string "{STR_VAR_2} para ti.\p"
    .string "Entonces, {PLAYER}, dime algo.\p"
    .string "¿Ya recolectaste datos de al menos\n"
    .string "{STR_VAR_1} tipos de POKéMON?$"

Route15_WestEntrance_2F_Text_GreatHereYouGo::
    .string "¡Bien! ¡atrapaste u obtuviste\n"
    .string "{STR_VAR_3} tipos de POKéMON!\p"
    .string "¡Felicidades!\n"
    .string "¡Aquí tienes!$"

Route15_WestEntrance_2F_Text_ReceivedItemFromAide::
    .string "{PLAYER} recibió {STR_VAR_2}\n"
    .string "del AYUDANTE.$"

Route15_WestEntrance_2F_Text_ExplainExpShare::
    .string "REPARTIR EXP. es un objeto que\n"
    .string "debe llevar un POKéMON.\p"
    .string "El POKéMON recibirá parte de los\n"
    .string "puntos de EXP. obtenidos en\l"
    .string "batalla sin tener que luchar.$"

Route15_WestEntrance_2F_Text_LargeShiningBird::
    .string "Veamos lo que estos binoculares\n"
    .string "tienen para mostrar…\p"
    .string "Un ave grande y brillante está\n"
    .string "volando hacia el mar.$"

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon::
    .string "Veamos lo que estos binoculares\n"
    .string "tienen para mostrar…\p"
    .string "¡Parece que hay una pequeña isla\n"
    .string "en el horizonte!$"

