SilphCo_9F_Text_YouShouldTakeQuickNap::
    .string "Te ves cansad{OA}.\n"
    .string "Deberías tomar una pequeña siesta.$"

SilphCo_9F_Text_DontGiveUp::
    .string "¡No te rindas!$"

SilphCo_9F_Text_ThankYouSoMuch::
    .string "Muchísimas gracias.$"

SilphCo_9F_Text_Grunt1Intro::
    .string "¡Parece que tus POKéMON te adoran,\n"
    .string "niñ{OA}!$"

SilphCo_9F_Text_Grunt1Defeat::
    .string "¡Gaaah!$"

SilphCo_9F_Text_Grunt1PostBattle::
    .string "Si hubiera empezado como\n"
    .string "ENTRENADOR a tu edad…$"

SilphCo_9F_Text_EdIntro::
    .string "¡Tús POKéMON tienen puntos\n"
    .string "débiles! ¡Puedo verlos!$"

SilphCo_9F_Text_EdDefeat::
    .string "¡Me destruiste!$"

SilphCo_9F_Text_EdPostBattle::
    .string "Explotar puntos débiles funciona.\n"
    .string "Piensa en las ventajas de tipos.$"

SilphCo_9F_Text_Grunt2Intro::
    .string "¡Soy uno de los cuatro HERMANOS\n"
    .string "ROCKET!$"

SilphCo_9F_Text_Grunt2Defeat::
    .string "¡Arg!\n"
    .string "¡Hermanos, perdí!$"

SilphCo_9F_Text_Grunt2PostBattle::
    .string "¡Mis hermanos me vengarán!$"

SilphCo_9F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P9$"

