SSAnne_2F_Room3_Text_SeenMonsFerryPeople:: @ 8173E3A
    .string "¡Ah, sí, he visto a varios POKéMON\n"
    .string "cargar gente a través del agua!$"

SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown:: @ 8173E7B
    .string "Los árboles pequeños pueden\n"
    .string "cortarse con el movimiento CORTE.\p"
    .string "¡Pero recuerda esto!\n"
    .string "CORTE es una técnica de MO.\p"
    .string "Una vez aprendida, no es fácil\n"
    .string "de olvidar.$"

