Route25_Text_JoeyIntro:: @ 81890C0
    .string "ENTRENADORES locales vienen aquí\n"
    .string "a practicar.$"

Route25_Text_JoeyDefeat:: @ 81890E6
    .string "Eres decente.$"

Route25_Text_JoeyPostBattle:: @ 81890F5
    .string "Cada POKéMON tienen debilidades.\n"
    .string "Incluso los más fuertes.\p"
    .string "Es por eso que es mejor criar a\n"
    .string "POKéMON de diferentes tipos.$"

Route25_Text_DanIntro:: @ 8189165
    .string "Papá me llevó a una gran fiesta en\n"
    .string "el SANTA ANA en CIUDAD CARMÍN.$"

Route25_Text_DanDefeat:: @ 81891A6
    .string "¡No estoy enojado!$"

Route25_Text_DanPostBattle:: @ 81891B3
    .string "En el SANTA ANA, ví ENTRENADORES\n"
    .string "de todas partes del mundo.$"

Route25_Text_FlintIntro:: @ 81891EB
    .string "Soy un chico genial.\n"
    .string "¡Tengo una novia!$"

Route25_Text_FlintDefeat:: @ 8189212
    .string "Aww, rayos…$"

Route25_Text_FlintPostBattle:: @ 818921D
    .string "Oh, bueno.\n"
    .string "Mi novia me animará.$"

Route25_Text_KelseyIntro:: @ 8189247
    .string "¡Hola!\n"
    .string "¡Mi novio es genial!$"

Route25_Text_KelseyDefeat:: @ 8189261
    .string "No estoy en la mejor forma…$"

Route25_Text_KelseyPostBattle:: @ 8189281
    .string "Ojalá mi novio fuera tan bueno\n"
    .string "cómo tu.$"

Route25_Text_ChadIntro:: @ 81892A9
    .string "Tenía esta sensación…\n"
    .string "¡Sabía que tenía que enfrentarte!$"

Route25_Text_ChadDefeat:: @ 81892D9
    .string "¡También sabía que perdería!$"

Route25_Text_ChadPostBattle:: @ 81892EF
    .string "Si tu POKéMON está confuso en\n"
    .string "batalla, usa a otro en su lugar.\p"
    .string "Esa es una buena táctica.$"

Route25_Text_HaleyIntro:: @ 8189333
    .string "Mi amigo tiene muchos POKéMON\n"
    .string "lindos. ¡Me da mucha envidia!$"

Route25_Text_HaleyDefeat:: @ 8189364
    .string "¡No tengo tanta envidia!$"

Route25_Text_HaleyPostBattle:: @ 8189378
    .string "¿Vienes del MONTE LUNA?\n"
    .string "¿Me podrías dar un CLEFAIRY?$"

Route25_Text_FranklinIntro:: @ 81893A7
    .string "Acabo de bajar del MONTE LUNA,\n"
    .string "¡pero aún me queda energía!$"

Route25_Text_FranklinDefeat:: @ 81893EA
    .string "¡Trabajaste duro!$"

Route25_Text_FranklinPostBattle:: @ 81893FB
    .string "¡Rayos!\n"
    .string "Un ZUBAT me mordió en esa cueva.$"

Route25_Text_NobIntro:: @ 8189423
    .string "Voy a ver la colección de un\n"
    .string "POKéMANÍACO en el cabo.$"

Route25_Text_NobDefeat:: @ 8189459
    .string "Me venciste, ¡y además lo hiciste\n"
    .string "muy bien!$"

Route25_Text_NobPostBattle:: @ 818947E
    .string "Ese POKéMANÍACO si que le es fiel\n"
    .string "a su nombre.\p"
    .string "Su colección incluye muchas\n"
    .string "especies raras de POKéMON.$"

Route25_Text_WayneIntro:: @ 81894DE
    .string "¿Vas a ver a BILL?\n"
    .string "¡Primero, luchemos!$"

Route25_Text_WayneDefeat:: @ 818950A
    .string "Me rindo.$"

Route25_Text_WaynePostBattle:: @ 818951C
    .string "La ruta debajo es un atajo a\n"
    .string "CUIDAD CELESTE.$"

Route25_Text_SeaCottageSign:: @ 818954C
    .string "CASA DEL MAR\n"
    .string "¡BILL vive aquí!$"

Route25_Text_MistyHighHopesAboutThisPlace:: @ 8189569
    .string "Este cabo es famoso para las citas.\p"
    .string "MISTY, la LÍDER DE GIMNASIO, tiene\n"
    .string "altas esperanzas sobre este lugar.$"

Route25_Text_AreYouHereAlone:: @ 81895C2
    .string "Hola, ¿estás sol{OA}?\p"
    .string "Si estás en el CABO CELESTE…\n"
    .string "Bueno, debería ser con una pareja.$"

