Route25_Text_JoeyIntro::
    .string "ENTRENADORES locales vienen aquí\n"
    .string "a practicar.$"

Route25_Text_JoeyDefeat::
    .string "Eres decente.$"

Route25_Text_JoeyPostBattle::
    .string "Cada POKéMON tienen debilidades.\n"
    .string "Incluso los más fuertes.\p"
    .string "Es por eso que es mejor criar a\n"
    .string "POKéMON de diferentes tipos.$"

Route25_Text_DanIntro::
    .string "Papá me llevó a una gran fiesta en\n"
    .string "el SANTA ANA en CIUDAD CARMÍN.$"

Route25_Text_DanDefeat::
    .string "¡No estoy enojado!$"

Route25_Text_DanPostBattle::
    .string "En el SANTA ANA, ví ENTRENADORES\n"
    .string "de todas partes del mundo.$"

Route25_Text_FlintIntro::
    .string "Soy un chico genial.\n"
    .string "¡Tengo una novia!$"

Route25_Text_FlintDefeat::
    .string "Aww, rayos…$"

Route25_Text_FlintPostBattle::
    .string "Oh, bueno.\n"
    .string "Mi novia me animará.$"

Route25_Text_KelseyIntro::
    .string "¡Hola!\n"
    .string "¡Mi novio es genial!$"

Route25_Text_KelseyDefeat::
    .string "No estoy en la mejor forma…$"

Route25_Text_KelseyPostBattle::
    .string "Ojalá mi novio fuera tan bueno\n"
    .string "cómo tu.$"

Route25_Text_ChadIntro::
    .string "Tenía esta sensación…\n"
    .string "¡Sabía que tenía que enfrentarte!$"

Route25_Text_ChadDefeat::
    .string "¡También sabía que perdería!$"

Route25_Text_ChadPostBattle::
    .string "Si tu POKéMON está confuso en\n"
    .string "batalla, usa a otro en su lugar.\p"
    .string "Esa es una buena táctica.$"

Route25_Text_HaleyIntro::
    .string "Mi amigo tiene muchos POKéMON\n"
    .string "lindos. ¡Me da mucha envidia!$"

Route25_Text_HaleyDefeat::
    .string "¡No tengo tanta envidia!$"

Route25_Text_HaleyPostBattle::
    .string "¿Vienes del MONTE LUNA?\n"
    .string "¿Me podrías dar un CLEFAIRY?$"

Route25_Text_FranklinIntro::
    .string "Acabo de bajar del MONTE LUNA,\n"
    .string "¡pero aún me queda energía!$"

Route25_Text_FranklinDefeat::
    .string "¡Trabajaste duro!$"

Route25_Text_FranklinPostBattle::
    .string "¡Rayos!\n"
    .string "Un ZUBAT me mordió en esa cueva.$"

Route25_Text_NobIntro::
    .string "Voy a ver la colección de un\n"
    .string "POKéMANÍACO en el cabo.$"

Route25_Text_NobDefeat::
    .string "Me venciste, ¡y además lo hiciste\n"
    .string "muy bien!$"

Route25_Text_NobPostBattle::
    .string "Ese POKéMANÍACO si que le es fiel\n"
    .string "a su nombre.\p"
    .string "Su colección incluye muchas\n"
    .string "especies raras de POKéMON.$"

Route25_Text_WayneIntro::
    .string "¿Vas a ver a BILL?\n"
    .string "¡Primero, luchemos!$"

Route25_Text_WayneDefeat::
    .string "Me rindo.$"

Route25_Text_WaynePostBattle::
    .string "La ruta debajo es un atajo a\n"
    .string "CUIDAD CELESTE.$"

Route25_Text_SeaCottageSign::
    .string "CASA DEL MAR\n"
    .string "¡BILL vive aquí!$"

Route25_Text_MistyHighHopesAboutThisPlace::
    .string "Este cabo es famoso para las citas.\p"
    .string "MISTY, la LÍDER DE GIMNASIO, tiene\n"
    .string "altas esperanzas sobre este lugar.$"

Route25_Text_AreYouHereAlone::
    .string "Hola, ¿estás sol{OA}?\p"
    .string "Si estás en el CABO CELESTE…\n"
    .string "Bueno, debería ser con una pareja.$"

