ThreeIsland_Port_Text_WereKantoRiderFederation::
    .string "¡Somos la FEDERACIÓN\n"
    .string "MOTORISTA DE KANTO!\p"
    .string "¡Vrrun! ¡Vavavavuuum! ¡Vrrun!\p"
    .string "¡Mi moto es débil, por eso hago\n"
    .string "los ruidos del escape yo mismo!$"

ThreeIsland_Port_Text_ForkOverMoney::
    .string "¡Ey, ey, señora!\n"
    .string "¡Denos algo de dinero!$"

ThreeIsland_Port_Text_IllCallThePolice::
    .string "¡Ahhhhh!\p"
    .string "¡¿Qu-Quienes son?!\n"
    .string "Vo… ¡voy a llamar a la policía!$"

ThreeIsland_Port_Text_ThankGoodnessBikersGone::
    .string "Esos MOTORISTAS…\n"
    .string "¿Se han ido?\p"
    .string "¡Oh, qué suerte!\n"
    .string "¡Me habían dejado horrorizada!$"

ThreeIsland_Port_Text_EverythingTurnedOutForBest::
    .string "Esos MOTORISTAS huyeron,\n"
    .string "y LOSTELLE fue encontrada a salvo.\p"
    .string "¡Todo termino bien!$"

