PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround:: @ 818DC67
    .string "{RIVAL}: Oh, ¿solo eres tú, {PLAYER}?\n"
    .string "El abuelo no está.$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting:: @ 818DC94
    .string "{RIVAL}: ¡Abuelo!\n"
    .string "¡Estoy harto de esperar!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe:: @ 818DCB9
    .string "{RIVAL}: ¡Oye! ¡Abuelo, no es justo!\n"
    .string "¿Y yo qué?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer:: @ 818DCE2
    .string "{RIVAL}: Je, no necesito ser un\n"
    .string "avaro como tu. ¡Soy maduro!\p"
    .string "¡Adelántate y elige, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen:: @ 818DD34
    .string "{RIVAL}: ¡Entonces, tomaré este!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak:: @ 818DD52
    .string "¡{RIVAL} recibió el {STR_VAR_1}\n"
    .string "del PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher:: @ 818DD75
    .string "{RIVAL}: Mi POKéMON parece ser\n"
    .string "mucho más fuerte que el tuyo.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons:: @ 818DDA4
    .string "{RIVAL}: ¡Espera, {PLAYER}!\n"
    .string "¡Probemos a nuestros POKéMON!\p"
    .string "¡Vamos, te venceré!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat:: @ 818DDEA
    .string "¿QUÉ?\n"
    .string "¡Increíble!\l"
    .string "¡Escogí al POKéMON equivocado!$"

@ Also used for early Route 22 battle
Text_RivalVictory:: @ 818DE1A
    .string "{RIVAL}: ¡Si!\n"
    .string "¿Soy grandioso o que?$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon:: @ 818DE38
    .string "{RIVAL}: ¡Bien! ¡Haré que mi\n"
    .string "POKéMON luche para fortalecerlo!\p"
    .string "¡{PLAYER}! ¡Abuelo!\n"
    .string "¡Hasta luego!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps:: @ 818DE8D
    .string "{RIVAL}: ¡Abuelo!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor:: @ 818DE99
    .string "{RIVAL}: ¡Casi lo olvidaba!\n"
    .string "¿Para que me llamaste?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps:: @ 818DEC8
    .string "{RIVAL}: ¡Está bien, abuelo!\n"
    .string "¡Déjamelo a mí!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap:: @ 818DEF3
    .string "{PLAYER}, odio decirlo, pero no\n"
    .string "necesito tu ayuda para esto.\p"
    .string "¡Ya sé! ¡Le pediré prestado un\n"
    .string "MAPA a mi hermana!\p"
    .string "¡Y le diré que no te dé ninguno\n"
    .string "a ti, {PLAYER}! ¡Jajaja!\p"
    .string "¡No te molestes en ir a mi casa\n"
    .string "después de esto!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne:: @ 818DFBC
    .string "OAK: ¿{RIVAL}?\n"
    .string "Déjame pensar…\p"
    .string "Oh, cierto, ¡te pedí que vinieras!\n"
    .string "¡Solo espera!\p"
    .string "{PLAYER}, toma.\p"
    .string "Aquí hay tres POKéMON.\p"
    .string "¡Jaja!\p"
    .string "Los POKéMON están dentro de\n"
    .string "estás POKéBOLAS.\p"
    .string "Cuando yo era joven, fui un\n"
    .string "buen ENTRENADOR de POKéMON.\p"
    .string "Pero ahora, en mi vejez, solo\n"
    .string "me quedan estos tres.\p"
    .string "Puedes tener uno de ellos.\n"
    .string "¡Adelante, elige!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival:: @ 818E0EA
    .string "OAK: Se paciente, {RIVAL}.\n"
    .string "¡También puedes tener uno!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose:: @ 818E116
    .string "OAK: Ahora, {PLAYER}.\p"
    .string "Esas tres POKéBOLAS contienen\n"
    .string "un POKéMON cada una.\p"
    .string "¿Cuál es el que vas a elegir\n"
    .string "para ti?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet:: @ 818E177
    .string "OAK: ¡Oye!\n"
    .string "¡No te vayas aún!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander:: @ 818E194
    .string "¡Ah! Tu elección es CHARMANDER.\n"
    .string "Debes criarlo con paciencia.\p"
    .string "Así que, {PLAYER}, ¿reclamas a\n"
    .string "CHARMANDER, POKéMON de tipo FUEGO?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle:: @ 818E207
    .string "¡Hm! Tu elección es SQUIRTLE.\n"
    .string "Criarlo vale la pena.\p"
    .string "Así que, {PLAYER}, ¿te decides por\n"
    .string "SQUIRTLE, POKéMON de tipo AGUA?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur:: @ 818E272
    .string "¡Ya veo! Tu elección es BULBASAUR.\n"
    .string "Criarlo es muy fácil.\p"
    .string "Así que, {PLAYER}, ¿quieres a\n"
    .string "BULBASAUR, POKéMON de tipo PLANTA?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic:: @ 818E2E5
    .string "¡Este POKéMON tiene mucha energía!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak:: @ 818E30D
    .string "¡{PLAYER} recibió {STR_VAR_1}\n"
    .string "del PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon:: @ 818E330
    .string "OAK: Si un POKéMON aparece,\n"
    .string "tu POKéMON podrá luchar contra él.\p"
    .string "Junto a tu POKéMON, deberías poder\n"
    .string "llegar al siguiente pueblo.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow:: @ 818E3AD
    .string "OAK: {PLAYER}, entrena a tu joven\n"
    .string "POKéMON luchando.\p"
    .string "Necesita luchar para poder crecer.$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe:: @ 818E405
    .string "OAK: ¡Oh, {PLAYER}!\n"
    .string "¿Como esta mi viejo POKéMON?\p"
    .string "Creo que se esta volviendo más\n"
    .string "apegado a ti.\p"
    .string "Pareces tener talento como\n"
    .string "ENTRENADOR{AM} POKéMON.\p"
    .string "¿Qué es eso?\n"
    .string "¿Tienes algo para mí?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel:: @ 818E4AF
    .string "{PLAYER} entregó el PAQUETE DE OAK.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered:: @ 818E4CA
    .string "¡Ah!\n"
    .string "¡Es la POKéBOLA perzonalizada!\p"
    .string "Ya la había encargado.\n"
    .string "¡Gracias!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo:: @ 818E508
    .string "OAK: ¡Ah, sí!\n"
    .string "Quiero perdirles un favor.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk:: @ 818E536
    .string "¡Aquí en el escritorio esta un\n"
    .string "invento mío, la POKéDEX!\p"
    .string "Registra automáticamente datos\n"
    .string "sobre los POKéMON que hayan\l"
    .string "visto o capturado.\p"
    .string "Es una enciclopedia de alta\n"
    .string "tecnología.$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou:: @ 818E5C5
    .string "OAK: {PLAYER} y {RIVAL}.\n"
    .string "Tomen estas con ustedes.$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak:: @ 818E5EA
    .string "{PLAYER} recibió la POKéDEX\n"
    .string "del PROF. OAK.$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese:: @ 818E612
    .string "OAK: No puedes obtener datos\n"
    .string "detallados de los POKéMON con\l"
    .string "sólo verlos.\p"
    .string "Necesitas atraparlos para\n"
    .string "obtener datos completos.\p"
    .string "Aquí hay algunas herramientas para\n"
    .string "atrapar POKéMON salvajes.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls:: @ 818E6B3
    .string "{PLAYER} recibió cinco POKéBOLAS.$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching:: @ 818E6D0
    .string "Cuando aparezca un POKéMON\n"
    .string "salvaje, todo vale.\p"
    .string "¡Solo lanza una POKéBOLA\n"
    .string "e intenta atraparlo!\p"
    .string "Pero esto no siempre funciona.\p"
    .string "Un POKéMON sano puede huir.\n"
    .string "¡Tienes que tener suerte!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream:: @ 818E784
    .string "Crear una guía completa de todos\n"
    .string "los POKéMON en el mundo…\p"
    .string "¡Ese era mi sueño!\p"
    .string "Pero ya soy muy viejo.\n"
    .string "No puedo hacerlo.\p"
    .string "Por eso, quiero que ustedes dos\n"
    .string "hagan realidad ese sueño por mí.\p"
    .string "Adelante, ustedes dos.\p"
    .string "¡Está es una gran iniciativa en\n"
    .string "la historia de los POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait:: @ 818E871
    .string "¡Los POKéMON alrededor del mundo\n"
    .string "te están esperando, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex:: @ 818E89C
    .string "Ah, {PLAYER}!\n"
    .string "How is your POKéDEX shaping up?\p"
    .string "{RIVAL} has already caught some\n"
    .string "POKéMON and added to the data.\p"
    .string "So, {PLAYER}, let's have a look at\n"
    .string "your POKéDEX.\p"
    .string "…What's the matter?\n"
    .string "You've added no new data at all.\p"
    .string "I'll give you these, so do try a\n"
    .string "little harder.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime:: @ 818E98E
    .string "OAK: Come see me sometime.\p"
    .string "After all, I want to know how your\n"
    .string "POKéDEX is coming along.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia:: @ 818E9E5
    .string "Es como una enciclopedia, pero\n"
    .string "las páginas están en blanco.$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls:: @ 818EA19
    .string "Esas de ahí son POKéBOLAS.\n"
    .string "¡Dentro de ellas hay POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon:: @ 818EA45
    .string "Ese es el último POKéMON\n" 
    .string "del PROF. OAK.$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu:: @ 818EA66
    .string "¡Presiona START para abrir el MENÚ!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu:: @ 818EA84
    .string "La opción de GUARDAR está en\n"
    .string "el MENÚ. Usala regularmente.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints:: @ 818EAB6
    .string "Todo POKéMON tiene sus puntos\n"
    .string "fuertes y débiles frente al resto.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage:: @ 818EAF4
    .string "Aquí hay un correo electronico.\p"
    .string "…\p"
    .string "¡Al fin!\n"
    .string "¡Los ENTRENADORES de élite de la\l"
    .string "LIGA POKéMON están listos para\l"
    .string "desafiar al que se presente!\p"
    .string "¡Traigan a sus mejores POKéMON\n"
    .string "para pobrar su habilidad!\p"
    .string "CG de la LIGA POKéMON\n"
    .string "MESETA AÑIL\p"
    .string "¡PROF. OAK, por favor visítenos!\n"
    .string "…$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide:: @ 818EBE6
    .string "Estudio a los POKéMON como\n"
    .string "AYUDANTE del PROF. OAK.$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons:: @ 818EC0B
    .string "Hi, {PLAYER}. I bet you've become\n"
    .string "good friends with your POKéMON.\p"
    .string "By the way, did you know about\n"
    .string "DAISY?\p"
    .string "If you show DAISY your POKéMON,\n"
    .string "she can tell how much it likes you.\p"
    .string "Occasionally, she will even groom\n"
    .string "a POKéMON for you.\p"
    .string "This is a secret, so please don't\n"
    .string "tell anyone.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow:: @ 818ED15
    .string "PROF. OAK is going to have his own\n"
    .string "radio show soon.\p"
    .string "The program will be called PROF.\n"
    .string "OAK's POKéMON SEMINAR.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons:: @ 818ED81
    .string "Puede que el PROF. OAK no parezca\n"
    .string "gran cosa, pero él es la autoridad\l"
    .string "en POKéMON.\p"
    .string "Es altamente apreciado por\n"
    .string "muchos ENTRENADORES POKéMON.$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer:: @ 818EDF5
    .string "Ah, now this is excellent!\p"
    .string "{PLAYER}, I have another important\n"
    .string "favor to ask of you.\p"
    .string "I need you to listen closely.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons:: @ 818EE60
    .string "Recently, there have been sightings\n"
    .string "of many rare POKéMON species.\p"
    .string "I'm talking about POKéMON that\n"
    .string "have never been seen in KANTO.\p"
    .string "I would love to go see things for\n"
    .string "myself, but I'm much too old.\p"
    .string "Since I can't do it, {PLAYER}, I'd\n"
    .string "like you to go in my place.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything:: @ 818EF59
    .string "{RIVAL}: Hey, I heard that!\p"
    .string "Gramps, what's with favoring\n"
    .string "{PLAYER} over me all the time?\p"
    .string "I went and collected more POKéMON,\n"
    .string "and faster, too.\p"
    .string "You should just let me handle\n"
    .string "everything.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes:: @ 818F004
    .string "OAK: I know, I know.\n"
    .string "Of course I need your help, too.\p"
    .string "Now, I need to see both your\n"
    .string "POKéDEXES.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits:: @ 818F062
    .string "PROF. OAK took both POKéDEX\n"
    .string "units.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData:: @ 818F085
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "…And that's done!\p"
    .string "Now these units can record data on\n"
    .string "a lot more POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded:: @ 818F0E8
    .string "{PLAYER}'s POKéDEX was upgraded!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex:: @ 818F103
    .string "Now, {PLAYER} and {RIVAL}!\p"
    .string "This time, you really must work\n"
    .string "towards filling your POKéDEXES.\p"
    .string "I urge you to make them the best\n"
    .string "and the most complete of all time!\p"
    .string "Truly, this is a monumentally great\n"
    .string "undertaking in POKéMON history!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex:: @ 818F1DB
    .string "{RIVAL}: Gramps, calm down.\n"
    .string "Don't get so excited.\p"
    .string "I'll get the POKéDEX completed,\n"
    .string "don't you worry about a thing.\p"
    .string "I think I'll try looking around\n"
    .string "ONE ISLAND first…\p"
    .string "Anyways, I'm outta here!$"
