PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{RIVAL}: Oh, ¿solo eres tú, {PLAYER}?\n"
    .string "El abuelo no está.$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{RIVAL}: ¡Abuelo!\n"
    .string "¡Estoy harto de esperar!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{RIVAL}: ¡Oye! ¡Abuelo, no es justo!\n"
    .string "¿Y yo qué?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{RIVAL}: Je, no necesito ser un\n"
    .string "avaro como tu. ¡Soy maduro!\p"
    .string "¡Adelántate y elige, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{RIVAL}: ¡Entonces, tomaré este!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "¡{RIVAL} recibió el {STR_VAR_1}\n"
    .string "del PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{RIVAL}: Mi POKéMON parece ser\n"
    .string "mucho más fuerte que el tuyo.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{RIVAL}: ¡Espera, {PLAYER}!\n"
    .string "¡Probemos a nuestros POKéMON!\p"
    .string "¡Vamos, te venceré!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "¿QUÉ?\n"
    .string "¡Increíble!\l"
    .string "¡Escogí al POKéMON equivocado!$"

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "{RIVAL}: ¡Si!\n"
    .string "¿Soy grandioso o que?$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{RIVAL}: ¡Bien! ¡Haré que mi\n"
    .string "POKéMON luche para fortalecerlo!\p"
    .string "¡{PLAYER}! ¡Abuelo!\n"
    .string "¡Hasta luego!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: ¡Abuelo!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: ¡Casi lo olvidaba!\n"
    .string "¿Para que me llamaste?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: ¡Está bien, abuelo!\n"
    .string "¡Déjamelo a mí!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "{PLAYER}, odio decirlo, pero no\n"
    .string "necesito tu ayuda para esto.\p"
    .string "¡Ya sé! ¡Le pediré prestado un\n"
    .string "MAPA a mi hermana!\p"
    .string "¡Y le diré que no te dé ninguno\n"
    .string "a ti, {PLAYER}! ¡Jajaja!\p"
    .string "¡No te molestes en ir a mi casa\n"
    .string "después de esto!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "OAK: ¿{RIVAL}?\n"
    .string "Déjame pensar…\p"
    .string "Oh, cierto, ¡te pedí que vinieras!\n"
    .string "¡Solo espera!\p"
    .string "{PLAYER}, toma.\p"
    .string "Aquí hay tres POKéMON.\p"
    .string "¡Jaja!\p"
    .string "Los POKéMON están dentro de\n"
    .string "estás POKéBOLAS.\p"
    .string "Cuando yo era joven, fui un\n"
    .string "buen ENTRENADOR de POKéMON.\p"
    .string "Pero ahora, en mi vejez, solo\n"
    .string "me quedan estos tres.\p"
    .string "Puedes tener uno de ellos.\n"
    .string "¡Adelante, elige!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "OAK: Se paciente, {RIVAL}.\n"
    .string "¡También puedes tener uno!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "OAK: Ahora, {PLAYER}.\p"
    .string "Esas tres POKéBOLAS contienen\n"
    .string "un POKéMON cada una.\p"
    .string "¿Cuál es el que vas a elegir\n"
    .string "para ti?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "OAK: ¡Oye!\n"
    .string "¡No te vayas aún!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "¡Ah! Tu elección es CHARMANDER.\n"
    .string "Debes criarlo con paciencia.\p"
    .string "Así que, {PLAYER}, ¿reclamas a\n"
    .string "CHARMANDER, POKéMON de tipo FUEGO?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "¡Hm! Tu elección es SQUIRTLE.\n"
    .string "Criarlo vale la pena.\p"
    .string "Así que, {PLAYER}, ¿te decides por\n"
    .string "SQUIRTLE, POKéMON de tipo AGUA?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "¡Ya veo! Tu elección es BULBASAUR.\n"
    .string "Criarlo es muy fácil.\p"
    .string "Así que, {PLAYER}, ¿quieres a\n"
    .string "BULBASAUR, POKéMON de tipo PLANTA?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "¡Este POKéMON tiene mucha energía!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "¡{PLAYER} recibió {STR_VAR_1}\n"
    .string "del PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "OAK: Si un POKéMON aparece,\n"
    .string "tu POKéMON podrá luchar contra él.\p"
    .string "Junto a tu POKéMON, deberías poder\n"
    .string "llegar al siguiente pueblo.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "OAK: {PLAYER}, entrena a tu joven\n"
    .string "POKéMON luchando.\p"
    .string "Necesita luchar para poder crecer.$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "OAK: ¡Oh, {PLAYER}!\n"
    .string "¿Como esta mi viejo POKéMON?\p"
    .string "Creo que se esta volviendo más\n"
    .string "apegado a ti.\p"
    .string "Pareces tener talento como\n"
    .string "ENTRENADOR{AM} POKéMON.\p"
    .string "¿Qué es eso?\n"
    .string "¿Tienes algo para mí?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} entregó el PAQUETE DE OAK.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "¡Ah!\n"
    .string "¡Es la POKéBOLA perzonalizada!\p"
    .string "Ya la había encargado.\n"
    .string "¡Gracias!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "OAK: ¡Ah, sí!\n"
    .string "Quiero perdirles un favor.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "¡Aquí en el escritorio esta un\n"
    .string "invento mío, la POKéDEX!\p"
    .string "Registra automáticamente datos\n"
    .string "sobre los POKéMON que hayan\l"
    .string "visto o capturado.\p"
    .string "Es una enciclopedia de alta\n"
    .string "tecnología.$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "OAK: {PLAYER} y {RIVAL}.\n"
    .string "Tomen estas con ustedes.$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER} recibió la POKéDEX\n"
    .string "del PROF. OAK.$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "OAK: No puedes obtener datos\n"
    .string "detallados de los POKéMON con\l"
    .string "sólo verlos.\p"
    .string "Necesitas atraparlos para\n"
    .string "obtener datos completos.\p"
    .string "Aquí hay algunas herramientas para\n"
    .string "atrapar POKéMON salvajes.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER} recibió cinco POKéBOLAS.$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "Cuando aparezca un POKéMON\n"
    .string "salvaje, todo vale.\p"
    .string "¡Solo lanza una POKéBOLA\n"
    .string "e intenta atraparlo!\p"
    .string "Pero esto no siempre funciona.\p"
    .string "Un POKéMON sano puede huir.\n"
    .string "¡Tienes que tener suerte!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "Crear una guía completa de todos\n"
    .string "los POKéMON en el mundo…\p"
    .string "¡Ese era mi sueño!\p"
    .string "Pero ya soy muy viejo.\n"
    .string "No puedo hacerlo.\p"
    .string "Por eso, quiero que ustedes dos\n"
    .string "hagan realidad ese sueño por mí.\p"
    .string "Adelante, ustedes dos.\p"
    .string "¡Está es una gran iniciativa en\n"
    .string "la historia de los POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "¡Los POKéMON alrededor del mundo\n"
    .string "te están esperando, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "¡Ah, {PLAYER}!\n"
    .string "¿Cómo va tu POKéDEX?\p"
    .string "{RIVAL} ya ha atrapado algunos\n"
    .string "POKéMON y añadió algunos datos.\p"
    .string "Entonces, {PLAYER}, déjame darle\n"
    .string "un vistazo a tu POKéDEX.\p"
    .string "…¿Qué pasa?\n"
    .string "No has añadido ni un solo dato.\p"
    .string "Te daré estas, pero intenta\n"
    .string "esforzarte más.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "OAK: Ven a verme alguna vez.\p"
    .string "Después de todo, quiero saber como\n"
    .string "avanza tu POKéDEX.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "Es como una enciclopedia, pero\n"
    .string "las páginas están en blanco.$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "Esas de ahí son POKéBOLAS.\n"
    .string "¡Dentro de ellas hay POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "Ese es el último POKéMON\n" 
    .string "del PROF. OAK.$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "¡Presiona START para abrir el MENÚ!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "La opción de GUARDAR está en\n"
    .string "el MENÚ. Usala regularmente.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "Todo POKéMON tiene sus puntos\n"
    .string "fuertes y débiles frente al resto.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "Aquí hay un correo electronico.\p"
    .string "…\p"
    .string "¡Al fin!\n"
    .string "¡Los ENTRENADORES de élite de la\l"
    .string "LIGA POKéMON están listos para\l"
    .string "desafiar al que se presente!\p"
    .string "¡Traigan a sus mejores POKéMON\n"
    .string "para pobrar su habilidad!\p"
    .string "SC de la LIGA POKéMON\n"
    .string "MESETA AÑIL\p"
    .string "¡PROF. OAK, por favor visítenos!\n"
    .string "…$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "Estudio a los POKéMON como\n"
    .string "AYUDANTE del PROF. OAK.$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "Hola, {PLAYER}. Seguro que tus\n"
    .string "POKéMON son tus amigos ahora.\p"
    .string "Por cierto, ¿conoces a DAISY?\p"
    .string "Si le enseñas tus POKéMON a DAISY,\n"
    .string "podrá decirte si les agradas o no.\p"
    .string "De vez en cuando, incluso\n"
    .string "cepillará a un POKéMON por ti.\p"
    .string "Esto es secreto, así que no le\n"
    .string "digas a nadie, por favor.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "El PROF. OAK tendrá un programa de\n"
    .string "radio pronto.\p"
    .string "El programa se llamará “SEMINARIO\n"
    .string "POKéMON DEL PROFESOR OAK.”$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "Puede que el PROF. OAK no parezca\n"
    .string "gran cosa, pero él es la autoridad\l"
    .string "en POKéMON.\p"
    .string "Es altamente apreciado por\n"
    .string "muchos ENTRENADORES POKéMON.$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "¡Ah, esto es excelente!\p"
    .string "{PLAYER}, tengo que pedirte otro\n"
    .string "favor importante.\p"
    .string "Necesito que escuches atentamente.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "Recientemente, se han avistado\n"
    .string "muchas especies raras de POKéMON.\p"
    .string "Estoy hablando de POKéMON que\n"
    .string "jamás se habían visto en KANTO.\p"
    .string "Me encantaría ir a ver por mi\n"
    .string "cuenta, pero soy demasiado viejo.\p"
    .string "Como no puedo hacerlo, {PLAYER},\n"
    .string "quisiera que fueras en mi lugar.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: ¡Ey, escuché eso!\p"
    .string "Abuelo, ¿porqué siempre prefieres\n"
    .string "a {PLAYER} que a mi?\p"
    .string "Atrapé a más POKéMON, y también\n"
    .string "más rápido.\p"
    .string "Solo deberías dejar que me\n"
    .string "encargue de todo.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "OAK: Lo sé, lo sé.\p"
    .string "Por supuesto que también necesito\n"
    .string "de tu ayuda.\p"
    .string "Ahora, necesito las POKéDEX\n"
    .string "de ambos.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "El PROF. OAK tomó ambas unidades\n"
    .string "de la POKéDEX.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "…¡Y está hecho!\p"
    .string "Ahora estas unidades pueden\n"
    .string "registrar a muchos más POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "¡La POKéDEX de {PLAYER} fue\n"
    .string "mejorada!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "Ahora, {PLAYER} y {RIVAL}.\p"
    .string "Esta vez, realmente se tienen que\n"
    .string "esforzar en llenar sus POKéDEX.\p"
    .string "¡Les insisto que las conviertan en\n"
    .string "las mejores y más completas de\l"
    .string "todos los tiempos!\p"
    .string "¡Este es un proyecto monumental en\n"
    .string "la historia de los POKéMON!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: Abuelo, cálmate.\n"
    .string "No te emociones tanto.\p"
    .string "Terminaré la POKéDEX, no te\n"
    .string "preocupes por nada.\p"
    .string "Creo que primero intentaré buscar\n"
    .string "en la ISLA PRIMA…\p"
    .string "Como sea, ¡me voy!$"

