@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull:: @ 819E890
    .string "{PLAYER}{KUN}の　バッグ\n"
    .string "いっぱい　みたい　だね$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames:: @ 819E8A6
	.string "¿No crees que es difícil pensar en\n"
	.string "buenos nombres para POKéMON?\p"
    .string "¿En especial si atrapaste\n"
    .string "a muchos?\p"
    .string "En PUEBLO LAVANDA, hay un hombre\n"
    .string "que evalúa apodos de los POKéMON.\p"
    .string "Incluso puede ayudarte a cambiar\n"
    .string "sus apodos.$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender:: @ 819E97B
    .string "Si tu objetivo es llegar a PUEBLO\n"
    .string "LAVANDA, ve por el TÚNEL ROCA.\p"
	.string "Puedes llegar al TÚNEL ROCA desde\n"
	.string "CIUDAD CELESTE.$"

