Route9_Text_AliciaIntro:: @ 81847B7
    .string "¡Tienes POKéMON contigo!\n"            /* (E) "You have POKéMON with you!\n" */
    .string "¡Eres mí{OA}!$"                        /* (E) "You're mine!$" */

Route9_Text_AliciaDefeat:: @ 81847DF
    .string "Me engañaste…$"                        /* (E) "You deceived me…$" */

Route9_Text_AliciaPostBattle:: @ 81847F0
    .string "El túnel cerca de aquí está\n"         /* (E) "The tunnel coming up is pitch-black\n" */
    .string "totalmente oscuro.\p"                  /* (E) "inside.\p" */
    .string "Necesitarás DESTELLO para poder\n"     /* (E) "You'll need FLASH to get through\n" */
    .string "cruzarlo.$"                            /* (E) "there.$" */

Route9_Text_ChrisIntro:: @ 8184844
    .string "¿Quién anda ahí con esos POKéMON\n"    /* (E) "Who's that walking there with those\n" */
    .string "de tan buen aspecto?$"                 /* (E) "good-looking POKéMON?$" */

Route9_Text_ChrisDefeat:: @ 818487E
    .string "¡Apagado como una luz!$"               /* (E) "Out like a light!$" */

Route9_Text_ChrisPostBattle:: @ 8184890
    .string "¡Sigue caminando!$"                    /* (E) "Keep walking!$" */

Route9_Text_DrewIntro:: @ 818489E
    .string "Tomaré el TÚNEL ROCA para ir a\n"      /* (E) "I'm taking the ROCK TUNNEL to\n" */
    .string "PUEBLO LAVANDA…$"                      /* (E) "go to LAVENDER…$" */

Route9_Text_DrewDefeat:: @ 81848CC
    .string "No me puedo comparar…$"                /* (E) "Can't measure up…$" */

Route9_Text_DrewPostBattle:: @ 81848DE
    .string "¿Vas a ir al TÚNEL ROCA también?$"     /* (E) "Are you off to ROCK TUNNEL, too?$" */

Route9_Text_CaitlinIntro:: @ 81848FF
    .string "¡No te atrevas a subestimarme!$"       /* (E) "Don't you dare patronize me!$" */

Route9_Text_CaitlinDefeat:: @ 818491C
    .string "¡No!\n"                                /* (E) "No!\n" */
    .string "Eres demasiado.$"                      /* (E) "You're too much.$" */

Route9_Text_CaitlinPostBattle:: @ 8184931
    .string "Obviamente eres talentos{OA}.\n"       /* (E) "You're obviously talented.\n" */
    .string "¡Buena suerte para ti!$"               /* (E) "Good luck to you!$" */

Route9_Text_JeremyIntro:: @ 818495E
    .string "¡Muajaja!\n"                           /* (E) "Bwahaha!\n" */
    .string "¡Qué bien! ¡Estaba aburrido, eh!$"     /* (E) "Great! I was bored, eh!$" */

Route9_Text_JeremyDefeat:: @ 818497F
    .string "¡No te detengas, eh!\p"                /* (E) "Keep it coming, eh!\p" */
    .string "Oh, espera.\n"                         /* (E) "Oh wait.\n" */
    .string "¡Me quede sin POKéMON!$"               /* (E) "I'm out of POKéMON!$" */

Route9_Text_JeremyPostBattle:: @ 81849B0
    .string "¿Sí que tuviste agallas para\n"        /* (E) "You sure had guts standing up to\n" */
    .string "enfrentarme, eh?$"                     /* (E) "me there, eh?$" */

Route9_Text_BriceIntro:: @ 81849DF
    .string "¡Jajaja!\n"                            /* (E) "Hahaha!\n" */
    .string "¿Te crees muy rudo, no es así?$"       /* (E) "Aren't you a little toughie!$" */

Route9_Text_BriceDefeat:: @ 8184A04
    .string "¿Qué es eso?$"                         /* (E) "What's that?$" */

Route9_Text_BricePostBattle:: @ 8184A11
    .string "¡Jajaja!\n"                            /* (E) "Hahaha!\n" */
    .string "¡Los niños deben ser duros!$"          /* (E) "Kids should be tough!$" */

Route9_Text_BrentIntro:: @ 8184A2F
    .string "¡Madrugo todos los días para criar\n"  /* (E) "I got up early every day to raise\n" */
    .string "a mis POKéMON desde capullos!$"        /* (E) "my POKéMON from cocoons!$" */

Route9_Text_BrentDefeat:: @ 8184A6A
    .string "¿QUÉ?\p"                               /* (E) "WHAT?\p" */
    .string "¡Qué gran pérdida de tiempo!$"         /* (E) "What a total waste of time!$" */

Route9_Text_BrentPostBattle:: @ 8184A8C
    .string "Tengo que atrapar algo más que\n"      /* (E) "I have to collect more than bugs\n" */
    .string "bichos para volverme más fuerte…$"     /* (E) "to get stronger…$" */

Route9_Text_AlanIntro:: @ 8184ABE
    .string "¡Jajajaja!\n"                          /* (E) "Hahahaha!\n" */
    .string "¡Adelante!$"                           /* (E) "Bring it on!$" */

Route9_Text_AlanDefeat:: @ 8184AD5
    .string "¡Jajajaja!\n"                          /* (E) "Hahahaha!\n" */
    .string "¡Me venciste justamente!$"             /* (E) "You beat me fair!$" */

Route9_Text_AlanPostBattle:: @ 8184AF1
    .string "¡Jajajaja!\n"                          /* (E) "Hahahaha!\n" */
    .string "¡Los robustos siempre nos reímos!$"    /* (E) "Us hearty guys always laugh!$" */

Route9_Text_ConnerIntro:: @ 8184B18
    .string "¡Vamos, mis super POKéMON BICHO!$"     /* (E) "Go, my super BUG POKéMON!$" */

Route9_Text_ConnerDefeat:: @ 8184B32
    .string "Mis bichos…$"                          /* (E) "My bugs…$" */

Route9_Text_ConnerPostBattle:: @ 8184B3B
    .string "¡Si no te gustan los POKéMON BICHO,\n" /* (E) "If you don't like BUG POKéMON,\n" */
	.string "me molestas!$"                         /* (E) "you bug me!$" */

Route9_Text_RouteSign:: @ 8184B66
    .string "RUTA 9\n"                              /* (E) "ROUTE 9\n" */
    .string "CIUDAD CELESTE - TÚNEL ROCA$"          /* (E) "CERULEAN CITY - ROCK TUNNEL$" */

