Route9_Text_AliciaIntro::
    .string "¡Tienes POKéMON contigo!\n"            /* (E) "You have POKéMON with you!\n" */
    .string "¡Eres mí{OA}!$"                        /* (E) "You're mine!$" */

Route9_Text_AliciaDefeat::
    .string "Me engañaste…$"                        /* (E) "You deceived me…$" */

Route9_Text_AliciaPostBattle::
    .string "El túnel cerca de aquí está\n"         /* (E) "The tunnel coming up is pitch-black\n" */
    .string "totalmente oscuro.\p"                  /* (E) "inside.\p" */
    .string "Necesitarás DESTELLO para poder\n"     /* (E) "You'll need FLASH to get through\n" */
    .string "cruzarlo.$"                            /* (E) "there.$" */

Route9_Text_ChrisIntro::
    .string "¿Quién anda ahí con esos POKéMON\n"    /* (E) "Who's that walking there with those\n" */
    .string "de tan buen aspecto?$"                 /* (E) "good-looking POKéMON?$" */

Route9_Text_ChrisDefeat::
    .string "¡Apagado como una luz!$"               /* (E) "Out like a light!$" */

Route9_Text_ChrisPostBattle::
    .string "¡Sigue caminando!$"                    /* (E) "Keep walking!$" */

Route9_Text_DrewIntro::
    .string "Tomaré el TÚNEL ROCA para ir a\n"      /* (E) "I'm taking the ROCK TUNNEL to\n" */
    .string "PUEBLO LAVANDA…$"                      /* (E) "go to LAVENDER…$" */

Route9_Text_DrewDefeat::
    .string "No me puedo comparar…$"                /* (E) "Can't measure up…$" */

Route9_Text_DrewPostBattle::
    .string "¿Vas a ir al TÚNEL ROCA también?$"     /* (E) "Are you off to ROCK TUNNEL, too?$" */

Route9_Text_CaitlinIntro::
    .string "¡No te atrevas a subestimarme!$"       /* (E) "Don't you dare patronize me!$" */

Route9_Text_CaitlinDefeat::
    .string "¡No!\n"                                /* (E) "No!\n" */
    .string "Eres demasiado.$"                      /* (E) "You're too much.$" */

Route9_Text_CaitlinPostBattle::
    .string "Obviamente eres talentos{OA}.\n"       /* (E) "You're obviously talented.\n" */
    .string "¡Buena suerte para ti!$"               /* (E) "Good luck to you!$" */

Route9_Text_JeremyIntro::
    .string "¡Muajaja!\n"                           /* (E) "Bwahaha!\n" */
    .string "¡Qué bien! ¡Estaba aburrido, eh!$"     /* (E) "Great! I was bored, eh!$" */

Route9_Text_JeremyDefeat::
    .string "¡No te detengas, eh!\p"                /* (E) "Keep it coming, eh!\p" */
    .string "Oh, espera.\n"                         /* (E) "Oh wait.\n" */
    .string "¡Me quede sin POKéMON!$"               /* (E) "I'm out of POKéMON!$" */

Route9_Text_JeremyPostBattle::
    .string "¿Sí que tuviste agallas para\n"        /* (E) "You sure had guts standing up to\n" */
    .string "enfrentarme, eh?$"                     /* (E) "me there, eh?$" */

Route9_Text_BriceIntro::
    .string "¡Jajaja!\n"                            /* (E) "Hahaha!\n" */
    .string "¿Te crees muy rudo, no es así?$"       /* (E) "Aren't you a little toughie!$" */

Route9_Text_BriceDefeat::
    .string "¿Qué es eso?$"                         /* (E) "What's that?$" */

Route9_Text_BricePostBattle::
    .string "¡Jajaja!\n"                            /* (E) "Hahaha!\n" */
    .string "¡Los niños deben ser duros!$"          /* (E) "Kids should be tough!$" */

Route9_Text_BrentIntro::
    .string "¡Madrugo todos los días para criar\n"  /* (E) "I got up early every day to raise\n" */
    .string "a mis POKéMON desde capullos!$"        /* (E) "my POKéMON from cocoons!$" */

Route9_Text_BrentDefeat::
    .string "¿QUÉ?\p"                               /* (E) "WHAT?\p" */
    .string "¡Qué gran pérdida de tiempo!$"         /* (E) "What a total waste of time!$" */

Route9_Text_BrentPostBattle::
    .string "Tengo que atrapar algo más que\n"      /* (E) "I have to collect more than bugs\n" */
    .string "insectos para volverme más fuerte…$"     /* (E) "to get stronger…$" */

Route9_Text_AlanIntro::
    .string "¡Jajajaja!\n"                          /* (E) "Hahahaha!\n" */
    .string "¡Adelante!$"                           /* (E) "Bring it on!$" */

Route9_Text_AlanDefeat::
    .string "¡Jajajaja!\n"                          /* (E) "Hahahaha!\n" */
    .string "¡Me venciste justamente!$"             /* (E) "You beat me fair!$" */

Route9_Text_AlanPostBattle::
    .string "¡Jajajaja!\n"                          /* (E) "Hahahaha!\n" */
    .string "¡Los robustos siempre nos reímos!$"    /* (E) "Us hearty guys always laugh!$" */

Route9_Text_ConnerIntro::
    .string "¡Vamos, súper POKéMON INSECTOS!$"      /* (E) "Go, my super BUG POKéMON!$" */

Route9_Text_ConnerDefeat::
    .string "Mis insectos…$"                        /* (E) "My bugs…$" */

Route9_Text_ConnerPostBattle::
    .string "¡Si no te gustan los POKéMON\n"        /* (E) "If you don't like BUG POKéMON,\n" */
	.string "INSECTO, me molestas!$"                /* (E) "you bug me!$" */

Route9_Text_RouteSign::
    .string "RUTA 9\n"                              /* (E) "ROUTE 9\n" */
    .string "CIUDAD CELESTE - TÚNEL ROCA$"          /* (E) "CERULEAN CITY - ROCK TUNNEL$" */

