Route24_Text_JustEarnedFabulousPrize:: @ 8188C3C
    .string "¡Felicidades! ¡Venciste a nuestros\n"
    .string "cinco ENTRENADORES participantes!\p"
    .string "¡Te ganaste un fabuloso premio!$"

Route24_Text_ReceivedNuggetFromMysteryTrainer:: @ 8188C93
    .string "¡{PLAYER} recibió una PEPITA\n"
    .string "del ENTRENADOR misterioso!$"

Route24_Text_YouDontHaveAnyRoom:: @ 8188CC2
    .string "¡No tienes espacio!$"

Route24_Text_JoinTeamRocket:: @ 8188CDB
    .string "Por cierto, ¿te gustaría unirte\n"
    .string "al EQUIPO ROCKET?\p"
    .string "¡Somos un grupo de criminales\n"
    .string "profesionales especializados\l"
    .string "en POKéMON!\p"
    .string "¿Quieres unirte?\p"
    .string "¿Estás segur{OA}?\p"
    .string "¡Vamos, únete a nosotros!\p"
    .string "¡Te estoy diciendo que te unas!\p"
    .string "…Bien, ¡necesitas que te convezca!\p"
    .string "¡Te haré una oferta que no podrás\n"
    .string "rechazar!$"

Route24_Text_RocketDefeat:: @ 8188DDC
    .string "¡Arrgh!\n"
    .string "¡Eres buen{OA}!$"

Route24_Text_YoudBecomeTopRocketLeader:: @ 8188DF1
    .string "Con tu habilidad, serías un{A}\n"
    .string "líder en el EQUIPO ROCKET.\p"
    .string "¡Vamos, piensa en la oportunidad!\n"
    .string "No dejes que se desperdicie.$"

Route24_Text_ShaneIntro:: @ 8188E74
    .string "¡Vi tu hazaña desde la hierba!$"

Route24_Text_ShaneDefeat:: @ 8188E94
    .string "¡No pensé que ganaría!$"

Route24_Text_ShanePostBattle:: @ 8188EA3
    .string "Me escondí porque las personas en\n"
    .string "el puente me dan miedo.$"

Route24_Text_EthanIntro:: @ 8188ED9
    .string "¡De acuerdo! ¡Soy el Número 5!\n"
    .string "¡Te aplastaré!$"

Route24_Text_EthanDefeat:: @ 8188EFA
    .string "¡Wuow!\n"
    .string "¡Es demasiado!$"

Route24_Text_EthanPostBattle:: @ 8188F0A
    .string "Di lo mejor de mi mismo.\n"
    .string "¡No me arrepiento de nada!$"

Route24_Text_ReliIntro:: @ 8188F2C
    .string "¡Soy la Número 4!\n"
    .string "¿Te estás cansando?$"

Route24_Text_ReliDefeat:: @ 8188F46
    .string "¡También perdí!$"

Route24_Text_ReliPostBattle:: @ 8188F53
    .string "¡Di lo mejor de mi misma, así\n"
    .string "que no tengo arrepentimientos!$"

Route24_Text_TimmyIntro:: @ 8188F76
    .string "¡Aquí está el Número 3!\n"
    .string "¡No será tán fácil!$"

Route24_Text_TimmyDefeat:: @ 8188F95
    .string "¡Au!\n"
    .string "¡Me aplastaste!$"

Route24_Text_TimmyPostBattle:: @ 8188FA7
    .string "Di lo mejor de mi mismo.\n"
    .string "¡No me arrepiento de nada!$"

Route24_Text_AliIntro:: @ 8188FC9
    .string "¡Soy segunda!\n"
    .string "¡Ahora es en serio!$"

Route24_Text_AliDefeat:: @ 8188FE7
    .string "¿Cómo pude perder?$"

Route24_Text_AliPostBattle:: @ 8188FF9
    .string "Di lo mejor de mi misma.\n"
    .string "¡No me arrepiento de nada!$"

Route24_Text_CaleIntro:: @ 818901B
    .string "¡La gente se refiere a esto cómo\n"
    .string "el PUENTE PEPITA!\p"
    .string "¡Vence a estos cinco ENTRENADORES\n"
    .string "y gana un fabuloso premio!\p"
    .string "¿Crees que tienes lo necesario?$"

Route24_Text_CaleDefeat:: @ 818908C
    .string "¡Wuu!\n"
    .string "¡Buen trabajo!$"

Route24_Text_CalePostBattle:: @ 818909E
    .string "Di lo mejor de mi mismo.\n"
    .string "¡No me arrepiento de nada!$"
