Route24_Text_JustEarnedFabulousPrize::
    .string "¡Felicidades! ¡Venciste a nuestros\n"
    .string "cinco ENTRENADORES participantes!\p"
    .string "¡Te ganaste un fabuloso premio!$"

Route24_Text_ReceivedNuggetFromMysteryTrainer::
    .string "¡{PLAYER} recibió una PEPITA\n"
    .string "del ENTRENADOR misterioso!$"

Route24_Text_YouDontHaveAnyRoom::
    .string "¡No tienes espacio!$"

Route24_Text_JoinTeamRocket::
    .string "Por cierto, ¿te gustaría unirte\n"
    .string "al EQUIPO ROCKET?\p"
    .string "¡Somos un grupo de criminales\n"
    .string "profesionales especializados\l"
    .string "en POKéMON!\p"
    .string "¿Quieres unirte?\p"
    .string "¿Estás segur{OA}?\p"
    .string "¡Vamos, únete a nosotros!\p"
    .string "¡Te estoy diciendo que te unas!\p"
    .string "…Bien, ¡necesitas que te convezca!\p"
    .string "¡Te haré una oferta que no podrás\n"
    .string "rechazar!$"

Route24_Text_RocketDefeat::
    .string "¡Arrgh!\n"
    .string "¡Eres buen{OA}!$"

Route24_Text_YoudBecomeTopRocketLeader::
    .string "Con tu habilidad, serías un{A}\n"
    .string "líder en el EQUIPO ROCKET.\p"
    .string "¡Vamos, piensa en la oportunidad!\n"
    .string "No dejes que se desperdicie.$"

Route24_Text_ShaneIntro::
    .string "¡Vi tu hazaña desde la hierba!$"

Route24_Text_ShaneDefeat::
    .string "¡No pensé que ganaría!$"

Route24_Text_ShanePostBattle::
    .string "Me escondí porque las personas en\n"
    .string "el puente me dan miedo.$"

Route24_Text_EthanIntro::
    .string "¡De acuerdo! ¡Soy el Número 5!\n"
    .string "¡Te aplastaré!$"

Route24_Text_EthanDefeat::
    .string "¡Wuow!\n"
    .string "¡Es demasiado!$"

Route24_Text_EthanPostBattle::
    .string "Di lo mejor de mi mismo.\n"
    .string "¡No me arrepiento de nada!$"

Route24_Text_ReliIntro::
    .string "¡Soy la Número 4!\n"
    .string "¿Te estás cansando?$"

Route24_Text_ReliDefeat::
    .string "¡También perdí!$"

Route24_Text_ReliPostBattle::
    .string "¡Di lo mejor de mi misma, así\n"
    .string "que no tengo arrepentimientos!$"

Route24_Text_TimmyIntro::
    .string "¡Aquí está el Número 3!\n"
    .string "¡No será tán fácil!$"

Route24_Text_TimmyDefeat::
    .string "¡Au!\n"
    .string "¡Me aplastaste!$"

Route24_Text_TimmyPostBattle::
    .string "Di lo mejor de mi mismo.\n"
    .string "¡No me arrepiento de nada!$"

Route24_Text_AliIntro::
    .string "¡Soy segunda!\n"
    .string "¡Ahora es en serio!$"

Route24_Text_AliDefeat::
    .string "¿Cómo pude perder?$"

Route24_Text_AliPostBattle::
    .string "Di lo mejor de mi misma.\n"
    .string "¡No me arrepiento de nada!$"

Route24_Text_CaleIntro::
    .string "¡La gente se refiere a esto cómo\n"
    .string "el PUENTE PEPITA!\p"
    .string "¡Vence a estos cinco ENTRENADORES\n"
    .string "y gana un fabuloso premio!\p"
    .string "¿Crees que tienes lo necesario?$"

Route24_Text_CaleDefeat::
    .string "¡Wuu!\n"
    .string "¡Buen trabajo!$"

Route24_Text_CalePostBattle::
    .string "Di lo mejor de mi mismo.\n"
    .string "¡No me arrepiento de nada!$"
