ThreeIsland_Mart_Text_TrueThatCeldadonDeptStoreBigger::
    .string "¿Es verdad?\p"
    .string "¿La TIENDA DEP. PRISMA es varias\n"
    .string "veces más grande que esta tienda?$"

ThreeIsland_Mart_Text_PeopleHealWithBerriesFromForest::
    .string "A veces compro medicina aquí.\p"
    .string "Pero mucha gente cura a sus\n"
    .string "POKéMON con BAYAS del BOSQUE BAYA.\p"
    .string "Después de todo, las BAYAS son\n"
    .string "gratis y nunca se acaban.$"

ThreeIsland_Mart_Text_BikersWereAboutToTrashMart::
    .string "Esos MOTORISTAS estaban por\n"
    .string "destrozar esta TIENDA POKéMON.\p"
    .string "¡Por suerte decidieron irse!$"

