ThreeIsland_BondBridge_Text_NikkiIntro::
    .string "El olor salado del mar…\n"
    .string "Me llega al corazón.$"

ThreeIsland_BondBridge_Text_NikkiDefeat::
    .string "…Sniff, sniff…\n"
    .string "Algo huele mal…$"

ThreeIsland_BondBridge_Text_NikkiPostBattle::
    .string "Tal vez ese olor viene de tus\n"
    .string "POKéMON sudorosos…$"

ThreeIsland_BondBridge_Text_VioletIntro::
    .string "¿A dónde vas con tanta prisa?$"

ThreeIsland_BondBridge_Text_VioletDefeat::
    .string "Estas criando a unos POKéMON\n"
    .string "maravillosos.$"

ThreeIsland_BondBridge_Text_VioletPostBattle::
    .string "Si sigues este camino, terminarás\n"
    .string "llegando al BOSQUE BAYA.$"

ThreeIsland_BondBridge_Text_AmiraIntro::
    .string "Mi mami dijo que no puedo nadar\n"
    .string "sin mi flotador.$"

ThreeIsland_BondBridge_Text_AmiraDefeat::
    .string "¡Waaah!\n"
    .string "¡Waaah!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle::
    .string "¡Este año, finalmente voy a\n"
    .string "aprender a nadar!$"

ThreeIsland_BondBridge_Text_AlexisIntro::
    .string "¡Yay, yay!\n"
    .string "¡POKéMON!$"

ThreeIsland_BondBridge_Text_AlexisDefeat::
    .string "¿Ahora que pasa?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle::
    .string "¿Acabo de ganar?\n"
    .string "¿O perdí?$"

ThreeIsland_BondBridge_Text_TishaIntro::
    .string "¡Oh, no, no te acerques!\n"
    .string "¡Por favor, aléjate de mi!$"

ThreeIsland_BondBridge_Text_TishaDefeat::
    .string "¡De acuerdo, ganaste!\n"
    .string "¿Te puedes ir ahora, por favor?$"

ThreeIsland_BondBridge_Text_TishaPostBattle::
    .string " Un POKéMON mordió mi traje\n"
    .string "de baño.\p"
    .string "¡No puedo salir del agua!$"

ThreeIsland_BondBridge_Text_JoyIntro::
    .string "JOY: ¡Te enseñaremos cual es\n"
    .string "nuestro POKéMON favorito!$"

ThreeIsland_BondBridge_Text_JoyDefeat::
    .string "JOY: Ohh…\n"
    .string "¡MEG!$"

ThreeIsland_BondBridge_Text_JoyPostBattle::
    .string "JOY: ¿No fue eso divertido?\n"
    .string "¡Espero que se pueda repetir!$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
    .string "JOY: Realmente quiero luchar junto\n"
    .string "a MEG.\p"
    .string "Un POKéMON no es suficiente.$"

ThreeIsland_BondBridge_Text_MegIntro::
    .string "MEG: Te mostraremos a nuestro\n"
    .string "POKéMON favorito.$"

ThreeIsland_BondBridge_Text_MegDefeat::
    .string "MEG: Ohh…\n"
    .string "¡JOY!$"

ThreeIsland_BondBridge_Text_MegPostBattle::
    .string "MEG: ¿JOY, te divertiste?$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
    .string "MEG: Quiero una batalla junto con\n"
    .string "JOY.\p"
    .string "Un POKéMON no es suficiente.$"

ThreeIsland_BondBridge_Text_BerryForestAhead::
    .string "BOSQUE BAYA ADELANTE$"

ThreeIsland_BondBridge_Text_BondBridgeSign::
    .string "PUENTE UNIÓN\n"
    .string "Por favor cruce tranquilamente.\p"
    .string "BOSQUE BAYA ADELANTE$"

