CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
    .string "El REPELENTE no solo aleja bichos,\n"
    .string "también sirve con POKéMON débiles.\p"
    .string "Pon tu POKéMON más fuerte a la\n"
    .string "izquierda de la LISTA DE POKéMON.\p"
    .string "Si tu primer POKéMON es fuerte, el\n"
    .string "efecto del REPELENTE es aumentado.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
    .string "¿Conoces los CARAMELOS RAROS?\n"
    .string "No los venden en las tiendas.\p"
    .string "Creo que hacen que los POKéMON\n"
    .string "crezcan muy rápido de repente.$"

