Route11_Text_HugoIntro::
    .string "¡Gana, pierde, o empata!$"

Route11_Text_HugoDefeat::
    .string "¡Agh!\n"
    .string "¡No terminó a mi favor!$"

Route11_Text_HugoPostBattle::
    .string "¡Los POKéMON son vida!\n"
    .string "¡Y vivir es jugar!$"

Route11_Text_JasperIntro::
    .string "¡Competición!\n"
    .string "¡No me canso de competir!$"

Route11_Text_JasperDefeat::
    .string "¡Tenía una oportunidad!$"

Route11_Text_JasperPostBattle::
    .string "¡No puedes ser un cobarde en el\n"
    .string "mundo de los POKéMON!$"

Route11_Text_EddieIntro::
    .string "¡Vamos allá, pero no hagas trampa!$"

Route11_Text_EddieDefeat::
    .string "¿Eh?\n"
    .string "¡No puede ser!$"

Route11_Text_EddiePostBattle::
    .string "Di lo mejor de mi mismo.\n"
    .string "No me arrepiento de nada.$"

Route11_Text_BraxtonIntro::
    .string "¡Cuidado!\n"
    .string "¡Estoy colocando unos cables!$"

Route11_Text_BraxtonDefeat::
    .string "¡Eso fue electrizante!$"

Route11_Text_BraxtonPostBattle::
    .string "¡Dile a todo el mundo que ahorren\n"
    .string "energía!$"

Route11_Text_DillonIntro::
    .string "Me acabo de volver ENTRENADOR.\n"
    .string "Pero, creo que puedo ganar.$"

Route11_Text_DillonDefeat::
    .string "Mis POKéMON no pudieron ganar…\n"
    .string "¿No han crecido lo suficiente?$"

Route11_Text_DillonPostBattle::
    .string "¿Ahora qué?\n"
    .string "¡Déjame solo!$"

Route11_Text_DirkIntro::
    .string "¡Jajaja!\n"
    .string "¡No he perdido nunca!$"

Route11_Text_DirkDefeat::
    .string "¡Mi primera derrota!$"

Route11_Text_DirkPostBattle::
    .string "Solo tuviste suerte, eso es todo.$"

Route11_Text_DarianIntro::
    .string "Nunca he ganado antes…$"

Route11_Text_DarianDefeat::
    .string "Lo veía venir…$"

Route11_Text_DarianPostBattle::
    .string "Tuve mala suerte, como siempre.$"

Route11_Text_YasuIntro::
    .string "Soy el mejor de mi clase.\n"
    .string "Entreno cada mañana.$"

Route11_Text_YasuDefeat::
    .string "¡Rayos!\n"
    .string "¡Mis POKéMON necesitan ser más\n"
    .string "fuertes!$"

Route11_Text_YasuPostBattle::
    .string "Hay un POKÉMON gordo que llega\n"
    .string "bajando de las montañas.\p"
    .string "Apuesto a que sería fuerte si lo\n"
    .string "pudieras atrapar.$"

Route11_Text_BernieIntro::
    .string "¡Cuidado con los cables sueltos!$"

Route11_Text_BernieDefeat::
    .string "¡Whoa!\n"
    .string "¡Si que tienes chispa!$"

Route11_Text_BerniePostBattle::
    .string "Bueno, será mejor que vuelva al\n"
    .string "trabajo.$"

Route11_Text_DaveIntro::
    .string "Críe a mis POKÉMON con cuidado.\n"
    .string "¡Ya deberían estar listos!$"

Route11_Text_DaveDefeat::
    .string "¡Adiós!\n"
    .string "¡Gracias, y adiós!$"

Route11_Text_DavePostBattle::
    .string "Tch…\n"
    .string "¡Mejor buscaré unos más fuertes!$"

Route11_Text_DiglettsCave::
    .string "CUEVA DIGLETT$"

