Route11_Text_HugoIntro:: @ 8184F01
    .string "¡Gana, pierde, o empata!$"

Route11_Text_HugoDefeat:: @ 8184F15
    .string "¡Agh!\n"
    .string "¡No terminó a mi favor!$"

Route11_Text_HugoPostBattle:: @ 8184F2E
    .string "¡Los POKéMON son vida!\n"
    .string "¡Y vivir es jugar!$"

Route11_Text_JasperIntro:: @ 8184F5D
    .string "¡Competición!\n"
    .string "¡No me canso de competir!$"

Route11_Text_JasperDefeat:: @ 8184F7E
    .string "¡Tenía una oportunidad!$"

Route11_Text_JasperPostBattle:: @ 8184F8E
    .string "¡No puedes ser un cobarde en el\n"
    .string "mundo de los POKéMON!$"

Route11_Text_EddieIntro:: @ 8184FBD
    .string "¡Vamos allá, pero no hagas trampa!$"

Route11_Text_EddieDefeat:: @ 8184FD8
    .string "¿Eh?\n"
    .string "¡No puede ser!$"

Route11_Text_EddiePostBattle:: @ 8184FEF
    .string "Di lo mejor de mi mismo.\n"
    .string "No me arrepiento de nada.$"

Route11_Text_BraxtonIntro:: @ 8185011
    .string "¡Cuidado!\n"
    .string "¡Estoy colocando unos cables!$"

Route11_Text_BraxtonDefeat:: @ 8185037
    .string "¡Eso fue electrizante!$"

Route11_Text_BraxtonPostBattle:: @ 818504A
    .string "¡Dile a todo el mundo que ahorren\n"
    .string "energía!$"

Route11_Text_DillonIntro:: @ 818506A
    .string "Me acabo de volver ENTRENADOR.\n"
    .string "Pero, creo que puedo ganar.$"

Route11_Text_DillonDefeat:: @ 818509B
    .string "Mis POKéMON no pudieron ganar…\n"
    .string "¿No han crecido lo suficiente?$"

Route11_Text_DillonPostBattle:: @ 81850CF
    .string "¿Ahora qué?\n"
    .string "¡Déjame solo!$"

Route11_Text_DirkIntro:: @ 81850E9
    .string "¡Jajaja!\n"
    .string "¡No he perdido nunca!$"

Route11_Text_DirkDefeat:: @ 8185105
    .string "¡Mi primera derrota!$"

Route11_Text_DirkPostBattle:: @ 8185114
    .string "Solo tuviste suerte, eso es todo.$"

Route11_Text_DarianIntro:: @ 8185135
    .string "Nunca he ganado antes…$"

Route11_Text_DarianDefeat:: @ 818514E
    .string "Lo veía venir…$"

Route11_Text_DarianPostBattle:: @ 8185161
    .string "Tuve mala suerte, como siempre.$"

Route11_Text_YasuIntro:: @ 818517B
    .string "Soy el mejor de mi clase.\n"
    .string "Entreno cada mañana.$"

Route11_Text_YasuDefeat:: @ 81851AC
    .string "¡Rayos!\n"
    .string "¡Mis POKéMON necesitan ser más\n"
    .string "fuertes!$"

Route11_Text_YasuPostBattle:: @ 81851D2
    .string "Hay un POKÉMON gordo que llega\n"
    .string "bajando de las montañas.\p"
    .string "Apuesto a que sería fuerte si lo\n"
    .string "pudieras atrapar.$"

Route11_Text_BernieIntro:: @ 8185236
    .string "¡Cuidado con los cables sueltos!$"

Route11_Text_BernieDefeat:: @ 8185250
    .string "¡Whoa!\n"
    .string "¡Si que tienes chispa!$"

Route11_Text_BerniePostBattle:: @ 8185266
    .string "Bueno, será mejor que vuelva al\n"
    .string "trabajo.$"

Route11_Text_DaveIntro:: @ 8185285
    .string "Críe a mis POKÉMON con cuidado.\n"
    .string "¡Ya deberían estar listos!$"

Route11_Text_DaveDefeat:: @ 81852C1
    .string "¡Adiós!\n"
    .string "¡Gracias, y adiós!$"

Route11_Text_DavePostBattle:: @ 81852E3
    .string "Tch…\n"
    .string "¡Mejor buscaré unos más fuertes!$"

Route11_Text_DiglettsCave:: @ 8185308
    .string "CUEVA DIGLETT$"

