CeladonCity_House1_Text_SlotsReelInTheDough::
    .string "¡Jejeje!\p"
    .string "¡Las tragamonedas atraen dinero,\n"
    .string "muchísimo!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
    .string "¡JEFE!\p"
    .string "¡Acabamos de enviar dos mil\n"
    .string "POKéMON más como premios de las\l"
    .string "tragamonedas hoy!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
    .string "¡No toques el cartel en la SALA\n"
    .string "DE JUEGOS!\p"
    .string "¡No hay ningún interruptor detrás!$"

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of DIGLETT.", and is removed altogether in FRLG
Text_ItsABuddhistAltar::
    .string "ぶつだん　だ‥$"
