Route14_Text_CarterIntro::
    .string "Necesitas usar MTs para enseñar\n"
    .string "buenos movimientos a tus POKéMON.$"

Route14_Text_CarterDefeat::
    .string "No soy tan bueno aún.$"

Route14_Text_CarterPostBattle::
    .string "¿Tienes algunas MOs, cierto?\p"
    .string "Los POKéMON no pueden olvidar esos\n"
    .string "movimientos fácilmente.$"

Route14_Text_MitchIntro::
    .string "Mis POKéMON pájaros deberían estar\n"
    .string "listos para la batalla.$"

Route14_Text_MitchDefeat::
    .string "¡Aún no están listos!$"

Route14_Text_MitchPostBattle::
    .string "Mis POKéMON pájaros necesitan\n"
    .string "aprender mejores movimientos.$"

Route14_Text_BeckIntro::
    .string "Tienen MTs a la venta en la TIENDA\n"
    .string "DEPARTAMENTAL PRISMA.\p"
    .string "Las MTs no son muy raras, pero\n"
    .string "poca gente tiene MOs.$"

Route14_Text_BeckDefeat::
    .string "¡Aww, que mal!$"

Route14_Text_BeckPostBattle::
    .string "Intenta enseñar a tus POKéMON\n"
    .string "ataques de sus mismos tipos.\p"
    .string "Eso aparentemente potencia el\n"
    .string "poder de ese ataque.$"

Route14_Text_MarlonIntro::
    .string "¿Les enseñaste a VOLAR a tus\n"
    .string "POKéMON pájaros?\p"
    .string "¡Serás capaz de elevarte al cielo\n"
    .string "con ellos!$"

Route14_Text_MarlonDefeat::
    .string "¡Caí en llamas!$"

Route14_Text_MarlonPostBattle::
    .string "Los POKéMON pájaros son mi\n"
    .string "única y verdadera pasión.\p"
    .string "No quiero criar otra cosa.$"

Route14_Text_DonaldIntro::
    .string "¿Has oído de la leyenda de los\n"
    .string "espejismos alados?$"

Route14_Text_DonaldDefeat::
    .string "¿Por qué?\n"
    .string "¿Por qué perdí?$"

Route14_Text_DonaldPostBattle::
    .string "Bueno, los espejismos alados son\n"
    .string "legendarias aves POKéMON.\p"
    .string "Existen tres: ARTICUNO, ZAPDOS,\n"
    .string "y MOLTRES.$"

Route14_Text_BennyIntro::
    .string "No es lo mío, pero esta bien.\n"
    .string "¡Vamos!$"

Route14_Text_BennyDefeat::
    .string "¡Lo sabía!$"

Route14_Text_BennyPostBattle::
    .string "Ganar, perder…es insignificante\n"
    .string "bajo este gran cielo.$"

Route14_Text_LukasIntro::
    .string "Adelante, adelante.\n"
    .string "¡Vamos, vamos, vamos!$"

Route14_Text_LukasDefeat::
    .string "¡Arrg!\n"
    .string "¡Perdí! ¡piérdete!$"

Route14_Text_LukasPostBattle::
    .string "¿Qué, qué, qué?\n"
    .string "¿Ahora qué quieres?$"

Route14_Text_IsaacIntro::
    .string "Necesito perder algo de tiempo.\n"
    .string "Cállate y lucha.$"

Route14_Text_IsaacDefeat::
    .string "¿Qué?\n"
    .string "¿¡Tú!?$"

Route14_Text_IsaacPostBattle::
    .string "Criar POKéMON es muy pesado.$"

Route14_Text_GeraldIntro::
    .string "Manejamos por aquí por el espacio\n"
    .string "abierto.$"

Route14_Text_GeraldDefeat::
    .string "¡Aniquilado!$"

Route14_Text_GeraldPostBattle::
    .string "Es genial que hicieras a tus\n"
    .string "POKéMON tan fuertes.\p"
    .string "¡El poder lo es todo!\n"
    .string "¡Y lo sabes!$"

Route14_Text_MalikIntro::
    .string "¿Batalla POKéMON?\n"
    .string "¡Genial! ¡vamos!$"

Route14_Text_MalikDefeat::
    .string "¡Pulverizado!$"

Route14_Text_MalikPostBattle::
    .string "¡Tú sabes quien ganaría en un\n"
    .string "uno-a-uno entre tú y yo!$"

Route14_Text_RouteSign::
    .string "RUTA 14\n"
    .string "Al oeste de CIUDAD FUCSIA$"

Route14_Text_KiriIntro::
    .string "KIRI: JAN, esforcémonos mucho,\n"
    .string "mucho juntas.$"

Route14_Text_KiriDefeat::
    .string "KIRI: Ayy…\n"
    .string "¿Perdimos, verdad?$"

Route14_Text_KiriPostBattle::
    .string "KIRI: ¿Perdimos por mi culpa?$"

Route14_Text_KiriNotEnoughMons::
    .string "KIRI: Podemos luchar si tienes dos\n"
    .string "POKéMON.$"

Route14_Text_JanIntro::
    .string "JAN: ¡KIRI, allá vamos!\n"
    .string "¡Tenemos que esforzarnos mucho!$"

Route14_Text_JanDefeat::
    .string "JAN: ¡Eeeeh!\n"
    .string "¡No es justo!$"

Route14_Text_JanPostBattle::
    .string "JAN: ¡KIRI, no llores!\p"
    .string "Nos esforzaremos más la próxima\n"
    .string "vez.$"

Route14_Text_JanNotEnoughMons::
    .string "JAN: ¿Quieres luchar?\n"
    .string "No tienes POKéMON suficientes.$"
