ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "¡Uf! Estoy intentando memorizar\n"
    .string "todos mis apuntes.$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "¡Muy bien!\p"
    .string "¡Asegurate de leer cuidadosamente\n"
    .string "lo que está en la pizarra!$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "Voy a revisar el cuaderno.\p"
    .string "Primera página…\p"
    .string "Las POKéBOLAS son para atrapar\n"
    .string "a los POKéMON.\p"
    .string "Puedes llevar hasta seis POKéMON.\p"
    .string "Los ENTRENADORES son las personas\n"
    .string "que crian y tienen batallas\l"
    .string "con sus POKéMON.$"   

ViridianCity_School_Text_NotebookSecondPage::
    .string "Segunda página…\p"
    .string "Un POKéMON sano no es tan fácil\n"
    .string "de atrapar, así que conviene\l"
    .string "debilitarlo primero.\p"
    .string "Causa problemas de estado como los\n"
    .string "venenos, las quemaduras y otros.$"

ViridianCity_School_Text_NotebookThirdPage::
    .string "Tercera página…\p"
    .string "Los ENTRENADORES POKéMON buscan\n"
    .string "participar en batallas POKéMON.\p"
    .string "Para los ENTRENADORES, la victoria\n"
    .string "tiene un sabor muy dulce.\p"
    .string "En los GIMNASIOS POKéMON se libran\n"  
    .string "batallas constantemente.$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "Cuarta página…\p"
    .string "El objetivo de todo ENTRENADOR\n"
    .string "es el derrotar a los ocho mejores\l"
    .string "LÍDERES DE GIMNASIO.\p"
    .string "El que lo consiga, podrá desafiar…\p"
    .string "¡Al ALTO MANDO de la LIGA\n"
    .string "POKéMON!$"

ViridianCity_School_Text_TurnThePage::
    .string "¿Paso la página?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "NIÑA: ¡Oye!\n"
    .string "¡No mires mis apuntes!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .string "La pizarra indica los problemas de\n"
    .string "ESTADO de los POKéMON durante\l"
    .string "las batallas.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "¿Sobre qué tema te gustaría leer?$"

ViridianCity_School_Text_ExplainSleep::
    .string "Un POKéMON no puede atacar si\n"
    .string "está dormido.\p"
    .string "Los POKéMON seguirán dormidos\n"
    .string "incluso después de pelear.\p"
    .string "Usa DESPERTAR para que despierten.$"

ViridianCity_School_Text_ExplainBurn::
    .string "Las quemaduras reducen el poder de\n"
    .string "ATAQUE y van restando PS.\p"
    .string "Las quemaduras permanecerán tras\n"
    .string "la batalla.\p"
    .string "Usa ANTIQUEMAR para curar las\n"
    .string "quemaduras.$"

ViridianCity_School_Text_ExplainPoison::
    .string "Estando envenenado, un POKéMON\n"
    .string "seguirá perdiendo energía.\p"
    .string "El veneno sigue haciendo efecto\n"
    .string "tras la batalla.\p"
    .string "¡Usa un ANTÍDOTO para curar\n" 
    .string "el envenenamiento!$"

ViridianCity_School_Text_ExplainFreeze::
    .string "Al ser congelado, un POKéMON se\n"
    .string "vuelve totalmente inmovil.\p"
    .string "Y seguira congelado tras la\n"
    .string "batalla.\p"
    .string "Usa el ANTIHIELO para descongelar\n"
    .string "a los pobres POKéMON.$"

ViridianCity_School_Text_ExplainParalysis::
    .string "La parálisis reduce VELOCIDAD y\n"
    .string "puede anular movimientos.\p"
    .string "Persiste tras las batallas.\p"
    .string "Usa ANTIPARALIZAR para tratarla.$"

