SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner::
    .string "Este barco, ¡es un trasatlántico\n"
    .string "para los ENTRENADORES del mundo!\p"
    .string "En cada puerto, hacemos fiestas\n"
    .string "con ENTRENADORES invitados.$"

SSAnne_2F_Corridor_Text_RivalIntro::
    .string "{RIVAL}: ¡Bonjour!\n"
    .string "¡{PLAYER}!\p"
    .string "¡Me sorprende verte aquí!\n"
    .string "¿{PLAYER}, realmente te invitaron?\p"
    .string "¿Y cómo va tu POKéDEX?\p"
    .string "Ya atrapé a 40 POKéMON distintos.\n"
    .string "Hay varios tipos por todas partes.\p"
    .string "Gatea en zonas de hierba alta,\n"
    .string "y busca duro por ellos.$"

SSAnne_2F_Corridor_Text_RivalDefeat::
    .string "¡Humph!\p"
    .string "¡Al menos estas criando a tus\n"
    .string "POKéMON!$"

SSAnne_2F_Corridor_Text_RivalVictory::
    .string "{PLAYER}‥！\n"
    .string "ふなよい　してるのか！\p"
    .string "もっと　からだ\n"
    .string "きたえた　ほうが　いいぜ！$"

SSAnne_2F_Corridor_Text_RivalPostBattle::
    .string "{RIVAL}: Escuché que había un\n"
    .string "maestro del CORTE a bordo.\p"
    .string "¡Pero sólo era un viejo mareado!\p"
    .string "Aunque la técnica de CORTE en sí\n"
    .string "es muy útil.\p"
    .string "Sí, la necesitaré.\p"
    .string "Tú también deberías ir a verlo.\n"
    .string "¡Hasta nunca!$"

