Route10_Text_MarkIntro:: @ 8184B8A
    .string "¿Wow, viniste hasta aquí?\n"             /* (E) "Wow, you came all the way here?\n" */
    .string "¿También eres un{OA} POKéMANÍAC{OAM}?\l" /* (E) "Maybe you're a POKéMANIAC, too?\l" */
    .string "¿Quieres ver mi colección?$"             /* (E) "Want to see my collection?$" */

Route10_Text_MarkDefeat:: @ 8184BE5
    .string "Humph.\n"                                /* (E) "Humph.\n" */
    .string "¡No estoy molesto!$"                     /* (E) "I'm not angry!$" */

Route10_Text_MarkPostBattle:: @ 8184BFB
    .string "¡Tengo más POKéMON raros en casa!$"      /* (E) "I have more rare POKéMON at home!$" */

Route10_Text_ClarkIntro:: @ 8184C1D
    .string "¡Ja-jaja-ja-ja!$"                        /* (E) "Ha-hahah-ah-ha!$" */

Route10_Text_ClarkDefeat:: @ 8184C2D
    .string "¡Ja-jaja!\n"                             /* (E) "Ha-haha!\n" */
    .string "¡No me río!\l"                           /* (E) "Not laughing!\l" */
    .string "¡A-alergia! ¡A-a-a-chú!$"                /* (E) "Ha-hay fever! Haha-ha-choo!$" */

Route10_Text_ClarkPostBattle:: @ 8184C60
    .string "¡A-a-a-chú!\n"                           /* (E) "Haha-ha-choo!\n" */
    .string "¡A-chú!\l"                               /* (E) "Ha-choo!\l" */
    .string "¡A-chú! ¡Agh!$"                          /* (E) "Snort! Snivel!$" */

Route10_Text_HermanIntro:: @ 8184C86
    .string "¡Hola, niñ{OA}!\n"                       /* (E) "Hi, kid!\n" */
    .string "¿Quieres ver mis POKéMON?$"              /* (E) "Want to see my POKéMON?$" */

Route10_Text_HermanDefeat:: @ 8184CA7
    .string "¡Oh, no!\n"                              /* (E) "Oh, no!\n" */
    .string "¡Mis POKéMON!$"                          /* (E) "My POKéMON!$" */

Route10_Text_HermanPostBattle:: @ 8184CBB
    .string "No me agradas.\n"                        /* (E) "I don't like you.\n" */
    .string "¡No me agrada nadie mejor que yo!$"      /* (E) "I don't like anyone better than me!$" */

Route10_Text_HeidiIntro:: @ 8184CF1
    .string "He estado en un GIMNASIO POKéMON\n"      /* (E) "I've been out at a POKéMON GYM\n" */
    .string "varias veces.\p"                         /* (E) "a few times.\p" */
    .string "…Pero siempre pierdo.$"                  /* (E) "…But I always lose.$" */

Route10_Text_HeidiDefeat:: @ 8184D31
    .string "¡Ohh!\n"                                 /* (E) "Ohh!\n" */
    .string "¡Después de tanto entrenamiento!$"       /* (E) "After all my training!$" */

Route10_Text_HeidiPostBattle:: @ 8184D4D
    .string "Ví a algunos POKéMANÍACOS\n"             /* (E) "I noticed some POKéMANIACS\n" */
    .string "merodeando por aquí.\p"                  /* (E) "prowling around.\p" */
    .string "¿Puedes imaginarlo? ¿Ellos?\n"           /* (E) "Can you imagine? Them?\n" */
    .string "¿Aquí en las montañas?$"                 /* (E) "Up here in the mountains?$" */

Route10_Text_TrentIntro:: @ 8184DAA
    .string "¡Ah!\n"                                  /* (E) "Ah!\n" */
    .string "¡El aire de montaña es delicioso!$"      /* (E) "This mountain air is delicious!$" */

Route10_Text_TrentDefeat:: @ 8184DCE
    .string "¡Eso aclaró mi cabeza!$"                 /* (E) "That cleared my head!$" */

Route10_Text_TrentPostBattle:: @ 8184DE4
    .string "¡Me llené de aire de montaña!$"          /* (E) "I feel bloated on mountain air!$" */

Route10_Text_CarolIntro:: @ 8184E04
    .string "Me siento un poco débil.\n"              /* (E) "I'm feeling a bit faint.\n" */
    .string "No he escalado desde hace tiempo.$"      /* (E) "I haven't hiked in some time.$" */

Route10_Text_CarolDefeat:: @ 8184E3B
    .string "Estoy demasiado cansada.\n"              /* (E) "I'm too tired.\n" */
    .string "No estaba lista para esto.$"             /* (E) "I wasn't up for it.$" */

Route10_Text_CarolPostBattle:: @ 8184E5E
    .string "Los POKéMON aquí en las montañas\n"      /* (E) "The POKéMON here in the mountains\n" */
    .string "son tan toscos…\p"                       /* (E) "are so chunky…\p" */
    .string "¡Ojalá existiera un POKéMON\n"           /* (E) "I wish there were pink POKéMON\n" */
    .string "rosado con flores!$"                     /* (E) "with a floral pattern!$" */

Route10_Text_RockTunnelDetourToLavender:: @ 8184EC5
    .string "TÚNEL ROCA\n"                            /* (E) "ROCK TUNNEL\n" */
    .string "Desvío a PUEBLO LAVANDA$"                /* (E) "Detour to LAVENDER TOWN$" */

Route10_Text_RockTunnel:: @ 8184EE9
    .string "TÚNEL ROCA$"                             /* (E) "ROCK TUNNEL$" */

Route10_Text_PowerPlant:: @ 8184EF5
    .string "CENTRAL ENERGÍA$"                        /* (E) "POWER PLANT$" */

