LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
    .string "Acabo de mudarme a este pueblo.\p"
    .string "Escuché que el SR. FUJI tampoco es\n"
    .string "de por aquí.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
    .string "Que raro, el SR. FUJI no está.\n"
    .string "¿Adónde se fue?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
    .string "El SR. FUJI estaba rezando por\n"
    .string "la madre de CUBONE a solas.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
    .string "Esta es la casa del SR. FUJI.\p"
    .string "Es muy amable.\p"
    .string "Él cuida de los POKéMON huérfanos\n"
    .string "y abandonados.$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
    .string "¡Es tan cálido!\n"
    .string "Los POKéMON son agradables de\l"
    .string "abrazar.$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
    .string "NIDORINO: ¡Gaoo!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
    .string "PSYDUCK: ¡Gwappa!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
    .string "SR. FUJI: {PLAYER}…\p"
    .string "Tu misión con la POKéDEX es una\n"
    .string "que requiere una gran dedicación.\p"
    .string "Sin un amor profundo por los\n"
    .string "POKéMON, tu misión puede fallar.\p"
    .string "No estoy seguro si esto ayudará,\n"
    .string "pero quiero que lo tengas.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
    .string "{PLAYER} recibió una POKé FLAUTA\n"
    .string "del SR. FUJI.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
    .string "Al escuchar la POKé FLAUTA,\n"
    .string "un POKéMON dormido se levantará.\p"
    .string "Intenta usarla en POKéMON que sean\n"
    .string "obstáculos durmientes.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
    .string "¡Haz espacio para esto!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
    .string "SR. FUJI: ¿Te ha ayudado mi\n"
    .string "POKé FLAUTA?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
    .string "REVISTA DE FANS DE POKéMON\n"
    .string "¡Concurso mensual de dibujo!\p"
    .string "El formulario de inscripción se…\p"
    .string "¡Fue! lo cortaron de la revista.\n"
    .string "Seguro alguien ya se inscribió.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
    .string "Hay revistas de POKéMON aquí.\p"
    .string "INFORMANTE POKéMON…\p"
    .string "FAN POKéMON…$"

