RockTunnel_1F_Text_LennyIntro:: @ 8179366
    .string "¡Este túnel recorre un largo\n"          /* (E) "This tunnel goes a long way, kid!$" */
    .string "camino, niñ{OA}!$"

RockTunnel_1F_Text_LennyDefeat:: @ 8179388
    .string "¡Doh!\n"                                 /* (E) "Doh!\n" */
    .string "¡Tú ganas!$"                             /* (E) "You win!$" */

RockTunnel_1F_Text_LennyPostBattle:: @ 8179396
    .string "Cuidado con los ONIX.\n"                 /* (E) "Watch for ONIX.\n" */
    .string "Solo aparecen ocasionalmente.\p"         /* (E) "They appear only occasionally.\p" */
    .string "Si encuentras uno de nivel alto,\n"      /* (E) "High-level ones can put the\n" */
    .string "¡te podría dar un apretón!$"             /* (E) "squeeze on you!$" */

RockTunnel_1F_Text_OliverIntro:: @ 81793F1
    .string "Hmm.\n"                                  /* (E) "Hmm.\n" */
    .string "Puede que esté perdido aquí…$"           /* (E) "Maybe I'm lost in here…$" */

RockTunnel_1F_Text_OliverDefeat:: @ 817940E
    .string "¡Tengo que calmarme!\n"                  /* (E) "Ease up!\n" */
    .string "¿Qué estoy haciendo?\l"                  /* (E) "What am I doing?\l" */
    .string "¿Dónde está la salida?$"                 /* (E) "Which way is out?$" */

RockTunnel_1F_Text_OliverPostBattle:: @ 817943A
    .string "Ese POKéMON dormido en la RUTA 12\n"     /* (E) "That sleeping POKéMON on ROUTE 12\n" */
    .string "me obligó a tomar este desvío.$"         /* (E) "forced me to take this detour.$" */

RockTunnel_1F_Text_LucasIntro:: @ 817947B
    .string "¡La gente de fuera como tú debería\n"    /* (E) "Outsiders like you need to show me\n" */
    .string "respetarme!$"                            /* (E) "some respect!$" */

RockTunnel_1F_Text_LucasDefeat:: @ 81794AC
    .string "¡Me rindo!$"                             /* (E) "I give!$" */

RockTunnel_1F_Text_LucasPostBattle:: @ 81794B4
    .string "¡Tienes talento para escalar!$"          /* (E) "You're talented enough to hike!$" */

RockTunnel_1F_Text_AshtonIntro:: @ 81794D4
    .string "¡Batalla POKéMON!\n"                     /* (E) "POKéMON fight!\n" */
    .string "¡List{OA}, vamos!$"                      /* (E) "Ready, go!$" */

RockTunnel_1F_Text_AshtonDefeat:: @ 81794EE
    .string "¡Se acabó!$"                             /* (E) "Game over!$" */

RockTunnel_1F_Text_AshtonPostBattle:: @ 81794F9
    .string "¡Conseguiré un ZUBAT por el camino!$"    /* (E) "Oh well, I'll get a ZUBAT as I go!$" */

RockTunnel_1F_Text_LeahIntro:: @ 817951C
    .string "¡Ey!\p"                                  /* (E) "Eek!\p" */
    .string "¡No intentes alguna tontería en\n"       /* (E) "Don't try anything funny in the\n" */
    .string "la oscuridad!$"                          /* (E) "dark!$" */

RockTunnel_1F_Text_LeahDefeat:: @ 8179547
    .string "Estaba demasiado oscuro…$"               /* (E) "It was too dark…$" */

RockTunnel_1F_Text_LeahPostBattle:: @ 8179558
    .string "Vi a un MACHOP en este túnel.$"          /* (E) "I saw a MACHOP in this tunnel.$" */

RockTunnel_1F_Text_DanaIntro:: @ 8179577
    .string "Vine hasta aquí buscando POKéMON\n"      /* (E) "I came this far looking for wild\n" */
    .string "salvajes.$"                              /* (E) "POKéMON.$" */

RockTunnel_1F_Text_DanaDefeat:: @ 81795A1
    .string "¡Me quedé sin POKéMON!$"                 /* (E) "I'm out of POKéMON!$" */

RockTunnel_1F_Text_DanaPostBattle:: @ 81795B5
    .string "Parecías lind{OA} e inofensiv{OA}.\n"    /* (E) "You looked cute and harmless.\n" */
    .string "¡Sí que me equivoqué!$"                  /* (E) "Was I ever wrong!$" */

RockTunnel_1F_Text_ArianaIntro:: @ 81795E5
    .string "¡Tienes POKéMON!\n"                      /* (E) "You have POKéMON!\n" */
    .string "¡Empecemos!$"                            /* (E) "Let's start!$" */

RockTunnel_1F_Text_ArianaDefeat:: @ 8179604
    .string "¡Peleas duro!$"                          /* (E) "You play hard!$" */

RockTunnel_1F_Text_ArianaPostBattle:: @ 8179613
    .string "¡Ufff!\n"                                /* (E) "Whew!\n" */
    .string "Ahora estoy sudando.$"                   /* (E) "I'm all sweaty now.$" */

RockTunnel_1F_Text_RouteSign:: @ 817962D
    .string "TÚNEL ROCA\n"                            /* (E) "ROCK TUNNEL\n" */
    .string "CIUDAD CELESTE - PUEBLO LAVANDA$"        /* (E) "CERULEAN CITY - LAVENDER TOWN$" */

