CeladonCity_Restaurant_Text_TakingBreakRightNow::
    .string "¡Hola!\p"
    .string "Lo siento, pero ahora mismo nos\n"
    .string "estamos tomando un descanso.$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
    .string "Mis POKéMON son débiles, así que\n"
    .string "debo ir a la FARMACIA seguido.$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
    .string "¡Pss! se dice que hay un sótano\n"
    .string "bajo la SALA DE JUEGOS.$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
    .string "Nom…\p"
    .string "El hombre en esa mesa lo perdió\n"
    .string "todo en las tragamonedas.$"

CeladonCity_Restaurant_Text_TakeThisImBusted::
    .string "¡Adelante! ¡ríete!\n"
    .string "¡Estoy totalmente quebrado!\p"
    .string "¡No más tragamonedas para mí!\n"
    .string "¡Me limpiaré!\p"
    .string "¡Ten!\n"
    .string "¡Ya no necesitaré esto!$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan::
    .string "{PLAYER} recibió un MONEDERO\n"
    .string "del hombre.$"

CeladonCity_Restaurant_Text_MakeRoomForThis::
    .string "¡Haz espacio para esto!$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack::
    .string "Siempre creí que lo recuperaría\n"
    .string "todo…$"

