TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "Soy el MANÍACO de los\n"
    .string "MOVIMIENTOS POKéMON.\p"
    .string "Conozco cada movimiento que\n"
    .string "un POKéMON puede aprender\l"
    .string "mientras crece.\p"
    .string "También soy un maníaco de los\n"
    .string "hongos.\p"
    .string "Tráeme dos HONGOS PEQUEÑOS, o un\n"
    .string "HONGO GRANDE.\p"
    .string "Si haces eso por mi, le enseñaré\n"
    .string "un movimiento a un POKéMON.$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "Sniff, sniff…\n"
    .string "¡Hm! ¡hueles a HONGOS!\p"
    .string "¿Quieres que le enseñe un\n"
    .string "movimiento a uno de tus POKéMON?$"

TwoIsland_House_Text_TutorWhichMon::
    .string "¿Qué POKéMON necesita un tutor?$"

TwoIsland_House_Text_TeachWhichMove::
    .string "¿Qué movimiento debería enseñar?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "Lo siento…\p"
    .string "Parece que no tengo un movimiento\n"
    .string "que enseñarle a ese POKéMON.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "Entonces, necesito un HONGO o dos.\n"
    .string "¿Qué me vas a dar?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} entregó dos\n"
    .string "HONGOS PEQUEÑOS.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} entregó un\n"
    .string "HONGO GRANDE.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "Si tus POKéMON necesitan aprender\n"
    .string "un movimiento, necesito un\l"
    .string "HONGO o dos.$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "¿Huh? no hay ningún movimiento que\n"
    .string "pueda enseñarle a un HUEVO.$"

