Text_UltimateMoveThatMon::
    .string "Perfeccioné el movimiento\n"
    .string "definitivo de este tipo…\p"
    .string "Pero, ¿hay alguien que lo use a\n"
    .string "futuro?\p"
    .string "…¿Hm? ¡hmmm!\p"
    .string "T-tú…\n"
    .string "E-ese {STR_VAR_1}…$"

Text_JustMistaken::
    .string "…No…\n"
    .string "Solo me equivoqué.$"

Text_AllowMeToTeachMonUltimateMove::
    .string "¡Oh! ¡este es!\n"
    .string "¡Este es el POKéMON!\p"
    .string "¡Este {STR_VAR_1} es digno de\n"
    .string "aprender mi movimiento definitivo!\p"
    .string "¿Lo permitirás?\p"
    .string "¿Permitirás que tu {STR_VAR_1}\n"
    .string "aprenda {STR_VAR_2}?$"

Text_YouRejectIt::
    .string "¡Gaah! ¿lo rechazas?\n"
    .string "¡No, no seré engañada!$"

Text_LetMeConferUltimateMove::
    .string "¿Lo permitirás?\p"
    .string "Entonces, déjame enseñarle\n"
    .string "{STR_VAR_2} a tu {STR_VAR_1}.\p"
    .string "¡Ggggrah-awooo!$"

Text_TaughtMove::
    .string "Uf, uf, uf…\p"
    .string "No pensé que podría enseñar ese\n"
    .string "movimiento en toda mi vida…$"

Text_MakeBestUseOfMove::
    .string "¡Te imploro que le des el mejor\n"
    .string "uso a ese movimiento!$"

Text_PassedOnEverythingIKnow::
    .string "Gasp, gasp, gasp…\p"
    .string "Ya no tengo remordimientos.\n"
    .string "Enseñé todo lo que sé.\p"
    .string "Ahora puedo vivir mi vida sabiendo\n"
    .string "que mi trabajo esta hecho.$"

Text_FeelRejuvenated::
    .string "Después de que te pasé mi\n"
    .string "conocimiento, me sentí aliviada.\p"
    .string "¡De hecho, me siento rejuvenecida,\n"
    .string "como si fuera joven otra vez!$"
