Route1_Text_WorkAtPokeMartTakeSample::
    .string "¡Hola!\n"
    .string "Trabajo en una TIENDA POKéMON.\p"
    .string "Es parte de una cadena de tiendas\n"
    .string "que vende todo tipo de objetos.\p"
    .string "Por favor, visítanos en CIUDAD VERDE.\p"
    .string "Mira, te daré una muestra.\n"
    .string "¡Aquí tienes!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Por favor ve a vernos si necesitas\n"
    .string "POKéBOLAS para atrapar POKéMON.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} puso la POCIÓN\n"
    .string "en el BOLSILLO de OBJETOS\l"
    .string "de la MOCHILA.$"

Route1_Text_CanJumpFromLedges::
    .string "¿Ves esos bordes en el camino?\p"
    .string "Dan un poco de miedo, pero puedes\n"
    .string "saltar por encima de ellos.\p"
    .string "De esa forma podrás volver más\n"
    .string "rápidamente a PUEBLO PALETA.$"

Route1_Text_RouteSign::
    .string "RUTA 1\n"
    .string "PUEBLO PALETA - CIUDAD VERDE$"

