PokemonTower_5F_Text_RestHereInPurifiedSpace::
    .string "¡Ven, niñ{OA}!\n"
    .string "He purificado este espacio.\l"
    .string "Puedes descansar aquí.$"

PokemonTower_5F_Text_TammyIntro::
    .string "Da…me…\n"
    .string "todo…tu…$"

PokemonTower_5F_Text_TammyDefeat::
    .string "¡Ah!$"

PokemonTower_5F_Text_TammyPostBattle::
    .string "Estaba bajo posesión.$"

PokemonTower_5F_Text_RuthIntro::
    .string "Te…unirás…\n"
    .string "a…nosotros…$"

PokemonTower_5F_Text_RuthDefeat::
    .string "¡Qué pesadilla!$"

PokemonTower_5F_Text_RuthPostBattle::
    .string "Estaba poseída.$"

PokemonTower_5F_Text_KarinaIntro::
    .string "¡Zombis!$"

PokemonTower_5F_Text_KarinaDefeat::
    .string "¿Ah?$"

PokemonTower_5F_Text_KarinaPostBattle::
    .string "Recobré el conocimiento.$"

PokemonTower_5F_Text_JanaeIntro::
    .string "Urgah…\n"
    .string "Urff…$"

PokemonTower_5F_Text_JanaeDefeat::
    .string "¡Uuuu!$"

PokemonTower_5F_Text_JanaePostBattle::
    .string "Caí ante los espíritus malvados\n"
    .string "a pesar de mi entrenamiento\l"
    .string "en las montañas…$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
    .string "Entraste a la zona protegida\n"
    .string "y purificada.\p"
    .string "Los POKéMON de {PLAYER} fueron\n"
    .string "curados completamente.$"

