Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad::
    .string "¡No se permiten peatones en la\n"
    .string "CICLOVÍA!$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse::
    .string "La CICLOVÍA va cuesta abajo junto\n"
    .string "al mar. Es un viaje excelente.$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp::
    .string "¡Disculpa!\n"
    .string "¡Espera, por favor!$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort::
    .string "¿Cómo entraste?\n"
    .string "¡Buen esfuerzo!$"

