Route12_FishingHouse_Text_DoYouLikeToFish::
    .string "Soy el hermano menor del\n"
    .string "GURÚ DE LA PESCA.\p"
    .string "¡Simplemente aaamo pescar!\n"
    .string "No soporto vivir sin ello.\p"
    .string "¿Dime, te gusta pescar?$"

Route12_FishingHouse_Text_TakeThisAndFish::
    .string "¡Grandioso! Me gusta tu estilo.\n"
    .string "Creo que podemos ser amigos.\p"
    .string "¡Toma esto y pesca, joven amig{OA}!$"

Route12_FishingHouse_Text_ReceivedSuperRod::
    .string "{PLAYER} recibió una SUPER CAÑA\n"
    .string "del hermano del GURÚ DE LA PESCA.$"

Route12_FishingHouse_Text_IfYouCatchBigMagikarpShowMe::
    .string "¡Pescar es una forma de vida!\n"
    .string "Es cómo la más fina poesía.\p"
    .string "De los mares a los ríos, ve y\n"
    .string "atrapa algo grande, mi amig{OA}.\p"
    .string "Ahora, tengo algo que pedirte.\p"
    .string "Si atrapas un gran MAGIKARP con\n"
    .string "esa CAÑA, quiero verlo.\p"
    .string "Por más que ame a los peces, tambíen\n"
    .string "amo ver MAGIKARP gigantescos.$"

Route12_FishingHouse_Text_OhThatsDisappointing::
    .string "Oh…\n"
    .string "Eso es tan decepcionante…$"

Route12_FishingHouse_Text_TryFishingBringMeMagikarp::
    .string "¡Hola ahí, {PLAYER}!\n"
    .string "¿Has estado pescando?\p"
    .string "Intenta pescar con la SUPER CAÑA\n"
    .string "en cualquier cuerpo de agua.\p"
    .string "Encontrarás diferentes POKéMON en\n"
    .string "diferentes lugares.\p"
    .string "Oh, y no olvides traerme un\n"
    .string "MAGIKARP gigantesco.$"

Route12_FishingHouse_Text_OhMagikarpAllowMeToSee::
    .string "¿Oh? {PLAYER}?\n"
    .string "¡Pero si esto es un MAGIKARP!\p"
    .string "¡Déjame verlo, rápido!$"

Route12_FishingHouse_Text_WhoaXInchesTakeThis::
    .string "… … …¡Woh!\n"
    .string "¡{STR_VAR_2} pulgadas!\p"
    .string "¡Tienes una gran apreciación por\n"
    .string "los aspectos finos y poéticos de\l"
    .string "la pesca!\p"
    .string "Debes tomar esto.\n"
    .string "¡Insisto!$"

Route12_FishingHouse_Text_LookForwardToGreaterRecords::
    .string "¡Espero con ansias ver récords\n"
    .string "mayores de tu parte!$"

Route12_FishingHouse_Text_HuhXInchesSameSizeAsLast::
    .string "¿Uh?\n"
    .string "¿{STR_VAR_2} pulgadas?\p"
    .string "Es del mismo tamaño que el que\n"
    .string "mostraste antes.$"

Route12_FishingHouse_Text_HmmXInchesDoesntMeasureUp::
    .string "Hmm…\n"
    .string "Este es de {STR_VAR_2} pulgadas de largo.\p"
    .string "No se compara con el de {STR_VAR_3}\n"
    .string "pulgadas que mostraste antes.$"

Route12_FishingHouse_Text_DoesntLookLikeMagikarp::
    .string "Uh… eso no se ve como un MAGIKARP.$"

Route12_FishingHouse_Text_NoRoomForGift::
    .string "¡Oh, no!\p"
    .string "Tenía un regalo para ti, pero no\n"
    .string "tienes espacio para eso.$"

Route12_FishingHouse_Text_MostGiganticMagikarpXInches::
    .string "El MAGIKARP más grande que haya\n"
    .string "presenciado jamás…\p"
    .string "¡{STR_VAR_3} pulgadas!$"

Route12_FishingHouse_Text_BlankChartOfSomeSort::
    .string "Es una especie de pizarrón.\p"
    .string "Tiene espacios para escribir\n"
    .string "récords de algún tipo.$"

