CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
    .string "No hay nada que no sepa, como\n"
    .string "escribí en el pizarrón.\p"
    .string "¡Yo sé sobre el mundo de los\n"
    .string "POKéMON en tu GAME BOY ADVANCE!\p"
    .string "¡Reúnete con tus amigos y disfruta\n"
    .string "intercambiar POKéMON!$"

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
    .string "¡{PLAYER} obtuvo un EEVEE!$"

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull::
    .string "ポケモンが　いっぱいだ\n"
    .string "ボックスを　かえて　きなさい$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
    .string "Clase POKéMON\p"
    .string "Usando el Conector Inalámbrico.$"

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading::
    .string "¿Qué capítulo quieres leer?$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainWirelessClub::
    .string "El CLUB INALÁMBRICO POKéMON está\n"
    .string "en el piso superior de cualquier\l"
    .string "CENTRO POKéMON.\p"
    .string "Visita uno para conectarte con\n"
    .string "tu(s) amigo(s) usando tu\l"
    .string "Conector Inalámbrico de GBA.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainDirectCorner::
    .string "Para conectarte sólo con un amigo,\n"
    .string "ve a la ZONA DIRECTA.\p"
    .string "Es el mostrador derecho del\n"
    .string "CLUB INALÁMBRICO POKéMON.\p"
    .string "Ve a la SALA DE INTERCAMBIOS\n"
    .string "o al COLISEO con tu amigo.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainUnionRoom::
    .string "Para conectarte y comunicarte con\n"
    .string "cualquiera, ve a la SALA UNIÓN.\p"
    .string "Es el mostrador izquierdo en el\n"
    .string "CLUB INALÁMBRICO POKéMON.\p"
    .string "Ve a la SALA UNIÓN y disfruta\n" 
    .string "encontrarte con más ENTRENADORES.$"

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .string "Es un informe sobre MTs.\p"
    .string "… …\p"
    .string "Hay cincuenta TMs en total.\p"
    .string "También hay siete MOs que pueden\n"
    .string "usarse repetidamente.\p"
    .string "SILPH S.A.$"

