CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon::
    .string "¡Sí que quiero a ese PORYGON!\p"
    .string "¡Pero es difícil ganar en las\n"
    .string "tragamonedas!$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday::
    .string "¡Gajaja! ¡gané mucho hoy!\n"
    .string "Ojalá fuera así todos los días…$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired::
    .string "Se necesita un MONEDERO…$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes::
    .string "Cambiamos tus MONEDAS por premios.$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize::
    .string "¿Cúal premio te gustaría?$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo::
    .string "はい どうぞ$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize::
    .string "¿Entonces, quieres {STR_VAR_1}?$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM::
    .string "De acuerdo, ¿quieres una MT de\n"
    .string "{STR_VAR_2}?$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins::
    .string "Lo siento, necesitas más MONEDAS\n"
    .string "que esas.$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom::
    .string "おきゃくさん もう もてないよ$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen::
    .string "あっ そう$"

