SilphCo_10F_Text_GruntIntro::
    .string "¡Bienvenid{OA} al PISO 10!\n"
    .string "¡Me alegra que me acompañes!$"

SilphCo_10F_Text_GruntDefeat::
    .string "¡Estoy aturdido!$"

SilphCo_10F_Text_GruntPostBattle::
    .string "Buen intento, pero la sala de\n"
    .string "juntas está en el piso de arriba.$"

SilphCo_10F_Text_TravisIntro::
    .string "¡Basta de tus tontos juegos!$"

SilphCo_10F_Text_TravisDefeat::
    .string "¡Se acabaron los intentos!$"

SilphCo_10F_Text_TravisPostBattle::
    .string "¿Estás satisfech{OA} con vencerme?\n"
    .string "¡Entonces vete a casa!$"

SilphCo_10F_Text_WaaaImScared::
    .string "¡Waaaaa!\n"
    .string "¡Tengo miedo!$"

SilphCo_10F_Text_KeepMeCryingASecret::
    .string "Sobre mí llorando…\n"
    .string "Por favor mantenlo en secreto.$"

SilphCo_10F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P10$"

