SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale::
    .string "{PLAYER}: ¡Hola!\n"
    .string "¿Te gustan los POKéMON?\p"
    .string "{PLAYER}: No, te lo pregunté a tí.\p"
    .string "{PLAYER}: ¿Huh?\n"
    .string "¡Eres extraña!\p"
    .string "IMITADORA: ¿Hmm? ¿dejar de imitar?\n"
    .string "¡Pero es mi pasatiempo favorito!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale::
    .string "{PLAYER}: Hola.\n"
    .string "Seguro te gustan los POKéMON.\p"
    .string "{PLAYER}: No, yo no.\n"
    .string "Yo te pregunté a tí.\p"
    .string "{PLAYER}: ¿Perdón?\n"
    .string "¡Eres rara!\p"
    .string "IMITADORA: ¿Hmm? ¿dejar de imitar?\n"
    .string "¡Pero es mi pasatiempo favorito!$"

Text_MimicTeach::
    .string "¡Oh, guau!\n"
    .string "¡Un POké MUÑECO!\p"
    .string "¿Para mí?\n"
    .string "¡Gracias!\p"
    .string "¿Sabes qué?\n"
    .string "Puedo enseñar el movimiento MÍMICA.$"

Text_MimicDeclined::
    .string "¿No te gusta MÍMICA?$"

Text_MimicWhichMon::
    .string "¡Adoro MÍMICA!\n"
    .string "¿Quién va a aprenderlo?$"

Text_MimicTaughtMale::
    .string "{PLAYER}: ¡Hola!\n"
    .string "¡Gracias por lo de antes!\p"
    .string "{PLAYER}: ¿Perdón?\p"
    .string "{PLAYER}: ¿Es tan divertido imitar\n"
    .string "mis movimientos?\p"
    .string "IMITADORA: ¡Claro que sí!\n"
    .string "¡Es muy gracioso!$"

Text_MimicTaughtFemale::
    .string "{PLAYER}: ¡Hola!\n"
    .string "Gracias por lo que hiciste por\l"
    .string "nosotros.\p"
    .string "{PLAYER}: ¿Perdón?\p"
    .string "{PLAYER}: ¿Es tan divertido copiar\n"
    .string "lo que digo y lo que hago?\p"
    .string "IMITADORA: ¡Claro que sí!\n"
    .string "¡Es muy gracioso!$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag::
    .string "にもつが　いっぱいね！$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP::
    .string "{PLAYER}“やあ！　こんにちは！\n"
    .string "きみ　ポケモン　すきかい？\p"
    .string "{PLAYER}“ぼく　じゃなくって\n"
    .string "きみに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥‥　えー　なんだよ！\n"
    .string "ヘンな　やつ　だなあ！\p"
    .string "モノマネむすめ“‥‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし　\n"
    .string "ものまね　しゅみ　なんだ　もん！”$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP::
    .string "{PLAYER}“こんにちは！\n"
    .string "ポケモン　すきなのね？\p"
    .string "{PLAYER}“わたし　じゃなくって\n"
    .string "あなたに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥　えー　なんなの！\n"
    .string "おかしなこ　ねー！\p"
    .string "モノマネむすめ“‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし\n"
    .string "ものまね　しゅみ　なんだ　もん！$"

SaffronCity_CopycatsHouse_2F_Text_Doduo::
    .string "DODUO: ¡Giiih!\p"
    .string "¡ESPEJITO, ESPEJITO! ¿QUIÉN ES\n"
    .string "LA MÁS BELLA DE TODAS?$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll::
    .string "¡Es un POKéMON raro!\n"
    .string "¿Uh? ¡es solo un muñeco!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
    .string "¡Un juego donde MARIO tiene un\n"
    .string "balde en la cabeza!$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets::
    .string "…\p"
    .string "¡Mis secretos!\p"
    .string "Habilidad: ¡La mímica!\n"
    .string "Pasatiempo: ¡Coleccionar muñecos!\l"
    .string "POKéMON favorito: ¡CLEFAIRY!$"

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee::
    .string "？　みえないぞ‥$"
