PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "MAMÁ: …Claro.\n"
    .string "Todos los niños se van de casa\l"
    .string "algún día. O eso dice la TV.\p"
    .string "Ah, nuestro vecino, el PROF. OAK,\n"
    .string "estaba buscándote.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "MAMÁ: …Claro.\n"
    .string "Todas las niñas sueñan con viajar.\l"
    .string "O eso dice la TV.\p"
    .string "Ah, nuestro vecino, el PROF. OAK,\n"
    .string "estaba buscándote.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "MAMÁ: ¡{PLAYER}!\n"
    .string "Deberías tomar un pequeño descanso.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "MAMÁ: ¡Oh, bien! Tú y tus POKéMON\n"
    .string "se ven muy bien.\l"
    .string "¡Quídate!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "Hay una película en la TV.\n"
    .string "Cuatro niños están caminando por\l"
    .string "las vías del tren.\p"
    .string "…Bueno, yo tambien debería irme.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "Hay una película en la TV.\n"
    .string "Una niña con coletas esta caminando\l"
    .string "por un camino de ladrillos.\p"
    .string "…Bueno, yo tambien debería irme.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Ups, lado equivocado…$"

