PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou:: @ 818D2F0
    .string "MAMÁ: …Claro.\n"
    .string "Todos los niños se van de casa\l"
    .string "algún día. O eso dice la TV.\p"
    .string "Ah, nuestro vecino, el PROF. OAK,\n"
    .string "estaba buscándote.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou:: @ 818D360
    .string "MAMÁ: …Claro.\n"
    .string "Todas las niñas sueñan con viajar.\l"
    .string "O eso dice la TV.\p"
    .string "Ah, nuestro vecino, el PROF. OAK,\n"
    .string "estaba buscándote.$"
    
PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest:: @ 818D3D1
    .string "MAMÁ: ¡{PLAYER}!\n"
    .string "Deberías tomar un pequeño descanso.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare:: @ 818D3F8
    .string "MAMÁ: ¡Oh, bien! Tú y tus POKéMON\n"
    .string "se ven muy bien.\l"
    .string "¡Quídate!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad:: @ 818D43E
    .string "Hay una película en la TV.\n"
    .string "Cuatro niños están caminando por\l"
    .string "las vías del tren.\p"
    .string "…Bueno, yo tambien debería irme.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad:: @ 818D492
    .string "Hay una película en la TV.\n"
    .string "Una niña con coletas esta caminando\l"
    .string "por un camino de ladrillos.\p"
    .string "…Bueno, yo tambien debería irme.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide:: @ 818D4F9
    .string "Oops, lado equivocado…$"
