LavenderTown_House2_Text_WantMeToRateNicknames::
    .string "¡Hola, hola!\n"
    .string "¡Soy el INSPECTOR DE APODOS!\p"
    .string "¿Quieres que evalue los apodos de\n"
    .string "tus POKéMON?$"

LavenderTown_House2_Text_CritiqueWhichMonsNickname::
    .string "¿Que apodo de POKéMON debería\n"
    .string "evaluar?$"

LavenderTown_House2_Text_GiveItANicerName::
    .string "¿{STR_VAR_1}, cierto?\n"
    .string "¡Ese es un nombre decente!\p"
    .string "Pero, ¿te gustaría darle uno\n"
    .string "mejor?\p"
    .string "¿Que te parece?$"

LavenderTown_House2_Text_WhatShallNewNicknameBe::
    .string "Ah, bien. Entonces, ¿cúal será el\n"
    .string "nuevo apodo?$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsName::
    .string "¡Hecho! de ahora en adelante, este\n"
    .string "POKéMON se llamará {STR_VAR_1}!\p"
    .string "¡Tiene un mejor nombre que antes!\n"
    .string "¡Sí que tienes suerte!$"

LavenderTown_House2_Text_ISeeComeVisitAgain::
    .string "Ya veo.\n"
    .string "Vuelve cuando quieras.$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName::
    .string "¡Hecho! de ahora en adelante, este\n"
    .string "POKéMON se llamará {STR_VAR_1}!\p"
    .string "Se ve igual que antes, pero\n"
    .string "aún así, ¡es vastamente superior!\p"
    .string "¡Sí que tienes suerte!$"

LavenderTown_House2_Text_TrulyImpeccableName::
    .string "¿{STR_VAR_1}, cierto?\n"
    .string "¡Es un nombre realmente impecable!\p"
    .string "¡Cuida bien a {STR_VAR_1}!$"

LavenderTown_House2_Text_ThatIsMerelyAnEgg::
    .string "Espera, espera.\n"
    .string "¡Eso es solo un HUEVO!$"

