RocketHideout_B3F_Text_Grunt1Intro::
    .string "¡Deja de meterte en los asuntos\n"
    .string "del EQUIPO ROCKET o verás!$"

RocketHideout_B3F_Text_Grunt1Defeat::
    .string "¡Uf!\n"
    .string "¡Derribado!$"

RocketHideout_B3F_Text_Grunt1PostBattle::
    .string "¿VISOR SILPH?\n"
    .string "Oh, esa máquina que el JEFE robó.\p"
    .string "Está por aquí.$"

RocketHideout_B3F_Text_Grunt2Intro::
    .string "¡Nos avisaron de arriba que\n"
    .string "llegarías!!$"

RocketHideout_B3F_Text_Grunt2Defeat::
    .string "¿Qué?\n"
    .string "¿Perdí? ¡no!$"

RocketHideout_B3F_Text_Grunt2PostBattle::
    .string "¡Adelante, ve!\p"
    .string "Pero no podrás llegar sin una\n"
    .string "LLAVE ASCENSOR.$"

