SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies::
    .string "La tasa de crecimiento de los\n"
    .string "POKéMON varía entre especies.$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame::
    .string "SILPH es conocida por todos.\p"
    .string "Es víctima de su propia fama - eso\n"
    .string "atrajo al EQUIPO ROCKET.$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets::
    .string "Ay…\n"
    .string "¿No sería genial?\p"
    .string "¿Si el ALTO MANDO llegara y\n"
    .string "aplastara al EQUIPO ROCKET?$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff::
    .string "¡El EQUIPO ROCKET huyó!\n"
    .string "¡Podemos salir de forma segura!\l"
    .string "¡Qué bien!$"

