Route16_House_Text_FoundMySecretRetreat::
    .string "Oh, cielos.\n"
    .string "Encontraste mi escondite secreto.\p"
    .string "Por favor no le digas a nadie\n"
    .string "que estoy aquí.\p"
    .string "¡Te lo compensaré con esto!$"

Route16_House_Text_ReceivedHM02FromGirl::
    .string "{PLAYER} recibió MO02\n"
    .string "de la chica.$"

Route16_House_Text_ExplainHM02::
    .string "MO02 es VUELO.\n"
    .string "Es un movimiento súper conveniente.\p"
    .string "Por favor, dale un buen uso.$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "No tienes espacio para esto.$"

Route16_House_Text_Fearow::
    .string "FEAROW: ¡Kyueen!$"

