PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "La TORRE POKéMON fue eregida\n"
    .string "en memoria de los POKéMON que\l"
    .string "han fallecido.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "¿Viniste a rendir homenaje?\p"
    .string "Bendito sea tu amor por los\n"
    .string "POKéMON, niño.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "¿Viniste a rendir homenaje?\p"
    .string "Bendito sea tu amor por los\n"
    .string "POKéMON, niña.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "Vine a rezar por mi querido\n"
    .string "CLEFAIRY.\p"
    .string "¡Sniff!\n"
    .string "No puedo dejar de llorar…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "Mi GROWLITHE…\n"
    .string "¿Por qué tuviste que morir?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "Soy una CHAMÁN.\p"
    .string "Puedo sentir espíritus traviesos\n"
    .string "en lo más alto de la TORRE.$"

