FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
    .string "Al guarda le pusimos “SLOWPOKE”\n"
    .string "de apodo.\p"
    .string "Ya sabes, tiene la mirada perdida\n"
    .string "de un SLOWPOKE.$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
    .string "El GUARDA SLOWPOKE sabe mucho\n"
    .string "sobre los POKéMON.\p"
    .string "Incluso tiene fósiles de POKéMON\n"
    .string "raros y extintos.$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
    .string "El GUARDA SLOWPOKE entró, pero\n"
    .string "no podía entenderlo.\p"
    .string "¡Creo que tiene un problema\n"
    .string "del habla!$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
    .string "El GUARDA SLOWPOKE gestiona una\n"
    .string "campaña de publicidad justo ahora.\p"
    .string "Intenta llegar al rincón más\n"
    .string "lejano de la ZONA SAFARI.\p"
    .string "Si lo logras, ganarás un premio\n"
    .string "muy útil.$"

