Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers:: @ 819E523
    .string "Los tipos de los POKéMON se\n"
    .string "enfrentan de formas distintas.\p"
    .string "Cada tipo es fuerte contra algunos\n"
    .string "tipos y débil ante otros.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000:: @ 819E59D
    .string "Una PEPITA es totalmente inútil.\n"
    .string "Así que la vendí por ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender:: @ 819E5D2
    .string "Se dice que hay fantasmas que\n"
    .string "espantan en PUEBLO LAVANDA.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons:: @ 819E5FB
    .string "Oh… ¡{PLAYER}!\n"
    .string "¡Te he estado buscando!\p"
    .string "Soy yo, uno de los siempre\n" 
    .string "presentes AYUDANTES del PROF. OAK.\p"
    .string "Si tu POKéDEX tiene datos completos\n"
    .string "de 20 especies, se supone que\l"
    .string "debería darte una recompensa.\p"
    .string "El PROF. OAK me encargo la\n"
    .string "PIEDRA ETERNA para ti.\p"
    .string "Entonces, {PLAYER}, dime algo.\p"
    .string "¿Ya recolectaste datos de al menos\n"
    .string "20 tipos de POKéMON?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo:: @ 819E733
    .string "¡Bien! ¡atrapaste u obtuviste\n"
    .string "{STR_VAR_3} tipos de POKéMON!\p"
    .string "¡Felicidades!\n"
    .string "¡Aquí tienes!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide:: @ 819E786
    .string "{PLAYER} recibió la PIEDRA ETERNA\n"
    .string "del AYUDANTE.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone:: @ 819E7AF
    .string "Hacer evolucionar a los POKéMON\n"
    .string "puede añadir a la POKéDEX.\p"
    .string "Pero, puede que quieras evitar\n"
    .string "la evolución de cierto POKéMON.\p"
    .string "En ese caso, dale la PIEDRA ETERNA\n"
    .string "a ese POKéMON.\p"
    .string "Previene la evolución, según\n"
    .string "el PROFESOR.$"

