ViridianCity_Text_CanCarryMonsAnywhere::
    .string "¡Esas POKéBOLAS en tu cintura!\n"
    .string "¿Tienes POKéMON, cierto?\p"
    .string "Es genial poder llevar y usar los\n"
    .string "POKéMON en cualquier momento\l"
    .string "y lugar.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "Este GIMNASIO POKéMON siempre\n"
    .string "está cerrado.\p"
    .string "¿Quién será su LÍDER?$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "¡El LÍDER de GIMNASIO de VERDE\n"
    .string "regresó!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "¿Quieres saber algo sobre los dos\n"
    .string "tipos de orugas POKéMON?$"

ViridianCity_Text_OhOkayThen::
    .string "Oh, ¡de acuerdo!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "CATERPIE no tiene veneno,\n"
    .string "pero WEEDLE sí.\p"
    .string "Ten cuidado, puede que tus POKéMON\n"
    .string "reciban el PIQUETE VENENOSO\l"
    .string "de WEEDLE.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "¡Oh, Abuelo!\n"
    .string "¡No seas tan grosero!\p"
    .string "Lo siento tanto.\n"
    .string "Todavía no se ha tomado su café.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "De vez en cuando voy de compras\n"
    .string "a CIUDAD PLATEADA.\p"
    .string "Cuando voy, tengo que tomar el\n"
    .string "sinuoso camino del BOSQUE VERDE.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "¡Tienes absolutamente prohibido\n"
    .string "pasar por aquí!\p"
    .string "¡Ésta es propiedad privada!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Bueno, ya tomé mi café, ¡y era lo\n"
    .string "que necesitaba para reactivarme!\p"
    .string "¿Oh?\n"
    .string "¿Qué es esa caja roja?\p"
    .string "Ah, así que estás trabajando\n"
    .string "en tu POKéDEX.\p"
    .string "Entonces, dejame darte algo de\n"
    .string "información.\p"
    .string "Cuando atrapes un POKéMON,\n"
    .string "la POKéDEX actualizará sus datos\l"
    .string "automáticamente.\p"
    .string "…¿No sabes atrapar POKéMON?\p"
    .string "¡En ese caso, supongo que tendre\n"
    .string "que mostrarte como!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "¡Listo! no me diras que no\n"
    .string "ha sido educativo, ¿eh?\p"
    .string "Vamos, toma esto.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "Úsala si es que hay algo que\n"
    .string "no entiendas.\p"
    .string "Te enseñara lo básico de ser un{A}\n"
    .string "ENTRENADOR{AM} POKéMON.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Bueno, ya tomé mi café, ¡y era lo\n"
    .string "que necesitaba para reactivarme!\p"
    .string "Pero lo hice muy cargado.\n"
    .string "Me dio dolor de cabeza…\p"
    .string "Por cierto, ¿estás llenando tu\n"
    .string "POKéDEX?\p"
    .string "Primero, concentrate en debilitar\n"
    .string "al POKéMON antes de intentar\l"
    .string "atraparlo.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Bueno, ya tomé mi café, ¡y era lo\n"
    .string "que necesitaba para reactivarme!\p"
    .string "Pero lo hice muy cargado.\n"
    .string "Me dio dolor de cabeza…\p"
    .string "Por cierto, ¿te esta ayudando\n"
    .string "mi vieja ENSEÑAME TV?$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "¡Wajaja!\n"
    .string "¡Mi nieto esta en el programa!\p"
    .string "Como él es quien enseña, es\n"
    .string "muy probable que aprendas.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… Estás muy ocupad{OA}, incluso\n"
    .string "para usar la ENSEÑAME TV…\p"
    .string "El tiempo es dinero, y ninguno de\n"
    .string "los dos debería ser malgastado…$"

ViridianCity_Text_CitySign::
    .string "CIUDAD VERDE\n"
    .string "El paraíso del eterno verdor.$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "Atrapa POKéMON y amplía tu\n"
    .string "colección.\p"
    .string "Cuantos más tengas, las batallas\n"
    .string "serán más fáciles.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "Los ataques de los POKéMON están\n"
    .string "limitados por sus PUNTOS de PODER,\l"
    .string "o PP.\p"
    .string "Para rellenar PP, deja que tus\n"
    .string "POKéMON cansados descansen en\l"
    .string "un CENTRO POKéMON.$"

ViridianCity_Text_GymSign::
    .string "GIMNASIO POKéMON DE CIUDAD VERDE$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "Las puertas del GIMNASIO están\n"
    .string "cerradas…$"
