CeruleanCity_Text_RivalIntro::
    .string "{RIVAL}: ¡Hey! ¡{PLAYER}!\p"
    .string "¿Sigues en problemas por aquí?\p"
    .string "¡A mí me va genial! ¡Atrapé muchos\n"
    .string "POKéMON fuertes y listos!\p"
    .string "Bueno, ¡déjame ver que atrapaste,\n"
    .string "{PLAYER}!$"

CeruleanCity_Text_RivalDefeat::
    .string "¡Hey!\n"
    .string "¡Relájate!\l"
    .string "¡Ya ganaste!$"

CeruleanCity_Text_RivalPostBattle::
    .string "{RIVAL}: ¿Hey, adivina que?\p"
    .string "Fui con BILL e hice que me\n"
    .string "enseñara sus POKéMON raros.\p"
    .string "¡Eso añadió muchas páginas a mi\n"
    .string "POKéDEX!\p"
    .string "Después de todo, BILL es un\n"
    .string "POKéMANÍACO mundialmente famoso.\p"
    .string "También invento el Sistema de\n"
    .string "Almacenamiento de POKéMON.\p"
    .string "Cómo usas su sistema, deberías ir\n"
    .string "a darle las gracias.\p"
    .string "Bueno, ¡será mejor que me vaya!\n"
    .string "¡Hasta nunca!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
    .string "Oh, sí, cierto.\p"
    .string "Me siento mal por tí. En serio.\n"
    .string "Siempre estas gateando trás de mi.\p"
    .string "Así que, te daré un pequeño\n"
    .string "regalo cómo un favor.$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
    .string "Un{A} chismos{OA} cómo tu…\n"
    .string "Esa cosa es perfecta.\p"
    .string "No la necesito porque no me\n"
    .string "importan mucho los demás.\p"
    .string "De acuerdo, esta vez me voy de\n"
    .string "verdad. ¡Hasta nunca!$"

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory::
    .string "なんたって！\n"
    .string "おれは　てんさい　だからよ！$"

CeruleanCity_Text_GruntIntro::
    .string "¡Ey! ¡Vete de aquí!\n"
    .string "¡Este no es tu patio!\p"
    .string "…¿Eh?\n"
    .string "¿Yo?\p"
    .string "¡Yo soy un espectador inocente!\n"
    .string "¿No me crees?{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

CeruleanCity_Text_GruntDefeat::
    .string "RECLUTA: ¡Basta! ¡Me rindo!\n"
    .string "¡Me iré silenciosamente!$"

CeruleanCity_Text_OkayIllReturnStolenTM::
    .string "…De acuerdo.\n"
    .string "Regresaré la MT que robé.$"

CeruleanCity_Text_RecoveredTM28FromGrunt::
    .string "{PLAYER} recuperó la MT28 del\n"
    .string "RECLUTA del EQUIPO ROCKET.$"

CeruleanCity_Text_BetterGetMovingBye::
    .string "¡Será mejor que me vaya!\n"
    .string "¡Adiós!$"

CeruleanCity_Text_MakeRoomForThisCantRun::
    .string "¡Haz espacio para esto!\n"
    .string "¡No puedo escapar hasta que te la de!$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
    .string "¿También entrenas POKéMON?\p"
    .string "Atrapar, luchar…\n"
    .string "Es una vida dura, ¿no es así?$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
    .string "¿Sabías que puedes CORTAR árboles\n"
    .string "pequeños?\p"
    .string "Incluso puedes CORTARS ese pequeño\n"
    .string "árbol enfrente de la tienda,\p"
    .string "Aunque creo que hay una forma de\n"
    .string "rodearlo.$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
    .string "Si ese SLOWBRO no estuviera ahí,\n"
    .string "podrías CORTAR ese pequeño árbol.\p"
    .string "Así podrías pasar al otro lado.\p"
    .string "Aunque creo que hay una forma de\n"
    .string "rodearlo.$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
    .string "¿Estás haciendo una enciclopedia\n"
    .string "sobre POKéMON? Suena divertido.$"

CeruleanCity_Text_PeopleHereWereRobbed::
    .string "La gente aquí sufrió un robo.\p"
    .string "¡Es obvio que el EQUIPO ROCKET\n"
    .string "está detrás de este crimen atroz!\p"
    .string "¡Incluso nuestra FUERZA POLICIAL\n"
    .string "tiene problemas con los ROCKETS!$"

CeruleanCity_Text_SlowbroUseSonicboom::
    .string "¡Bien! SLOWBRO!\n"
    .string "¡Usa EXPLOSIÓN SÓNICA!$"

CeruleanCity_Text_SlowbroPayAttention::
    .string "¡Vamos, SLOWBRO, pon atención!$"

CeruleanCity_Text_SlowbroPunch::
    .string "¡SLOWBRO, golpea!$"

CeruleanCity_Text_NoYouBlewItAgain::
    .string "¡No!\n"
    .string "¡Lo arruinaste otra vez!$"

CeruleanCity_Text_SlowbroWithdraw::
    .string "¡SLOWBRO, REFUGIO!$"

CeruleanCity_Text_HardToControlMonsObedience::
    .string "¡No! ¡Eso está mal!\n"
    .string "¡Es tan difícil controlar a los\l"
    .string "POKéMON!\p"
    .string "La obediencia de tus POKéMON\n"
    .string "depende de tus habilidades\l"
    .string "cómo ENTRENADOR{AM}.$"

CeruleanCity_Text_SlowbroTookSnooze::
    .string "SLOWBRO se tomó un descanso…$"

CeruleanCity_Text_SlowbroLoafingAround::
    .string "SLOWBRO está holgazaneando…$"

CeruleanCity_Text_SlowbroTurnedAway::
    .string "SLOWBRO volteo hacia otro lado…$"

CeruleanCity_Text_SlowbroIgnoredOrders::
    .string "SLOWBRO ignoró las órdenes…$"

CeruleanCity_Text_WantBrightRedBicycle::
    .string "Quiero una bonita BICICLETA roja.\p"
    .string "La guardaré en casa, para que\n"
    .string "no se ensucie.$"

CeruleanCity_Text_ThisIsCeruleanCave::
    .string "This is CERULEAN CAVE.\p"
    .string "Horribly strong POKéMON live inside\n"
    .string "there.\p"
    .string "It takes a very special TRAINER to\n"
    .string "be allowed inside there.\p"
    .string "You'd have to be strong enough to\n"
    .string "become the POKéMON LEAGUE\l"
    .string "CHAMPION for starters.\p"
    .string "And, you would have to have\n"
    .string "made a great achievement.$"

CeruleanCity_Text_CitySign::
    .string "CIUDAD CELESTE\n"
    .string "Una misteriosa aura azulada\l"
    .string "la rodea.$"

CeruleanCity_Text_TrainerTipsHeldItems::
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "Puedes entregar objetos a\n"
    .string "tus POKéMON.\p"
    .string "Incluso, puede que usen el objeto\n"
    .string "en batalla.$"

CeruleanCity_Text_BikeShopSign::
    .string "¡Césped y cuevas bajo control!\n"
    .string "TIENDA DE BICICLETAS$"

CeruleanCity_Text_GymSign::
    .string "GIMNASIO POKéMON de CIUDAD CELESTE\n"
    .string "LÍDER: MISTY\l"
    .string "¡La sirena ruda!$"

