CeruleanCity_BikeShop_Text_WelcomeToBikeShop:: @ 8192755
    .string "¡Hola!\n"
    .string "Bienvenid{OA} a la TIENDA DE BICIS.\p"
    .string "¡Tenemos una BICICLETA justo para\n"
    .string "ti!$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt:: @ 8192796
    .string "¡Lo siento!\n"
    .string "¡No puedes pagarla!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo:: @ 81927B2
    .string "Oh, eso es…\p"
    .string "¡Un BONO BICICLETA!\p"
    .string "¡Bien!\n"
    .string "¡Aquí tienes!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle:: @ 81927E1
    .string "{PLAYER} cambió el\n"
    .string "BONO por una BICICLETA.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain:: @ 819280E
    .string "¡Gracias!\n"
    .string "¡Vuelve cuando quieras!$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle:: @ 8192833
    .string "¿Te gusta tu nueva BICICLETA?\n"
    .string "¿Te gusta cómo se maneja?\p"
    .string "¡Puedes llevarla al CAMINO\n"
    .string "DE CICLISTAS e incluso a cuevas!$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle:: @ 81928A8
    .string "¡Será mejor que hagas espacio para\n"
    .string "tu BICICLETA!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe:: @ 81928CF
    .string "Una plana BICICLETA de ciudad\n"
    .string "basta para mí.\p"
    .string "Después de todo, no puedes poner\n"
    .string "una cesta en una BICI de montaña.$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive:: @ 8192937
    .string "¡Estas BICIS son geniales, pero\n"
    .string "son muy caras!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool:: @ 8192968
    .string "Wow.\n"
    .string "¡Tu BICI es realmente genial!$"

@ Unused
CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket:: @ 8192987
    .string "ついに　はつばい！\p"
    .string "ドイツ　せい　さいこうきゅう\n"
    .string "おりたたみ　じてんしゃ！$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle:: @ 81929AD
    .string "¡Una BICICLETA nueva y reluciente!$"

