CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
    .string "¡Hola!\p"
    .string "Bienvenid{OA} a la TIENDA DEP.\n"
    .string "PRISMA.\p"
    .string "El tablero de la derecha describe\n"
    .string "un plano de la tienda.$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
    .string "P1: MOSTRADOR DE SERVICIO\p"
    .string "P2: MERCADO DE ENTRENADORES\p"
    .string "P3: TIENDA DE VIDEOJUEGOS\p"
    .string "P4: REGALOS\p"
    .string "P5: FARMACIA\p"
    .string "AZOTEA: MÁQUINAS EXPENDEDORAS$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
    .string "P1: MOSTRADOR DE SERVICIO$"

