CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
    .string "Los POKéMON capturados tienen un\n"
    .string "N.º de IDENTIDAD y un EO.\p"
    .string "EO es de “ENTRENADOR Original” -\n"
    .string "quién lo haya atrapado primero.$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
    .string "¡Muy bien!\p"
    .string "¡Mi compañero va a cambiarme su\n"
    .string "KANGASKHAN por mi HAUNTER!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
    .string "¡Vamos, HAUNTER!\p"
    .string "¡Me encantan los HAUNTER!\n"
    .string "¡Los colecciono!\p"
    .string "¿Huh?\p"
    .string "¡HAUNTER se volvió un POKéMON\n"
    .string "diferente al ser intercambiado!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
    .string "Puedes identificar a los POKéMON\n"
    .string "de intercambios por su N.º ID.$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
    .string "Es una Super NES.$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
    .string "¡Un juego de rol!\n"
    .string "¡No hay tiempo para eso!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
    .string "¡Un juego de deportes!\n"
    .string "¡A papá le gustaría!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
    .string "¡Un juego de rompecabezas!\n"
    .string "¡Se ve adictivo!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
    .string "¡Un juego de peleas!\n"
    .string "¡Se ve difícil!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
    .string "P3: TIENDA DE VIDEOJUEGOS$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
    .string "¡Rojo y Verde!\n"
    .string "¡Ambos juegos de POKéMON!$"

Text_CounterTeach::
    .string "¡Oh, hola!\n"
    .string "Finalmente terminé POKéMON.\p"
    .string "¿Tú no? ¿que tal si te enseño\n"
    .string "un buen movimiento?\p"
    .string "El movimiento que tengo en mente\n"
    .string "es CONTRAATAQUE.\p"
    .string "¡No te voy a enseñar el que acabo\n"
    .string "de aprender, claro!$"

Text_CounterDeclined::
    .string "¿No estás interesad{OA}? ven a verme\n"
    .string "si cambias de opinión.$"

Text_CounterWhichMon::
    .string "¿Qué POKéMON quiere aprender\n"
    .string "CONTRAATAQUE?$"

Text_CounterTaught::
    .string "¿Estás usando ese CONTRAATAQUE\n"
    .string "que le enseñé a tu POKéMON?$"
