Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30::
    .string "¡Hola! ¿me recuerdas?\n"
    .string "Soy uno de los AYUDANTES del\l"
    .string "PROF. OAK.\p"
    .string "Si tu POKéDEX tiene datos completos\n"
    .string "de {STR_VAR_1} especies, se supone que\l"
    .string "debería darte una recompensa.\p"
    .string "El PROF. OAK me encargo un\n"
    .string "{STR_VAR_2} para ti.\p"
    .string "Entonces, {PLAYER}, dime algo.\p"
    .string "¿Ya recolectaste datos de al menos\n"
    .string "{STR_VAR_1} tipos de POKéMON?$"

Route11_EastEntrance_2F_Text_GreatHereYouGo::
    .string "¡Bien! ¡atrapaste u obtuviste\n"
    .string "{STR_VAR_3} tipos de POKéMON!\p"
    .string "¡Felicidades!\n"
    .string "¡Aquí tienes!$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide::
    .string "{PLAYER} recibió {STR_VAR_2}\n"
    .string "del AYUDANTE.$"

Route11_EastEntrance_2F_Text_ExplainItemfinder::
    .string "Hay objetos en el suelo que pueden\n"
    .string "estar ocultos a la vista.\p"
    .string "Usa el BUSCA OBJETOS para detectar\n"
    .string "objetos ocultos cerca de ti.\p"
    .string "Pero es un poco limitado.\n"
    .string "No puede localizar objetos con\l"
    .string "exactitud.\p"
    .string "Lo que hace es mostrar en que\n"
    .string "dirección está el objeto.\p"
    .string "Usalo para orientarte, luego\n"
    .string "revisa el área a mano.$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
    .string "Veamos lo que estos binoculares\n"
    .string "tienen para mostrar…\p"
    .string "¡Un gran POKéMON está dormido en\n"
    .string "un camino!$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView::
    .string "Veamos lo que estos binoculares\n"
    .string "tienen para mostrar…\p"
    .string "¡Qué vista tan impresionante!$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
    .string "Veamos lo que estos binoculares\n"
    .string "tienen para mostrar…\p"
    .string "Para llegar a PUEBLO LAVANDA desde\n"
    .string "CIUDAD CELESTE…\p"
    .string "parece que ir por el TÚNEL ROCA\n"
    .string "sería una buena ruta.$"

