PewterCity_House1_Text_Nidoran:: @ 81915BB
    .string "NIDORAN♂: ¡Bowbow!$"

PewterCity_House1_Text_NidoranSit:: @ 81915CD
    .string "¡NIDORAN, sentado!$"

PewterCity_House1_Text_TradeMonsAreFinicky:: @ 81915DB
    .string "Nuestro POKéMON es un forastero,\n"
    .string "así que es dificíl de manejar.\p"
    .string "Un forastero es un POKéMON que\n"
    .string "obtienes en un intercambio.\p"
    .string "Crece rapido, pero a veces ignora\n"
    .string "a los ENTRENADORES novatos\l"
    .string "en batalla.\p"
    .string "Ojalá tuvieramos algunas MEDALLAS…$"
