Route13_Text_SebastianIntro::
    .string "¡Mis POKéMON pájaros quieren\n"
    .string "luchar contigo!$"

Route13_Text_SebastianDefeat::
    .string "¿Mi combinación de PIDGEY y\n"
    .string "PIDGEOTTO perdió?$"

Route13_Text_SebastianPostBattle::
    .string "Mis POKéMON se ven felices aunque\n"
    .string "hayan perdido.$"

Route13_Text_SusieIntro::
    .string "Me dicen que soy buena para\n"
    .string "mi edad.$"

Route13_Text_SusieDefeat::
    .string "¡Ohh!\n"
    .string "¡Perdí!$"

Route13_Text_SusiePostBattle::
    .string "Quiero ser una buena ENTRENADORA.\n"
    .string "Entrenaré mucho, ya verás.$"

Route13_Text_ValerieIntro::
    .string "¡Guau!\n"
    .string "¡Tus MEDALLAS son geniales!$"

Route13_Text_ValerieDefeat::
    .string "¡No fue suficiente!$"

Route13_Text_ValeriePostBattle::
    .string "Conseguiste esas MEDALLAS de los\n"
    .string "LÍDERES de GIMNASIO. ¡Lo sé!$"

Route13_Text_GwenIntro::
    .string "Mis lindos POKéMON quieren\n"
    .string "conocerte.$"

Route13_Text_GwenDefeat::
    .string "¡Bien hecho!\n"
    .string "¡Fue una victoria total!$"

Route13_Text_GwenPostBattle::
    .string "Tienes que hacer que tus POKéMON\n"
    .string "luchen para fortalecerlos.$"

Route13_Text_AlmaIntro::
    .string "Una vez encontré CARBURANTE en\n"
    .string "una cueva mientras exploraba.$"

Route13_Text_AlmaDefeat::
    .string "¡Oh, qué mal!\n"
    .string "¡Lo arruiné!$"

Route13_Text_AlmaPostBattle::
    .string "CARBURANTE aumentó la VELOCIDAD\n"
    .string "de mis POKéMON.$"

Route13_Text_PerryIntro::
    .string "No voy a perder.\n"
    .string "¡No si el viento está a mi favor!$"

Route13_Text_PerryDefeat::
    .string "¡El viento cambió de dirección!$"

Route13_Text_PerryPostBattle::
    .string "Perdí.\n"
    .string "Creo que me iré a casa con VUELO.$"

Route13_Text_LolaIntro::
    .string "Claro, jugaré contigo, cielo.$"

Route13_Text_LolaDefeat::
    .string "¡Oh!\n"
    .string "¡Eres una pequeña bestia!$"

Route13_Text_LolaPostBattle::
    .string "Me pregunto cuál es más fuerte…\n"
    .string "¿Un POKéMON macho, o una hembra?$"

Route13_Text_SheilaIntro::
    .string "¿Quieres que luchemos con POKéMON?$"

Route13_Text_SheilaDefeat::
    .string "¿Ya se acabó?$"

Route13_Text_SheilaPostBattle::
    .string "En realidad no sé nada sobre\n"
    .string "POKéMON.\p"
    .string "Los que uso… ¡los escogí por\n"
    .string "su apariencia!$"

Route13_Text_JaredIntro::
    .string "¿Y tú qué miras?$"

Route13_Text_JaredDefeat::
    .string "¡Rayos!\n"
    .string "¡Qué humillación!$"

Route13_Text_JaredPostBattle::
    .string "¡Piérdete!$"

Route13_Text_RobertIntro::
    .string "Siempre uso POKéMON pájaros.\n"
    .string "He dedicado mi vida a ellos.$"

Route13_Text_RobertDefeat::
    .string "¡Me quedé sin energía!$"

Route13_Text_RobertPostBattle::
    .string "Ojalá pudiera volar como PIDGEY\n"
    .string "y PIDGEOTTO…$"

Route13_Text_LookToLeftOfThatPost::
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "¡Mira, mira!\n"
    .string "¡Mira a la izquierda de ese poste!$"

Route13_Text_SelectToSwitchItems::
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "Usa SELECT para cambiar objetos en\n"
    .string "la ventana de OBJETOS.$"

Route13_Text_RouteSign::
    .string "RUTA 13\n"
    .string "PUENTE SILENCIO, al norte$"

