VermilionCity_PokemonCenter_1F_Text_TrainerMonsStrongerThanWild:: @ 81940AF
    .string "Aún si son del mismo nivel, los\n"
    .string "POKéMON pueden tener habilidades\l"
    .string "y estadísticas muy distintas.\p"
    .string "POKéMON críados por un ENTRENADOR\n"
    .string "son más fuertes que uno salvaje.$"

VermilionCity_PokemonCenter_1F_Text_PoisonedMonFaintedWhileWalking:: @ 8194145
    .string "¡Mi POKéMON fue envenenado!\n"
    .string "¡Se debilitó mientras caminábamos!$"

VermilionCity_PokemonCenter_1F_Text_AllMonWeakToSpecificTypes:: @ 8194180
    .string "Es cierto que un POKéMON de mayor\n"
    .string "nivel será más poderoso…\p"
    .string "Pero, todo POKéMON tiene puntos\n"
    .string "débiles contra tipos específicos.\p"
    .string "Así que, no parece que exista un\n"
    .string "POKéMON universalmente fuerte.$"

VermilionCity_PokemonCenter_1F_Text_UrgeToBattleSomeoneAgain:: @ 8194234
    .string "El impulso de luchar con alguien\n"
    .string "con el que te has enfrentado antes…\p"
    .string "¿Alguna vez tuviste ese impulso?\n"
    .string "Estoy segura de que sí.\p"
    .string "También he querido luchar contra\n"
    .string "ciertas personas, una y otra vez.\p"
    .string "Por eso, regalé varios de estos.\n"
    .string "Por favor, ¡toma uno!$"

VermilionCity_PokemonCenter_1F_Text_UseDeviceForRematches:: @ 819430F
    .string "Usa este dispositivo y encontrarás\n"
    .string "ENTRENADORES buscando revancha.\p"
    .string "Aunque, tienes que cargar su\n"
    .string "batería para usarlo.$"

VermilionCity_PokemonCenter_1F_Text_ExplainVSSeeker:: @ 8194381
    .string "¿Cómo se usa el BUSCA PELEAS?\n"
    .string "Realmente es muy simple.\p"
    .string "Deja que haga bip-bip-bip, y los\n"
    .string "ENTRENADORES cerca lo notarán.\p"
    .string "Si alguien quiere una revancha,\n"
    .string "te lo hará saber de inmediato.\p"
    .string "Carga su batería y úsala mientras\n"
    .string "estas en el camino.$"
