ViridianCity_Text_CanCarryMonsAnywhere:: @ 817DABB
    .string "¡Esas POKéBOLAS en tu cintura!\n"
    .string "¿Tienes POKéMON, cierto?\p"
    .string "Es genial poder llevar y usar los\n"         
    .string "POKéMON en cualquier momento\l"
    .string "y lugar.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs:: @ 817DB39
    .string "Este GIMNASIO POKéMON siempre\n"
    .string "está cerrado.\p"
    .string "¿Quién será su LÍDER?$"

ViridianCity_Text_ViridiansGymLeaderReturned:: @ 817DB78
    .string "¡El LÍDER de GIMNASIO de VERDE\n"
    .string "regresó!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons:: @ 817DB98
    .string "¿Quieres saber algo sobre los dos\n"
    .string "tipos de orugas POKéMON?$"

ViridianCity_Text_OhOkayThen:: @ 817DBD5
    .string "Oh, ¡de acuerdo!$"

ViridianCity_Text_ExplainCaterpieWeedle:: @ 817DBE4
    .string "CATERPIE no tiene veneno,\n"
    .string "pero WEEDLE sí.\p"
    .string "Ten cuidado, puede que tus POKéMON\n"
    .string "reciban el PIQUETE VENENOSO\l"
    .string "de WEEDLE.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet:: @ 817DC4E
    .string "¡Oh, Abuelo!\n"
    .string "¡Durmiendo aquí, de todos los\l"
    .string "lugares!\p"
    .string "No podemos hacer nada…\n"
    .string "Tendremos que esperar a\l"
    .string "que deje de estar ebrio…$"

ViridianCity_Text_GoShoppingInPewterOccasionally:: @ 817DC99
    .string "De vez en cuando voy de compras\n"
    .string "a CIUDAD PLATEADA.\p"
    .string "Cuando voy, tengo que tomar el\n"
    .string "sinuoso camino del BOSQUE VERDE.$"

ViridianCity_Text_ThisIsPrivateProperty:: @ 817DD03
    .string "¡Aagh…! Hip… ¡Quedate justo ahí!\n"
    .string "¡Escucha lo que tengo que decir!\p"
    .string "…¡Oye!\n"
    .string "¡Dije que no te vayas!$"

ViridianCity_Text_ShowYouHowToCatchMons:: @ 817DD4E
    .string "Mmm…\n"
    .string "¡Parece que estaba bastante\l"
    .string "borracho!\p"
    .string "¿Oh?\n"
    .string "¿Qué es esa caja roja?\p"
    .string "Ah, así que estás trabajando\n"
    .string "en tu POKéDEX.\p"
    .string "Entonces, dejame darte algo de\n"
    .string "información.\p"
    .string "Cuando atrapes un POKéMON,\n"
    .string "la POKéDEX actualizará sus datos\l"
    .string "automáticamente.\p"
    .string "…¿No sabes atrapar POKéMON?\p"
    .string "¡En ese caso, supongo que tendre\n"
    .string "que mostrarte como!$"

ViridianCity_Text_ThatWasEducationalTakeThis:: @ 817DE9B
    .string "¡Listo! no me diras que no\n"
    .string "ha sido educativo, ¿eh?\p"
    .string "Vamos, toma esto.$"

ViridianCity_Text_WatchThatToLearnBasics:: @ 817DEEB
    .string "Úsala si es que hay algo que\n"
    .string "no entiendas.\p"
    .string "Te enseñara lo básico de ser un{A}\n"
    .string "ENTRENADOR{AM} POKéMON.$"

ViridianCity_Text_WeakenMonsFirstToCatch:: @ 817DF61
    .string "¡Parece que estaba bastante\n"
    .string "borracho!\p"
    .string "Me duele la cabeza…\p"
    .string "Por cierto, ¿estás llenando tu\n"
    .string "POKéDEX?\p"
    .string "Primero, concentrate en debilitar\n"
    .string "al POKéMON antes de intentar\l"
    .string "atraparlo.$"

ViridianCity_Text_HowsTeachyTVHelping:: @ 817E046
    .string "¡Parece que estaba bastante\n"
    .string "borracho!\p"
    .string "Me duele la cabeza…\p"
    .string "Por cierto, ¿te esta ayudando\n"
    .string "mi vieja ENSEÑAME TV?$"

ViridianCity_Text_MyGrandsonOnTheShow:: @ 817E0EA
    .string "¡Wajaja!\n"
    .string "¡Mi nieto esta en el programa!\p"
    .string "Como él es quien enseña, es\n"
    .string "muy probable que aprendas.$"

ViridianCity_Text_TooBusyForTeachyTV:: @ 817E14E
    .string "Hm… Estás muy ocupad{OA}, incluso\n"
    .string "para usar la ENSEÑAME TV…\p"
    .string "El tiempo es dinero, y ninguno de\n"
    .string "los dos debería ser malgastado…$"

ViridianCity_Text_CitySign:: @ 817E1BB
    .string "CIUDAD VERDE \n"
    .string "El paraíso del eterno verdor.$"

ViridianCity_Text_CatchMonsForEasierBattles:: @ 817E1E7
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "Atrapa POKéMON y amplía tu\n"
    .string "colección.\p"
    .string "Cuantos más tengas, las batallas\n"
    .string "serán más fáciles.$"

ViridianCity_Text_MovesLimitedByPP:: @ 817E24D
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "Los ataques de los POKéMON están\n"
    .string "limitados por sus PUNTOS de PODER,\l"
    .string "o PP.\p"
    .string "Para rellenar PP, deja que tus\n"
    .string "POKéMON cansados descansen en\l"
    .string "un CENTRO POKéMON.$"

ViridianCity_Text_GymSign:: @ 817E2DB
    .string "GIMNASIO POKéMON DE CIUDAD VERDE$"

ViridianCity_Text_GymDoorsAreLocked:: @ 817E2F5
    .string "Las puertas del GIMNASIO están\n"
    .string "cerradas…$"
