CeruleanCity_House4_Text_NothingEntertaining::
    .string "Suspiro…\n"
    .string "Mucho tiempo, muy poco por hacer…\p"
    .string "¿No esta pasando nada interesante\n"
    .string "en algún lado?$"

CeruleanCity_House4_Text_NewNewsInformativeHaveThis::
    .string "¡Ah!\n"
    .string "¡Un nuevo reportaje de noticias!\p"
    .string "Hmm…\p"
    .string "¡Ya veo!\n"
    .string "¡Eso fue bastante informativo!\p"
    .string "Aplaudo tu interés por las\n"
    .string "noticias a tan temprana edad.\p"
    .string "Cómo gracias por compartirme las\n" 
    .string "noticias, quiero que tengas esto.$"

CeruleanCity_House4_Text_IncredibleNewsHaveBerries::
    .string "¡Oh, oh!\n"
    .string "¡Eh-este reportaje de noticias!\p"
    .string "Hmm…\p"
    .string "¡Maravilloso!\n"
    .string "¡Qué increíble pieza de noticias!\p"
    .string "¡No había visto una historia tan\n"
    .string "increíble en un largo tiempo!\p"
    .string "Gracias por compartir noticias\n"
    .string "fantásticas. ¡Ten estas BAYAS!$"

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers::
    .string "Parece una pena el no compartir\n"
    .string "estas noticias con otra gente…\p"
    .string "Ojalá pudiera contarle a alguien…\n"
    .string "Cuéntale las noticias a otros…$"

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis::
    .string "Ah, ¿esparciste la noticia por mí?\p"
    .string "Las buenas noticias valen la pena\n"
    .string "cuando mucha gente las comparte.\p"
    .string "¡Cómo agradecimiento por esparcir\n"
    .string "las noticias, toma esto!$"

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries::
    .string "¿Esparciste más esas noticias?\n"
    .string "¡Magnífico!\p"
    .string "Esas noticias deben estar\n"
    .string "encantadas de ser compartidas.\p"
    .string "¡Si, así es!\p"
    .string "Considera esto una muestra de\n"
    .string "apreciación de mi y las noticias.\p"
    .string "Te daré más BAYAS que lo usual.$"

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews::
    .string "Estoy disfrutando bastante todas\n"
    .string "estas noticias.\p"
    .string "¡Sí, estoy satisfecho!\n"
    .string "No estaré aburrido por un tiempo.$"

CeruleanCity_House4_Text_YourBerryPouchIsFull::
    .string "¿Hm? Tu SACO DE BAYAS esta lleno.\n"
    .string "Mi regalo se queda aquí, entonces.$"

