PokemonLeague_AgathasRoom_Text_Intro::
    .string " Soy AGATHA, del ALTO MANDO.\p"
    .string "Se dice que OAK tiene mucho\n"
    .string "interés en ti, niñ{OA}.\p"
    .string "Ese viejo fue fuerte y apuesto\n"
    .string "alguna vez.\p"
    .string "Pero eso fue hace décadas.\n"
    .string "Es una sombra de lo que fue.\p"
    .string "Ahora solo quiere jugar con\n"
    .string "su POKéDEX.\p"
    .string "Él se equivoca.\n"
    .string "¡Los POKéMON son para luchar!\p"
    .string "¡{PLAYER}! ¡Te mostraré cómo lucha\n"
    .string "una ENTRENADORA de verdad!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_RematchIntro::
    .string "Soy AGATHA, del ALTO MANDO.\p"
    .string "¿Eres es{EA} niñ{OA} que OAK tomó\n"
    .string "como su protegid{OA}, cierto?\p"
    .string "Ese viejo fue fuerte y apuesto\n"
    .string "alguna vez.\p"
    .string "Pero eso fue hace décadas.\n"
    .string "Es una sombra de lo que fue.\p"
    .string "Ahora solo quiere jugar con\n"
    .string "su POKéDEX.\p"
    .string "Él se equivoca.\n"
    .string "¡Los POKéMON son para luchar!\p"
    .string "¡{PLAYER}! ¡Te mostraré cómo lucha\n"
    .string "una ENTRENADORA de verdad!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_Defeat::
    .string "¡Oh, oh!\n"
    .string "¡Eres alguien especial, niñ{OA}!$"

PokemonLeague_AgathasRoom_Text_PostBattle::
    .string "¡Tú ganas!\p"
    .string "Ahora veo lo que ese viejo vió\n"
    .string "en tí.\p"
    .string "No tengo nada más que decir.\n"
    .string "¡Ahora corre, niñ{OA}!$"

