VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon:: @ 81949CB
	.string "¡Hola!\n"
	.string "¿Tienes a un {STR_VAR_1}?\p"
	.string "¿Quieres intercambiarlo por mi\n"
	.string "{STR_VAR_2}?$"

VermilionCity_House2_Text_ThatsTooBad:: @ 81949FD
	.string "Qué mal.$"

VermilionCity_House2_Text_ThisIsNoMon:: @ 8194A0D
	.string "…Este no es un {STR_VAR_1}.\p"
	.string "¡Si consigues uno, por favor\n"
	.string "cámbialo conmigo!$"

VermilionCity_House2_Text_ThankYou:: @ 8194A44
	.string "¡Gracias!$"

VermilionCity_House2_Text_HowIsMyOldMon:: @ 8194A4F
	.string "¿Cómo está mi viejo {STR_VAR_2}?\n"
	.string "¡A mi {STR_VAR_1} le va genial!$"
