VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon::
	.string "¡Hola!\n"
	.string "¿Tienes a un {STR_VAR_1}?\p"
	.string "¿Quieres intercambiarlo por mi\n"
	.string "{STR_VAR_2}?$"

VermilionCity_House2_Text_ThatsTooBad::
	.string "Qué mal.$"

VermilionCity_House2_Text_ThisIsNoMon::
	.string "…Este no es un {STR_VAR_1}.\p"
	.string "¡Si consigues uno, por favor\n"
	.string "cámbialo conmigo!$"

VermilionCity_House2_Text_ThankYou::
	.string "¡Gracias!$"

VermilionCity_House2_Text_HowIsMyOldMon::
	.string "¿Cómo está mi viejo {STR_VAR_2}?\n"
	.string "¡A mi {STR_VAR_1} le va genial!$"
