CeladonCity_Text_GotMyKoffingInCinnabar::
    .string "Conseguí a mi KOFFING en CANELA.\p"
    .string "Suele portarse bien, pero expulsa\n"
    .string "veneno cuando se enoja.$"

CeladonCity_Text_GymIsGreatFullOfWomen::
    .string "¡Jeje! ¡Este GIMNASIO es genial!\n"
    .string "¡Está lleno de mujeres!$"

CeladonCity_Text_GameCornerIsBadForCitysImage::
    .string "PRISMA presume sus esfuerzos para\n"
    .string "mantener a la ciudad hermosa.\p"
    .string "Por eso la nueva SALA DE JUEGOS es\n"
    .string "mala para la imagen de la cuidad.$"

CeladonCity_Text_BlewItAllAtSlots::
    .string "Ay…\n"
    .string "¡Lo perdí todo en la tragamonedas!\p"
    .string "¡Sabía que debí haber cambiado mis\n"
    .string "MONEDAS por premios!$"

CeladonCity_Text_MyTrustedPalPoliwrath::
    .string "Éste es mi fiel amigo, POLIWRATH.\p"
    .string "Evolucionó de un POLIWHIRL cuándo\n"
    .string "usé una PIEDRA AGUA.$"

CeladonCity_Text_Poliwrath::
    .string "POLIWRATH: ¡Ribi ribit!$"

CeladonCity_Text_GetLostOrIllPunchYou::
    .string "¿Qué estás mirando?\n"
    .string "Piérdete, o te golpearé.$"

CeladonCity_Text_KeepOutOfTeamRocketsWay::
    .string "¡Sal del camino del EQUIPO ROCKET!$"

CeladonCity_Text_ExplainXAccuracyDireHit::
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "PRECISIÓN X aumenta la precisión\n"
    .string "de ataques.\p"
    .string "CRÍTICO X aumenta la probabilidad\n"
    .string "de ataques críticos.\p"
    .string "¡Consigue tus objetos en la TIENDA\n"
    .string "DEPARTAMENTAL PRISMA!$"

CeladonCity_Text_CitySign::
    .string "CIUDAD PRISMA\n"
    .string "La cuidad de sueños arcoíris.$"

CeladonCity_Text_GymSign::
    .string "LÍDER de GIMNASIO POKéMON de\n"
    .string "CIUDAD PRISMA: ERIKA\l"
    .string "¡Princesa amante de la naturaleza!$"

CeladonCity_Text_MansionSign::
    .string "MANSIÓN PRISMA$"

CeladonCity_Text_DeptStoreSign::
    .string "¡Encuentra lo que necesites en la\n"
    .string "TIENDA DEPARTAMENTAL PRISMA!$"

CeladonCity_Text_GuardSpecProtectsFromStatus::
    .string "CONSEJOS PARA ENTRENADORES\p"
    .string "GUARDIA X protege a POKéMON de la\n"
    .string "reducción de estadísticas durante\l"
    .string "la batalla.\p"
    .string "¡Consigue tus objetos en la TIENDA\n"
    .string "DEPARTAMENTAL PRISMA!$"

CeladonCity_Text_PrizeExchangeSign::
    .string "¡Se cambian MONEDAS por premios!\n"
    .string "CAMBIO DE PREMIOS$"

CeladonCity_Text_GameCornerSign::
    .string "SALA DE JUEGOS ROCKET\n"
    .string "¡El patio de juegos para adultos!$"

CeladonCity_Text_ScaldedTongueOnTea::
    .string "Aaaagh, ow…\n"
    .string "¡Me quemé la lengua!\p"
    .string "Esa ancianita agradable en la\n"
    .string "MANSIÓN me dió algo de TÉ.\p"
    .string "¡Pero estaba hirviendo!\n"
    .string "Tendré que enfriarlo para beberlo.$"

Text_SoftboiledTeach::
    .string "¡Hola!\p"
    .string "Te ví pasar, pero no había tenido\n"
    .string "la oportunidad de hablar contigo.\p"
    .string "Debe ser buena suerte que\n"
    .string "finalmente nos reunieramos.\p"
    .string "Quiero celebrar enseñándote\n"
    .string "el movimiento HUEVO COCIDO.$"

Text_SoftboiledDeclined::
    .string "Te estaré esperando siempre.\p"
    .string "Espero que podamos hablar\n"
    .string "otra vez.$"

Text_SoftboiledWhichMon::
    .string "¿Qué POKéMON tendrá la oportunidad\n"
    .string "de aprender HUEVO COCIDO?$"

Text_SoftboiledTaught::
    .string "¡Te deseo la mejor de las suertes!$"

CeladonCity_Text_SomeoneStoleSilphScope::
    .string "Oh, que voy a hacer…\p"
    .string "Alguien robó nuestro VISOR SILPH.\p"
    .string "El ladrón vino corriendo por aquí,\n"
    .string "estoy seguro.\p"
    .string "¡Pero lo perdí de vista!\n"
    .string "¿A dónde se fue?$"

