ViridianCity_Mart_Text_YouCameFromPallet::
    .string "¡Oye!\n"
    .string "¿Vienes de PUEBLO PALETA?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "¿Conoces al PROF. OAK, cierto?\p"
    .string "Llego una orden suya.\n"
    .string "¿Se la podrias llevar?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} recibio el PAQUETE DE OAK\n"
    .string "del empleado de la TIENDA POKéMON.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "¡Bueno, gracias! Por favor saluda\n"
    .string "al PROF. OAK de mi parte.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "Escuche que en esta tienda se\n"
    .string "venden muchos ANTÍDOTOS.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "Tengo que comprar algunas\n"
    .string "POCIONES.\p"
    .string "Nunca sabes cuándo tus POKéMON\n"
    .string "necesitarán curarse rapido.$"
