VermilionCity_Gym_Text_LtSurgeIntro:: @ 8194BA4
    .string "¡Ey, niñ{OA}! ¿Qué crees que estas\n"
    .string "haciendo aquí?\p"
    .string "¡No resistirás mucho en combate!\n"
    .string "¡No con tu poder diminuto!\p"
    .string "¡Los POKéMON eléctricos me\n"
    .string "salvaron durante la guerra!\p"
    .string "¡Electrocutaron a mis enemigos y\n"
    .string "con eso los paralizaron!\p"
    .string "¡Y te haré lo mismo a tí!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

VermilionCity_Gym_Text_LtSurgePostBattle:: @ 8194C8E
    .string "¡Un pequeño consejo, niñ{OA}!\p"
    .string "¡La electricidad es muy poderosa!\p"
    .string "Pero, ¡es inútil contra POKéMON\n"
    .string "de tipo TIERRA!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis:: @ 8194CFA
    .string "¡La MEDALLA TRUENO mejora la\n"
    .string "VELOCIDAD de tus POKéMON!\p"
    .string "¡Y deja a tus POKéMON volar cómo\n"
    .string "el rayo cuando quieras, niñ{OA}!\p"
    .string "¡Eres especial, niñ{OA}!\n"
    .string "¡Toma esto!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge:: @ 8194D87
    .string "{PLAYER} recibió MT34\n"
    .string "del TENIENTE SURGE.$"

VermilionCity_Gym_Text_ExplainTM34:: @ 8194DA8
    .string "¡MT34 contiene ONDA CHOQUE!\p"
    .string "¡Úsala en un POKéMON ELÉCTRICO!$"

VermilionCity_Gym_Text_MakeRoomInYourBag:: @ 8194DE3
    .string "¡Niñ{OA}, haz espacio en tu MOCHILA!$"

VermilionCity_Gym_Text_LtSurgeDefeat:: @ 8194E03
    .string "¡Esto sí que es una sorpresa!\p"
    .string "¡Sí que eres fuerte, niñ{OA}!\p"
    .string "¡Entonces, toma la MEDALLA TRUENO!$"

VermilionCity_Gym_Text_TuckerIntro:: @ 8194E57
    .string "Cuando estaba en el ejército, el\n"
    .string "TENIENTE SURGE era mi jefe.\p"
    .string "Era un jefe duro.$"

VermilionCity_Gym_Text_TuckerDefeat:: @ 8194EA5
    .string "¡Basta!\n"
    .string "¡Eres muy buen{OA}!$"

VermilionCity_Gym_Text_TuckerPostBattle:: @ 8194EBD
    .string "Abrir esa puerta no es tan fácil.\p"
    .string "El TENIENTE SURGE fue famoso por su\n"
    .string "naturaleza cautelosa en combate.$"

VermilionCity_Gym_Text_BailyIntro:: @ 8194F1F
    .string "No soy muy fuerte, ¡pero soy bueno\n"
    .string "con la electricidad!\p"
    .string "Por eso me uní a este GIMNASIO.$"

VermilionCity_Gym_Text_BailyDefeat:: @ 8194F6F
    .string "¡Estoy frito!$"

VermilionCity_Gym_Text_BailyPostBattle:: @ 8194F76
    .string "¡De acuerdo, hablaré!\p"
    .string "El TENIENTE SURGE dijo que ocultó\n"
    .string "los interruptores dentro de algo.$"

VermilionCity_Gym_Text_DwayneIntro:: @ 8194FBD
    .string "¡Este lugar no es para niños!\n"
    .string "¡No importa si eres buen{OA}!$"

VermilionCity_Gym_Text_DwayneDefeat:: @ 8194FF1
    .string "¡Wow!\n"
    .string "¡Me sorprendiste!$"

VermilionCity_Gym_Text_DwaynePostBattle:: @ 8195004
    .string "El TENIENTE SURGE puso las trampas\n"
    .string "en el GIMNASIO por su cuenta.\p"
    .string "Instaló cerraduras dobles por\n"
    .string "todos lados.\l"
    .string "Déjame darte una pista.\p"
    .string "Cuando abras la primer cerradura,\n"
    .string "la segunda esta justo a un lado.$"

VermilionCity_Gym_Text_GymGuyAdvice:: @ 81950B4
    .string "¡Yo!\n"
    .string "¡Futur{OA} campe{ONONA}!\p"
    .string "El TENIENTE SURGE tiene un apodo.\p"
    .string "¡La gente se refiere a él cómo el\n"
    .string "Rayo americano!\p"
    .string "Es un experto con los POKéMON\n"
    .string "eléctricos.\p"
    .string "Los POKéMON de tipo VOLADOR/AGUA\n"
    .string "sufren contra el tipo ELÉCTRICO.\p"
    .string "Además, cuídate de la parálisis.\p"
    .string "El TENIENTE SURGE es cauteloso.\p"
    .string "Se encerró a si mismo, para que\n"
    .string "llegar a él no sea fácil.$"

VermilionCity_Gym_Text_GymGuyPostVictory:: @ 81951EC
    .string "¡Fiu!\n"
    .string "¡Esa batalla fue electrizante!$"

VermilionCity_Gym_Text_GymStatue:: @ 819520B
    .string "GIMNASIO POKéMON DE CARMÍN\n"
    .string "LÍDER: TENIENTE SURGE\p"
    .string "ENTRENADORES VICTORIOSOS:\n"
    .string "{RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon:: @ 8195248
    .string "GIMNASIO POKéMON DE CARMÍN\n"
    .string "LÍDER: TENIENTE SURGE\p"
    .string "ENTRENADORES VICTORIOSOS:\n"
    .string "{RIVAL}, {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere:: @ 8195289
    .string "¡Nop!\n"
    .string "Solo hay basura aquí.$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened:: @ 81952A8
    .string "¡Ey! ¡hay un interruptor bajo la\n"
    .string "basura! ¡enciéndelo!\p"
    .string "¡La primer cerradura se abrío!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash:: @ 81952FB
    .string "ガサゴソ‥！\n"
    .string "おっと！　ゴミばこの　そこに\l"
    .string "また　スイッチが　あった！\l"
    .string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened:: @ 8195330
    .string "¡La segunda cerradura se abrío!\n"
    .string "¡La puerta motorizada se abre!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset:: @ 819536C
    .string "¡Nop!\n"
    .string "Solo hay basura aquí.\p"
    .string "¡Ey!\n"
    .string "¡Las cerraduras se reiniciaron!$"

