FuchsiaCity_SafariZone_Entrance_Text_WelcomeToSafariZone::
    .string "¡Bienvenid{OA} a la ZONA SAFARI!$"

FuchsiaCity_SafariZone_Entrance_Text_PlaySafariGameFor500::
    .string "Por solo ¥500, puedes jugar el\n"
    .string "JUEGO SAFARI.\p"
    .string "Puedes explorar el gran safari\n"
    .string "y atrapar lo que quieras.\p"
    .string "¿Quieres jugar?$"

FuchsiaCity_SafariZone_Entrance_Text_ThatllBe500WeOnlyUseSpecialBalls::
    .string "¡Serán ¥500, por favor!\p"
    .string "Solo usamos un tipo especial de\n"
    .string "POKéBOLAS aquí.$"

FuchsiaCity_SafariZone_Entrance_Text_PlayerReceived30SafariBalls::
    .string "{PLAYER} recibió 30 BOLAS SAFARI\n"
    .string "del recepcionista.$"

FuchsiaCity_SafariZone_Entrance_Text_CallYouOnPAWhenYouRunOut::
    .string "Te avisaremos cuando te quedes\n"
    .string "sin tiempo o sin BOLAS SAFARI.\p"
    .string "¡Bueno, te deseo la mejor de las\n"
    .string "suertes!$"

FuchsiaCity_SafariZone_Entrance_Text_OkayPleaseComeAgain::
    .string "De acuerdo.\n"
    .string "¡Regresa cuando quieras!$"

FuchsiaCity_SafariZone_Entrance_Text_OopsNotEnoughMoney::
    .string "¡Ups!\n"
    .string "¡Te falta dinero!$"

FuchsiaCity_SafariZone_Entrance_Text_GoingToLeaveSafariZoneEarly::
    .string "¿Vas a salir de la ZONA SAFARI\n"
    .string "antes de tiempo?$"

FuchsiaCity_SafariZone_Entrance_Text_PleaseReturnSafariBalls::
    .string "Por favor regresa cualquier\n"
    .string "BOLA SAFARI sobrante.$"

FuchsiaCity_SafariZone_Entrance_Text_GoodLuck::
    .string "¡Buena suerte!$"

FuchsiaCity_SafariZone_Entrance_Text_CatchFairShareComeAgain::
    .string "¿Atrapaste bastantes?\n"
    .string "¡Vuelve de nuevo!$"

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone::
    .string "¡Hola! ¿es tu primera vez\n"
    .string "en la ZONA SAFARI?$"

FuchsiaCity_SafariZone_Entrance_Text_ExplainSafariZone::
    .string "La ZONA SAFARI realmente consiste\n"
    .string "de cuatro zonas.\p"
    .string "Cada zona tiene tipos de POKéMON\n"
    .string "diferentes, incluso algunos raros.\p"
    .string "Usa las BOLAS SAFARI para\n"
    .string "atraparlos.\p"
    .string "También puedes lanzar CEBO o\n"
    .string "ROCAS, aparte de las BOLAS SAFARI.\p"
    .string "Si lanzas CEBO, es menos probable\n"
    .string "que el POKéMON escape, pero será\l"
    .string "más difícil de atrapar.\p"
    .string "Si lanzas ROCAS, es más probable\n"
    .string "que el POKéMON escape, pero será\l"
    .string "más fácil de atrapar.\p"
    .string "¡Cuando ya no tengas tiempo o\n"
    .string "BOLAS SAFARI, el juego termina!$"

FuchsiaCity_SafariZone_Entrance_Text_SorryYoureARegularHere::
    .string "¡Lo siento, eres alguien habitual!$"

