Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze:: @ 819D52C
    .string "¿Vas a ir al BOSQUE VERDE?\n"
    .string "Ese lugar es un laberinto natural.\l"
    .string "Ten cuidado de no perderte.$"

Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite:: @ 819D58B
    .string "Puede que RATTATA sea pequeño,\n"
    .string "pero no subestimes su mordida.\p"
    .string "¿Ya has atrapado alguno?$"
