SaffronCity_PokemonTrainerFanClub_Text_HuhYou::
    .string "¿Uh?\n"
    .string "Tú…$"

SaffronCity_PokemonTrainerFanClub_Text_YourePlayerWereYourFansNow::
    .string "Tal vez seas…\n"
    .string "… …\p"
    .string "¡Eres tú!\n"
    .string "¡Eres {PLAYER}!\p"
    .string "¡Estábamos hablando sobre tí!\p"
    .string "Hablabamos sobre como apareció un{A}\n"
    .string "ENTRENADOR{AM} increíblemente buen{OA}.\p"
    .string "¡Y es{EA} eres tú!\n"
    .string "¡Eres tan genial!\p"
    .string "Entonces, decidimos que nos\n"
    .string "convertiremos en tu CLUB DE FANS!\p"
    .string "Esperamos que sigas luchando y nos\n"
    .string "muestres lo genial que eres.\p"
    .string "De esa forma, tal vez más personas\n"
    .string "se vuelvan fans como yo.$"

SaffronCity_PokemonTrainerFanClub_Text_AlwaysCheerForYou::
    .string "¡Siempre te daré ánimos!\p"
    .string "¡Vamos, {PLAYER}, vamos!$"

SaffronCity_PokemonTrainerFanClub_Text_IllAlwaysBelieveInYou::
    .string "Voy a creer en tí siempre,\n"
    .string "{PLAYER}.\p"
    .string "Por favor, muéstrale a los demás\n"
    .string "como eres cuando luchas en serio.$"

SaffronCity_PokemonTrainerFanClub_Text_WasYourFanNotAnymore::
    .string "Lo siento.\n"
    .string "Era tu fan antes.\p"
    .string "Pero ahora, parece que has perdido\n"
    .string "la motivación de antes.\p"
    .string "Creo que {STR_VAR_1} se ha vuelto\n"
    .string "mucho más genial últimamente.$"

SaffronCity_PokemonTrainerFanClub_Text_EveryonesYourFanButICantBe::
    .string "¡Oh!\n"
    .string "¡{PLAYER}!\p"
    .string "Recientemente, todos han estado\n"
    .string "emocionados sobre tí.\p"
    .string "Entiendo el porqué.\n"
    .string "Sé que eres fuerte.\p"
    .string "Pero, ¿sabes qué?\p"
    .string "Ahora que soy fan de {STR_VAR_1},\n"
    .string "no puedo dejar de ser su fan.$"

SaffronCity_PokemonTrainerFanClub_Text_TrainersCoolWhenBattling::
    .string "Creo que los ENTRENADORES son\n"
    .string "geniales cuando luchan.\p"
    .string "¿No lo crees?$"

SaffronCity_PokemonTrainerFanClub_Text_CanYouAutographShorts::
    .string "¡Oh! ¡es {PLAYER}!\n"
    .string "¡Genial!\p"
    .string "¡Oh!\n"
    .string "¡Oh, sí!\p"
    .string "¿Puedes autografiar algo?\n"
    .string "¿Qué tal mis pantalones cortos?$"

SaffronCity_PokemonTrainerFanClub_Text_CountingOnYou::
    .string "Sin importar que tanto calor haga…\p"
    .string "o que tan frío este afuera……\p"
    .string "¡Siempre he creído en, y usado,\n"
    .string "pantalones cortos!\p"
    .string "¡Cuento contigo en que sigas\n"
    .string "ganando!\p"
    .string "¡Creo en tí tanto como creo en los\n"
    .string "pantalones cortos!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksMyHero::
    .string "¡BROCK es mi héroe!\n"
    .string "¡Es un hombre entre hombres!\p"
    .string "Jeje, hice que mi mamá hiciera\n"
    .string "algo por mí.\p"
    .string "¡Hice que bordara “BROCK” en mis\n"
    .string "pantalones!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksFanToBitterEnd::
    .string "…  …\p"
    .string "…  …\n"
    .string "¡Soy fan de BROCK!\p"
    .string "¡Incluso si fuera su único fan,\n"
    .string "juro por mi determinación de roca,\l"
    .string "y por mis pantalones!\p"
    .string "¡Qué seré su fan hasta el final!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksLastWordOnCool::
    .string "¡BROCK es el más genial que hay,\n"
    .string "y fin!\p"
    .string "¡Es el ejemplo de lo que quiero\n"
    .string "ser!$"

SaffronCity_PokemonTrainerFanClub_Text_HadPleasureOfWatchingYouBattle::
    .string "{PLAYER}, tuve el placer de\n"
    .string "verte luchar.\p"
    .string "Me trajo dulces recuerdos de\n"
    .string "mi ya lejana juventud.\p"
    .string "Sigue por el camino del éxito.\n"
    .string "¡Soy fan tuyo!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverSeenTrainerOfYourMagnificence::
    .string "He viajado largo y ancho por\n"
    .string "el mundo.\p"
    .string "Pero nunca había visto un{A}\n"
    .string "ENTRENADOR{AM} tan magnífic{OA} como tú.\p"
    .string "¡Confía en tus habilidades y sigue\n"
    .string "luchando!\p"
    .string "¡Prométeme que lo harás, mi joven\n"
    .string "ídolo!$"

SaffronCity_PokemonTrainerFanClub_Text_HmmAndYouAre::
    .string "Hmm…\n"
    .string "¿Y tú eres?\p"
    .string "¿Esperabas obtener una membresía\n"
    .string "en nuestro CLUB DE FANS?$"

SaffronCity_PokemonTrainerFanClub_Text_YouveStillAWaysToGo::
    .string "Ah, así que eres es{EA} {PLAYER}\n"
    .string "que tanto mencionan.\p"
    .string "Ciertamente tienes el aspecto de\n"
    .string "un{A} ganador{A}.\p"
    .string "Pero para aceptarte como alguien\n"
    .string "grandioso con los POKéMON…\p"
    .string "… …\p"
    .string "¡Aún te falta mucho camino!$"

SaffronCity_PokemonTrainerFanClub_Text_YoullBeTalkedAboutIfYouKeepWinning::
    .string "Todos los que estamos aquí somos\n"
    .string "fans de los ENTRENADORES POKéMON.\p"
    .string "Como se ven en batalla…\n"
    .string "Son la imagen de la genialidad.\p"
    .string "Puede que también se hable de\n"
    .string "tí aquí, si sigues ganando.$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeYouOneDay::
    .string "¡Es {PLAYER}!\n"
    .string "¡Es {PLAYER}!\p"
    .string "¡Quiero llegar a ser como {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneButMeStoppedBeingYourFan::
    .string "Todos dejaron de ser fans de\n"
    .string "{PLAYER}…\p"
    .string "¡Pero eso signfica que tengo a\n"
    .string "{PLAYER} solo para mí!\p"
    .string "¡Hurra! ¡vamos!\n"
    .string "¡Mi inigualable  {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeSabrina::
    .string "¿Sabes qué?\n"
    .string "¡Quiero ser como SABRINA!\p"
    .string "¡Quiero ser una chica psíquica,\n"
    .string "justo como ella!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingSabrinasFan::
    .string "Incluso si soy la única, no dejaré\n"
    .string "de ser fan de SABRINA.\p"
    .string "Mi sueño es ser como SABRINA,\n"
    .string "linda, pero genial.\p"
    .string "¡Quiero ser una chica psíquica,\n"
    .string "justo como ella!$"

SaffronCity_PokemonTrainerFanClub_Text_CanIBecomeCoolTrainerOneDay::
    .string "Me pregunto si me puedo convertir\n"
    .string "en una gran ENTRENADORA algún día.$"

SaffronCity_PokemonTrainerFanClub_Text_TheWayYouBattleIsCool::
    .string "¡Oh, sí, oh, sí!\n"
    .string "¡Genial! ¡demasiado genial!\p"
    .string "…¿Uh?\n"
    .string "No, tú no.\p"
    .string "Solo la forma en la que peleas.\n"
    .string "Eso es genial.$"

SaffronCity_PokemonTrainerFanClub_Text_ImOnlyOneLeftOfYourFans::
    .string "¡Yo, {PLAYER}!\p"
    .string "Parece que soy el único que queda\n"
    .string "de tus fans.\p"
    .string "Pero, sabes, me gusta ser un fan\n"
    .string "único… es menos estresante.\p"
    .string "¡Sigue mejorando!$"

SaffronCity_PokemonTrainerFanClub_Text_LoveWayTrainerTalks::
    .string "¿{STR_VAR_1} es genial, huh?\n"
    .string "Amo la forma en la que habla.\p"
    .string "Realmente disfrutaría el poder\n"
    .string "conocerlo en persona una vez.$"

SaffronCity_PokemonTrainerFanClub_Text_ImLoneTrainerFan::
    .string "¿Uh, puedes creerlo?\n"
    .string "Ahora todos son fans tuyos.\p"
    .string "¿Así que después de todo, soy el\n"
    .string "único fan de {STR_VAR_1}?\p"
    .string "Eh, ser el único fan de {STR_VAR_1}\n"
    .string "es mi estilo, de todos modos.$"

SaffronCity_PokemonTrainerFanClub_Text_AdoreWayYouBattle::
    .string "¡Oh, cielos!\n"
    .string "¿De verdad eres tú, {PLAYER}?\p"
    .string "Tengo que decirte, que adoro la\n"
    .string "forma en la que luchas.\p"
    .string "Espero que sigas así.\n"
    .string "¡Seré tu fan número uno!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourNumberOneFan::
    .string "¡Oh, cielos!\n"
    .string "¡Si es {PLAYER}!\p"
    .string "Es tan decepcionante… ¡ahora soy\n"
    .string "tu fan número uno, y el único!\p"
    .string "¡Bueno, no se puede hacer nada!\n"
    .string "¡Al menos déjame animarte!\p"
    .string "¡Hurra, hurra, {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_TrainerHasBeenOnFire::
    .string "Recientemente, {STR_VAR_1} ha\n"
    .string "estado de maravilla.\p"
    .string "La forma en la que pelea…\n"
    .string "¡es justo como me gusta!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneTalksAboutYou::
    .string "¡Oh, hola!\n"
    .string "¡Si se trata de {PLAYER}!\p"
    .string "Últimamente, los demás solo hablan\n"
    .string "de tí.\p"
    .string "Me siento solo porque prefiero a\n"
    .string "{STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YouReallyAreAmazing::
    .string "¡Increíble!\n"
    .string "¡{PLAYER}, si que eres increíble!\p"
    .string "En vez de solo mirar, tal vez\n"
    .string "debería convertirme en ENTRENADOR.$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourOnlyFan::
    .string "Soy tu único fan…\n"
    .string "Ayy… esto es solitario…\p"
    .string "¿No podrías esforzarte más en que\n"
    .string "la gente te preste atención?$"

SaffronCity_PokemonTrainerFanClub_Text_WhyCantOthersSeeMastersDignity::
    .string "El Maestro {STR_VAR_1} es tan digno…\n"
    .string "Es totalmente de mi tipo.\p"
    .string "¿Por qué los demás no pueden ver\n"
    .string "la dignidad que desprende?$"

SaffronCity_PokemonTrainerFanClub_Text_BelieveInMasterWithAllMyHeart::
    .string "Yo creo en el Maestro {STR_VAR_1}\n"
    .string "con todo mi corazón.\p"
    .string "Incluso si soy la única que cree\n"
    .string "en él.\p"
    .string "Aunque nunca me sentiré sola.\p"
    .string "No si sigo pensando en el Maestro\n"
    .string "{STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YourBattleStyleIsEducational::
    .string "¡Hayiah!\p"
    .string "Tu estilo de pelea es bastante\n"
    .string "educativo.\p"
    .string "¡Espero que sigas alcanzando el\n"
    .string "éxito, hayiah!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingYourFan::
    .string "¡En vez de ver a otros luchar,\n"
    .string "lucha tú mism{OA}!\p"
    .string "…El DOJO de mi MAESTRO me hizo\n" 
    .string "así…\p"
    .string "¡Pero eso no evitará que sea\n"
    .string "tu fan!\p"
    .string "¡No puedo dejar de ser tu fan!$"

SaffronCity_PokemonTrainerFanClub_Text_OnlyMasterHasMyRespect::
    .string "¡Hayiah! solo hay un ENTRENADOR\n"
    .string "que tiene mi respeto.\p"
    .string "Y no es nadie más que mi\n"
    .string "MAESTRO del DOJO DE PELEA.\p"
    .string "¡Deberías convertirte en fan de mi\n"
    .string "MAESTRO, como yo! ¡hayiah!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverBeFanOfAnyoneButMaster::
    .string "¡Hayiah! Respeto a mi MAESTRO del\n"
    .string "DOJO DE PELEA.\p"
    .string "¡Nunca seré fan de alguien que\n"
    .string "no sea mi MAESTRO!\p"
    .string "Incluso me escabulliré del DOJO\n"
    .string "para informar de su grandeza.\p"
    .string "¡Hayiah!$"

