Route8_Text_AidanIntro::
    .string "Pareces buen{OA} con los POKéMON,\n"
    .string "pero… ¿Qué tal en química?$"

Route8_Text_AidanDefeat::
    .string "¡Ah!\n"
    .string "¡Fusión nuclear!$"

Route8_Text_AidanPostBattle::
    .string "¡Se me da mejor la escuela!$"

Route8_Text_StanIntro::
    .string "¡Muy bien!\n"
    .string "¡Vamos a jugar!$"

Route8_Text_StanDefeat::
    .string "¡Rayos!\n"
    .string "¡Me quedé corto!$"

Route8_Text_StanPostBattle::
    .string "Hoy no es mi día de suerte.$"

Route8_Text_GlennIntro::
    .string "Deberías saberlo.\n"
    .string "¡Necesitas estrategia para ganar!$"

Route8_Text_GlennDefeat::
    .string "¡Esto no es lógico!$"

Route8_Text_GlennPostBattle::
    .string "Usar a GRIMER primero…y…\n"
    .string "…y…entonces…$"

Route8_Text_PaigeIntro::
    .string "¡Me gustan los NIDORAN, así que\n"
    .string "los colecciono!$"

Route8_Text_PaigeDefeat::
    .string "¿Por qué?\n"
    .string "¿¿Por qué??$"

Route8_Text_PaigePostBattle::
    .string "¡Los POKéMON se vuelven feos al\n"
    .string "crecer! No deberían evolucionar.$"

Route8_Text_LeslieIntro::
    .string "La escuela es divertida, pero los\n"
    .string "POKéMON también lo son.$"

Route8_Text_LeslieDefeat::
    .string "Me dejaste claro que debería\n"
    .string "dedicarme a la escuela.$"

Route8_Text_LesliePostBattle::
    .string "Había planeado tomar algo de aire\n"
    .string "fresco para variar, pero…\p"
    .string "Estamos atorados por culpa de las\n"
    .string "entradas en AZAFRÁN.$"

Route8_Text_AndreaIntro::
    .string "¡MEOWTH es muy lindo, meow, meow,\n"
    .string "meow!$"

Route8_Text_AndreaDefeat::
    .string "¡Meeeeyow!$"

Route8_Text_AndreaPostBattle::
    .string "¡Creo que PIDGEY y RATTATA también\n"
    .string "son lindos!$"

Route8_Text_MeganIntro::
    .string "Debemos vernos tontas estando\n"
    .string "aquí.$"

Route8_Text_MeganDefeat::
    .string "¡Mira lo que le hiciste a mis\n"
    .string "pobres, lindos POKéMON!$"

Route8_Text_MeganPostBattle::
    .string "El guarda de la entrada a AZAFRÁN\n"
    .string "no nos deja pasar.\p"
    .string "Sé que hace su trabajo, pero creo\n"
    .string "que es grosero.$"

Route8_Text_RichIntro::
    .string "¡Soy un jugador errante!$"

Route8_Text_RichDefeat::
    .string "¡Perdí la gran oportunidad!$"

Route8_Text_RichPostBattle::
    .string "¡El jugar y los POKéMON son como\n"
    .string "comer maní! ¡No puedo parar!$"

Route8_Text_JuliaIntro::
    .string "¿Qué POKéMON es lindo, redondo y\n"
    .string "suave?$"

Route8_Text_JuliaDefeat::
    .string "¡Detente!\p"
    .string "¡No seas rud{OA} con mis CLEFAIRY!$"

Route8_Text_JuliaPostBattle::
    .string "Leí que CLEFAIRY evoluciona cuando\n"
    .string "es expuesto a una PIEDRA LUNAR.\p"
    .string "Lo leí en un DIARIO POKéMON.\n"
    .string "¿Será verdad?$"

Route8_Text_UndergroundPathSign::
    .string "VÍA SUBTERRÁNEA\n"
    .string "CIUDAD PRISMA - PUEBLO LAVANDA$"

Route8_Text_EliIntro::
    .string "ELI: El poder de gemelas es\n"
    .string "fantástico. ¿Lo sabías?$"

Route8_Text_EliDefeat::
    .string "ELI: Pero…\n"
    .string "Usamos nuestro poder de gemelas…$"

Route8_Text_EliPostBattle::
    .string "ELI: ¡Atrapé a mis POKéMON con\n"
    .string "ANNE!$"

Route8_Text_EliNotEnoughMons::
    .string "ELI: No podemos luchar si no\n"
    .string "tienes dos POKéMON.$"

Route8_Text_AnneIntro::
    .string "ANNE: ¡Te asombraremos con nuestro\n"
    .string "poder de gemelas!$"

Route8_Text_AnneDefeat::
    .string "ANNE: Nuestro poder de gemelas…$"

Route8_Text_AnnePostBattle::
    .string "ANNE: Estoy criando POKéMON con\n"
    .string "ELI.$"

Route8_Text_AnneNotEnoughMons::
    .string "ANNE: ¡Hola, hola! ¡Luchemos!\n"
    .string "Pero trae dos POKéMON.$"

Route8_Text_RicardoIntro::
    .string "Mi moto esta fallando, viejo.$"

Route8_Text_RicardoDefeat::
    .string "Ahh, viejo.\n"
    .string "Esto no es lo mío.$"

Route8_Text_RicardoPostBattle::
    .string "Tengo hierba atrapada en los\n"
    .string "radios de las ruedas, viejo.$"

Route8_Text_JarenIntro::
    .string "¡Apártate del camino, o te pasaré\n"
    .string "por encima!$"

Route8_Text_JarenDefeat::
    .string "¿Vas en serio, niñ{OA}?$"

Route8_Text_JarenPostBattle::
    .string "No creas que eres tod{OA} especial\n"
    .string "y eso solo por esto.$"
