CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
    .string "Estoy comprando un regalo para mi\n"
    .string "novia.\p"
    .string "Supongo que será un POKé MUÑECO.\n"
    .string "Son muy populares.$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
    .string "Escuché algo útil.\p"
    .string "Si un POKéMON salvaje aparece,\n"
    .string "puedes distraerlo con un\l"
    .string "POKé MUÑECO.\p"
    .string "Puedes escapar mientras ese\n"
    .string "POKéMON salvaje esta distraido.$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
    .string "¡Exprésate con regalos!\n"
    .string "P4: REGALOS\p"
    .string "¡Evolución Especial!\n"
    .string "¡Piedras elementales en venta!$"
