SilphCo_3F_Text_WhatAmIToDo::
    .string "Trabajo para SILPH S.A.\n"
    .string "¿Qué debo hacer?$"

SilphCo_3F_Text_YouAndYourMonsSavedUs::
    .string "¡{PLAYER}!\n"
    .string "¡Tú y tus POKéMON nos salvaron!$"

SilphCo_3F_Text_GruntIntro::
    .string "¡Deja de molestarnos, niñ{OA}!$"

SilphCo_3F_Text_GruntDefeat::
    .string "¡Me rindo!$"

SilphCo_3F_Text_GruntPostBattle::
    .string "¿Una pista? ¡puedes abrir puertas\n"
    .string "con una LLAVE MAGNÉTICA!$"

SilphCo_3F_Text_JoseIntro::
    .string "¡Apoyo al EQUIPO ROCKET más de lo\n"
    .string "que apoyo a SILPH S.A.!$"

SilphCo_3F_Text_JoseDefeat::
    .string "¡Realmente me venciste!$"

SilphCo_3F_Text_JosePostBattle::
    .string "Humph…\p"
    .string "Los ROCKET dijeron que si ayudaba,\n"
    .string "me dejarían estudiar POKéMON.$"

SilphCo_3F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P3$"

