PalletTown_Text_OakDontGoOut::
    .string "OAK: ¡Oye! ¡Espera!\n"
    .string "¡No te vayas!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "OAK: ¡No es seguro! ¡En la hierba\n"
    .string "viven POKéMON salvajes!\p"
    .string "Necesitas a tu propio POKéMON\n"
    .string "como protección.\p"
    .string "¡Ya sé!\n"
    .string "¡Vamos, ven conmigo!$"

PalletTown_Text_RaisingMonsToo::
    .string "Yo también estoy criando POKéMON.\p"
    .string "Cuando se hagan fuertes,\n"
    .string "podrán protegerme.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "¡La tecnología es incredíble!\p"
    .string "Ahora puedes guardar y sacar\n"
    .string "objetos y POKéMON, via PC.$"

PalletTown_Text_OakPokemonResearchLab::
    .string "LABORATORIO DE INVESTIGACIÓN\n"
    .string "DE POKéMON DEL PROFESOR OAK$"
               
PalletTown_Text_PlayersHouse::
    .string "Casa de {PLAYER}$"

PalletTown_Text_RivalsHouse::
    .string "Casa de {RIVAL}$"

PalletTown_Text_TownSign::
    .string "PUEBLO PALETA\n"
    .string "¡Un lienzo en blanco de tu viaje!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "OAK: ¡Ah, {PLAYER}!\n"
    .string "¿Regresaste, eh?\p"
    .string "¿Cuantas especies has llenado en\n"
    .string "tu POKéDEX?\p"
    .string "¿Puedo verla?\p"
    .string "Veamos…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "Has atrapado {STR_VAR_2}…\p"
    .string "Hm, parece que estas haciendo\n"
    .string "un esfuerzo honesto.\p"
    .string "Cuando logres llenar más, ven a\n"
    .string "enseñarme, por favor.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "Atrapaste… ¿¡{STR_VAR_2}!?\n"
    .string "¡Esto si que es impresionante!\p"
    .string "Hay algo que quiero pedirte,\n"
    .string "{PLAYER}.\p"
    .string "Ven.\n"
    .string "Sígueme.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "OAK: ¡Ah, {PLAYER}!\n"
    .string "Parece que disfrutas tus viajes.\p"
    .string "Conociéndote, {PLAYER}, es fácil\n"
    .string "imaginarte viajando a lugares\l"
    .string "más exóticos.\p"
    .string "Bien, bien.\n"
    .string "Jojojo.$"

