PalletTown_Text_OakDontGoOut:: @ 817D72C
    .string "OAK: ¡Oye! ¡Espera!\n"
    .string "¡No te vayas!$"

PalletTown_Text_OakGrassUnsafeNeedMon:: @ 817D74A
    .string "OAK: ¡No es seguro! ¡En la hierba\n"
    .string "viven POKéMON salvajes!\p"
    .string "Necesitas a tu propio POKéMON\n"
    .string "como protección.\p"
    .string "¡Ya sé!\n"
    .string "¡Vamos, ven conmigo!$"
             
PalletTown_Text_RaisingMonsToo:: @ 817D7C8
    .string "Yo también estoy criando POKéMON.\p"
    .string "Cuando se hagan fuertes,\n"
    .string "podrán protegerme.$"

PalletTown_Text_CanStoreItemsAndMonsInPC:: @ 817D80D
    .string "¡La tecnología es incredíble!\p"
    .string "Ahora puedes guardar y sacar\n"
    .string "objetos y POKéMON, via PC.$"
             
PalletTown_Text_OakPokemonResearchLab:: @ 817D866
    .string "LABORATORIO DE INVESTIGACIÓN\n"
    .string "DE POKéMON DEL PROFESOR OAK$"
               
PalletTown_Text_PlayersHouse:: @ 817D87F
    .string "Casa de {PLAYER}$"

PalletTown_Text_RivalsHouse:: @ 817D88A
    .string "Casa de {RIVAL}$"

PalletTown_Text_TownSign:: @ 817D895
    .string "PUEBLO PALETA\n"
    .string "¡Un lienzo en blanco de tu viaje!$"

PalletTown_Text_OakLetMeSeePokedex:: @ 817D8BF
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You're back, are you?\p"
    .string "How much have you filled in your\n"
    .string "POKéDEX?\p"
    .string "May I see it?\p"
    .string "Let's see…$"

PalletTown_Text_CaughtXPuttingInHonestEffort:: @ 817D925
    .string "You've caught {STR_VAR_2}…\p"
    .string "Hm, it looks as if you're putting\n"
    .string "in an honest effort.\p"
    .string "When you manage to fill it some\n"
    .string "more, come show me, please.$"

PalletTown_Text_CaughtXImpressiveFollowMe:: @ 817D9AA
    .string "You've caught… {STR_VAR_2}!?\n"
    .string "Now, this is impressive!\p"
    .string "There's something I wanted to ask\n"
    .string "of you, {PLAYER}.\p"
    .string "Come.\n"
    .string "Follow me.$"

PalletTown_Text_OakYouEnjoyingTraveling:: @ 817DA16
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You seem to be enjoying traveling.\p"
    .string "Knowing you, {PLAYER}, I can easily\n"
    .string "imagine you going out to even more\l"
    .string "exotic locales.\p"
    .string "Good for you, good for you.\n"
    .string "Hohoho.$"
