ThreeIsland_BerryForest_Text_HelpScaryPokemon::
    .string "LOSTELLE: Guaa… Sniff…\n"
    .string "¡Oh! ¡por favor, ayuda!\p"
    .string "Un POKéMON aterrador apareció hace\n"
    .string "poco.\p"
    .string "Siguió asustando.\n"
    .string "Asustó a LOSTELLE.\p"
    .string "¡El miedo no me deja moverme!\n"
    .string "Pero quiero ir a casa…$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
    .string "¡Oh! ¡aquí viene otra vez!\n"
    .string "¡No! ¡vete! ¡me da miedo!\p"
    .string "¡Waaaaaaah!\n"
    .string "¡Quiero a mi papi!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
    .string "¡Ohh! ¡eso dio mucho miedo!\n"
    .string "¡Gracias!\p"
    .string "LOSTELLE vino a tomar algunas\n"
    .string "BAYAS.\p"
    .string "¡Puedes tener esto!$"

ThreeIsland_BerryForest_Text_LetsGoHome::
    .string "¿Cómo te llamas?\p"
    .string "LOSTELLE tiene miedo, ¿puedo ir\n"
    .string "contigo a la casa de mi papi?\p"
    .string "¡Bien!\n"
    .string "¡Vamos a casa!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
    .string "Tu SACO DE BAYAS está lleno.\n"
    .string "Supongo que no quieres esto.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
    .string "Este es el BOSQUE BAYA\p"
    .string "Se amable y comparte BAYAS con\n"
    .string "otras personas y con POKéMON.$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
    .string "¡Cuidado con los POKéMON salvajes\n"
    .string "que aman las BAYAS!$"

