CeladonCity_Hotel_Text_ThisHotelIsForPeople::
    .string "¿POKéMON?\n"
    .string "No, este hotel es para personas.\p"
    .string "Estamos llenos, lo siento.$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
    .string "Estoy de vacaciones con mi hermano\n"
    .string "y mi novio.\p"
    .string "¡PRISMA es una ciudad tan bonita!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
    .string "¿Por qué?\n"
    .string "¿Por qué trajo a su hermano?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
    .string "¡Yippii! ¡estoy de vacaciones!\n"
    .string "¡Mi hermana me trajo! ¡genial!$"

